using System;
using System.Collections.Generic;
using SephiriaEnhancements.Configuration;

namespace SephiriaEnhancements.Inventory
{
    internal static class InventoryItemRecoveryLocalization
    {
        private const string Prefix = "SephiriaEnhancements.InventoryItemRecovery.";
        internal const string NoSpace = Prefix + "NoSpace",
            CannotStore = Prefix + "CannotStore", Moved = Prefix + "Moved", Checking = Prefix + "Checking",
            Unverified = Prefix + "Unverified";
        internal const string Title = Prefix + "Title", Help = Prefix + "Help", Confirm = Prefix + "Confirm",
            Cancel = Prefix + "Cancel", Selection = Prefix + "Selection", ItemUnverified = Prefix + "ItemUnverified",
            Stored = Prefix + "Stored", Grouping = Prefix + "Grouping", GroupingPrompt = Prefix + "GroupingPrompt",
            Grouped = Prefix + "Grouped", AlreadyGrouped = Prefix + "AlreadyGrouped", Restored = Prefix + "Restored";
        private static readonly string[] Keys = { NoSpace, CannotStore, Moved, Checking, Unverified,
            Title, Help, Confirm, Cancel, Selection, ItemUnverified, Stored, Grouping, GroupingPrompt, Grouped, AlreadyGrouped, Restored };
        private static readonly Dictionary<string, string[]> Texts = new()
        {
            ["en-US"] = new[] { "No empty sub-bag slot.", "This item cannot be stored in the sub-bag.", "{0}: moved to the sub-bag. Its effects are inactive there. Retrieve it manually when needed.", "Checking current item effects…", "Could not identify which items affect these bonuses. You can still group items by type.", "Some bonuses cannot be confirmed", "Selected items move to the sub-bag, where their effects are inactive. Retrieve them manually later.", "Move selected and continue", "Cancel", "Selected {0} / {1} · Free sub-bag slots: {2}", "Cannot confirm this item's effects.", "In the sub-bag · effects inactive", "Group by type", "Group the entire main backpack by item type, leaving empty slots at the end? Bonus and combo goals will not be enforced. Bonuses may decrease and MP costs may increase.", "Grouped by type. Check your bonuses and MP costs.", "Items are already grouped by type. No items moved.", "Item positions restored. Check your bonuses and MP costs." },
            ["zh-CN"] = new[] { "子背包没有空位。", "此物品无法放入子背包。", "{0}：已移入子背包，在其中不生效。需要时请手动取回。", "正在核对当前物品效果……", "无法确定哪些物品影响了这些加成。你仍可选择按种类整理。", "部分加成无法确认", "选中的物品将移入子背包，暂时不再生效。之后需手动取回。", "移出所选并继续", "取消", "已选 {0} / {1} · 子背包空位：{2}", "无法确认这件物品的效果。", "已移入子背包 · 效果未生效", "按种类整理", "将整个主背包的同类物品收拢，空位留在末尾？本次不按加成和组合目标整理，可能降低加成或增加耗蓝。", "已按种类整理。请检查加成和耗蓝。", "物品已按种类排列，本次没有移动。", "已恢复物品摆放。请检查加成和耗蓝。" },
            ["zh-TW"] = new[] { "子背包沒有空位。", "此物品無法放入子背包。", "{0}：已移入子背包，在其中不生效。需要時請手動取回。", "正在核對目前物品效果……", "無法確定哪些物品影響了這些加成。你仍可選擇按種類整理。", "部分加成無法確認", "選中的物品將移入子背包，暫時不再生效。之後需手動取回。", "移出所選並繼續", "取消", "已選 {0} / {1} · 子背包空位：{2}", "無法確認這件物品的效果。", "已移入子背包 · 效果未生效", "按種類整理", "將整個主背包的同類物品集中，空位留在末尾？本次不依加成與組合目標整理，可能降低加成或增加耗魔。", "已按種類整理。請檢查加成和耗魔。", "物品已按種類排列，本次沒有移動。", "已恢復物品擺放。請檢查加成和耗魔。" },
            ["ja-JP"] = new[] { "サブバッグに空きがありません。", "このアイテムはサブバッグに入れられません。", "{0}：サブバッグへ移しました。中では効果がありません。必要なときに手動で戻してください。", "現在のアイテム効果を確認中…", "どのアイテムがボーナスに影響しているか特定できません。種類別の整理は可能です。", "一部のボーナスを確認できません", "選んだアイテムをサブバッグに移します。中では効果がありません。後で手動で戻してください。", "選択した物を移して続行", "キャンセル", "選択 {0} / {1} · サブバッグの空き：{2}", "このアイテムの効果を確認できません。", "サブバッグ内 · 効果なし", "種類別に整理", "メインバッグ全体を種類別にまとめ、空きを末尾に移しますか？ボーナスと組み合わせの目標は適用されません。ボーナスが減ったり、MP消費が増えたりする可能性があります。", "種類別に整理しました。ボーナスとMP消費を確認してください。", "すでに種類別に並んでいます。移動はありません。", "配置を戻しました。ボーナスとMP消費を確認してください。" },
            ["ko-KR"] = new[] { "보조 가방에 빈칸이 없습니다.", "이 아이템은 보조 가방에 넣을 수 없습니다.", "{0}: 보조 가방으로 옮겼습니다. 그곳에서는 효과가 없습니다. 필요할 때 직접 꺼내세요.", "현재 아이템 효과 확인 중…", "어떤 아이템이 보너스에 영향을 주는지 확인하지 못했습니다. 종류별 정리는 가능합니다.", "일부 보너스를 확인할 수 없습니다", "선택한 아이템을 보조 가방으로 옮깁니다. 그곳에서는 효과가 없습니다. 나중에 직접 꺼내세요.", "선택한 아이템을 옮기고 계속", "취소", "선택 {0} / {1} · 보조 가방 빈칸: {2}", "이 아이템의 효과를 확인할 수 없습니다.", "보조 가방에 보관됨 · 효과 없음", "종류별 정리", "주 가방 전체를 종류별로 모으고 빈칸을 뒤로 옮길까요? 보너스와 조합 목표는 적용하지 않습니다. 보너스가 줄거나 MP 소모가 늘 수 있습니다.", "종류별로 정리했습니다. 보너스와 MP 소모를 확인하세요.", "이미 종류별로 정리되어 있습니다. 이동한 아이템이 없습니다.", "아이템 배치를 되돌렸습니다. 보너스와 MP 소모를 확인하세요." },
            ["de-DE"] = new[] { "Kein freier Platz in der Zusatztasche.", "Dieser Gegenstand darf nicht in die Zusatztasche.", "{0}: in die Zusatztasche verschoben. Dort ohne Wirkung. Bei Bedarf manuell zurückholen.", "Aktuelle Gegenstandseffekte werden geprüft…", "Die betroffenen Gegenstände konnten nicht bestimmt werden. Sortieren nach Typ ist weiterhin möglich.", "Einige Boni sind unbestätigt", "Ausgewählte Gegenstände kommen in die Zusatztasche. Dort wirken ihre Effekte nicht. Hole sie später manuell zurück.", "Auswahl verschieben und fortfahren", "Abbrechen", "Ausgewählt {0} / {1} · Freie Zusatzplätze: {2}", "Effekte dieses Gegenstands nicht bestätigt.", "In der Zusatztasche · Effekte inaktiv", "Nach Typ sortieren", "Den gesamten Hauptrucksack nach Gegenstandstyp sortieren und freie Plätze ans Ende verschieben? Bonus- und Komboziele werden nicht berücksichtigt. Boni können sinken und MP-Kosten steigen.", "Nach Typ sortiert. Prüfe Boni und MP-Kosten.", "Bereits nach Typ sortiert. Nichts verschoben.", "Anordnung wiederhergestellt. Prüfe Boni und MP-Kosten." },
            ["es-ES"] = new[] { "No hay huecos en la bolsa auxiliar.", "Este objeto no se puede guardar en la bolsa auxiliar.", "{0}: movido a la bolsa auxiliar, donde no tiene efecto. Recupéralo manualmente cuando lo necesites.", "Comprobando los efectos actuales…", "No se identificaron los objetos que afectan a estas bonificaciones. Aún puedes ordenar por tipo.", "No se pueden confirmar algunas bonificaciones", "Los objetos elegidos pasarán a la bolsa auxiliar, donde no tendrán efecto. Recupéralos manualmente después.", "Mover selección y continuar", "Cancelar", "Seleccionados {0} / {1} · Huecos auxiliares: {2}", "No se pueden confirmar los efectos de este objeto.", "En la bolsa auxiliar · efectos inactivos", "Ordenar por tipo", "¿Ordenar toda la mochila principal por tipo y dejar los huecos al final? No se aplicarán los objetivos de bonificaciones y combos. Las bonificaciones pueden bajar y el coste de MP subir.", "Ordenado por tipo. Revisa las bonificaciones y el coste de MP.", "Ya está ordenado por tipo. No se movió ningún objeto.", "Posiciones restauradas. Revisa las bonificaciones y el coste de MP." },
            ["fr-FR"] = new[] { "Aucune place dans le sac secondaire.", "Cet objet ne peut pas aller dans le sac secondaire.", "{0} : déplacé dans le sac secondaire, où ses effets sont inactifs. Récupérez-le manuellement au besoin.", "Vérification des effets actuels…", "Impossible de déterminer les objets concernés. Le rangement par type reste possible.", "Certains bonus ne sont pas confirmés", "Les objets choisis iront dans le sac secondaire, où leurs effets seront inactifs. Récupérez-les manuellement ensuite.", "Déplacer la sélection et continuer", "Annuler", "Sélection : {0} / {1} · Places secondaires : {2}", "Impossible de confirmer les effets de cet objet.", "Dans le sac secondaire · effets inactifs", "Ranger par type", "Ranger tout le sac principal par type, avec les places libres à la fin ? Les objectifs de bonus et de combos seront ignorés. Les bonus peuvent diminuer et les coûts en MP augmenter.", "Rangé par type. Vérifiez les bonus et les coûts en MP.", "Déjà rangé par type. Aucun objet déplacé.", "Positions rétablies. Vérifiez les bonus et les coûts en MP." },
            ["it-IT"] = new[] { "Nessuno spazio nella borsa secondaria.", "Questo oggetto non può andare nella borsa secondaria.", "{0}: spostato nella borsa secondaria, dove non ha effetto. Recuperalo manualmente quando serve.", "Verifica degli effetti attuali…", "Non è stato possibile identificare gli oggetti coinvolti. Puoi comunque ordinare per tipo.", "Alcuni bonus non sono confermati", "Gli oggetti scelti andranno nella borsa secondaria, dove non avranno effetto. Recuperali manualmente dopo.", "Sposta selezione e continua", "Annulla", "Selezionati {0} / {1} · Spazi aggiuntivi: {2}", "Impossibile confermare gli effetti di questo oggetto.", "Nella borsa secondaria · effetti inattivi", "Ordina per tipo", "Ordinare tutto lo zaino principale per tipo, lasciando gli spazi vuoti alla fine? Gli obiettivi di bonus e combo non saranno applicati. I bonus possono diminuire e il costo in MP aumentare.", "Ordinato per tipo. Controlla bonus e costi in MP.", "Già ordinato per tipo. Nessun oggetto spostato.", "Posizioni ripristinate. Controlla bonus e costi in MP." },
            ["pl-PL"] = new[] { "Brak miejsca w torbie dodatkowej.", "Tego przedmiotu nie można schować do torby dodatkowej.", "{0}: przeniesiono do torby dodatkowej. Efekty są tam nieaktywne. W razie potrzeby wyjmij go ręcznie.", "Sprawdzanie aktualnych efektów przedmiotów…", "Nie udało się wskazać przedmiotów wpływających na te premie. Nadal możesz uporządkować je według typu.", "Nie można potwierdzić części premii", "Wybrane przedmioty trafią do torby dodatkowej. Ich efekty będą tam nieaktywne. Później wyjmij je ręcznie.", "Przenieś wybrane i kontynuuj", "Anuluj", "Wybrano {0} / {1} · Wolne miejsca w torbie: {2}", "Nie można potwierdzić efektów tego przedmiotu.", "W torbie dodatkowej · efekty nieaktywne", "Ułóż według typu", "Uporządkować cały główny plecak według typu, zostawiając wolne miejsca na końcu? Cele premii i kombinacji nie będą uwzględniane. Premie mogą zmaleć, a koszt MP wzrosnąć.", "Ułożono według typu. Sprawdź premie i koszt MP.", "Przedmioty są już ułożone według typu. Nic nie przeniesiono.", "Przywrócono pozycje przedmiotów. Sprawdź premie i koszt MP." },
            ["pt-BR"] = new[] { "Não há espaço na bolsa auxiliar.", "Este item não pode ir para a bolsa auxiliar.", "{0}: movido para a bolsa auxiliar, onde seus efeitos ficam inativos. Retire-o manualmente quando precisar.", "Verificando os efeitos atuais…", "Não foi possível identificar os itens que afetam esses bônus. Ainda é possível organizar por tipo.", "Alguns bônus não foram confirmados", "Os itens escolhidos irão para a bolsa auxiliar, onde seus efeitos ficarão inativos. Retire-os manualmente depois.", "Mover seleção e continuar", "Cancelar", "Selecionados {0} / {1} · Espaços auxiliares: {2}", "Não foi possível confirmar os efeitos deste item.", "Na bolsa auxiliar · efeitos inativos", "Organizar por tipo", "Organizar toda a mochila principal por tipo e deixar os espaços vazios no fim? As metas de bônus e combos não serão aplicadas. Os bônus podem diminuir e os custos de MP aumentar.", "Organizado por tipo. Confira os bônus e custos de MP.", "Já está organizado por tipo. Nenhum item foi movido.", "Posições restauradas. Confira os bônus e custos de MP." },
            ["ru-RU"] = new[] { "В дополнительной сумке нет места.", "Этот предмет нельзя положить в дополнительную сумку.", "{0}: перемещён в дополнительную сумку. Эффекты там не действуют. При необходимости заберите вручную.", "Проверка текущих эффектов предметов…", "Не удалось определить предметы, влияющие на эти бонусы. Сортировка по типу доступна.", "Некоторые бонусы не подтверждены", "Выбранные предметы попадут в дополнительную сумку. Там их эффекты не действуют. Позже заберите их вручную.", "Перенести выбранное и продолжить", "Отмена", "Выбрано {0} / {1} · Свободных ячеек сумки: {2}", "Не удалось подтвердить эффекты предмета.", "В дополнительной сумке · эффекты неактивны", "Сортировать по типу", "Сгруппировать весь основной рюкзак по типу, оставив пустые ячейки в конце? Цели бонусов и комбинаций учитываться не будут. Бонусы могут уменьшиться, а расход MP — вырасти.", "Предметы сгруппированы. Проверьте бонусы и расход MP.", "Предметы уже сгруппированы. Ничего не перемещено.", "Расположение восстановлено. Проверьте бонусы и расход MP." },
            ["sv-SE"] = new[] { "Ingen ledig plats i extraväskan.", "Föremålet får inte läggas i extraväskan.", "{0}: flyttat till extraväskan. Effekterna är inaktiva där. Hämta tillbaka det manuellt vid behov.", "Kontrollerar aktuella föremålseffekter…", "Det gick inte att identifiera vilka föremål som påverkar bonusarna. Du kan fortfarande sortera efter typ.", "Vissa bonusar kan inte bekräftas", "Valda föremål flyttas till extraväskan. Deras effekter är inaktiva där. Hämta tillbaka dem manuellt senare.", "Flytta valda och fortsätt", "Avbryt", "Valda {0} / {1} · Lediga extraplatser: {2}", "Föremålets effekter kunde inte bekräftas.", "I extraväskan · effekter inaktiva", "Sortera efter typ", "Sortera hela huvudryggsäcken efter typ och lämna tomma platser sist? Bonus- och kombomål används inte. Bonusar kan minska och MP-kostnader öka.", "Sorterat efter typ. Kontrollera bonusar och MP-kostnader.", "Redan sorterat efter typ. Inga föremål flyttades.", "Placeringen återställd. Kontrollera bonusar och MP-kostnader." },
            ["th-TH"] = new[] { "กระเป๋ารองไม่มีช่องว่าง", "ไอเทมนี้ใส่กระเป๋ารองไม่ได้", "{0}: ย้ายไปกระเป๋ารองแล้ว เอฟเฟกต์ไม่ทำงานในนั้น โปรดนำกลับเองเมื่อต้องการ", "กำลังตรวจสอบเอฟเฟกต์ไอเทมปัจจุบัน…", "ระบุไอเทมที่มีผลต่อโบนัสเหล่านี้ไม่ได้ แต่ยังจัดตามประเภทได้", "ยืนยันโบนัสบางส่วนไม่ได้", "ไอเทมที่เลือกจะย้ายไปกระเป๋ารองและเอฟเฟกต์จะไม่ทำงานในนั้น ต้องนำกลับเองภายหลัง", "ย้ายที่เลือกแล้วดำเนินการต่อ", "ยกเลิก", "เลือก {0} / {1} · ช่องกระเป๋ารองว่าง: {2}", "ไม่สามารถยืนยันเอฟเฟกต์ของไอเทมนี้ได้", "อยู่ในกระเป๋ารอง · เอฟเฟกต์ไม่ทำงาน", "จัดตามประเภท", "จัดไอเทมทั้งกระเป๋าหลักตามประเภทและเว้นช่องว่างไว้ท้ายกระเป๋าหรือไม่? จะไม่ใช้เป้าหมายโบนัสและคอมโบ โบนัสอาจลดลงและค่า MP อาจเพิ่มขึ้น", "จัดตามประเภทแล้ว โปรดตรวจสอบโบนัสและค่า MP", "ไอเทมเรียงตามประเภทอยู่แล้ว ไม่มีการย้าย", "คืนตำแหน่งไอเทมแล้ว โปรดตรวจสอบโบนัสและค่า MP" },
            ["tr-TR"] = new[] { "Yan çantada boş yer yok.", "Bu eşya yan çantaya konamaz.", "{0}: yan çantaya taşındı. Orada etkileri devre dışıdır. Gerektiğinde elle geri alın.", "Mevcut eşya etkileri kontrol ediliyor…", "Bu bonusları etkileyen eşyalar belirlenemedi. Yine de türe göre sıralayabilirsiniz.", "Bazı bonuslar doğrulanamadı", "Seçilen eşyalar yan çantaya taşınır. Orada etkileri devre dışı kalır. Sonra elle geri alın.", "Seçilenleri taşı ve devam et", "İptal", "Seçilen {0} / {1} · Boş yan çanta yuvası: {2}", "Bu eşyanın etkileri doğrulanamıyor.", "Yan çantada · etkiler devre dışı", "Türe göre sırala", "Ana çantanın tamamı türe göre sıralanıp boş yuvalar sona alınsın mı? Bonus ve kombo hedefleri uygulanmaz. Bonuslar azalabilir ve MP maliyetleri artabilir.", "Türe göre sıralandı. Bonusları ve MP maliyetlerini kontrol edin.", "Zaten türe göre sıralı. Hiçbir eşya taşınmadı.", "Eşya konumları geri yüklendi. Bonusları ve MP maliyetlerini kontrol edin." }
        };
        internal static void Register(Action<string, string, string> addText) =>
            LocalizationGroup.Register(addText, LocalizationLanguages.All, Keys, Texts);
    }
}
