using System;
using System.Collections.Generic;
using System.Linq;
using SephiriaEnhancements.Configuration;

namespace SephiriaEnhancements.Inventory
{
    internal static class InventorySpecialEffectLocalization
    {
        private const string Prefix = "SephiriaEnhancements.InventorySpecialEffects.";
        internal const string Title = Prefix + "Title", KeepCost = Prefix + "KeepCost", AllowCost = Prefix + "AllowCost",
            CostHelp = Prefix + "CostHelp", NoCost = Prefix + "NoCost", Reset = Prefix + "Reset", NoPositionEffects = Prefix + "NoPositionEffects";
        internal const string Persistence = Prefix + "Persistence";
        internal static readonly string[] PositionModes = { Prefix + "Preserve", Prefix + "Improve", Prefix + "Redistribute" };
        internal static readonly string[] PositionHelp = { Prefix + "PreserveHelp", Prefix + "ImproveHelp", Prefix + "RedistributeHelp" };
        private static readonly string[] Keys = new[] { Title }.Concat(PositionModes).Concat(PositionHelp)
            .Concat(new[] { NoPositionEffects, KeepCost, AllowCost, CostHelp, NoCost, Reset, Persistence }).ToArray();
        private static readonly Dictionary<string, string[]> Texts = new()
        {
            ["en-US"] = new[] {
                "Special effects",
                "Keep current bonuses",
                "Keep and improve bonuses",
                "Seek more bonuses",
                "Keep current bonuses. Artifact and Combo goals come first.",
                "Keep current bonuses and try to improve them. Artifact and Combo goals come first.",
                "Some artifacts may lose bonuses to gain more overall. Artifact and Combo goals come first.",
                "No matching placement effects in this backpack.",
                "Do not increase MP cost",
                "Allow higher MP cost",
                "Upgrading multishot magic artifacts can cost more MP. Choose whether to allow this. Manually chosen artifact levels take precedence.",
                "No artifacts here need more MP when upgraded.",
                "Reset these options",
                "These options are saved for future games." },
            ["zh-CN"] = new[] {
                "特殊效果",
                "保留当前加成",
                "保留并提升加成",
                "追求更多加成",
                "保留当前加成。优先满足神器与连招目标。",
                "保留当前加成，再尝试提升。优先满足神器与连招目标。",
                "允许部分神器失去加成，争取更高的总加成。优先满足神器与连招目标。",
                "当前背包没有适用的摆放效果。",
                "不增加耗蓝",
                "允许增加耗蓝",
                "多发法术神器升级后可能更耗蓝，由你决定是否允许。手动指定神器等级时，以指定等级为准。",
                "当前没有升级后更耗蓝的神器。",
                "重置本页选项",
                "本页选项会保留到下次游玩。" },
            ["zh-TW"] = new[] {
                "特殊效果",
                "保留目前加成",
                "保留並提升加成",
                "追求更多加成",
                "保留目前加成。優先滿足神器與連招目標。",
                "保留目前加成，再嘗試提升。優先滿足神器與連招目標。",
                "允許部分神器失去加成，爭取更高的總加成。優先滿足神器與連招目標。",
                "目前背包沒有適用的擺放效果。",
                "不增加耗魔",
                "允許增加耗魔",
                "多發法術神器升級後可能更耗魔，由你決定是否允許。手動指定神器等級時，以指定等級為準。",
                "目前沒有升級後更耗魔的神器。",
                "重設本頁選項",
                "本頁選項會保留到下次遊玩。" },
            ["ja-JP"] = new[] {
                "特殊効果",
                "現在の補正を維持",
                "補正を維持・強化",
                "より多くの補正を狙う",
                "現在の補正を維持します。アーティファクトとコンボの目標を優先します。",
                "現在の補正を維持し、さらに強化を狙います。アーティファクトとコンボの目標を優先します。",
                "全体の補正を増やすため、一部の補正が失われる場合があります。アーティファクトとコンボの目標を優先します。",
                "このバッグには対象の配置効果がありません。",
                "MP消費を増やさない",
                "MP消費の増加を許可",
                "多重発射魔法のアーティファクトは強化でMP消費が増える場合があります。許可するか選べます。手動で指定したレベルが優先されます。",
                "強化でMP消費が増えるアーティファクトはありません。",
                "このページを初期化",
                "この設定は次回のプレイにも引き継がれます。" },
            ["ko-KR"] = new[] {
                "특수 효과",
                "현재 보너스 유지",
                "보너스 유지 및 강화",
                "더 많은 보너스 추구",
                "현재 보너스를 유지합니다. 아티팩트와 콤보 목표가 우선합니다.",
                "현재 보너스를 유지하며 더 높입니다. 아티팩트와 콤보 목표가 우선합니다.",
                "전체 보너스를 높이기 위해 일부 보너스를 잃을 수 있습니다. 아티팩트와 콤보 목표가 우선합니다.",
                "가방에 해당 배치 효과가 없습니다.",
                "MP 소모 유지",
                "MP 소모 증가 허용",
                "다중 발사 마법 아티팩트는 강화 시 MP 소모가 늘 수 있습니다. 허용 여부를 선택하세요. 직접 지정한 레벨이 우선합니다.",
                "강화 시 MP 소모가 늘어나는 아티팩트가 없습니다.",
                "이 페이지 초기화",
                "이 설정은 다음 플레이에도 유지됩니다." },
            ["de-DE"] = new[] {
                "Sondereffekte",
                "Boni behalten",
                "Boni behalten und steigern",
                "Mehr Boni anstreben",
                "Aktuelle Boni behalten. Artefakt- und Combo-Ziele gehen vor.",
                "Aktuelle Boni behalten und steigern. Artefakt- und Combo-Ziele gehen vor.",
                "Einzelne Artefakte dürfen Boni für insgesamt mehr verlieren. Artefakt- und Combo-Ziele gehen vor.",
                "Keine passenden Platzierungseffekte im Rucksack.",
                "MP-Kosten nicht erhöhen",
                "Höhere MP-Kosten erlauben",
                "Mehrfachschuss-Magieartefakte können nach Aufwertungen mehr MP kosten. Du entscheidest, ob das erlaubt ist. Manuell gewählte Stufen gehen vor.",
                "Hier kostet kein Artefakt nach Aufwertungen mehr MP.",
                "Diese Optionen zurücksetzen",
                "Diese Optionen bleiben für künftige Spiele gespeichert." },
            ["es-ES"] = new[] {
                "Efectos especiales",
                "Conservar bonificaciones",
                "Conservar y mejorar",
                "Buscar más bonificaciones",
                "Conserva las bonificaciones. Las metas de artefactos y combos van primero.",
                "Conserva las bonificaciones e intenta mejorarlas. Las metas de artefactos y combos van primero.",
                "Algunos artefactos pueden perder bonificaciones para ganar más en total. Las metas de artefactos y combos van primero.",
                "No hay efectos de colocación pertinentes en la mochila.",
                "No aumentar el gasto de PM",
                "Permitir gastar más PM",
                "Mejorar artefactos mágicos de disparo múltiple puede gastar más PM. Tú decides si lo permites. Los niveles elegidos manualmente van primero.",
                "Ningún artefacto aquí gasta más PM al mejorarlo.",
                "Restablecer estas opciones",
                "Estas opciones se guardan para futuras partidas." },
            ["fr-FR"] = new[] {
                "Effets spéciaux",
                "Garder les bonus actuels",
                "Garder et améliorer les bonus",
                "Chercher plus de bonus",
                "Garde les bonus actuels. Les objectifs d’artefacts et de combos priment.",
                "Garde les bonus et tente de les améliorer. Les objectifs d’artefacts et de combos priment.",
                "Certains artefacts peuvent perdre des bonus pour en gagner davantage au total. Les objectifs d’artefacts et de combos priment.",
                "Aucun effet de placement concerné dans ce sac.",
                "Ne pas dépenser plus de PM",
                "Autoriser plus de PM",
                "Améliorer les artefacts magiques à tirs multiples peut coûter plus de PM. À toi de décider. Les niveaux choisis manuellement priment.",
                "Aucun artefact ici ne coûte plus de PM après amélioration.",
                "Réinitialiser ces options",
                "Ces options sont conservées pour les prochaines parties." },
            ["it-IT"] = new[] {
                "Effetti speciali",
                "Mantieni i bonus attuali",
                "Mantieni e migliora i bonus",
                "Cerca più bonus",
                "Mantieni i bonus attuali. Gli obiettivi di artefatti e combo vengono prima.",
                "Mantieni i bonus e prova a migliorarli. Gli obiettivi di artefatti e combo vengono prima.",
                "Alcuni artefatti possono perdere bonus per ottenerne di più in totale. Gli obiettivi di artefatti e combo vengono prima.",
                "Nessun effetto di posizionamento pertinente nello zaino.",
                "Non aumentare il costo PM",
                "Consenti più spesa di PM",
                "Potenziare artefatti magici a colpi multipli può costare più PM. Decidi se consentirlo. I livelli scelti manualmente vengono prima.",
                "Nessun artefatto qui costa più PM dopo il potenziamento.",
                "Ripristina queste opzioni",
                "Queste opzioni vengono salvate per le prossime partite." },
            ["pl-PL"] = new[] {
                "Efekty specjalne",
                "Zachowaj obecne premie",
                "Zachowaj i zwiększ premie",
                "Szukaj większych premii",
                "Zachowaj obecne premie. Cele artefaktów i kombinacji są ważniejsze.",
                "Zachowaj premie i spróbuj je zwiększyć. Cele artefaktów i kombinacji są ważniejsze.",
                "Część artefaktów może stracić premie, by zyskać więcej łącznie. Cele artefaktów i kombinacji są ważniejsze.",
                "Brak pasujących efektów rozmieszczenia w plecaku.",
                "Nie zwiększaj kosztu PM",
                "Zezwól na wyższy koszt PM",
                "Ulepszanie magicznych artefaktów wielostrzału może kosztować więcej PM. Ty decydujesz. Ręcznie wybrane poziomy są ważniejsze.",
                "Żaden artefakt tutaj nie kosztuje więcej PM po ulepszeniu.",
                "Resetuj te opcje",
                "Te opcje są zachowywane na kolejne gry." },
            ["pt-BR"] = new[] {
                "Efeitos especiais",
                "Manter bônus atuais",
                "Manter e melhorar bônus",
                "Buscar mais bônus",
                "Mantém os bônus atuais. Metas de artefatos e combos vêm primeiro.",
                "Mantém os bônus e tenta melhorá-los. Metas de artefatos e combos vêm primeiro.",
                "Alguns artefatos podem perder bônus para ganhar mais no total. Metas de artefatos e combos vêm primeiro.",
                "Nenhum efeito de posição relevante na mochila.",
                "Não aumentar gasto de PM",
                "Permitir gastar mais PM",
                "Melhorar artefatos mágicos de disparo múltiplo pode custar mais PM. Você decide se permite. Níveis escolhidos manualmente vêm primeiro.",
                "Nenhum artefato aqui gasta mais PM após melhorar.",
                "Redefinir estas opções",
                "Estas opções são salvas para as próximas partidas." },
            ["ru-RU"] = new[] {
                "Особые эффекты",
                "Сохранить текущие бонусы",
                "Сохранить и усилить бонусы",
                "Стремиться к большим бонусам",
                "Сохранить текущие бонусы. Цели артефактов и комбинаций важнее.",
                "Сохранить бонусы и попытаться усилить их. Цели артефактов и комбинаций важнее.",
                "Некоторые артефакты могут потерять бонусы ради большего общего усиления. Цели артефактов и комбинаций важнее.",
                "В рюкзаке нет подходящих эффектов размещения.",
                "Не увеличивать расход маны",
                "Разрешить больший расход маны",
                "Улучшение магических артефактов мультивыстрела может требовать больше маны. Решение за вами. Вручную заданные уровни важнее.",
                "Здесь нет артефактов с ростом расхода маны при улучшении.",
                "Сбросить эти настройки",
                "Эти настройки сохраняются для следующих игр." },
            ["sv-SE"] = new[] {
                "Specialeffekter",
                "Behåll nuvarande bonusar",
                "Behåll och förbättra bonusar",
                "Sök fler bonusar",
                "Behåll nuvarande bonusar. Artefakt- och kombomål går först.",
                "Behåll bonusar och försök förbättra dem. Artefakt- och kombomål går först.",
                "Vissa artefakter kan förlora bonusar för större total vinst. Artefakt- och kombomål går först.",
                "Inga passande placeringseffekter i ryggsäcken.",
                "Öka inte MP-kostnaden",
                "Tillåt högre MP-kostnad",
                "Magiska flerskottsartefakter kan kosta mer MP efter uppgradering. Du väljer om det tillåts. Manuellt valda nivåer går först.",
                "Ingen artefakt här kostar mer MP efter uppgradering.",
                "Återställ dessa val",
                "Dessa val sparas till kommande spel." },
            ["th-TH"] = new[] {
                "เอฟเฟกต์พิเศษ",
                "รักษาโบนัสปัจจุบัน",
                "รักษาและเพิ่มโบนัส",
                "หาโบนัสให้มากขึ้น",
                "รักษาโบนัสปัจจุบัน เป้าหมายอาร์ติแฟกต์และคอมโบสำคัญกว่า",
                "รักษาโบนัสและพยายามเพิ่มให้มากขึ้น เป้าหมายอาร์ติแฟกต์และคอมโบสำคัญกว่า",
                "บางอาร์ติแฟกต์อาจเสียโบนัสเพื่อให้ได้โบนัสรวมมากขึ้น เป้าหมายอาร์ติแฟกต์และคอมโบสำคัญกว่า",
                "ไม่มีเอฟเฟกต์การจัดวางที่เกี่ยวข้องในกระเป๋า",
                "ไม่เพิ่มการใช้ MP",
                "อนุญาตให้ใช้ MP เพิ่ม",
                "การอัปเกรดอาร์ติแฟกต์เวทยิงหลายลูกอาจใช้ MP มากขึ้น คุณเลือกได้ว่าจะอนุญาตหรือไม่ ระดับที่เลือกเองสำคัญกว่า",
                "ไม่มีอาร์ติแฟกต์ที่ใช้ MP เพิ่มเมื่ออัปเกรด",
                "รีเซ็ตตัวเลือกหน้านี้",
                "ตัวเลือกเหล่านี้จะถูกเก็บไว้สำหรับการเล่นครั้งต่อไป" },
            ["tr-TR"] = new[] {
                "Özel etkiler",
                "Mevcut bonusları koru",
                "Bonusları koru ve artır",
                "Daha çok bonus ara",
                "Mevcut bonusları korur. Eser ve kombo hedefleri önce gelir.",
                "Bonusları korur ve artırmaya çalışır. Eser ve kombo hedefleri önce gelir.",
                "Toplam kazanç için bazı eserler bonus kaybedebilir. Eser ve kombo hedefleri önce gelir.",
                "Çantada uygun yerleşim etkisi yok.",
                "MP maliyetini artırma",
                "Daha çok MP harcamaya izin ver",
                "Çoklu atış büyü eserlarını yükseltmek daha çok MP harcatabilir. İzin verip vermemek sana bağlı. Elle seçilen seviyeler önce gelir.",
                "Burada yükseltilince daha çok MP harcayan eser yok.",
                "Bu seçenekleri sıfırla",
                "Bu seçenekler sonraki oyunlar için kaydedilir." },
        };
        internal static void Register(Action<string, string, string> addText) =>
            LocalizationGroup.Register(addText, LocalizationLanguages.All, Keys, Texts);
    }
}
