using System.Collections.Generic;

namespace SephiriaEnhancements.Inventory
{
    internal static partial class InventoryOptimizationLocalization
    {
        private static readonly Dictionary<string, string[]> Texts = new()
        {
            ["en-US"] = new[]
            {
                "Analyzing inventory layout…",
                "A better layout was found. Applying it…",
                "Inventory optimization complete.",
                "No better inventory layout was found in this search.",
                "Open the standard inventory before optimizing it.",
                "Inventory state is not ready yet. Try again shortly.",
                "There are no items to optimize.",
                "Some inventory items cannot be uniquely identified. Optimization stopped.",
                "Optimization is not supported for the current inventory state. This attempt was skipped.",
                "Item position effects could not be verified. Optimization stopped.",
                "This inventory contains position effects that require host-side verification. Optimizing it as a non-host player is not yet supported.",
                "The inventory changed, so this optimization was cancelled.",
                "The inventory was closed, so this optimization was cancelled.",
                "The game entered a new floor or flow, so this optimization was cancelled.",
                "Applying the inventory layout timed out and was cancelled.",
                "A safe inventory operation plan could not be created.",
                "The layout was applied, but its effects differed from the prediction. Optimization stopped. You can try again.",
                "Inventory optimization is already in progress.",
                "Place or cancel the item you are holding first.",
                "Inventory optimization stopped because you picked up an item.",
                "Inventory optimization encountered an unexpected error and has been temporarily disabled.",
                "Inventory optimization tendency",
                "Automatic chooses the search method from inventory size and expected gain. Stable favors less work and fewer changes; Aggressive spends more time seeking greater gains.",
                "Automatic",
                "Stable",
                "Aggressive",
                "Inventory optimization",
                "Combo targets",
                "Optimize inventory",
                "Mark artifacts",
                "Finish marking",
                "Choose artifacts to prioritize this run · Marked: {0}",
                "Artifacts prioritized this run: {0}",
                "Priority artifacts: {0} · Other goal adjustments: {1}",
                "Priority · left first",
                "Avoid · prefer inactive",
                "Click/drag marks; right-click removes.\n{0}: edit the pointed/focused level goal.\nChanges goals, not inventory items.",
                "Bind “Switch locked target”",
                "Choose a slot to place or swap.\nRight-click to cancel.\nScroll to turn pages.",
                "Inventory optimization",
                "Adjust combo targets",
                "Back to artifact queue",
                "Automatically using the current game preset",
                "Automatically analyzing the current inventory",
                "Goal adjustments this run: {0}",
                "Keep active",
                "Choose automatically",
                "Level {0} or higher",
                "Count: {0} or more",
                "Count: {0} or fewer",
                "No minimum count (0)",
                "No targets of this type in the inventory",
                "Page {0}/{1}",
                "Searching with the current targets…",
                "Applying inventory layout…",
                "Automatic",
                "Priority",
                "Avoid",
            },
            ["zh-CN"] = new[]
            {
                "正在分析背包布局……",
                "已找到更优布局，正在应用……",
                "背包优化完成。",
                "本次未找到更好的背包布局。",
                "请先打开普通背包界面再使用背包优化。",
                "背包状态尚未准备完成，请稍后重试。",
                "背包中没有可优化的物品。",
                "无法唯一识别背包中的部分物品，已停止优化。",
                "当前背包状态暂不支持优化，本次已跳过。",
                "无法验证物品的位置效果，已停止优化。",
                "当前背包含有需要房主端验证的位置效果，暂不支持非房主玩家优化此背包。",
                "背包状态已经变化，本次优化已取消。",
                "背包界面已关闭，本次优化已取消。",
                "游戏已进入新的楼层或流程，本次优化已取消。",
                "应用背包布局超时，本次优化已取消。",
                "无法生成安全的背包操作计划。",
                "布局已应用，但实际效果与预期不符。本次优化已停止，可以重试。",
                "背包优化正在进行中。",
                "请先放下或取消当前拿起的物品。",
                "你拿起了物品，本次背包优化已停止。",
                "背包优化发生意外错误，已暂时停用。",
                "背包优化倾向",
                "自动会根据背包规模与预期收益选择搜索方式；稳定倾向减少耗时和改动，激进倾向投入更多时间寻找更高收益。",
                "自动",
                "稳定",
                "激进",
                "背包优化",
                "连招目标",
                "优化背包",
                "标记神器",
                "完成标记",
                "选择要临时优先的神器；已标记 {0} 件",
                "本次探索临时优先 {0} 件神器",
                "临时优先 {0} 件神器，另有 {1} 项目标调整",
                "优先队列 · 越靠前越优先",
                "排除区 · 优先保持不生效",
                "点击或拖动标记换位；右键移除\n{0}：调整所指神器的等级目标\n只修改目标，不移动神器",
                "请绑定“切换锁定目标”",
                "选择格子放下或交换。\n右键取消；滚轮翻页。",
                "背包优化",
                "调整连招目标",
                "返回神器队列",
                "自动参考当前游戏预设",
                "自动分析当前背包",
                "本次探索有 {0} 项目标调整",
                "只需生效",
                "自动选择",
                "至少 {0} 级",
                "计数至少 {0}",
                "计数最多 {0}",
                "计数不限（0）",
                "当前背包没有此类目标",
                "第 {0}/{1} 页",
                "正在按当前目标搜索……",
                "正在应用背包布局……",
                "自动",
                "优先",
                "避免",
            },
            ["zh-TW"] = new[]
            {
                "正在分析背包配置……",
                "已找到更佳配置，正在套用……",
                "背包最佳化完成。",
                "本次未找到更好的背包配置。",
                "請先開啟一般背包介面再使用背包最佳化。",
                "背包狀態尚未準備完成，請稍後重試。",
                "背包中沒有可最佳化的物品。",
                "無法唯一識別背包中的部分物品，已停止最佳化。",
                "目前背包狀態暫不支援最佳化，本次已略過。",
                "無法驗證物品的位置效果，已停止最佳化。",
                "目前背包含有需要房主端驗證的位置效果，暫不支援非房主玩家最佳化此背包。",
                "背包狀態已經變更，本次最佳化已取消。",
                "背包介面已關閉，本次最佳化已取消。",
                "遊戲已進入新的樓層或流程，本次最佳化已取消。",
                "套用背包配置逾時，本次最佳化已取消。",
                "無法產生安全的背包操作計畫。",
                "配置已套用，但實際效果與預期不符。本次最佳化已停止，可以重試。",
                "背包最佳化正在進行中。",
                "請先放下或取消目前拿起的物品。",
                "你拿起了物品，本次背包最佳化已停止。",
                "背包最佳化發生意外錯誤，已暫時停用。",
                "背包最佳化傾向",
                "自動會依背包規模與預期收益選擇搜尋方式；穩定傾向減少耗時和改動，積極傾向投入更多時間尋找更高收益。",
                "自動",
                "穩定",
                "積極",
                "背包最佳化",
                "連招目標",
                "最佳化背包",
                "標記神器",
                "完成標記",
                "選擇要暫時優先的神器；已標記 {0} 件",
                "本次探索暫時優先 {0} 件神器",
                "暫時優先 {0} 件神器，另有 {1} 項目標調整",
                "優先佇列 · 越靠前越優先",
                "排除區 · 優先保持不生效",
                "點擊或拖動標記換位；右鍵移除\n{0}：調整所指神器的等級目標\n只修改目標，不移動神器",
                "請綁定「切換鎖定目標」",
                "選擇格子放下或交換。\n右鍵取消；滾輪翻頁。",
                "背包最佳化",
                "調整連招目標",
                "返回神器佇列",
                "自動參考目前遊戲預設",
                "自動分析目前背包",
                "本次探索有 {0} 項目標調整",
                "只需生效",
                "自動選擇",
                "至少 {0} 級",
                "計數至少 {0}",
                "計數最多 {0}",
                "計數不限（0）",
                "目前背包沒有此類目標",
                "第 {0}/{1} 頁",
                "正在依目前目標搜尋……",
                "正在套用背包配置……",
                "自動",
                "優先",
                "避免",
            },
            ["ja-JP"] = new[]
            {
                "インベントリの配置を分析中…",
                "より良い配置が見つかりました。適用中…",
                "インベントリの最適化が完了しました。",
                "今回の検索では、より良い配置は見つかりませんでした。",
                "通常のインベントリ画面を開いてから最適化してください。",
                "インベントリの準備ができていません。少し待ってから再試行してください。",
                "最適化できるアイテムがありません。",
                "一部のアイテムを区別できないため、最適化を停止しました。",
                "現在のインベントリ状態では最適化できないため、今回はスキップしました。",
                "アイテムの配置効果を確認できないため、最適化を停止しました。",
                "このインベントリにはホスト側での確認が必要な配置効果があります。ホスト以外のプレイヤーによる最適化には未対応です。",
                "インベントリが変化したため、最適化をキャンセルしました。",
                "インベントリを閉じたため、最適化をキャンセルしました。",
                "フロアやゲームの進行状態が変わったため、最適化をキャンセルしました。",
                "配置の適用がタイムアウトしたため、キャンセルしました。",
                "安全に配置を変更する手順を作成できませんでした。",
                "配置は適用されましたが、効果が予測と異なったため停止しました。再試行できます。",
                "インベントリの最適化は既に進行中です。",
                "手に持っているアイテムを置くか、操作をキャンセルしてください。",
                "アイテムを持ち上げたため、最適化を停止しました。",
                "予期しないエラーのため、インベントリの最適化を一時的に無効にしました。",
                "最適化の方針",
                "自動はインベントリの規模と見込まれる効果から検索方法を選びます。安定は処理時間と変更を抑え、積極的は時間をかけてより良い結果を探します。",
                "自動",
                "安定",
                "積極的",
                "インベントリの最適化",
                "コンボ目標",
                "インベントリを最適化",
                "アーティファクトを指定",
                "指定を完了",
                "今回の探索で優先するアーティファクトを選択 · 指定数：{0}",
                "今回の探索で優先するアーティファクト：{0}",
                "優先アーティファクト：{0} · その他の目標調整：{1}",
                "優先順 · 左から優先",
                "回避 · 無効を優先",
                "印をクリック／ドラッグして移動、右クリックで削除。\n{0}：選択中のアーティファクトのレベル目標を変更。\n目標のみを変更し、アイテムは移動しません。",
                "「ロック対象切替」を割り当ててください",
                "配置または交換するマスを選択。\n右クリックでキャンセル、スクロールでページ切替。",
                "インベントリの最適化",
                "コンボ目標を調整",
                "アーティファクトの優先順に戻る",
                "現在のゲーム内プリセットを自動で参照",
                "現在のインベントリを自動で分析",
                "今回の探索の目標調整：{0}",
                "有効にする",
                "自動で選択",
                "レベル {0} 以上",
                "カウント {0} 以上",
                "カウント {0} 以下",
                "最低カウントなし（0）",
                "この種類の目標はインベントリにありません",
                "{0}/{1} ページ",
                "現在の目標で検索中…",
                "インベントリの配置を適用中…",
                "自動",
                "優先",
                "回避",
            },
            ["ko-KR"] = new[]
            {
                "인벤토리 배치 분석 중…",
                "더 나은 배치를 찾았습니다. 적용 중…",
                "인벤토리 최적화를 완료했습니다.",
                "이번 검색에서는 더 나은 배치를 찾지 못했습니다.",
                "일반 인벤토리 화면을 연 후 최적화해 주세요.",
                "인벤토리가 아직 준비되지 않았습니다. 잠시 후 다시 시도해 주세요.",
                "최적화할 아이템이 없습니다.",
                "일부 아이템을 구별할 수 없어 최적화를 중단했습니다.",
                "현재 인벤토리 상태는 최적화를 지원하지 않아 이번 시도를 건너뛰었습니다.",
                "아이템의 위치 효과를 확인할 수 없어 최적화를 중단했습니다.",
                "이 인벤토리에는 호스트 측에서 확인해야 하는 위치 효과가 있습니다. 호스트가 아닌 플레이어의 최적화는 아직 지원하지 않습니다.",
                "인벤토리가 변경되어 최적화를 취소했습니다.",
                "인벤토리를 닫아 최적화를 취소했습니다.",
                "층이나 게임 진행 상태가 변경되어 최적화를 취소했습니다.",
                "인벤토리 배치 적용 시간이 초과되어 취소했습니다.",
                "안전하게 배치를 변경할 순서를 만들지 못했습니다.",
                "배치는 적용되었지만 실제 효과가 예측과 달라 최적화를 중단했습니다. 다시 시도할 수 있습니다.",
                "이미 인벤토리 최적화가 진행 중입니다.",
                "들고 있는 아이템을 먼저 놓거나 이동을 취소해 주세요.",
                "아이템을 집어 들어 최적화를 중단했습니다.",
                "예기치 않은 오류로 인벤토리 최적화를 일시적으로 비활성화했습니다.",
                "인벤토리 최적화 성향",
                "자동은 인벤토리 규모와 예상 이득에 따라 검색 방식을 선택합니다. 안정은 시간과 변경을 줄이고, 적극은 더 많은 시간을 들여 높은 이득을 찾습니다.",
                "자동",
                "안정",
                "적극",
                "인벤토리 최적화",
                "콤보 목표",
                "인벤토리 최적화",
                "아티팩트 표시",
                "표시 완료",
                "이번 탐험에서 우선할 아티팩트 선택 · 표시: {0}",
                "이번 탐험의 우선 아티팩트: {0}",
                "우선 아티팩트: {0} · 기타 목표 조정: {1}",
                "우선순위 · 왼쪽부터",
                "제외 · 비활성 우선",
                "표시를 클릭하거나 드래그해 이동, 우클릭으로 제거합니다.\n{0}: 가리키거나 선택한 아티팩트의 레벨 목표를 변경합니다.\n목표만 바꾸며 아이템은 이동하지 않습니다.",
                "‘고정 대상 전환’을 지정해 주세요",
                "놓거나 교환할 칸을 선택하세요.\n우클릭으로 취소, 스크롤로 페이지를 넘깁니다.",
                "인벤토리 최적화",
                "콤보 목표 조정",
                "아티팩트 우선순위로 돌아가기",
                "현재 게임 프리셋을 자동으로 참조",
                "현재 인벤토리를 자동으로 분석",
                "이번 탐험의 목표 조정: {0}",
                "활성 상태 유지",
                "자동 선택",
                "레벨 {0} 이상",
                "개수 {0} 이상",
                "개수 {0} 이하",
                "최소 개수 없음 (0)",
                "인벤토리에 이 유형의 목표가 없습니다",
                "{0}/{1} 페이지",
                "현재 목표로 검색 중…",
                "인벤토리 배치 적용 중…",
                "자동",
                "우선",
                "제외",
            },
            ["de-DE"] = new[]
            {
                "Inventaranordnung wird analysiert…",
                "Bessere Anordnung gefunden. Wird angewendet…",
                "Inventaroptimierung abgeschlossen.",
                "Bei dieser Suche wurde keine bessere Anordnung gefunden.",
                "Öffne vor der Optimierung das normale Inventar.",
                "Das Inventar ist noch nicht bereit. Versuche es gleich erneut.",
                "Keine Gegenstände zum Optimieren vorhanden.",
                "Einige Gegenstände lassen sich nicht eindeutig zuordnen. Optimierung gestoppt.",
                "Der aktuelle Inventarzustand wird nicht unterstützt. Optimierung übersprungen.",
                "Positionseffekte der Gegenstände konnten nicht geprüft werden. Optimierung gestoppt.",
                "Dieses Inventar enthält Positionseffekte, die der Host prüfen muss. Eine Optimierung durch andere Spieler wird noch nicht unterstützt.",
                "Das Inventar hat sich geändert. Optimierung abgebrochen.",
                "Das Inventar wurde geschlossen. Optimierung abgebrochen.",
                "Die Ebene oder der Spielablauf hat sich geändert. Optimierung abgebrochen.",
                "Zeitüberschreitung beim Anwenden der Anordnung. Vorgang abgebrochen.",
                "Es konnte keine sichere Abfolge von Inventaraktionen ermittelt werden.",
                "Die Anordnung wurde angewendet, aber die Effekte weichen von der Vorhersage ab. Optimierung gestoppt. Du kannst es erneut versuchen.",
                "Die Inventaroptimierung läuft bereits.",
                "Lege zuerst den gehaltenen Gegenstand ab oder brich das Verschieben ab.",
                "Du hast einen Gegenstand aufgenommen. Optimierung gestoppt.",
                "Ein unerwarteter Fehler hat die Inventaroptimierung vorübergehend deaktiviert.",
                "Optimierungsstrategie",
                "Automatisch wählt die Suche nach Inventargröße und erwartetem Nutzen. Stabil bevorzugt weniger Zeitaufwand und Änderungen; Intensiv sucht länger nach besseren Ergebnissen.",
                "Automatisch",
                "Stabil",
                "Intensiv",
                "Inventaroptimierung",
                "Kombo-Ziele",
                "Inventar optimieren",
                "Artefakte markieren",
                "Markierung beenden",
                "Artefakte für diesen Lauf priorisieren · Markiert: {0}",
                "Priorisierte Artefakte in diesem Lauf: {0}",
                "Priorisierte Artefakte: {0} · Weitere Zielanpassungen: {1}",
                "Priorität · links zuerst",
                "Vermeiden · möglichst inaktiv",
                "Markierungen anklicken/ziehen; Rechtsklick entfernt sie.\n{0}: Stufenziel des gewählten Artefakts ändern.\nÄndert Ziele, verschiebt keine Gegenstände.",
                "Belege „Festes Ziel wechseln“",
                "Feld zum Ablegen oder Tauschen wählen.\nRechtsklick zum Abbrechen, Scrollen zum Blättern.",
                "Inventaroptimierung",
                "Kombo-Ziele anpassen",
                "Zurück zur Artefaktliste",
                "Aktuelle Spielvorlage wird automatisch berücksichtigt",
                "Aktuelles Inventar wird automatisch analysiert",
                "Zielanpassungen in diesem Lauf: {0}",
                "Aktiv halten",
                "Automatisch wählen",
                "Stufe {0} oder höher",
                "Anzahl: mindestens {0}",
                "Anzahl: höchstens {0}",
                "Keine Mindestanzahl (0)",
                "Keine Ziele dieser Art im Inventar",
                "Seite {0}/{1}",
                "Suche mit den aktuellen Zielen…",
                "Inventaranordnung wird angewendet…",
                "Automatisch",
                "Priorisieren",
                "Vermeiden",
            },
            ["fr-FR"] = new[]
            {
                "Analyse de l’inventaire…",
                "Meilleure disposition trouvée. Application…",
                "Optimisation de l’inventaire terminée.",
                "Cette recherche n’a pas trouvé de meilleure disposition.",
                "Ouvrez l’inventaire standard avant de l’optimiser.",
                "L’inventaire n’est pas encore prêt. Réessayez dans un instant.",
                "Aucun objet à optimiser.",
                "Certains objets ne peuvent pas être identifiés de façon unique. Optimisation arrêtée.",
                "L’état actuel de l’inventaire n’est pas pris en charge. Tentative ignorée.",
                "Impossible de vérifier les effets de position des objets. Optimisation arrêtée.",
                "Cet inventaire contient des effets de position qui doivent être vérifiés par l’hôte. Son optimisation par les autres joueurs n’est pas encore prise en charge.",
                "L’inventaire a changé. Optimisation annulée.",
                "L’inventaire a été fermé. Optimisation annulée.",
                "L’étage ou le déroulement du jeu a changé. Optimisation annulée.",
                "L’application de la disposition a expiré et a été annulée.",
                "Impossible de déterminer une suite sûre d’actions dans l’inventaire.",
                "La disposition a été appliquée, mais ses effets diffèrent des prévisions. Optimisation arrêtée. Vous pouvez réessayer.",
                "L’optimisation de l’inventaire est déjà en cours.",
                "Posez d’abord l’objet tenu ou annulez son déplacement.",
                "Vous avez pris un objet. Optimisation arrêtée.",
                "Une erreur inattendue a temporairement désactivé l’optimisation de l’inventaire.",
                "Stratégie d’optimisation",
                "Automatique choisit la recherche selon la taille de l’inventaire et le gain attendu. Stable limite le temps et les changements ; Approfondie prend plus de temps pour chercher de meilleurs résultats.",
                "Automatique",
                "Stable",
                "Approfondie",
                "Optimisation de l’inventaire",
                "Objectifs de combo",
                "Optimiser l’inventaire",
                "Marquer les artefacts",
                "Terminer le marquage",
                "Choisissez les artefacts prioritaires pour cette exploration · Marqués : {0}",
                "Artefacts prioritaires pour cette exploration : {0}",
                "Artefacts prioritaires : {0} · Autres objectifs modifiés : {1}",
                "Priorité · gauche d’abord",
                "Éviter · préférer inactif",
                "Cliquez/glissez les marques ; clic droit pour retirer.\n{0} : modifier le niveau visé de l’artefact sélectionné.\nChange les objectifs sans déplacer les objets.",
                "Attribuez « Changer de cible verrouillée »",
                "Choisissez une case pour poser ou échanger.\nClic droit pour annuler, molette pour changer de page.",
                "Optimisation de l’inventaire",
                "Ajuster les objectifs de combo",
                "Retour à la liste des artefacts",
                "Utilisation automatique du préréglage actuel du jeu",
                "Analyse automatique de l’inventaire actuel",
                "Objectifs modifiés pour cette exploration : {0}",
                "Garder actif",
                "Choisir automatiquement",
                "Niveau {0} ou plus",
                "Quantité : au moins {0}",
                "Quantité : au plus {0}",
                "Aucune quantité minimale (0)",
                "Aucun objectif de ce type dans l’inventaire",
                "Page {0}/{1}",
                "Recherche selon les objectifs actuels…",
                "Application de la disposition…",
                "Automatique",
                "Prioritaire",
                "Éviter",
            },
            ["es-ES"] = new[]
            {
                "Analizando el inventario…",
                "Se ha encontrado una disposición mejor. Aplicando…",
                "Optimización del inventario completada.",
                "Esta búsqueda no ha encontrado una disposición mejor.",
                "Abre el inventario normal antes de optimizarlo.",
                "El inventario aún no está listo. Vuelve a intentarlo en un momento.",
                "No hay objetos que optimizar.",
                "No se pueden identificar de forma única algunos objetos. Optimización detenida.",
                "El estado actual del inventario no admite la optimización. Se ha omitido este intento.",
                "No se han podido verificar los efectos de posición. Optimización detenida.",
                "Este inventario contiene efectos de posición que debe verificar el anfitrión. Otros jugadores aún no pueden optimizarlo.",
                "El inventario ha cambiado. Optimización cancelada.",
                "Se ha cerrado el inventario. Optimización cancelada.",
                "Ha cambiado la planta o el estado de la partida. Optimización cancelada.",
                "Se ha agotado el tiempo para aplicar la disposición. Operación cancelada.",
                "No se ha podido determinar una secuencia segura de acciones de inventario.",
                "La disposición se ha aplicado, pero sus efectos no coinciden con lo previsto. Optimización detenida. Puedes volver a intentarlo.",
                "La optimización del inventario ya está en curso.",
                "Coloca primero el objeto que sostienes o cancela su movimiento.",
                "Has recogido un objeto. Optimización detenida.",
                "Un error inesperado ha desactivado temporalmente la optimización del inventario.",
                "Estrategia de optimización",
                "Automática elige la búsqueda según el tamaño del inventario y la mejora prevista. Estable reduce el tiempo y los cambios; Intensiva dedica más tiempo a buscar mejores resultados.",
                "Automática",
                "Estable",
                "Intensiva",
                "Optimización del inventario",
                "Objetivos de combo",
                "Optimizar inventario",
                "Marcar artefactos",
                "Terminar de marcar",
                "Elige los artefactos prioritarios de esta expedición · Marcados: {0}",
                "Artefactos prioritarios de esta expedición: {0}",
                "Artefactos prioritarios: {0} · Otros objetivos ajustados: {1}",
                "Prioridad · primero a la izquierda",
                "Evitar · preferir inactivo",
                "Haz clic o arrastra las marcas; clic derecho para quitar.\n{0}: cambia el nivel objetivo del artefacto seleccionado.\nSolo cambia objetivos, no mueve objetos.",
                "Asigna «Cambiar objetivo fijado»",
                "Elige una casilla para colocar o intercambiar.\nClic derecho para cancelar; rueda para cambiar de página.",
                "Optimización del inventario",
                "Ajustar objetivos de combo",
                "Volver a la cola de artefactos",
                "Usando automáticamente el preajuste actual del juego",
                "Analizando automáticamente el inventario actual",
                "Objetivos ajustados en esta expedición: {0}",
                "Mantener activo",
                "Elegir automáticamente",
                "Nivel {0} o superior",
                "Cantidad: {0} o más",
                "Cantidad: {0} o menos",
                "Sin cantidad mínima (0)",
                "No hay objetivos de este tipo en el inventario",
                "Página {0}/{1}",
                "Buscando según los objetivos actuales…",
                "Aplicando la disposición…",
                "Automático",
                "Prioridad",
                "Evitar",
            },
            ["it-IT"] = new[]
            {
                "Analisi dell’inventario…",
                "Trovata una disposizione migliore. Applicazione…",
                "Ottimizzazione dell’inventario completata.",
                "Questa ricerca non ha trovato una disposizione migliore.",
                "Apri l’inventario normale prima di ottimizzarlo.",
                "L’inventario non è ancora pronto. Riprova tra poco.",
                "Non ci sono oggetti da ottimizzare.",
                "Alcuni oggetti non possono essere identificati in modo univoco. Ottimizzazione interrotta.",
                "Lo stato attuale dell’inventario non è supportato. Tentativo saltato.",
                "Impossibile verificare gli effetti di posizione. Ottimizzazione interrotta.",
                "Questo inventario contiene effetti di posizione che devono essere verificati dall’host. Gli altri giocatori non possono ancora ottimizzarlo.",
                "L’inventario è cambiato. Ottimizzazione annullata.",
                "L’inventario è stato chiuso. Ottimizzazione annullata.",
                "Il piano o lo stato della partita è cambiato. Ottimizzazione annullata.",
                "Tempo scaduto durante l’applicazione della disposizione. Operazione annullata.",
                "Impossibile determinare una sequenza sicura di azioni nell’inventario.",
                "La disposizione è stata applicata, ma gli effetti non corrispondono alla previsione. Ottimizzazione interrotta. Puoi riprovare.",
                "L’ottimizzazione dell’inventario è già in corso.",
                "Prima posa l’oggetto che tieni o annulla lo spostamento.",
                "Hai preso un oggetto. Ottimizzazione interrotta.",
                "Un errore imprevisto ha disattivato temporaneamente l’ottimizzazione dell’inventario.",
                "Strategia di ottimizzazione",
                "Automatica sceglie la ricerca in base alla dimensione dell’inventario e al beneficio previsto. Stabile riduce tempo e modifiche; Intensiva dedica più tempo a cercare risultati migliori.",
                "Automatica",
                "Stabile",
                "Intensiva",
                "Ottimizzazione inventario",
                "Obiettivi combo",
                "Ottimizza inventario",
                "Segna artefatti",
                "Termina selezione",
                "Scegli gli artefatti prioritari per questa esplorazione · Segnati: {0}",
                "Artefatti prioritari per questa esplorazione: {0}",
                "Artefatti prioritari: {0} · Altri obiettivi modificati: {1}",
                "Priorità · prima a sinistra",
                "Evita · preferisci inattivo",
                "Clicca/trascina i segni; clic destro per rimuovere.\n{0}: modifica il livello obiettivo dell’artefatto selezionato.\nCambia gli obiettivi senza spostare gli oggetti.",
                "Assegna «Cambia bersaglio bloccato»",
                "Scegli una casella per posare o scambiare.\nClic destro per annullare, rotella per cambiare pagina.",
                "Ottimizzazione inventario",
                "Modifica obiettivi combo",
                "Torna alla coda degli artefatti",
                "Uso automatico della configurazione attuale del gioco",
                "Analisi automatica dell’inventario attuale",
                "Obiettivi modificati in questa esplorazione: {0}",
                "Mantieni attivo",
                "Scegli automaticamente",
                "Livello {0} o superiore",
                "Conteggio: almeno {0}",
                "Conteggio: al massimo {0}",
                "Nessun conteggio minimo (0)",
                "Nessun obiettivo di questo tipo nell’inventario",
                "Pagina {0}/{1}",
                "Ricerca con gli obiettivi attuali…",
                "Applicazione della disposizione…",
                "Automatico",
                "Priorità",
                "Evita",
            },
            ["pt-BR"] = new[]
            {
                "Analisando o inventário…",
                "Uma disposição melhor foi encontrada. Aplicando…",
                "Otimização do inventário concluída.",
                "Esta busca não encontrou uma disposição melhor.",
                "Abra o inventário normal antes de otimizá-lo.",
                "O inventário ainda não está pronto. Tente novamente em instantes.",
                "Não há itens para otimizar.",
                "Não foi possível identificar alguns itens de forma única. Otimização interrompida.",
                "O estado atual do inventário não é compatível com a otimização. Esta tentativa foi ignorada.",
                "Não foi possível verificar os efeitos de posição. Otimização interrompida.",
                "Este inventário contém efeitos de posição que precisam ser verificados pelo anfitrião. Outros jogadores ainda não podem otimizá-lo.",
                "O inventário mudou. Otimização cancelada.",
                "O inventário foi fechado. Otimização cancelada.",
                "O andar ou o estado da partida mudou. Otimização cancelada.",
                "O tempo para aplicar a disposição se esgotou. Operação cancelada.",
                "Não foi possível determinar uma sequência segura de ações no inventário.",
                "A disposição foi aplicada, mas os efeitos diferiram do previsto. Otimização interrompida. Você pode tentar novamente.",
                "A otimização do inventário já está em andamento.",
                "Primeiro coloque o item que está segurando ou cancele o movimento.",
                "Você pegou um item. Otimização interrompida.",
                "Um erro inesperado desativou temporariamente a otimização do inventário.",
                "Estratégia de otimização",
                "Automática escolhe a busca conforme o tamanho do inventário e o ganho esperado. Estável reduz tempo e alterações; Intensiva dedica mais tempo a buscar resultados melhores.",
                "Automática",
                "Estável",
                "Intensiva",
                "Otimização do inventário",
                "Metas de combo",
                "Otimizar inventário",
                "Marcar artefatos",
                "Concluir marcação",
                "Escolha os artefatos prioritários desta exploração · Marcados: {0}",
                "Artefatos prioritários nesta exploração: {0}",
                "Artefatos prioritários: {0} · Outras metas ajustadas: {1}",
                "Prioridade · esquerda primeiro",
                "Evitar · preferir inativo",
                "Clique ou arraste as marcas; botão direito para remover.\n{0}: altere a meta de nível do artefato selecionado.\nAltera metas, sem mover os itens.",
                "Vincule “Alternar alvo travado”",
                "Escolha um espaço para colocar ou trocar.\nBotão direito para cancelar; rolagem para mudar de página.",
                "Otimização do inventário",
                "Ajustar metas de combo",
                "Voltar à fila de artefatos",
                "Usando automaticamente a predefinição atual do jogo",
                "Analisando automaticamente o inventário atual",
                "Metas ajustadas nesta exploração: {0}",
                "Manter ativo",
                "Escolher automaticamente",
                "Nível {0} ou superior",
                "Quantidade: {0} ou mais",
                "Quantidade: {0} ou menos",
                "Sem quantidade mínima (0)",
                "Não há metas desse tipo no inventário",
                "Página {0}/{1}",
                "Buscando com as metas atuais…",
                "Aplicando a disposição…",
                "Automático",
                "Prioridade",
                "Evitar",
            },
            ["pl-PL"] = new[]
            {
                "Analizowanie układu ekwipunku…",
                "Znaleziono lepszy układ. Stosowanie…",
                "Optymalizacja ekwipunku zakończona.",
                "To wyszukiwanie nie znalazło lepszego układu.",
                "Przed optymalizacją otwórz zwykły ekran ekwipunku.",
                "Ekwipunek nie jest jeszcze gotowy. Spróbuj za chwilę.",
                "Brak przedmiotów do optymalizacji.",
                "Nie można jednoznacznie rozpoznać części przedmiotów. Optymalizacja zatrzymana.",
                "Obecny stan ekwipunku nie jest obsługiwany. Pominięto tę próbę.",
                "Nie można zweryfikować efektów pozycji przedmiotów. Optymalizacja zatrzymana.",
                "Ten ekwipunek zawiera efekty pozycji wymagające weryfikacji u gospodarza. Optymalizacja przez pozostałych graczy nie jest jeszcze obsługiwana.",
                "Ekwipunek się zmienił. Optymalizacja anulowana.",
                "Ekwipunek został zamknięty. Optymalizacja anulowana.",
                "Zmieniło się piętro lub przebieg gry. Optymalizacja anulowana.",
                "Upłynął limit czasu stosowania układu. Operacja anulowana.",
                "Nie udało się ustalić bezpiecznej kolejności działań w ekwipunku.",
                "Układ zastosowano, ale efekty różnią się od przewidywanych. Optymalizacja zatrzymana. Możesz spróbować ponownie.",
                "Optymalizacja ekwipunku już trwa.",
                "Najpierw odłóż trzymany przedmiot lub anuluj przenoszenie.",
                "Podniesiono przedmiot. Optymalizacja zatrzymana.",
                "Nieoczekiwany błąd tymczasowo wyłączył optymalizację ekwipunku.",
                "Strategia optymalizacji",
                "Automatyczna dobiera wyszukiwanie do wielkości ekwipunku i oczekiwanej korzyści. Stabilna ogranicza czas i zmiany; Intensywna szuka dłużej, by uzyskać lepszy wynik.",
                "Automatyczna",
                "Stabilna",
                "Intensywna",
                "Optymalizacja ekwipunku",
                "Cele kombinacji",
                "Optymalizuj ekwipunek",
                "Oznacz artefakty",
                "Zakończ oznaczanie",
                "Wybierz priorytetowe artefakty na tę wyprawę · Oznaczone: {0}",
                "Priorytetowe artefakty w tej wyprawie: {0}",
                "Priorytetowe artefakty: {0} · Pozostałe zmiany celów: {1}",
                "Priorytet · od lewej",
                "Unikaj · najlepiej nieaktywne",
                "Klikaj lub przeciągaj znaczniki; prawy przycisk usuwa.\n{0}: zmień docelowy poziom wybranego artefaktu.\nZmienia cele bez przenoszenia przedmiotów.",
                "Przypisz „Zmień zablokowany cel”",
                "Wybierz pole, aby odłożyć lub zamienić.\nPrawy przycisk anuluje, kółko zmienia stronę.",
                "Optymalizacja ekwipunku",
                "Dostosuj cele kombinacji",
                "Wróć do kolejki artefaktów",
                "Automatyczne uwzględnianie bieżącego zestawu gry",
                "Automatyczna analiza bieżącego ekwipunku",
                "Zmiany celów w tej wyprawie: {0}",
                "Utrzymaj aktywność",
                "Wybierz automatycznie",
                "Poziom {0} lub wyższy",
                "Liczba: co najmniej {0}",
                "Liczba: najwyżej {0}",
                "Bez minimalnej liczby (0)",
                "Brak celów tego typu w ekwipunku",
                "Strona {0}/{1}",
                "Wyszukiwanie według bieżących celów…",
                "Stosowanie układu ekwipunku…",
                "Automatycznie",
                "Priorytet",
                "Unikaj",
            },
            ["ru-RU"] = new[]
            {
                "Анализ расположения предметов…",
                "Найдено лучшее расположение. Применение…",
                "Оптимизация инвентаря завершена.",
                "В ходе этого поиска лучшее расположение не найдено.",
                "Перед оптимизацией откройте обычный инвентарь.",
                "Инвентарь ещё не готов. Повторите попытку чуть позже.",
                "Нет предметов для оптимизации.",
                "Некоторые предметы невозможно однозначно различить. Оптимизация остановлена.",
                "Текущее состояние инвентаря не поддерживается. Эта попытка пропущена.",
                "Не удалось проверить эффекты расположения предметов. Оптимизация остановлена.",
                "В этом инвентаре есть эффекты расположения, требующие проверки на стороне хоста. Оптимизация другими игроками пока не поддерживается.",
                "Инвентарь изменился. Оптимизация отменена.",
                "Инвентарь закрыт. Оптимизация отменена.",
                "Этаж или состояние игры изменились. Оптимизация отменена.",
                "Время применения расположения истекло. Операция отменена.",
                "Не удалось определить безопасную последовательность действий в инвентаре.",
                "Расположение применено, но эффекты отличаются от прогноза. Оптимизация остановлена. Можно повторить попытку.",
                "Оптимизация инвентаря уже выполняется.",
                "Сначала положите удерживаемый предмет или отмените его перемещение.",
                "Вы взяли предмет. Оптимизация остановлена.",
                "Из-за непредвиденной ошибки оптимизация инвентаря временно отключена.",
                "Стратегия оптимизации",
                "Автоматическая выбирает поиск по размеру инвентаря и ожидаемой пользе. Стабильная сокращает время и изменения; Интенсивная дольше ищет лучший результат.",
                "Автоматическая",
                "Стабильная",
                "Интенсивная",
                "Оптимизация инвентаря",
                "Цели комбо",
                "Оптимизировать инвентарь",
                "Отметить артефакты",
                "Завершить выбор",
                "Выберите приоритетные артефакты на этот забег · Отмечено: {0}",
                "Приоритетные артефакты в этом забеге: {0}",
                "Приоритетные артефакты: {0} · Другие изменения целей: {1}",
                "Приоритет · слева направо",
                "Избегать · лучше неактивные",
                "Щёлкните или перетащите метку; ПКМ удаляет её.\n{0}: изменить целевой уровень выбранного артефакта.\nМеняются цели, а не расположение предметов.",
                "Назначьте «Сменить захваченную цель»",
                "Выберите ячейку для размещения или обмена.\nПКМ — отмена, колесо — смена страницы.",
                "Оптимизация инвентаря",
                "Настроить цели комбо",
                "Назад к очереди артефактов",
                "Автоматически учитывается текущий набор настроек игры",
                "Автоматический анализ текущего инвентаря",
                "Изменения целей в этом забеге: {0}",
                "Оставить активным",
                "Выбрать автоматически",
                "Уровень {0} или выше",
                "Количество: не менее {0}",
                "Количество: не более {0}",
                "Без минимального количества (0)",
                "В инвентаре нет целей этого типа",
                "Страница {0}/{1}",
                "Поиск по текущим целям…",
                "Применение расположения предметов…",
                "Автоматически",
                "Приоритет",
                "Избегать",
            },
            ["sv-SE"] = new[]
            {
                "Analyserar inventariets placering…",
                "Bättre placering hittad. Tillämpar…",
                "Inventarieoptimeringen är klar.",
                "Den här sökningen hittade ingen bättre placering.",
                "Öppna det vanliga inventariet före optimering.",
                "Inventariet är inte redo än. Försök igen om en stund.",
                "Det finns inga föremål att optimera.",
                "Vissa föremål kan inte identifieras entydigt. Optimeringen stoppades.",
                "Det aktuella inventarietillståndet stöds inte. Försöket hoppades över.",
                "Föremålens placeringseffekter kunde inte verifieras. Optimeringen stoppades.",
                "Inventariet innehåller placeringseffekter som måste verifieras av värden. Optimering av andra spelare stöds inte ännu.",
                "Inventariet ändrades. Optimeringen avbröts.",
                "Inventariet stängdes. Optimeringen avbröts.",
                "Våningen eller spelets förlopp ändrades. Optimeringen avbröts.",
                "Tidsgränsen för att tillämpa placeringen nåddes. Åtgärden avbröts.",
                "Ingen säker följd av inventarieåtgärder kunde skapas.",
                "Placeringen tillämpades, men effekterna skilde sig från beräkningen. Optimeringen stoppades. Du kan försöka igen.",
                "Inventarieoptimering pågår redan.",
                "Placera först föremålet du håller eller avbryt flytten.",
                "Du plockade upp ett föremål. Optimeringen stoppades.",
                "Ett oväntat fel har tillfälligt inaktiverat inventarieoptimeringen.",
                "Optimeringsstrategi",
                "Automatisk väljer sökning utifrån inventariestorlek och förväntad vinst. Stabil minskar tidsåtgång och ändringar; Intensiv söker längre efter bättre resultat.",
                "Automatisk",
                "Stabil",
                "Intensiv",
                "Inventarieoptimering",
                "Kombinationsmål",
                "Optimera inventariet",
                "Markera artefakter",
                "Avsluta markering",
                "Välj prioriterade artefakter för rundan · Markerade: {0}",
                "Prioriterade artefakter denna runda: {0}",
                "Prioriterade artefakter: {0} · Övriga måländringar: {1}",
                "Prioritet · vänster först",
                "Undvik · helst inaktiv",
                "Klicka/dra markeringar; högerklick tar bort.\n{0}: ändra nivåmålet för vald artefakt.\nÄndrar mål utan att flytta föremål.",
                "Tilldela ”Byt låst mål”",
                "Välj en ruta för att placera eller byta.\nHögerklick avbryter, skrollning byter sida.",
                "Inventarieoptimering",
                "Ändra kombinationsmål",
                "Tillbaka till artefaktkön",
                "Använder automatiskt spelets aktuella förval",
                "Analyserar automatiskt det aktuella inventariet",
                "Måländringar denna runda: {0}",
                "Håll aktiv",
                "Välj automatiskt",
                "Nivå {0} eller högre",
                "Antal: minst {0}",
                "Antal: högst {0}",
                "Inget minsta antal (0)",
                "Inga mål av denna typ i inventariet",
                "Sida {0}/{1}",
                "Söker med aktuella mål…",
                "Tillämpar inventarieplacering…",
                "Automatisk",
                "Prioritet",
                "Undvik",
            },
            ["tr-TR"] = new[]
            {
                "Envanter düzeni inceleniyor…",
                "Daha iyi bir düzen bulundu. Uygulanıyor…",
                "Envanter iyileştirmesi tamamlandı.",
                "Bu aramada daha iyi bir düzen bulunamadı.",
                "İyileştirmeden önce normal envanter ekranını açın.",
                "Envanter henüz hazır değil. Biraz sonra tekrar deneyin.",
                "İyileştirilecek eşya yok.",
                "Bazı eşyalar benzersiz olarak tanımlanamadı. İyileştirme durduruldu.",
                "Mevcut envanter durumu desteklenmiyor. Bu deneme atlandı.",
                "Eşyaların konum etkileri doğrulanamadı. İyileştirme durduruldu.",
                "Bu envanterde sunucu sahibinin doğrulaması gereken konum etkileri var. Diğer oyuncuların bu envanteri iyileştirmesi henüz desteklenmiyor.",
                "Envanter değişti. İyileştirme iptal edildi.",
                "Envanter kapatıldı. İyileştirme iptal edildi.",
                "Kat veya oyun akışı değişti. İyileştirme iptal edildi.",
                "Düzeni uygulama süresi aşıldı. İşlem iptal edildi.",
                "Güvenli bir envanter işlem sırası oluşturulamadı.",
                "Düzen uygulandı ancak etkiler tahminden farklı çıktı. İyileştirme durduruldu. Tekrar deneyebilirsiniz.",
                "Envanter iyileştirmesi zaten sürüyor.",
                "Önce tuttuğunuz eşyayı bırakın veya taşıma işlemini iptal edin.",
                "Bir eşya aldınız. İyileştirme durduruldu.",
                "Beklenmeyen bir hata nedeniyle envanter iyileştirmesi geçici olarak kapatıldı.",
                "İyileştirme stratejisi",
                "Otomatik, envanter boyutuna ve beklenen kazanca göre arama yöntemini seçer. Dengeli daha az zaman ve değişiklik ister; Yoğun daha iyi sonuçlar için daha uzun arar.",
                "Otomatik",
                "Dengeli",
                "Yoğun",
                "Envanter iyileştirmesi",
                "Kombo hedefleri",
                "Envanteri iyileştir",
                "Eserleri işaretle",
                "İşaretlemeyi bitir",
                "Bu keşifte öncelikli eserleri seçin · İşaretli: {0}",
                "Bu keşifte öncelikli eserler: {0}",
                "Öncelikli eserler: {0} · Diğer hedef değişiklikleri: {1}",
                "Öncelik · önce sol",
                "Kaçın · etkisiz olması tercih edilir",
                "İşaretlere tıklayın/sürükleyin; sağ tıkla kaldırın.\n{0}: seçili eserin seviye hedefini değiştirin.\nEşyaları taşımadan hedefleri değiştirir.",
                "“Kilitli hedefi değiştir” eylemini atayın",
                "Yerleştirmek veya takas etmek için yuva seçin.\nSağ tıkla iptal edin, tekerlekle sayfa değiştirin.",
                "Envanter iyileştirmesi",
                "Kombo hedeflerini ayarla",
                "Eser sırasına dön",
                "Oyunun mevcut ön ayarı otomatik kullanılıyor",
                "Mevcut envanter otomatik inceleniyor",
                "Bu keşifteki hedef değişiklikleri: {0}",
                "Etkin tut",
                "Otomatik seç",
                "Seviye {0} veya üstü",
                "Sayı: en az {0}",
                "Sayı: en fazla {0}",
                "Alt sayı sınırı yok (0)",
                "Envanterde bu tür hedef yok",
                "Sayfa {0}/{1}",
                "Mevcut hedeflerle aranıyor…",
                "Envanter düzeni uygulanıyor…",
                "Otomatik",
                "Öncelik",
                "Kaçın",
            },
            ["th-TH"] = new[]
            {
                "กำลังวิเคราะห์การจัดช่องเก็บของ…",
                "พบการจัดวางที่ดีกว่า กำลังนำไปใช้…",
                "ปรับช่องเก็บของเสร็จแล้ว",
                "การค้นหาครั้งนี้ไม่พบการจัดวางที่ดีกว่า",
                "โปรดเปิดหน้าช่องเก็บของปกติก่อนปรับการจัดวาง",
                "ช่องเก็บของยังไม่พร้อม โปรดลองอีกครั้งในอีกสักครู่",
                "ไม่มีไอเทมให้ปรับการจัดวาง",
                "ไม่สามารถแยกแยะไอเทมบางชิ้นได้ จึงหยุดการปรับช่องเก็บของ",
                "ยังไม่รองรับสถานะช่องเก็บของปัจจุบัน จึงข้ามการปรับครั้งนี้",
                "ไม่สามารถตรวจสอบเอฟเฟกต์จากตำแหน่งของไอเทมได้ จึงหยุดการปรับ",
                "ช่องเก็บของนี้มีเอฟเฟกต์จากตำแหน่งที่ต้องให้โฮสต์ตรวจสอบ ยังไม่รองรับการปรับโดยผู้เล่นที่ไม่ใช่โฮสต์",
                "ช่องเก็บของเปลี่ยนไป จึงยกเลิกการปรับครั้งนี้",
                "ปิดช่องเก็บของแล้ว จึงยกเลิกการปรับครั้งนี้",
                "ชั้นหรือสถานะการเล่นเปลี่ยนไป จึงยกเลิกการปรับครั้งนี้",
                "ใช้เวลาจัดวางเกินกำหนด จึงยกเลิกการปรับ",
                "ไม่สามารถหาลำดับการย้ายไอเทมที่ปลอดภัยได้",
                "จัดวางแล้ว แต่เอฟเฟกต์จริงต่างจากที่คาด จึงหยุดการปรับ คุณลองใหม่ได้",
                "กำลังปรับช่องเก็บของอยู่แล้ว",
                "โปรดวางไอเทมที่ถืออยู่หรือยกเลิกการย้ายก่อน",
                "คุณหยิบไอเทมขึ้นมา จึงหยุดการปรับช่องเก็บของ",
                "เกิดข้อผิดพลาดที่ไม่คาดคิด จึงปิดการปรับช่องเก็บของชั่วคราว",
                "แนวทางปรับช่องเก็บของ",
                "อัตโนมัติเลือกวิธีค้นหาจากขนาดช่องเก็บของและผลที่คาดว่าจะได้ คงที่ลดเวลาและการเปลี่ยนแปลง ส่วนเข้มข้นใช้เวลามากขึ้นเพื่อค้นหาผลที่ดีกว่า",
                "อัตโนมัติ",
                "คงที่",
                "เข้มข้น",
                "ปรับช่องเก็บของ",
                "เป้าหมายคอมโบ",
                "ปรับช่องเก็บของให้เหมาะสม",
                "ทำเครื่องหมายอาร์ติแฟกต์",
                "เสร็จสิ้นการทำเครื่องหมาย",
                "เลือกอาร์ติแฟกต์ที่ให้ความสำคัญในการสำรวจนี้ · ทำเครื่องหมายแล้ว: {0}",
                "อาร์ติแฟกต์สำคัญในการสำรวจนี้: {0}",
                "อาร์ติแฟกต์สำคัญ: {0} · เป้าหมายอื่นที่ปรับ: {1}",
                "ลำดับความสำคัญ · ซ้ายก่อน",
                "หลีกเลี่ยง · เน้นไม่ให้ทำงาน",
                "คลิกหรือลากเครื่องหมาย คลิกขวาเพื่อนำออก\n{0}: ปรับเป้าหมายระดับของอาร์ติแฟกต์ที่เลือก\nเปลี่ยนเฉพาะเป้าหมาย ไม่ย้ายไอเทม",
                "โปรดกำหนดปุ่ม “สลับเป้าหมายที่ล็อก”",
                "เลือกช่องเพื่อวางหรือสลับ\nคลิกขวาเพื่อยกเลิก เลื่อนล้อเมาส์เพื่อเปลี่ยนหน้า",
                "ปรับช่องเก็บของ",
                "ปรับเป้าหมายคอมโบ",
                "กลับสู่ลำดับอาร์ติแฟกต์",
                "อ้างอิงชุดตั้งค่าปัจจุบันของเกมโดยอัตโนมัติ",
                "วิเคราะห์ช่องเก็บของปัจจุบันโดยอัตโนมัติ",
                "เป้าหมายที่ปรับในการสำรวจนี้: {0}",
                "ให้ทำงาน",
                "เลือกอัตโนมัติ",
                "ระดับ {0} ขึ้นไป",
                "จำนวนอย่างน้อย {0}",
                "จำนวนไม่เกิน {0}",
                "ไม่กำหนดจำนวนขั้นต่ำ (0)",
                "ไม่มีเป้าหมายประเภทนี้ในช่องเก็บของ",
                "หน้า {0}/{1}",
                "กำลังค้นหาตามเป้าหมายปัจจุบัน…",
                "กำลังจัดวางไอเทม…",
                "อัตโนมัติ",
                "ให้ความสำคัญ",
                "หลีกเลี่ยง",
            },
        };
    }
}
