using System.Collections.Generic;

namespace SephiriaEnhancements.Inventory
{
    internal static partial class InventoryOptimizationLocalization
    {
        private static readonly Dictionary<string, string[]> Texts = new()
        {
            ["en-US"] = new[]
            {
                "Finding a better arrangement…",
                "Moving items…",
                "Inventory arrangement complete.",
                "No better arrangement found this time. Inventory unchanged.",
                "Smart Arrange requires an open backpack that allows normal item movement.",
                "Inventory not ready. Try again shortly.",
                "No items to arrange.",
                "Some items could not be identified. Arrangement stopped.",
                "Some item effects are not supported yet. Inventory unchanged.",
                "Could not confirm item effects after moving. Arrangement stopped.",
                "Inventory changed. Arrangement cancelled.",
                "Backpack arrangement is no longer available in this view. Arrangement stopped.",
                "The game has changed. Arrangement cancelled.",
                "Moving items took too long. Arrangement stopped.",
                "Could not prepare the item moves. Inventory unchanged.",
                "Item effects differed from what was expected. Arrangement stopped. Some items may have moved; check your inventory.",
                "Inventory arrangement is already in progress.",
                "Place or cancel the item you are holding first.",
                "Arrangement stopped because you picked up an item.",
                "Arrangement failed and is unavailable for this floor.",
                "Smart Arrange mode",
                "Open your backpack, put down held items, then choose Arrange. Quick saves time; Thorough looks longer.\nPut your most important artifacts first. Keep unwanted effects in the inactive area. Must goals come first, then earlier artifacts receive levels and damage bonuses first.\nColors show level or activation goals. Choose bonus and MP-cost preferences under Special effects. Interrupted moves are not undone automatically.",
                "Automatic",
                "Quick",
                "Thorough",
                "SMART ARRANGE",
                "Combo targets",
                "ARRANGE",
                "MARK ARTIFACTS",
                "FINISH MARKING",
                "Select priority artifacts for this run · {0} marked",
                "{0} priority artifacts for this run",
                "{0} prioritized · {1} other requirements",
                "PRIORITY · LEFT TO RIGHT",
                "KEEP THESE INACTIVE",
                "Click/drag marks; right-click removes marks.\n{0}\nGreen met · Yellow partial · Red unmet",
                "Select an artifact, then choose Edit goals",
                "Choose a slot to place or swap.\nRight-click to cancel.\nScroll to turn pages.",
                "SMART ARRANGE",
                "COMBO SETTINGS",
                "ARTIFACT SETTINGS",
                "Uses your game preset when arranging",
                "Uses your current items when arranging",
                "{0} requirements set",
                "Keep active",
                "Automatic",
                "Level {0} or higher",
                "MIN {0}",
                "MAX {0}",
                "No minimum",
                "No combos to configure",
                "PAGE {0}/{1}",
                "Finding a better arrangement…",
                "Moving items…",
                "AUTO",
                "MIN",
                "MAX",
                "Must",
                "Try",
                "Your Must requirements cannot all be met. Inventory unchanged; adjust the requirements.",
                "No arrangement meeting all Must requirements found this time. Inventory unchanged. Try Thorough or adjust your requirements.",
                "EDIT GOALS",
                "{0}: edit goals",
                "Try: best effort. Must (!): required to arrange.",
                "Saved for future runs. All Must goals must be met before arranging.",
                "Confirm: move mark; {0}: remove mark\nSelect an artifact to edit goals\nGreen met · Yellow partial · Red unmet",
                "Choose a slot and confirm to place or swap.\n{0}: cancel",
                "Auto · {0}",
                "Auto (cautious upgrades) · {0}",
                "Awaiting arrangement result",
                "Met",
                "Partly met",
                "Unmet",
                "Level {0}",
                "Active",
                "Inactive",
                "Keep inactive",
                "{0} · Arrangement goal",
                "Target",
                "Requirement",
                "Try to meet",
                "Must meet",
                "When arranging: {0}.\nArrange even if this goal cannot be met.",
                "When arranging: {0}.\nArrange only when all required goals are met.",
                "Back to artifacts",
            },
            ["zh-CN"] = new[]
            {
                "正在寻找更好的摆放……",
                "正在移动物品……",
                "背包整理完成。",
                "本次未找到更好的摆放，背包保持原样。",
                "智能整理需要背包已打开，且允许正常移动物品。",
                "背包尚未就绪，请稍后重试。",
                "背包中没有可整理的物品。",
                "无法识别部分物品，整理已停止。",
                "暂不支持部分物品的效果，本次未整理。",
                "无法确认物品摆放后的效果，整理已停止。",
                "背包已发生变化，本次整理已取消。",
                "当前界面已无法整理背包，本次整理已停止。",
                "游戏状态已变化，本次整理已取消。",
                "移动物品耗时过长，整理已停止。",
                "暂时无法完成物品移动，本次未整理。",
                "物品移动后的效果与预期不符，整理已停止。部分物品可能已移动，请检查背包。",
                "正在整理背包。",
                "请先放下或取消当前拿起的物品。",
                "你拿起了物品，本次整理已停止。",
                "整理出错，本层暂时无法使用。",
                "智能整理方式",
                "打开背包，放下手持物品后点击「整理」。快速少等一会儿，精细会找得更久。\n重要神器排前面，不想生效的放在下方。先满足「必须」，再优先给前面的神器分配等级与伤害加成。\n颜色只表示等级或生效要求。在「特殊效果」中选择加成与耗蓝偏好。整理中断后，已移动的物品不会自动归位。",
                "自动",
                "快速",
                "精细",
                "智能整理",
                "连招目标",
                "整理",
                "标记神器",
                "完成标记",
                "选择本次探索的优先神器 · 已标记 {0} 件",
                "本次探索：{0} 件优先神器",
                "优先神器 {0} 件 · 其他要求 {1} 项",
                "优先神器 · 从左到右",
                "这些神器不要生效",
                "点击或拖动标记换位；右键移除标记\n{0}\n绿：满足　黄：部分　红：未满足",
                "选中神器后，点击「调整要求」",
                "选择格子放下或交换。\n右键取消；滚轮翻页。",
                "智能整理",
                "连招设置",
                "神器设置",
                "整理时参考游戏预设",
                "按当前背包自动整理",
                "已设置 {0} 项要求",
                "只需生效",
                "自动",
                "至少 {0} 级",
                "至少 {0}",
                "最多 {0}",
                "不设下限",
                "暂无连招可设置",
                "第 {0}/{1} 页",
                "正在寻找更好的摆放……",
                "正在移动物品……",
                "自动",
                "至少",
                "最多",
                "必须",
                "尽量",
                "无法同时满足全部「必须」要求，背包保持原样。请调整要求。",
                "本次未找到满足全部「必须」要求的摆放，背包保持原样。可尝试精细整理或调整要求。",
                "调整要求",
                "{0}：调整要求",
                "尽量：争取满足；必须（!）：全部满足才整理。",
                "下次探索也会保留。全部「必须」要求满足后才整理。",
                "确认：移动标记；{0}：移除标记\n选中神器后可调整要求\n绿：满足　黄：部分　红：未满足",
                "选择格子并确认，放下或交换标记。\n{0}：取消",
                "自动 · {0}",
                "自动（谨慎升级） · {0}",
                "等待整理结果",
                "已满足",
                "部分满足",
                "本次未满足",
                "当前 {0} 级",
                "已生效",
                "未生效",
                "保持不生效",
                "{0} · 整理目标",
                "目标",
                "要求",
                "尽量满足",
                "必须满足",
                "整理时：{0}。\n无法满足此目标时，仍可整理。",
                "整理时：{0}。\n全部「必须满足」的目标都达到，才会整理。",
                "返回神器列表",
            },
            ["zh-TW"] = new[]
            {
                "正在尋找更好的擺放……",
                "正在移動物品……",
                "背包整理完成。",
                "本次未找到更好的擺放，背包保持原樣。",
                "智慧整理需要背包已開啟，且允許正常移動物品。",
                "背包尚未就緒，請稍後重試。",
                "背包中沒有可整理的物品。",
                "無法識別部分物品，整理已停止。",
                "暫不支援部分物品的效果，本次未整理。",
                "無法確認物品擺放後的效果，整理已停止。",
                "背包已發生變化，本次整理已取消。",
                "目前介面已無法整理背包，本次整理已停止。",
                "遊戲狀態已變化，本次整理已取消。",
                "移動物品耗時過長，整理已停止。",
                "暫時無法完成物品移動，本次未整理。",
                "物品移動後的效果與預期不符，整理已停止。部分物品可能已移動，請檢查背包。",
                "正在整理背包。",
                "請先放下或取消目前拿起的物品。",
                "你拿起了物品，本次整理已停止。",
                "整理出錯，本層暫時無法使用。",
                "智慧整理方式",
                "打開背包，放下手持物品後點擊「整理」。快速少等一會兒，精細會找得更久。\n重要神器排前面，不想生效的放在下方。先滿足「必須」，再優先給前面的神器分配等級與傷害加成。\n顏色只表示等級或生效要求。在「特殊效果」中選擇加成與耗魔偏好。整理中斷後，已移動的物品不會自動歸位。",
                "自動",
                "快速",
                "精細",
                "智慧整理",
                "連招目標",
                "整理",
                "標記神器",
                "完成標記",
                "選擇本次探索的優先神器 · 已標記 {0} 件",
                "本次探索：{0} 件優先神器",
                "優先神器 {0} 件 · 其他要求 {1} 項",
                "優先神器 · 從左到右",
                "這些神器不要生效",
                "點擊或拖動標記換位；右鍵移除標記\n{0}\n綠：滿足　黃：部分　紅：未滿足",
                "選取神器後，點擊「調整要求」",
                "選擇格子放下或交換。\n右鍵取消；滾輪翻頁。",
                "智慧整理",
                "連招設定",
                "神器設定",
                "整理時參考遊戲預設",
                "依目前背包自動整理",
                "已設定 {0} 項要求",
                "只需生效",
                "自動",
                "至少 {0} 級",
                "至少 {0}",
                "最多 {0}",
                "不設下限",
                "暫無連招可設定",
                "第 {0}/{1} 頁",
                "正在尋找更好的擺放……",
                "正在移動物品……",
                "自動",
                "至少",
                "最多",
                "必須",
                "盡量",
                "無法同時滿足全部「必須」要求，背包保持原樣。請調整要求。",
                "本次未找到滿足全部「必須」要求的擺放，背包保持原樣。可嘗試精細整理或調整要求。",
                "調整要求",
                "{0}：調整要求",
                "盡量：爭取滿足；必須（!）：全部滿足才整理。",
                "下次探索也會保留。全部「必須」要求滿足後才整理。",
                "確認：移動標記；{0}：移除標記\n選取神器後可調整要求\n綠：滿足　黃：部分　紅：未滿足",
                "選擇格子並確認，放下或交換標記。\n{0}：取消",
                "自動 · {0}",
                "自動（謹慎升級） · {0}",
                "等待整理結果",
                "已滿足",
                "部分滿足",
                "本次未滿足",
                "目前 {0} 級",
                "已生效",
                "未生效",
                "保持不生效",
                "{0} · 整理目標",
                "目標",
                "要求",
                "盡量滿足",
                "必須滿足",
                "整理時：{0}。\n無法滿足此目標時，仍可整理。",
                "整理時：{0}。\n所有「必須滿足」的目標都達成，才會整理。",
                "返回神器列表",
            },
            ["ja-JP"] = new[]
            {
                "インベントリの配置を分析中…",
                "より良い配置が見つかりました。適用中…",
                "インベントリの最適化が完了しました。",
                "今回の検索では、より良い配置は見つかりませんでした。",
                "通常のインベントリ画面を開いてから最適化してください。",
                "インベントリの準備ができていません。少し待ってから再試行してください。",
                "最適化できるアイテムがありません。",
                "一部のアイテムを区別できないため、最適化を停止しました。",
                "現在のインベントリ状態では最適化できないため、今回はスキップしました。",
                "アイテムの配置効果を確認できないため、最適化を停止しました。",
                "インベントリが変化したため、最適化をキャンセルしました。",
                "インベントリを閉じたため、最適化をキャンセルしました。",
                "フロアやゲームの進行状態が変わったため、最適化をキャンセルしました。",
                "配置の適用がタイムアウトしたため、キャンセルしました。",
                "安全に配置を変更する手順を作成できませんでした。",
                "配置は適用されましたが、効果が予測と異なったため停止しました。再試行できます。",
                "インベントリの最適化は既に進行中です。",
                "手に持っているアイテムを置くか、操作をキャンセルしてください。",
                "アイテムを持ち上げたため、最適化を停止しました。",
                "予期しないエラーのため、インベントリの最適化を一時的に無効にしました。",
                "最適化の方針",
                "バッグを開き、持っているアイテムを置いて整理を選びます。高速は待ち時間が短く、念入りは長く探します。\n重要なアーティファクトを前へ、不要な効果は無効の欄へ。必須目標を優先し、前のアイテムからレベルとダメージ補正を割り当てます。\n色はレベルか有効化の達成度です。特殊効果で補正とMP消費を選べます。中断しても移動済みのアイテムは自動で戻りません。",
                "自動",
                "高速",
                "入念",
                "インベントリの最適化",
                "コンボ目標",
                "インベントリを最適化",
                "アーティファクトを指定",
                "指定を完了",
                "今回の探索で優先するアーティファクトを選択 · 指定数：{0}",
                "今回の探索で優先するアーティファクト：{0}",
                "優先アーティファクト：{0} · その他の目標調整：{1}",
                "優先 · 左から順に",
                "これらは無効のまま",
                "印をクリック／ドラッグして移動、右クリックで削除。\n{0}：選択中のアーティファクトのレベル目標を変更。\n目標のみを変更し、アイテムは移動しません。",
                "「ロック対象切替」を割り当ててください",
                "配置または交換するマスを選択。\n右クリックでキャンセル、スクロールでページ切替。",
                "インベントリの最適化",
                "コンボ目標を調整",
                "アーティファクトの優先順に戻る",
                "現在のゲーム内プリセットを自動で参照",
                "現在のインベントリを自動で分析",
                "今回の探索の目標調整：{0}",
                "有効にする",
                "自動で選択",
                "レベル {0} 以上",
                "カウント {0} 以上",
                "カウント {0} 以下",
                "最低カウントなし（0）",
                "この種類の目標はインベントリにありません",
                "{0}/{1} ページ",
                "現在の目標で検索中…",
                "インベントリの配置を適用中…",
                "自動",
                "優先",
                "回避",
                "必須",
                "できれば",
                "必須条件をすべて満たすことはできません。配置は変更していません。条件を調整してください。",
                "今回は必須条件をすべて満たす配置が見つかりませんでした。配置は変更していません。詳細な整理か条件の調整を試してください。",
                "条件を調整",
                "{0}: 条件を調整",
                "できれば: 可能な限り。必須(!): すべて満たす場合のみ整理。",
                "次の探索でも保存。すべての必須目標を満たしてから整理します。",
                "決定: マークを移動; {0}: マークを削除\n神器を選んで条件を調整\n緑: 達成 · 黄: 一部 · 赤: 未達成",
                "マスを選んで決定し、配置または交換。\n{0}: キャンセル",
                "自動 · {0}",
                "自動（慎重に強化） · {0}",
                "整理結果を待っています",
                "達成",
                "一部達成",
                "未達成",
                "レベル {0}",
                "有効",
                "無効",
                "無効のままにする",
                "{0} · 整理目標",
                "目標",
                "条件",
                "できるだけ満たす",
                "必ず満たす",
                "整理時：{0}。\nこの目標を満たせなくても整理します。",
                "整理時：{0}。\n必須の目標をすべて満たす場合のみ整理します。",
                "アーティファクト一覧へ",
            },
            ["ko-KR"] = new[]
            {
                "인벤토리 배치 분석 중…",
                "더 나은 배치를 찾았습니다. 적용 중…",
                "인벤토리 최적화를 완료했습니다.",
                "이번 검색에서는 더 나은 배치를 찾지 못했습니다.",
                "일반 인벤토리 화면을 연 후 최적화해 주세요.",
                "인벤토리가 아직 준비되지 않았습니다. 잠시 후 다시 시도해 주세요.",
                "최적화할 아이템이 없습니다.",
                "일부 아이템을 구별할 수 없어 최적화를 중단했습니다.",
                "현재 인벤토리 상태는 최적화를 지원하지 않아 이번 시도를 건너뛰었습니다.",
                "아이템의 위치 효과를 확인할 수 없어 최적화를 중단했습니다.",
                "인벤토리가 변경되어 최적화를 취소했습니다.",
                "인벤토리를 닫아 최적화를 취소했습니다.",
                "층이나 게임 진행 상태가 변경되어 최적화를 취소했습니다.",
                "인벤토리 배치 적용 시간이 초과되어 취소했습니다.",
                "안전하게 배치를 변경할 순서를 만들지 못했습니다.",
                "배치는 적용되었지만 실제 효과가 예측과 달라 최적화를 중단했습니다. 다시 시도할 수 있습니다.",
                "이미 인벤토리 최적화가 진행 중입니다.",
                "들고 있는 아이템을 먼저 놓거나 이동을 취소해 주세요.",
                "아이템을 집어 들어 최적화를 중단했습니다.",
                "예기치 않은 오류로 인벤토리 최적화를 일시적으로 비활성화했습니다.",
                "인벤토리 최적화 성향",
                "가방을 열고 든 아이템을 내려놓은 뒤 정리를 선택하세요. 빠름은 대기 시간이 짧고, 꼼꼼은 더 오래 찾습니다.\n중요한 아티팩트를 앞에, 원치 않는 효과는 비활성 영역에 놓으세요. 필수 목표 다음으로 앞선 아이템에 레벨과 피해 보너스를 배분합니다.\n색은 레벨이나 활성화 목표만 표시합니다. 특수 효과에서 보너스와 MP 소모를 선택하세요. 중단되어도 옮긴 아이템은 자동 복구되지 않습니다.",
                "자동",
                "빠름",
                "정밀",
                "인벤토리 최적화",
                "콤보 목표",
                "인벤토리 최적화",
                "아티팩트 표시",
                "표시 완료",
                "이번 탐험에서 우선할 아티팩트 선택 · 표시: {0}",
                "이번 탐험의 우선 아티팩트: {0}",
                "우선 아티팩트: {0} · 기타 목표 조정: {1}",
                "우선순위 · 왼쪽부터",
                "이 아티팩트는 비활성 유지",
                "표시를 클릭하거나 드래그해 이동, 우클릭으로 제거합니다.\n{0}: 가리키거나 선택한 아티팩트의 레벨 목표를 변경합니다.\n목표만 바꾸며 아이템은 이동하지 않습니다.",
                "‘고정 대상 전환’을 지정해 주세요",
                "놓거나 교환할 칸을 선택하세요.\n우클릭으로 취소, 스크롤로 페이지를 넘깁니다.",
                "인벤토리 최적화",
                "콤보 목표 조정",
                "아티팩트 우선순위로 돌아가기",
                "현재 게임 프리셋을 자동으로 참조",
                "현재 인벤토리를 자동으로 분석",
                "이번 탐험의 목표 조정: {0}",
                "활성 상태 유지",
                "자동 선택",
                "레벨 {0} 이상",
                "개수 {0} 이상",
                "개수 {0} 이하",
                "최소 개수 없음 (0)",
                "인벤토리에 이 유형의 목표가 없습니다",
                "{0}/{1} 페이지",
                "현재 목표로 검색 중…",
                "인벤토리 배치 적용 중…",
                "자동",
                "우선",
                "제외",
                "필수",
                "가능하면",
                "필수 조건을 모두 충족할 수 없습니다. 가방은 그대로입니다. 조건을 조정하세요.",
                "이번에는 필수 조건을 모두 충족하는 배치를 찾지 못했습니다. 가방은 그대로입니다. 정밀 정리나 조건 조정을 시도하세요.",
                "조건 조정",
                "{0}: 조건 조정",
                "가능하면: 최대한 충족. 필수(!): 모두 충족해야 정리.",
                "다음 탐험에도 저장됩니다. 모든 필수 목표를 충족해야 정리합니다.",
                "확인: 표시 이동; {0}: 표시 제거\n유물을 선택해 조건 조정\n초록: 충족 · 노랑: 일부 · 빨강: 미충족",
                "칸을 선택하고 확인해 놓거나 교환하세요.\n{0}: 취소",
                "자동 · {0}",
                "자동 (신중한 강화) · {0}",
                "정리 결과 대기 중",
                "충족",
                "일부 충족",
                "미충족",
                "레벨 {0}",
                "활성",
                "비활성",
                "비활성 유지",
                "{0} · 정리 목표",
                "목표",
                "조건",
                "가능하면 충족",
                "반드시 충족",
                "정리 시: {0}.\n이 목표를 달성하지 못해도 정리합니다.",
                "정리 시: {0}.\n모든 필수 목표를 달성해야 정리합니다.",
                "아티팩트 목록으로",
            },
            ["de-DE"] = new[]
            {
                "Inventaranordnung wird analysiert…",
                "Bessere Anordnung gefunden. Wird angewendet…",
                "Inventaroptimierung abgeschlossen.",
                "Bei dieser Suche wurde keine bessere Anordnung gefunden.",
                "Öffne vor der Optimierung das normale Inventar.",
                "Das Inventar ist noch nicht bereit. Versuche es gleich erneut.",
                "Keine Gegenstände zum Optimieren vorhanden.",
                "Einige Gegenstände lassen sich nicht eindeutig zuordnen. Optimierung gestoppt.",
                "Der aktuelle Inventarzustand wird nicht unterstützt. Optimierung übersprungen.",
                "Positionseffekte der Gegenstände konnten nicht geprüft werden. Optimierung gestoppt.",
                "Das Inventar hat sich geändert. Optimierung abgebrochen.",
                "Das Inventar wurde geschlossen. Optimierung abgebrochen.",
                "Die Ebene oder der Spielablauf hat sich geändert. Optimierung abgebrochen.",
                "Zeitüberschreitung beim Anwenden der Anordnung. Vorgang abgebrochen.",
                "Es konnte keine sichere Abfolge von Inventaraktionen ermittelt werden.",
                "Die Anordnung wurde angewendet, aber die Effekte weichen von der Vorhersage ab. Optimierung gestoppt. Du kannst es erneut versuchen.",
                "Die Inventaroptimierung läuft bereits.",
                "Lege zuerst den gehaltenen Gegenstand ab oder brich das Verschieben ab.",
                "Du hast einen Gegenstand aufgenommen. Optimierung gestoppt.",
                "Ein unerwarteter Fehler hat die Inventaroptimierung vorübergehend deaktiviert.",
                "Optimierungsstrategie",
                "Rucksack öffnen, gehaltene Gegenstände ablegen und Sortieren wählen. Schnell spart Zeit; Gründlich sucht länger.\nWichtige Artefakte nach vorn, unerwünschte Effekte in den Inaktiv-Bereich. Muss-Ziele zuerst, dann erhalten frühere Artefakte zuerst Stufen und Schadensboni.\nFarben zeigen Stufen- oder Aktivierungsziele. Unter Sondereffekte wählst du Boni und MP-Kosten. Unterbrochene Bewegungen werden nicht automatisch rückgängig gemacht.",
                "Automatisch",
                "Schnell",
                "Gründlich",
                "Inventaroptimierung",
                "Kombo-Ziele",
                "Inventar optimieren",
                "Artefakte markieren",
                "Markierung beenden",
                "Artefakte für diesen Lauf priorisieren · Markiert: {0}",
                "Priorisierte Artefakte in diesem Lauf: {0}",
                "Priorisierte Artefakte: {0} · Weitere Zielanpassungen: {1}",
                "PRIORITÄT · VON LINKS NACH RECHTS",
                "DIESE INAKTIV HALTEN",
                "Markierungen anklicken/ziehen; Rechtsklick entfernt sie.\n{0}: Stufenziel des gewählten Artefakts ändern.\nÄndert Ziele, verschiebt keine Gegenstände.",
                "Belege „Festes Ziel wechseln“",
                "Feld zum Ablegen oder Tauschen wählen.\nRechtsklick zum Abbrechen, Scrollen zum Blättern.",
                "Inventaroptimierung",
                "Kombo-Ziele anpassen",
                "Zurück zur Artefaktliste",
                "Aktuelle Spielvorlage wird automatisch berücksichtigt",
                "Aktuelles Inventar wird automatisch analysiert",
                "Zielanpassungen in diesem Lauf: {0}",
                "Aktiv halten",
                "Automatisch wählen",
                "Stufe {0} oder höher",
                "Anzahl: mindestens {0}",
                "Anzahl: höchstens {0}",
                "Keine Mindestanzahl (0)",
                "Keine Ziele dieser Art im Inventar",
                "Seite {0}/{1}",
                "Suche mit den aktuellen Zielen…",
                "Inventaranordnung wird angewendet…",
                "Automatisch",
                "Priorisieren",
                "Vermeiden",
                "Pflicht",
                "Möglichst",
                "Nicht alle Pflichtbedingungen sind erfüllbar. Inventar unverändert; Bedingungen anpassen.",
                "Diesmal keine Anordnung für alle Pflichtbedingungen gefunden. Inventar unverändert. Gründlicher suchen oder Bedingungen anpassen.",
                "ZIELE BEARBEITEN",
                "{0}: Ziele bearbeiten",
                "Möglichst: bestes Bemühen. Pflicht (!): zum Anordnen erforderlich.",
                "Auch für spätere Erkundungen gespeichert. Alle Muss-Ziele müssen vor dem Sortieren erfüllt sein.",
                "Bestätigen: Markierung bewegen; {0}: entfernen\nArtefakt wählen, um Ziele zu bearbeiten\nGrün erfüllt · Gelb teilweise · Rot unerfüllt",
                "Feld wählen und zum Ablegen oder Tauschen bestätigen.\n{0}: abbrechen",
                "Automatisch · {0}",
                "Auto (vorsichtig aufwerten) · {0}",
                "Warte auf Sortierergebnis",
                "Erfüllt",
                "Teilweise erfüllt",
                "Unerfüllt",
                "Stufe {0}",
                "Aktiv",
                "Inaktiv",
                "Inaktiv halten",
                "{0} · Sortierziel",
                "Ziel",
                "Bedingung",
                "Möglichst erfüllen",
                "Muss erfüllt sein",
                "Beim Sortieren: {0}.\nAuch sortieren, wenn dieses Ziel nicht erreicht wird.",
                "Beim Sortieren: {0}.\nNur sortieren, wenn alle Pflichtziele erfüllt sind.",
                "Zurück zu Artefakten",
            },
            ["fr-FR"] = new[]
            {
                "Analyse de l’inventaire…",
                "Meilleure disposition trouvée. Application…",
                "Optimisation de l’inventaire terminée.",
                "Cette recherche n’a pas trouvé de meilleure disposition.",
                "Ouvrez l’inventaire standard avant de l’optimiser.",
                "L’inventaire n’est pas encore prêt. Réessayez dans un instant.",
                "Aucun objet à optimiser.",
                "Certains objets ne peuvent pas être identifiés de façon unique. Optimisation arrêtée.",
                "L’état actuel de l’inventaire n’est pas pris en charge. Tentative ignorée.",
                "Impossible de vérifier les effets de position des objets. Optimisation arrêtée.",
                "L’inventaire a changé. Optimisation annulée.",
                "L’inventaire a été fermé. Optimisation annulée.",
                "L’étage ou le déroulement du jeu a changé. Optimisation annulée.",
                "L’application de la disposition a expiré et a été annulée.",
                "Impossible de déterminer une suite sûre d’actions dans l’inventaire.",
                "La disposition a été appliquée, mais ses effets diffèrent des prévisions. Optimisation arrêtée. Vous pouvez réessayer.",
                "L’optimisation de l’inventaire est déjà en cours.",
                "Posez d’abord l’objet tenu ou annulez son déplacement.",
                "Vous avez pris un objet. Optimisation arrêtée.",
                "Une erreur inattendue a temporairement désactivé l’optimisation de l’inventaire.",
                "Stratégie d’optimisation",
                "Ouvre le sac, pose les objets tenus et choisis Ranger. Rapide réduit l’attente ; Minutieux cherche plus longtemps.\nPlace les artefacts importants en premier et les effets indésirables dans la zone inactive. Les objectifs obligatoires priment, puis les premiers artefacts reçoivent niveaux et bonus de dégâts.\nLes couleurs indiquent le niveau ou l’activation. Choisis bonus et PM dans Effets spéciaux. Une interruption n’annule pas les déplacements déjà faits.",
                "Automatique",
                "Rapide",
                "Approfondie",
                "Optimisation de l’inventaire",
                "Objectifs de combo",
                "Optimiser l’inventaire",
                "Marquer les artefacts",
                "Terminer le marquage",
                "Choisissez les artefacts prioritaires pour cette exploration · Marqués : {0}",
                "Artefacts prioritaires pour cette exploration : {0}",
                "Artefacts prioritaires : {0} · Autres objectifs modifiés : {1}",
                "PRIORITÉ · DE GAUCHE À DROITE",
                "GARDER CEUX-CI INACTIFS",
                "Cliquez/glissez les marques ; clic droit pour retirer.\n{0} : modifier le niveau visé de l’artefact sélectionné.\nChange les objectifs sans déplacer les objets.",
                "Attribuez « Changer de cible verrouillée »",
                "Choisissez une case pour poser ou échanger.\nClic droit pour annuler, molette pour changer de page.",
                "Optimisation de l’inventaire",
                "Ajuster les objectifs de combo",
                "Retour à la liste des artefacts",
                "Utilisation automatique du préréglage actuel du jeu",
                "Analyse automatique de l’inventaire actuel",
                "Objectifs modifiés pour cette exploration : {0}",
                "Garder actif",
                "Choisir automatiquement",
                "Niveau {0} ou plus",
                "Quantité : au moins {0}",
                "Quantité : au plus {0}",
                "Aucune quantité minimale (0)",
                "Aucun objectif de ce type dans l’inventaire",
                "Page {0}/{1}",
                "Recherche selon les objectifs actuels…",
                "Application de la disposition…",
                "Automatique",
                "Prioritaire",
                "Éviter",
                "Obligatoire",
                "Si possible",
                "Impossible de remplir toutes les conditions obligatoires. Inventaire inchangé ; ajustez les conditions.",
                "Aucune disposition remplissant toutes les conditions obligatoires trouvée cette fois. Inventaire inchangé. Essayez une recherche approfondie ou ajustez les conditions.",
                "MODIFIER LES OBJECTIFS",
                "{0} : modifier les objectifs",
                "Si possible : au mieux. Obligatoire (!) : nécessaire pour ranger.",
                "Conservé pour les prochaines explorations. Tous les objectifs obligatoires doivent être atteints pour ranger.",
                "Confirmer : déplacer la marque ; {0} : retirer\nChoisissez un artefact pour modifier les objectifs\nVert : rempli · Jaune : partiel · Rouge : non rempli",
                "Choisissez une case et confirmez pour placer ou échanger.\n{0} : annuler",
                "Automatique · {0}",
                "Auto (améliorations prudentes) · {0}",
                "En attente du résultat du rangement",
                "Rempli",
                "Partiellement rempli",
                "Non rempli",
                "Niveau {0}",
                "Actif",
                "Inactif",
                "Garder inactif",
                "{0} · Objectif de rangement",
                "Objectif",
                "Condition",
                "Si possible",
                "Obligatoire",
                "Lors du rangement : {0}.\nRanger même si cet objectif ne peut pas être atteint.",
                "Lors du rangement : {0}.\nRanger uniquement si tous les objectifs obligatoires sont atteints.",
                "Retour aux artefacts",
            },
            ["es-ES"] = new[]
            {
                "Analizando el inventario…",
                "Se ha encontrado una disposición mejor. Aplicando…",
                "Optimización del inventario completada.",
                "Esta búsqueda no ha encontrado una disposición mejor.",
                "Abre el inventario normal antes de optimizarlo.",
                "El inventario aún no está listo. Vuelve a intentarlo en un momento.",
                "No hay objetos que optimizar.",
                "No se pueden identificar de forma única algunos objetos. Optimización detenida.",
                "El estado actual del inventario no admite la optimización. Se ha omitido este intento.",
                "No se han podido verificar los efectos de posición. Optimización detenida.",
                "El inventario ha cambiado. Optimización cancelada.",
                "Se ha cerrado el inventario. Optimización cancelada.",
                "Ha cambiado la planta o el estado de la partida. Optimización cancelada.",
                "Se ha agotado el tiempo para aplicar la disposición. Operación cancelada.",
                "No se ha podido determinar una secuencia segura de acciones de inventario.",
                "La disposición se ha aplicado, pero sus efectos no coinciden con lo previsto. Optimización detenida. Puedes volver a intentarlo.",
                "La optimización del inventario ya está en curso.",
                "Coloca primero el objeto que sostienes o cancela su movimiento.",
                "Has recogido un objeto. Optimización detenida.",
                "Un error inesperado ha desactivado temporalmente la optimización del inventario.",
                "Estrategia de optimización",
                "Abre la mochila, suelta los objetos y elige Ordenar. Rápido ahorra tiempo; Minucioso busca más.\nPon primero tus artefactos importantes y los efectos no deseados en la zona inactiva. Primero las metas obligatorias, luego niveles y daño para los artefactos anteriores.\nLos colores indican nivel o activación. Elige bonus y PM en Efectos especiales. Los movimientos interrumpidos no se deshacen solos.",
                "Automática",
                "Rápido",
                "Exhaustivo",
                "Optimización del inventario",
                "Objetivos de combo",
                "Optimizar inventario",
                "Marcar artefactos",
                "Terminar de marcar",
                "Elige los artefactos prioritarios de esta expedición · Marcados: {0}",
                "Artefactos prioritarios de esta expedición: {0}",
                "Artefactos prioritarios: {0} · Otros objetivos ajustados: {1}",
                "PRIORIDAD · DE IZQUIERDA A DERECHA",
                "MANTENER ESTOS INACTIVOS",
                "Haz clic o arrastra las marcas; clic derecho para quitar.\n{0}: cambia el nivel objetivo del artefacto seleccionado.\nSolo cambia objetivos, no mueve objetos.",
                "Asigna «Cambiar objetivo fijado»",
                "Elige una casilla para colocar o intercambiar.\nClic derecho para cancelar; rueda para cambiar de página.",
                "Optimización del inventario",
                "Ajustar objetivos de combo",
                "Volver a la cola de artefactos",
                "Usando automáticamente el preajuste actual del juego",
                "Analizando automáticamente el inventario actual",
                "Objetivos ajustados en esta expedición: {0}",
                "Mantener activo",
                "Elegir automáticamente",
                "Nivel {0} o superior",
                "Cantidad: {0} o más",
                "Cantidad: {0} o menos",
                "Sin cantidad mínima (0)",
                "No hay objetivos de este tipo en el inventario",
                "Página {0}/{1}",
                "Buscando según los objetivos actuales…",
                "Aplicando la disposición…",
                "Automático",
                "Prioridad",
                "Evitar",
                "Obligatorio",
                "Intentar",
                "No se pueden cumplir todos los requisitos obligatorios. Inventario sin cambios; ajusta los requisitos.",
                "Esta vez no se encontró una disposición que cumpla todos los requisitos obligatorios. Inventario sin cambios. Prueba una búsqueda exhaustiva o ajusta los requisitos.",
                "EDITAR OBJETIVOS",
                "{0}: editar objetivos",
                "Intentar: hacer lo posible. Obligatorio (!): necesario para ordenar.",
                "Se guarda para futuras exploraciones. Ordena solo si se cumplen todas las metas obligatorias.",
                "Confirmar: mover marca; {0}: quitar marca\nElige un artefacto para editar objetivos\nVerde: cumplido · Amarillo: parcial · Rojo: incumplido",
                "Elige una casilla y confirma para colocar o intercambiar.\n{0}: cancelar",
                "Automático · {0}",
                "Auto (mejoras prudentes) · {0}",
                "Esperando resultado de ordenación",
                "Cumplido",
                "Parcialmente cumplido",
                "Incumplido",
                "Nivel {0}",
                "Activo",
                "Inactivo",
                "Mantener inactivo",
                "{0} · Objetivo al ordenar",
                "Objetivo",
                "Condición",
                "Intentar cumplir",
                "Obligatorio",
                "Al ordenar: {0}.\nOrdenar aunque no se cumpla este objetivo.",
                "Al ordenar: {0}.\nOrdenar solo si se cumplen todos los objetivos obligatorios.",
                "Volver a artefactos",
            },
            ["it-IT"] = new[]
            {
                "Analisi dell’inventario…",
                "Trovata una disposizione migliore. Applicazione…",
                "Ottimizzazione dell’inventario completata.",
                "Questa ricerca non ha trovato una disposizione migliore.",
                "Apri l’inventario normale prima di ottimizzarlo.",
                "L’inventario non è ancora pronto. Riprova tra poco.",
                "Non ci sono oggetti da ottimizzare.",
                "Alcuni oggetti non possono essere identificati in modo univoco. Ottimizzazione interrotta.",
                "Lo stato attuale dell’inventario non è supportato. Tentativo saltato.",
                "Impossibile verificare gli effetti di posizione. Ottimizzazione interrotta.",
                "L’inventario è cambiato. Ottimizzazione annullata.",
                "L’inventario è stato chiuso. Ottimizzazione annullata.",
                "Il piano o lo stato della partita è cambiato. Ottimizzazione annullata.",
                "Tempo scaduto durante l’applicazione della disposizione. Operazione annullata.",
                "Impossibile determinare una sequenza sicura di azioni nell’inventario.",
                "La disposizione è stata applicata, ma gli effetti non corrispondono alla previsione. Ottimizzazione interrotta. Puoi riprovare.",
                "L’ottimizzazione dell’inventario è già in corso.",
                "Prima posa l’oggetto che tieni o annulla lo spostamento.",
                "Hai preso un oggetto. Ottimizzazione interrotta.",
                "Un errore imprevisto ha disattivato temporaneamente l’ottimizzazione dell’inventario.",
                "Strategia di ottimizzazione",
                "Apri lo zaino, posa gli oggetti e scegli Riordina. Rapido riduce l’attesa; Accurato cerca più a lungo.\nMetti prima gli artefatti importanti e gli effetti indesiderati nell’area inattiva. Prima gli obiettivi obbligatori, poi livelli e bonus danno agli artefatti davanti.\nI colori indicano livello o attivazione. Scegli bonus e PM in Effetti speciali. Le mosse interrotte non vengono annullate automaticamente.",
                "Automatica",
                "Rapido",
                "Accurato",
                "Ottimizzazione inventario",
                "Obiettivi combo",
                "Ottimizza inventario",
                "Segna artefatti",
                "Termina selezione",
                "Scegli gli artefatti prioritari per questa esplorazione · Segnati: {0}",
                "Artefatti prioritari per questa esplorazione: {0}",
                "Artefatti prioritari: {0} · Altri obiettivi modificati: {1}",
                "PRIORITÀ · DA SINISTRA A DESTRA",
                "MANTIENI QUESTI INATTIVI",
                "Clicca/trascina i segni; clic destro per rimuovere.\n{0}: modifica il livello obiettivo dell’artefatto selezionato.\nCambia gli obiettivi senza spostare gli oggetti.",
                "Assegna «Cambia bersaglio bloccato»",
                "Scegli una casella per posare o scambiare.\nClic destro per annullare, rotella per cambiare pagina.",
                "Ottimizzazione inventario",
                "Modifica obiettivi combo",
                "Torna alla coda degli artefatti",
                "Uso automatico della configurazione attuale del gioco",
                "Analisi automatica dell’inventario attuale",
                "Obiettivi modificati in questa esplorazione: {0}",
                "Mantieni attivo",
                "Scegli automaticamente",
                "Livello {0} o superiore",
                "Conteggio: almeno {0}",
                "Conteggio: al massimo {0}",
                "Nessun conteggio minimo (0)",
                "Nessun obiettivo di questo tipo nell’inventario",
                "Pagina {0}/{1}",
                "Ricerca con gli obiettivi attuali…",
                "Applicazione della disposizione…",
                "Automatico",
                "Priorità",
                "Evita",
                "Obbligatorio",
                "Se possibile",
                "Non è possibile soddisfare tutti i requisiti obbligatori. Inventario invariato; modifica i requisiti.",
                "Questa volta non è stata trovata una disposizione che soddisfi tutti i requisiti obbligatori. Inventario invariato. Prova una ricerca approfondita o modifica i requisiti.",
                "MODIFICA OBIETTIVI",
                "{0}: modifica obiettivi",
                "Se possibile: fare il possibile. Obbligatorio (!): necessario per riordinare.",
                "Salvato per le prossime esplorazioni. Tutti gli obiettivi obbligatori devono essere raggiunti per riordinare.",
                "Conferma: sposta segno; {0}: rimuovi segno\nScegli un artefatto per modificare gli obiettivi\nVerde: soddisfatto · Giallo: parziale · Rosso: non soddisfatto",
                "Scegli una casella e conferma per posizionare o scambiare.\n{0}: annulla",
                "Automatico · {0}",
                "Auto (potenziamenti prudenti) · {0}",
                "In attesa del risultato del riordino",
                "Soddisfatto",
                "Parzialmente soddisfatto",
                "Non soddisfatto",
                "Livello {0}",
                "Attivo",
                "Inattivo",
                "Mantieni inattivo",
                "{0} · Obiettivo di riordino",
                "Obiettivo",
                "Requisito",
                "Se possibile",
                "Obbligatorio",
                "Durante il riordino: {0}.\nRiordina anche se questo obiettivo non viene raggiunto.",
                "Durante il riordino: {0}.\nRiordina solo se tutti gli obiettivi obbligatori sono raggiunti.",
                "Torna agli artefatti",
            },
            ["pt-BR"] = new[]
            {
                "Analisando o inventário…",
                "Uma disposição melhor foi encontrada. Aplicando…",
                "Otimização do inventário concluída.",
                "Esta busca não encontrou uma disposição melhor.",
                "Abra o inventário normal antes de otimizá-lo.",
                "O inventário ainda não está pronto. Tente novamente em instantes.",
                "Não há itens para otimizar.",
                "Não foi possível identificar alguns itens de forma única. Otimização interrompida.",
                "O estado atual do inventário não é compatível com a otimização. Esta tentativa foi ignorada.",
                "Não foi possível verificar os efeitos de posição. Otimização interrompida.",
                "O inventário mudou. Otimização cancelada.",
                "O inventário foi fechado. Otimização cancelada.",
                "O andar ou o estado da partida mudou. Otimização cancelada.",
                "O tempo para aplicar a disposição se esgotou. Operação cancelada.",
                "Não foi possível determinar uma sequência segura de ações no inventário.",
                "A disposição foi aplicada, mas os efeitos diferiram do previsto. Otimização interrompida. Você pode tentar novamente.",
                "A otimização do inventário já está em andamento.",
                "Primeiro coloque o item que está segurando ou cancele o movimento.",
                "Você pegou um item. Otimização interrompida.",
                "Um erro inesperado desativou temporariamente a otimização do inventário.",
                "Estratégia de otimização",
                "Abra a mochila, solte os itens e escolha Organizar. Rápido reduz a espera; Minucioso procura por mais tempo.\nColoque os artefatos importantes primeiro e os efeitos indesejados na área inativa. Primeiro as metas obrigatórias, depois níveis e dano para os artefatos da frente.\nAs cores indicam nível ou ativação. Escolha bônus e PM em Efeitos especiais. Interromper não desfaz movimentos já feitos.",
                "Automática",
                "Rápido",
                "Minucioso",
                "Otimização do inventário",
                "Metas de combo",
                "Otimizar inventário",
                "Marcar artefatos",
                "Concluir marcação",
                "Escolha os artefatos prioritários desta exploração · Marcados: {0}",
                "Artefatos prioritários nesta exploração: {0}",
                "Artefatos prioritários: {0} · Outras metas ajustadas: {1}",
                "PRIORIDADE · DA ESQUERDA À DIREITA",
                "MANTER ESTES INATIVOS",
                "Clique ou arraste as marcas; botão direito para remover.\n{0}: altere a meta de nível do artefato selecionado.\nAltera metas, sem mover os itens.",
                "Vincule “Alternar alvo travado”",
                "Escolha um espaço para colocar ou trocar.\nBotão direito para cancelar; rolagem para mudar de página.",
                "Otimização do inventário",
                "Ajustar metas de combo",
                "Voltar à fila de artefatos",
                "Usando automaticamente a predefinição atual do jogo",
                "Analisando automaticamente o inventário atual",
                "Metas ajustadas nesta exploração: {0}",
                "Manter ativo",
                "Escolher automaticamente",
                "Nível {0} ou superior",
                "Quantidade: {0} ou mais",
                "Quantidade: {0} ou menos",
                "Sem quantidade mínima (0)",
                "Não há metas desse tipo no inventário",
                "Página {0}/{1}",
                "Buscando com as metas atuais…",
                "Aplicando a disposição…",
                "Automático",
                "Prioridade",
                "Evitar",
                "Obrigatório",
                "Se possível",
                "Não é possível cumprir todos os requisitos obrigatórios. Inventário inalterado; ajuste os requisitos.",
                "Nenhuma disposição que cumpra todos os requisitos obrigatórios foi encontrada desta vez. Inventário inalterado. Tente uma busca completa ou ajuste os requisitos.",
                "EDITAR OBJETIVOS",
                "{0}: editar objetivos",
                "Se possível: fazer o possível. Obrigatório (!): necessário para organizar.",
                "Salvo para futuras explorações. Todas as metas obrigatórias devem ser atingidas para organizar.",
                "Confirmar: mover marca; {0}: remover\nSelecione um artefato para editar objetivos\nVerde: cumprido · Amarelo: parcial · Vermelho: não cumprido",
                "Escolha um espaço e confirme para colocar ou trocar.\n{0}: cancelar",
                "Automático · {0}",
                "Auto (melhorias prudentes) · {0}",
                "Aguardando resultado da organização",
                "Cumprido",
                "Parcialmente cumprido",
                "Não cumprido",
                "Nível {0}",
                "Ativo",
                "Inativo",
                "Manter inativo",
                "{0} · Objetivo da organização",
                "Objetivo",
                "Condição",
                "Se possível",
                "Obrigatório",
                "Ao organizar: {0}.\nOrganizar mesmo sem atingir este objetivo.",
                "Ao organizar: {0}.\nOrganizar somente se todos os objetivos obrigatórios forem atingidos.",
                "Voltar aos artefatos",
            },
            ["pl-PL"] = new[]
            {
                "Analizowanie układu ekwipunku…",
                "Znaleziono lepszy układ. Stosowanie…",
                "Optymalizacja ekwipunku zakończona.",
                "To wyszukiwanie nie znalazło lepszego układu.",
                "Przed optymalizacją otwórz zwykły ekran ekwipunku.",
                "Ekwipunek nie jest jeszcze gotowy. Spróbuj za chwilę.",
                "Brak przedmiotów do optymalizacji.",
                "Nie można jednoznacznie rozpoznać części przedmiotów. Optymalizacja zatrzymana.",
                "Obecny stan ekwipunku nie jest obsługiwany. Pominięto tę próbę.",
                "Nie można zweryfikować efektów pozycji przedmiotów. Optymalizacja zatrzymana.",
                "Ekwipunek się zmienił. Optymalizacja anulowana.",
                "Ekwipunek został zamknięty. Optymalizacja anulowana.",
                "Zmieniło się piętro lub przebieg gry. Optymalizacja anulowana.",
                "Upłynął limit czasu stosowania układu. Operacja anulowana.",
                "Nie udało się ustalić bezpiecznej kolejności działań w ekwipunku.",
                "Układ zastosowano, ale efekty różnią się od przewidywanych. Optymalizacja zatrzymana. Możesz spróbować ponownie.",
                "Optymalizacja ekwipunku już trwa.",
                "Najpierw odłóż trzymany przedmiot lub anuluj przenoszenie.",
                "Podniesiono przedmiot. Optymalizacja zatrzymana.",
                "Nieoczekiwany błąd tymczasowo wyłączył optymalizację ekwipunku.",
                "Strategia optymalizacji",
                "Otwórz plecak, odłóż trzymane przedmioty i wybierz porządkowanie. Szybkie skraca czekanie, Dokładne szuka dłużej.\nWażne artefakty daj na początek, niechciane efekty do strefy nieaktywnej. Najpierw cele obowiązkowe, potem poziomy i premie obrażeń dla wcześniejszych artefaktów.\nKolory pokazują poziom lub aktywację. Premie i PM wybierzesz w Efektach specjalnych. Przerwanie nie cofa wykonanych ruchów.",
                "Automatyczna",
                "Szybki",
                "Dokładny",
                "Optymalizacja ekwipunku",
                "Cele kombinacji",
                "Optymalizuj ekwipunek",
                "Oznacz artefakty",
                "Zakończ oznaczanie",
                "Wybierz priorytetowe artefakty na tę wyprawę · Oznaczone: {0}",
                "Priorytetowe artefakty w tej wyprawie: {0}",
                "Priorytetowe artefakty: {0} · Pozostałe zmiany celów: {1}",
                "PRIORYTET · OD LEWEJ DO PRAWEJ",
                "TE POZOSTAW NIEAKTYWNE",
                "Klikaj lub przeciągaj znaczniki; prawy przycisk usuwa.\n{0}: zmień docelowy poziom wybranego artefaktu.\nZmienia cele bez przenoszenia przedmiotów.",
                "Przypisz „Zmień zablokowany cel”",
                "Wybierz pole, aby odłożyć lub zamienić.\nPrawy przycisk anuluje, kółko zmienia stronę.",
                "Optymalizacja ekwipunku",
                "Dostosuj cele kombinacji",
                "Wróć do kolejki artefaktów",
                "Automatyczne uwzględnianie bieżącego zestawu gry",
                "Automatyczna analiza bieżącego ekwipunku",
                "Zmiany celów w tej wyprawie: {0}",
                "Utrzymaj aktywność",
                "Wybierz automatycznie",
                "Poziom {0} lub wyższy",
                "Liczba: co najmniej {0}",
                "Liczba: najwyżej {0}",
                "Bez minimalnej liczby (0)",
                "Brak celów tego typu w ekwipunku",
                "Strona {0}/{1}",
                "Wyszukiwanie według bieżących celów…",
                "Stosowanie układu ekwipunku…",
                "Automatycznie",
                "Priorytet",
                "Unikaj",
                "Wymagane",
                "W miarę możliwości",
                "Nie można spełnić wszystkich wymaganych warunków. Ekwipunek bez zmian; dostosuj warunki.",
                "Tym razem nie znaleziono układu spełniającego wszystkie wymagane warunki. Ekwipunek bez zmian. Spróbuj dokładnego wyszukiwania lub zmień warunki.",
                "EDYTUJ CELE",
                "{0}: edytuj cele",
                "W miarę możliwości: najlepsza próba. Wymagane (!): konieczne do ułożenia.",
                "Zapisane na kolejne wyprawy. Porządkowanie wymaga spełnienia wszystkich celów obowiązkowych.",
                "Potwierdź: przesuń znacznik; {0}: usuń\nWybierz artefakt, aby edytować cele\nZielony: spełnione · Żółty: częściowo · Czerwony: niespełnione",
                "Wybierz pole i potwierdź umieszczenie lub zamianę.\n{0}: anuluj",
                "Automatycznie · {0}",
                "Auto (ostrożne ulepszenia) · {0}",
                "Oczekiwanie na wynik porządkowania",
                "Spełnione",
                "Częściowo spełnione",
                "Niespełnione",
                "Poziom {0}",
                "Aktywny",
                "Nieaktywny",
                "Pozostaw nieaktywny",
                "{0} · Cel porządkowania",
                "Cel",
                "Warunek",
                "W miarę możliwości",
                "Wymagany",
                "Podczas porządkowania: {0}.\nPorządkuj nawet bez osiągnięcia tego celu.",
                "Podczas porządkowania: {0}.\nPorządkuj tylko po spełnieniu wszystkich wymaganych celów.",
                "Wróć do artefaktów",
            },
            ["ru-RU"] = new[]
            {
                "Анализ расположения предметов…",
                "Найдено лучшее расположение. Применение…",
                "Оптимизация инвентаря завершена.",
                "В ходе этого поиска лучшее расположение не найдено.",
                "Перед оптимизацией откройте обычный инвентарь.",
                "Инвентарь ещё не готов. Повторите попытку чуть позже.",
                "Нет предметов для оптимизации.",
                "Некоторые предметы невозможно однозначно различить. Оптимизация остановлена.",
                "Текущее состояние инвентаря не поддерживается. Эта попытка пропущена.",
                "Не удалось проверить эффекты расположения предметов. Оптимизация остановлена.",
                "Инвентарь изменился. Оптимизация отменена.",
                "Инвентарь закрыт. Оптимизация отменена.",
                "Этаж или состояние игры изменились. Оптимизация отменена.",
                "Время применения расположения истекло. Операция отменена.",
                "Не удалось определить безопасную последовательность действий в инвентаре.",
                "Расположение применено, но эффекты отличаются от прогноза. Оптимизация остановлена. Можно повторить попытку.",
                "Оптимизация инвентаря уже выполняется.",
                "Сначала положите удерживаемый предмет или отмените его перемещение.",
                "Вы взяли предмет. Оптимизация остановлена.",
                "Из-за непредвиденной ошибки оптимизация инвентаря временно отключена.",
                "Стратегия оптимизации",
                "Откройте рюкзак, положите предметы из рук и выберите сортировку. Быстрый режим сокращает ожидание, тщательный ищет дольше.\nВажные артефакты ставьте первыми, ненужные эффекты — в неактивную область. Сначала обязательные цели, затем уровни и бонусы урона первым артефактам.\nЦвета показывают уровень или активацию. Бонусы и ману выбирайте в особых эффектах. Прерывание не возвращает уже перемещённые предметы.",
                "Автоматическая",
                "Быстрый",
                "Тщательный",
                "Оптимизация инвентаря",
                "Цели комбо",
                "Оптимизировать инвентарь",
                "Отметить артефакты",
                "Завершить выбор",
                "Выберите приоритетные артефакты на этот забег · Отмечено: {0}",
                "Приоритетные артефакты в этом забеге: {0}",
                "Приоритетные артефакты: {0} · Другие изменения целей: {1}",
                "ПРИОРИТЕТ · СЛЕВА НАПРАВО",
                "ОСТАВИТЬ ЭТИ НЕАКТИВНЫМИ",
                "Щёлкните или перетащите метку; ПКМ удаляет её.\n{0}: изменить целевой уровень выбранного артефакта.\nМеняются цели, а не расположение предметов.",
                "Назначьте «Сменить захваченную цель»",
                "Выберите ячейку для размещения или обмена.\nПКМ — отмена, колесо — смена страницы.",
                "Оптимизация инвентаря",
                "Настроить цели комбо",
                "Назад к очереди артефактов",
                "Автоматически учитывается текущий набор настроек игры",
                "Автоматический анализ текущего инвентаря",
                "Изменения целей в этом забеге: {0}",
                "Оставить активным",
                "Выбрать автоматически",
                "Уровень {0} или выше",
                "Количество: не менее {0}",
                "Количество: не более {0}",
                "Без минимального количества (0)",
                "В инвентаре нет целей этого типа",
                "Страница {0}/{1}",
                "Поиск по текущим целям…",
                "Применение расположения предметов…",
                "Автоматически",
                "Приоритет",
                "Избегать",
                "Обязательно",
                "По возможности",
                "Нельзя выполнить все обязательные условия. Инвентарь не изменён; измените условия.",
                "В этот раз не найдена раскладка для всех обязательных условий. Инвентарь не изменён. Попробуйте тщательный поиск или измените условия.",
                "ИЗМЕНИТЬ ЦЕЛИ",
                "{0}: изменить цели",
                "По возможности: стараться выполнить. Обязательно (!): необходимо для раскладки.",
                "Сохраняется для будущих вылазок. Сортировка возможна при выполнении всех обязательных целей.",
                "Подтвердить: переместить метку; {0}: убрать\nВыберите артефакт для настройки целей\nЗелёный: выполнено · Жёлтый: частично · Красный: не выполнено",
                "Выберите ячейку и подтвердите размещение или обмен.\n{0}: отмена",
                "Автоматически · {0}",
                "Авто (осторожное улучшение) · {0}",
                "Ожидание результата сортировки",
                "Выполнено",
                "Частично выполнено",
                "Не выполнено",
                "Уровень {0}",
                "Активно",
                "Неактивно",
                "Оставить неактивным",
                "{0} · Цель сортировки",
                "Цель",
                "Условие",
                "По возможности",
                "Обязательно",
                "При сортировке: {0}.\nСортировать, даже если эта цель не достигнута.",
                "При сортировке: {0}.\nСортировать только при выполнении всех обязательных целей.",
                "К списку артефактов",
            },
            ["sv-SE"] = new[]
            {
                "Analyserar inventariets placering…",
                "Bättre placering hittad. Tillämpar…",
                "Inventarieoptimeringen är klar.",
                "Den här sökningen hittade ingen bättre placering.",
                "Öppna det vanliga inventariet före optimering.",
                "Inventariet är inte redo än. Försök igen om en stund.",
                "Det finns inga föremål att optimera.",
                "Vissa föremål kan inte identifieras entydigt. Optimeringen stoppades.",
                "Det aktuella inventarietillståndet stöds inte. Försöket hoppades över.",
                "Föremålens placeringseffekter kunde inte verifieras. Optimeringen stoppades.",
                "Inventariet ändrades. Optimeringen avbröts.",
                "Inventariet stängdes. Optimeringen avbröts.",
                "Våningen eller spelets förlopp ändrades. Optimeringen avbröts.",
                "Tidsgränsen för att tillämpa placeringen nåddes. Åtgärden avbröts.",
                "Ingen säker följd av inventarieåtgärder kunde skapas.",
                "Placeringen tillämpades, men effekterna skilde sig från beräkningen. Optimeringen stoppades. Du kan försöka igen.",
                "Inventarieoptimering pågår redan.",
                "Placera först föremålet du håller eller avbryt flytten.",
                "Du plockade upp ett föremål. Optimeringen stoppades.",
                "Ett oväntat fel har tillfälligt inaktiverat inventarieoptimeringen.",
                "Optimeringsstrategi",
                "Öppna ryggsäcken, lägg ner hållna föremål och välj Sortera. Snabb sparar tid; Noggrann söker längre.\nViktiga artefakter först, oönskade effekter i det inaktiva området. Måste-mål först, sedan får tidigare artefakter nivåer och skadebonusar först.\nFärger visar nivå eller aktivering. Välj bonusar och MP under Specialeffekter. Avbrutna flyttar ångras inte automatiskt.",
                "Automatisk",
                "Snabb",
                "Grundlig",
                "Inventarieoptimering",
                "Kombinationsmål",
                "Optimera inventariet",
                "Markera artefakter",
                "Avsluta markering",
                "Välj prioriterade artefakter för rundan · Markerade: {0}",
                "Prioriterade artefakter denna runda: {0}",
                "Prioriterade artefakter: {0} · Övriga måländringar: {1}",
                "PRIORITET · FRÅN VÄNSTER TILL HÖGER",
                "HÅLL DESSA INAKTIVA",
                "Klicka/dra markeringar; högerklick tar bort.\n{0}: ändra nivåmålet för vald artefakt.\nÄndrar mål utan att flytta föremål.",
                "Tilldela ”Byt låst mål”",
                "Välj en ruta för att placera eller byta.\nHögerklick avbryter, skrollning byter sida.",
                "Inventarieoptimering",
                "Ändra kombinationsmål",
                "Tillbaka till artefaktkön",
                "Använder automatiskt spelets aktuella förval",
                "Analyserar automatiskt det aktuella inventariet",
                "Måländringar denna runda: {0}",
                "Håll aktiv",
                "Välj automatiskt",
                "Nivå {0} eller högre",
                "Antal: minst {0}",
                "Antal: högst {0}",
                "Inget minsta antal (0)",
                "Inga mål av denna typ i inventariet",
                "Sida {0}/{1}",
                "Söker med aktuella mål…",
                "Tillämpar inventarieplacering…",
                "Automatisk",
                "Prioritet",
                "Undvik",
                "Krav",
                "Om möjligt",
                "Alla krav kan inte uppfyllas samtidigt. Inventariet är oförändrat; ändra kraven.",
                "Ingen placering som uppfyller alla krav hittades denna gång. Inventariet är oförändrat. Prova grundlig sökning eller ändra kraven.",
                "ÄNDRA MÅL",
                "{0}: ändra mål",
                "Om möjligt: bästa försök. Krav (!): måste uppfyllas för att ordna.",
                "Sparas för framtida utforskningar. Alla måste-mål ska nås innan sortering.",
                "Bekräfta: flytta markering; {0}: ta bort\nVälj en artefakt för att ändra mål\nGrön: uppfyllt · Gul: delvis · Röd: ej uppfyllt",
                "Välj en ruta och bekräfta för att placera eller byta.\n{0}: avbryt",
                "Automatiskt · {0}",
                "Auto (försiktiga uppgraderingar) · {0}",
                "Väntar på sorteringsresultat",
                "Uppfyllt",
                "Delvis uppfyllt",
                "Ej uppfyllt",
                "Nivå {0}",
                "Aktiv",
                "Inaktiv",
                "Håll inaktiv",
                "{0} · Sorteringsmål",
                "Mål",
                "Krav",
                "Om möjligt",
                "Obligatoriskt",
                "Vid sortering: {0}.\nSortera även om detta mål inte uppnås.",
                "Vid sortering: {0}.\nSortera endast när alla obligatoriska mål uppnås.",
                "Tillbaka till artefakter",
            },
            ["tr-TR"] = new[]
            {
                "Envanter düzeni inceleniyor…",
                "Daha iyi bir düzen bulundu. Uygulanıyor…",
                "Envanter iyileştirmesi tamamlandı.",
                "Bu aramada daha iyi bir düzen bulunamadı.",
                "İyileştirmeden önce normal envanter ekranını açın.",
                "Envanter henüz hazır değil. Biraz sonra tekrar deneyin.",
                "İyileştirilecek eşya yok.",
                "Bazı eşyalar benzersiz olarak tanımlanamadı. İyileştirme durduruldu.",
                "Mevcut envanter durumu desteklenmiyor. Bu deneme atlandı.",
                "Eşyaların konum etkileri doğrulanamadı. İyileştirme durduruldu.",
                "Envanter değişti. İyileştirme iptal edildi.",
                "Envanter kapatıldı. İyileştirme iptal edildi.",
                "Kat veya oyun akışı değişti. İyileştirme iptal edildi.",
                "Düzeni uygulama süresi aşıldı. İşlem iptal edildi.",
                "Güvenli bir envanter işlem sırası oluşturulamadı.",
                "Düzen uygulandı ancak etkiler tahminden farklı çıktı. İyileştirme durduruldu. Tekrar deneyebilirsiniz.",
                "Envanter iyileştirmesi zaten sürüyor.",
                "Önce tuttuğunuz eşyayı bırakın veya taşıma işlemini iptal edin.",
                "Bir eşya aldınız. İyileştirme durduruldu.",
                "Beklenmeyen bir hata nedeniyle envanter iyileştirmesi geçici olarak kapatıldı.",
                "İyileştirme stratejisi",
                "Çantayı aç, elindeki eşyaları bırak ve Düzenle seçeneğini kullan. Hızlı daha az bekletir; Ayrıntılı daha uzun arar.\nÖnemli eserleri öne, istenmeyen etkileri etkisiz alana koy. Önce zorunlu hedefler, sonra öndeki eserlere seviye ve hasar bonusları verilir.\nRenkler seviye veya etkinliği gösterir. Bonus ve MP tercihlerini Özel etkilerden seç. Kesilen taşımalarda eşyalar kendiliğinden geri dönmez.",
                "Otomatik",
                "Hızlı",
                "Kapsamlı",
                "Envanter iyileştirmesi",
                "Kombo hedefleri",
                "Envanteri iyileştir",
                "Eserleri işaretle",
                "İşaretlemeyi bitir",
                "Bu keşifte öncelikli eserleri seçin · İşaretli: {0}",
                "Bu keşifte öncelikli eserler: {0}",
                "Öncelikli eserler: {0} · Diğer hedef değişiklikleri: {1}",
                "ÖNCELİK · SOLDAN SAĞA",
                "BUNLARI ETKİSİZ TUT",
                "İşaretlere tıklayın/sürükleyin; sağ tıkla kaldırın.\n{0}: seçili eserin seviye hedefini değiştirin.\nEşyaları taşımadan hedefleri değiştirir.",
                "“Kilitli hedefi değiştir” eylemini atayın",
                "Yerleştirmek veya takas etmek için yuva seçin.\nSağ tıkla iptal edin, tekerlekle sayfa değiştirin.",
                "Envanter iyileştirmesi",
                "Kombo hedeflerini ayarla",
                "Eser sırasına dön",
                "Oyunun mevcut ön ayarı otomatik kullanılıyor",
                "Mevcut envanter otomatik inceleniyor",
                "Bu keşifteki hedef değişiklikleri: {0}",
                "Etkin tut",
                "Otomatik seç",
                "Seviye {0} veya üstü",
                "Sayı: en az {0}",
                "Sayı: en fazla {0}",
                "Alt sayı sınırı yok (0)",
                "Envanterde bu tür hedef yok",
                "Sayfa {0}/{1}",
                "Mevcut hedeflerle aranıyor…",
                "Envanter düzeni uygulanıyor…",
                "Otomatik",
                "Öncelik",
                "Kaçın",
                "Zorunlu",
                "Mümkünse",
                "Tüm zorunlu koşullar birlikte karşılanamıyor. Envanter değişmedi; koşulları ayarlayın.",
                "Bu sefer tüm zorunlu koşulları karşılayan düzen bulunamadı. Envanter değişmedi. Ayrıntılı aramayı deneyin veya koşulları ayarlayın.",
                "HEDEFLERİ DÜZENLE",
                "{0}: hedefleri düzenle",
                "Mümkünse: elinden geleni yap. Zorunlu (!): düzenleme için gerekli.",
                "Sonraki keşifler için kaydedilir. Düzenleme için tüm zorunlu hedefler karşılanmalı.",
                "Onayla: işareti taşı; {0}: kaldır\nHedefleri düzenlemek için eser seçin\nYeşil: tamam · Sarı: kısmen · Kırmızı: karşılanmadı",
                "Yerleştirmek veya değiştirmek için yuva seçip onaylayın.\n{0}: iptal",
                "Otomatik · {0}",
                "Otomatik (temkinli yükseltme) · {0}",
                "Düzenleme sonucu bekleniyor",
                "Karşılandı",
                "Kısmen karşılandı",
                "Karşılanmadı",
                "Seviye {0}",
                "Etkin",
                "Etkin değil",
                "Etkinleştirme",
                "{0} · Düzenleme hedefi",
                "Hedef",
                "Koşul",
                "Mümkünse karşıla",
                "Mutlaka karşıla",
                "Düzenlerken: {0}.\nBu hedef karşılanmasa da düzenle.",
                "Düzenlerken: {0}.\nYalnızca tüm zorunlu hedefler karşılandığında düzenle.",
                "Eser listesine dön",
            },
            ["th-TH"] = new[]
            {
                "กำลังวิเคราะห์การจัดช่องเก็บของ…",
                "พบการจัดวางที่ดีกว่า กำลังนำไปใช้…",
                "ปรับช่องเก็บของเสร็จแล้ว",
                "การค้นหาครั้งนี้ไม่พบการจัดวางที่ดีกว่า",
                "โปรดเปิดหน้าช่องเก็บของปกติก่อนปรับการจัดวาง",
                "ช่องเก็บของยังไม่พร้อม โปรดลองอีกครั้งในอีกสักครู่",
                "ไม่มีไอเทมให้ปรับการจัดวาง",
                "ไม่สามารถแยกแยะไอเทมบางชิ้นได้ จึงหยุดการปรับช่องเก็บของ",
                "ยังไม่รองรับสถานะช่องเก็บของปัจจุบัน จึงข้ามการปรับครั้งนี้",
                "ไม่สามารถตรวจสอบเอฟเฟกต์จากตำแหน่งของไอเทมได้ จึงหยุดการปรับ",
                "ช่องเก็บของเปลี่ยนไป จึงยกเลิกการปรับครั้งนี้",
                "ปิดช่องเก็บของแล้ว จึงยกเลิกการปรับครั้งนี้",
                "ชั้นหรือสถานะการเล่นเปลี่ยนไป จึงยกเลิกการปรับครั้งนี้",
                "ใช้เวลาจัดวางเกินกำหนด จึงยกเลิกการปรับ",
                "ไม่สามารถหาลำดับการย้ายไอเทมที่ปลอดภัยได้",
                "จัดวางแล้ว แต่เอฟเฟกต์จริงต่างจากที่คาด จึงหยุดการปรับ คุณลองใหม่ได้",
                "กำลังปรับช่องเก็บของอยู่แล้ว",
                "โปรดวางไอเทมที่ถืออยู่หรือยกเลิกการย้ายก่อน",
                "คุณหยิบไอเทมขึ้นมา จึงหยุดการปรับช่องเก็บของ",
                "เกิดข้อผิดพลาดที่ไม่คาดคิด จึงปิดการปรับช่องเก็บของชั่วคราว",
                "แนวทางปรับช่องเก็บของ",
                "เปิดกระเป๋า วางไอเทมที่ถือ แล้วเลือกจัดเรียง แบบเร็วรอน้อยกว่า แบบละเอียดใช้เวลาหานานกว่า\nวางอาร์ติแฟกต์สำคัญไว้ก่อน และเอฟเฟกต์ที่ไม่ต้องการไว้ช่องไม่ทำงาน ทำเป้าหมายที่จำเป็นก่อน แล้วให้ระดับและโบนัสความเสียหายกับอาร์ติแฟกต์ด้านหน้าก่อน\nสีบอกระดับหรือการทำงาน เลือกโบนัสและ MP ในเอฟเฟกต์พิเศษ หากหยุดกลางคัน ไอเทมที่ย้ายแล้วจะไม่กลับที่เดิมอัตโนมัติ",
                "อัตโนมัติ",
                "รวดเร็ว",
                "ละเอียด",
                "ปรับช่องเก็บของ",
                "เป้าหมายคอมโบ",
                "ปรับช่องเก็บของให้เหมาะสม",
                "ทำเครื่องหมายอาร์ติแฟกต์",
                "เสร็จสิ้นการทำเครื่องหมาย",
                "เลือกอาร์ติแฟกต์ที่ให้ความสำคัญในการสำรวจนี้ · ทำเครื่องหมายแล้ว: {0}",
                "อาร์ติแฟกต์สำคัญในการสำรวจนี้: {0}",
                "อาร์ติแฟกต์สำคัญ: {0} · เป้าหมายอื่นที่ปรับ: {1}",
                "ลำดับสำคัญ · ซ้ายไปขวา",
                "ไม่ให้ไอเทมเหล่านี้ทำงาน",
                "คลิกหรือลากเครื่องหมาย คลิกขวาเพื่อนำออก\n{0}: ปรับเป้าหมายระดับของอาร์ติแฟกต์ที่เลือก\nเปลี่ยนเฉพาะเป้าหมาย ไม่ย้ายไอเทม",
                "โปรดกำหนดปุ่ม “สลับเป้าหมายที่ล็อก”",
                "เลือกช่องเพื่อวางหรือสลับ\nคลิกขวาเพื่อยกเลิก เลื่อนล้อเมาส์เพื่อเปลี่ยนหน้า",
                "ปรับช่องเก็บของ",
                "ปรับเป้าหมายคอมโบ",
                "กลับสู่ลำดับอาร์ติแฟกต์",
                "อ้างอิงชุดตั้งค่าปัจจุบันของเกมโดยอัตโนมัติ",
                "วิเคราะห์ช่องเก็บของปัจจุบันโดยอัตโนมัติ",
                "เป้าหมายที่ปรับในการสำรวจนี้: {0}",
                "ให้ทำงาน",
                "เลือกอัตโนมัติ",
                "ระดับ {0} ขึ้นไป",
                "จำนวนอย่างน้อย {0}",
                "จำนวนไม่เกิน {0}",
                "ไม่กำหนดจำนวนขั้นต่ำ (0)",
                "ไม่มีเป้าหมายประเภทนี้ในช่องเก็บของ",
                "หน้า {0}/{1}",
                "กำลังค้นหาตามเป้าหมายปัจจุบัน…",
                "กำลังจัดวางไอเทม…",
                "อัตโนมัติ",
                "ให้ความสำคัญ",
                "หลีกเลี่ยง",
                "จำเป็น",
                "ถ้าเป็นไปได้",
                "ไม่สามารถทำตามเงื่อนไขจำเป็นทั้งหมดได้ กระเป๋าไม่เปลี่ยนแปลง โปรดปรับเงื่อนไข",
                "ครั้งนี้ไม่พบการจัดวางที่ตรงตามเงื่อนไขจำเป็นทั้งหมด กระเป๋าไม่เปลี่ยนแปลง ลองค้นหาอย่างละเอียดหรือปรับเงื่อนไข",
                "แก้ไขเป้าหมาย",
                "{0}: แก้ไขเป้าหมาย",
                "ถ้าเป็นไปได้: พยายามให้ตรงเป้า จำเป็น (!): ต้องครบจึงจะจัด",
                "บันทึกไว้สำหรับการสำรวจครั้งต่อไป ต้องครบเป้าหมายที่จำเป็นจึงจัดเรียง",
                "ยืนยัน: ย้ายเครื่องหมาย; {0}: ลบ\nเลือกวัตถุโบราณเพื่อแก้ไขเป้าหมาย\nเขียว: ครบ · เหลือง: บางส่วน · แดง: ไม่ครบ",
                "เลือกช่องแล้วยืนยันเพื่อวางหรือสลับ\n{0}: ยกเลิก",
                "อัตโนมัติ · {0}",
                "อัตโนมัติ (อัปเกรดอย่างระมัดระวัง) · {0}",
                "รอผลการจัดเรียง",
                "ครบแล้ว",
                "ครบบางส่วน",
                "ยังไม่ครบ",
                "ระดับ {0}",
                "ทำงาน",
                "ไม่ทำงาน",
                "คงไว้ไม่ให้ทำงาน",
                "{0} · เป้าหมายการจัดเรียง",
                "เป้าหมาย",
                "เงื่อนไข",
                "พยายามให้ได้",
                "ต้องทำให้ได้",
                "เมื่อจัดเรียง: {0}\nจัดเรียงได้แม้ไม่บรรลุเป้าหมายนี้",
                "เมื่อจัดเรียง: {0}\nจัดเรียงเมื่อบรรลุเป้าหมายที่จำเป็นทั้งหมดเท่านั้น",
                "กลับไปยังอาร์ติแฟกต์",
            },
        };
    }
}
