using System;
using System.Collections.Generic;

namespace SephiriaEnhancements.MultiplayerAccess.Presentation
{
    internal static class JoiningSupplyLocalization
    {
        internal const string Placed = "SephiriaEnhancements.JoiningSupplies.Placed";
        internal const string Ready = "SephiriaEnhancements.JoiningSupplies.Ready";
        internal const string MissingHistory = "SephiriaEnhancements.JoiningSupplies.MissingHistory";
        internal const string Failed = "SephiriaEnhancements.JoiningSupplies.Failed";
        internal const string ChoiceChanged = "SephiriaEnhancements.JoiningSupplies.ChoiceChanged";
        internal const string HostUnavailable = "SephiriaEnhancements.JoiningSupplies.HostUnavailable";
        private static readonly Dictionary<string, string[]> Texts = new()
        {
            ["en-US"] = new[] { "Your reward is nearby. Interact to claim it.", "Joining supplies: {0} route rewards remaining. Finish your level-up choices; then supplies arrive automatically outside combat. Choice rewards appear nearby.", "Earlier route rewards were not recorded for this exploration. Joining supplies include growth rewards and recorded opportunities only.", "Joining supplies stopped after an error. Some rewards may already have been received; they will not be sent again automatically.", "The choice was not applied. Check inventory space and whether this reward is still available, then try again.", "The host disabled joining supplies after an error. Supplies cannot be claimed from this host right now." },
            ["zh-CN"] = new[] { "奖励已放在身旁，互动即可领取。", "加入补给剩余 {0} 份路线奖励。请先领完升级奖励；随后补给会在非战斗时自动发放，自选奖励会出现在身旁。", "本次探索缺少早期路线奖励记录。加入补给仅包含成长奖励及已记录的奖励机会。", "加入补给因错误停止。部分奖励可能已经到账，不会自动重复发放。", "本次选择未生效。请检查背包空间及奖励是否仍可领取后重试。", "房主因错误停用了加入补给，目前无法向该房主领取补给。" },
            ["zh-TW"] = new[] { "獎勵已放在身旁，互動即可領取。", "加入補給剩餘 {0} 份路線獎勵。請先領完升級獎勵；隨後補給會在非戰鬥時自動發放，自選獎勵會出現在身旁。", "本次探索缺少早期路線獎勵紀錄。加入補給僅包含成長獎勵及已記錄的獎勵機會。", "加入補給因錯誤停止。部分獎勵可能已經到帳，不會自動重複發放。", "本次選擇未生效。請檢查背包空間及獎勵是否仍可領取後重試。", "房主因錯誤停用了加入補給，目前無法向該房主領取補給。" },
            ["ko-KR"] = new[] { "보상이 옆에 놓였습니다. 상호작용하여 받으세요.", "남은 참가 보급 경로 보상: {0}. 레벨업 보상을 모두 선택하면 전투 중이 아닐 때 보급이 자동 지급됩니다. 선택형 보상은 옆에 나타납니다.", "이번 탐험의 이전 경로 보상 기록이 없습니다. 성장 보상과 기록된 보상 기회만 보급에 포함됩니다.", "오류로 참가 보급이 중단되었습니다. 일부 보상은 이미 지급되었을 수 있으며 자동으로 다시 지급되지 않습니다.", "선택이 적용되지 않았습니다. 가방 공간과 보상 수령 가능 여부를 확인한 뒤 다시 시도하세요.", "오류로 호스트의 참가 보급이 중단되었습니다. 현재 이 호스트에게서 보급을 받을 수 없습니다." },
            ["ja-JP"] = new[] { "報酬を近くに配置しました。調べて受け取れます。", "参加補給のルート報酬：残り{0}。レベルアップ報酬をすべて選ぶと、戦闘外で補給が自動配布されます。選択式の報酬は近くに出現します。", "今回の探索には以前のルート報酬の記録がありません。補給には成長報酬と記録済みの報酬機会のみ含まれます。", "エラーにより参加補給を停止しました。一部の報酬は受け取り済みの可能性があり、自動で再配布しません。", "選択は反映されませんでした。バッグの空きと報酬を受け取れる状態かを確認して再試行してください。", "エラーによりホストが参加補給を停止しました。現在、このホストから補給を受け取れません。" },
            ["de-DE"] = new[] { "Deine Belohnung liegt in der Nähe. Interagiere, um sie abzuholen.", "Verbleibende Routenbelohnungen beim Beitritt: {0}. Wähle zuerst alle Stufenbelohnungen. Danach erhältst du Vorräte automatisch außerhalb des Kampfes; Auswahlbelohnungen erscheinen in deiner Nähe.", "Frühere Routenbelohnungen dieser Erkundung wurden nicht aufgezeichnet. Vorräte enthalten nur Stufenbelohnungen und aufgezeichnete Belohnungsgelegenheiten.", "Die Beitrittsvorräte wurden wegen eines Fehlers gestoppt. Einige Belohnungen wurden möglicherweise bereits erhalten und werden nicht automatisch erneut vergeben.", "Die Auswahl wurde nicht angewendet. Prüfe den Inventarplatz und ob die Belohnung noch verfügbar ist, und versuche es erneut.", "Der Host hat die Beitrittsvorräte nach einem Fehler deaktiviert. Dort können derzeit keine Vorräte abgeholt werden." },
            ["es-ES"] = new[] { "Tu recompensa está cerca. Interactúa para recogerla.", "Recompensas de ruta pendientes por incorporación: {0}. Elige primero todas las recompensas de nivel. Después recibirás provisiones automáticamente fuera de combate; las recompensas a elegir aparecerán cerca.", "No se registraron las recompensas de rutas anteriores de esta exploración. Las provisiones solo incluyen recompensas de nivel y oportunidades registradas.", "Las provisiones de incorporación se detuvieron por un error. Puede que ya hayas recibido algunas recompensas; no se volverán a entregar automáticamente.", "No se aplicó la selección. Comprueba el espacio del inventario y si la recompensa sigue disponible antes de reintentarlo.", "El anfitrión desactivó los suministros de entrada tras un error. Ahora no puedes reclamarlos en esta partida." },
            ["fr-FR"] = new[] { "Votre récompense est à proximité. Interagissez pour la récupérer.", "Récompenses de parcours restantes à l’arrivée : {0}. Choisissez d’abord toutes vos récompenses de niveau. Les provisions arrivent ensuite automatiquement hors combat ; les récompenses à choisir apparaissent à proximité.", "Les récompenses des parcours précédents de cette exploration n’ont pas été enregistrées. Les provisions comprennent seulement les récompenses de niveau et les occasions enregistrées.", "Les provisions d’arrivée ont été interrompues par une erreur. Certaines récompenses ont peut-être déjà été reçues et ne seront pas redistribuées automatiquement.", "Le choix n’a pas été appliqué. Vérifiez la place dans l’inventaire et la disponibilité de la récompense, puis réessayez.", "L’hôte a désactivé les provisions d’arrivée après une erreur. Elles ne peuvent pas être réclamées auprès de cet hôte pour le moment." },
            ["it-IT"] = new[] { "La ricompensa è vicina. Interagisci per ritirarla.", "Ricompense di percorso rimaste all’ingresso: {0}. Scegli prima tutte le ricompense di livello. Poi riceverai automaticamente le scorte fuori dal combattimento; le ricompense da scegliere appariranno vicino a te.", "Le ricompense dei percorsi precedenti di questa esplorazione non sono state registrate. Le scorte includono solo ricompense di livello e opportunità registrate.", "Le scorte d’ingresso sono state interrotte da un errore. Alcune ricompense potrebbero essere già state ricevute e non saranno inviate di nuovo automaticamente.", "La scelta non è stata applicata. Controlla lo spazio nell’inventario e la disponibilità della ricompensa, poi riprova.", "L’host ha disattivato le scorte d’ingresso dopo un errore. Al momento non puoi ritirarle da questo host." },
            ["pl-PL"] = new[] { "Nagroda jest w pobliżu. Wejdź z nią w interakcję, aby ją odebrać.", "Pozostałe nagrody tras po dołączeniu: {0}. Najpierw wybierz wszystkie nagrody za poziomy. Potem zaopatrzenie będzie przyznawane automatycznie poza walką; nagrody do wyboru pojawią się w pobliżu.", "Nagrody z wcześniejszych tras tej eksploracji nie zostały zapisane. Zaopatrzenie obejmuje tylko nagrody za poziomy i zapisane okazje do nagród.", "Zaopatrzenie po dołączeniu zatrzymano z powodu błędu. Część nagród mogła już zostać przyznana i nie zostanie automatycznie wysłana ponownie.", "Wybór nie został zastosowany. Sprawdź miejsce w ekwipunku i dostępność nagrody, a potem spróbuj ponownie.", "Gospodarz wyłączył zaopatrzenie po błędzie. Obecnie nie można go odebrać u tego gospodarza." },
            ["pt-BR"] = new[] { "Sua recompensa está por perto. Interaja para resgatá-la.", "Recompensas de rota restantes na entrada: {0}. Escolha primeiro todas as recompensas de nível. Depois, os suprimentos serão entregues automaticamente fora de combate; as recompensas de escolha aparecerão por perto.", "As recompensas das rotas anteriores desta exploração não foram registradas. Os suprimentos incluem apenas recompensas de nível e oportunidades registradas.", "Os suprimentos de entrada foram interrompidos por um erro. Algumas recompensas podem já ter sido recebidas e não serão reenviadas automaticamente.", "A escolha não foi aplicada. Confira o espaço no inventário e se a recompensa ainda está disponível antes de tentar de novo.", "O anfitrião desativou os suprimentos de entrada após um erro. Não é possível resgatá-los com esse anfitrião no momento." },
            ["ru-RU"] = new[] { "Ваша награда рядом. Взаимодействуйте с ней, чтобы забрать.", "Осталось наград маршрута при вступлении: {0}. Сначала выберите все награды за уровни. Затем припасы будут выдаваться автоматически вне боя; награды с выбором появятся рядом.", "Награды прежних маршрутов этого похода не записаны. Припасы включают только награды за уровни и записанные возможности получить награду.", "Выдача припасов при вступлении остановлена из-за ошибки. Часть наград могла быть получена; автоматически повторно они не выдаются.", "Выбор не применён. Проверьте место в инвентаре и доступность награды, затем повторите попытку.", "Хост отключил припасы для присоединившихся после ошибки. Сейчас получить их у этого хоста нельзя." },
            ["sv-SE"] = new[] { "Din belöning finns i närheten. Interagera för att hämta den.", "Återstående ruttbelöningar vid anslutning: {0}. Välj först alla nivåbelöningar. Sedan får du förråd automatiskt utanför strid; valbara belöningar dyker upp i närheten.", "Belöningar från tidigare rutter i denna utforskning registrerades inte. Förråden innehåller bara nivåbelöningar och registrerade belöningstillfällen.", "Anslutningsförråden stoppades efter ett fel. Vissa belöningar kan redan ha mottagits och skickas inte igen automatiskt.", "Valet tillämpades inte. Kontrollera plats i inventariet och att belöningen är tillgänglig, och försök igen.", "Värden har inaktiverat anslutningsförråd efter ett fel. De kan inte hämtas hos den här värden just nu." },
            ["th-TH"] = new[] { "รางวัลอยู่ใกล้ตัวแล้ว โต้ตอบเพื่อรับรางวัล", "รางวัลเส้นทางสำหรับผู้เข้าร่วมเหลือ {0} ชุด เลือกรางวัลเลเวลให้ครบก่อน จากนั้นจะได้รับเสบียงอัตโนมัติเมื่ออยู่นอกการต่อสู้ รางวัลที่ต้องเลือกจะปรากฏใกล้ตัว", "ไม่มีบันทึกรางวัลเส้นทางก่อนหน้าของการสำรวจนี้ เสบียงจึงมีเฉพาะรางวัลเลเวลและโอกาสรับรางวัลที่บันทึกไว้", "เสบียงสำหรับผู้เข้าร่วมหยุดเนื่องจากข้อผิดพลาด บางรางวัลอาจได้รับแล้วและจะไม่ส่งซ้ำโดยอัตโนมัติ", "ยังไม่ได้ใช้ตัวเลือกนี้ ตรวจสอบที่ว่างในกระเป๋าและว่ายังรับรางวัลได้หรือไม่ แล้วลองอีกครั้ง", "โฮสต์ปิดเสบียงสำหรับผู้เข้าร่วมเนื่องจากข้อผิดพลาด ขณะนี้รับเสบียงจากโฮสต์นี้ไม่ได้" },
            ["tr-TR"] = new[] { "Ödülün yakında. Almak için etkileşime gir.", "Katılım için kalan rota ödülü: {0}. Önce tüm seviye ödüllerini seç. Ardından erzaklar savaş dışında otomatik verilir; seçimli ödüller yakınında belirir.", "Bu keşfin önceki rota ödülleri kaydedilmedi. Erzaklar yalnızca seviye ödüllerini ve kaydedilmiş ödül fırsatlarını içerir.", "Katılım erzakları bir hata nedeniyle durduruldu. Bazı ödüller alınmış olabilir; otomatik olarak tekrar gönderilmezler.", "Seçim uygulanmadı. Envanter alanını ve ödülün hâlâ alınabilir olduğunu kontrol edip tekrar dene.", "Ev sahibi bir hata sonrası katılım erzaklarını devre dışı bıraktı. Şu anda bu ev sahibinden erzak alınamaz." },
        };
        internal static void Register(Action<string, string, string> addText, IEnumerable<string> languages) =>
            Configuration.LocalizationGroup.Register(addText, languages,
                new[] { Placed, Ready, MissingHistory, Failed, ChoiceChanged, HostUnavailable }, Texts);
    }
}
