using System;
using System.Collections.Generic;

namespace SephiriaEnhancements.MultiplayerAccess.Presentation
{
    internal static class JoiningSupplyLocalization
    {
        internal const string Claim = "SephiriaEnhancements.JoiningSupplies.Claim";
        internal const string Placed = "SephiriaEnhancements.JoiningSupplies.Placed";
        internal const string Unavailable = "SephiriaEnhancements.JoiningSupplies.Unavailable";
        internal const string Ready = "SephiriaEnhancements.JoiningSupplies.Ready";
        internal const string MissingHistory = "SephiriaEnhancements.JoiningSupplies.MissingHistory";
        internal const string Claimed = "SephiriaEnhancements.JoiningSupplies.Claimed";
        internal const string Failed = "SephiriaEnhancements.JoiningSupplies.Failed";
        internal const string ChoiceChanged = "SephiriaEnhancements.JoiningSupplies.ChoiceChanged";
        private static readonly Dictionary<string, string[]> Texts = new()
        {
            ["en-US"] = new[] { "Claim joining supplies", "Your reward is nearby. Interact to claim it; then claim the next one from the pause menu.", "Supplies are unavailable here. Wait for loading and combat to end, then try in an open area.", "Joining supplies: {0} remaining. Claim them one at a time from the pause menu.", "Earlier route rewards were not recorded for this exploration. Joining supplies include growth rewards and recorded opportunities only.", "Supplies claimed.", "Joining supplies stopped after an error. Some rewards may already have been received; they will not be sent again automatically.", "The choice was not applied. Check inventory space and whether this reward is still available, then try again." },
            ["zh-CN"] = new[] { "领取加入补给", "奖励已放在身旁。互动领取后，可从暂停菜单领取下一份。", "此处暂时无法领取补给。请等加载和战斗结束，移至空旷处再试。", "加入补给剩余 {0} 份，可从暂停菜单逐份领取。", "本次探索缺少早期路线奖励记录。加入补给仅包含成长奖励及已记录的奖励机会。", "补给已领取。", "加入补给因错误停止。部分奖励可能已经到账，不会自动重复发放。", "本次选择未生效。请检查背包空间及奖励是否仍可领取后重试。" },
            ["zh-TW"] = new[] { "領取加入補給", "獎勵已放在身旁。互動領取後，可從暫停選單領取下一份。", "此處暫時無法領取補給。請等載入和戰鬥結束，移至空曠處再試。", "加入補給剩餘 {0} 份，可從暫停選單逐份領取。", "本次探索缺少早期路線獎勵紀錄。加入補給僅包含成長獎勵及已記錄的獎勵機會。", "補給已領取。", "加入補給因錯誤停止。部分獎勵可能已經到帳，不會自動重複發放。", "本次選擇未生效。請檢查背包空間及獎勵是否仍可領取後重試。" },
            ["ko-KR"] = new[] { "참가 보급 받기", "보상이 옆에 놓였습니다. 상호작용으로 받은 뒤 일시정지 메뉴에서 다음 보급을 받으세요.", "여기서는 보급을 받을 수 없습니다. 로딩과 전투가 끝나면 넓은 곳에서 다시 시도하세요.", "남은 참가 보급: {0}. 일시정지 메뉴에서 하나씩 받으세요.", "이번 탐험의 이전 경로 보상 기록이 없습니다. 성장 보상과 기록된 보상 기회만 보급에 포함됩니다.", "보급을 받았습니다.", "오류로 참가 보급이 중단되었습니다. 일부 보상은 이미 지급되었을 수 있으며 자동으로 다시 지급되지 않습니다.", "선택이 적용되지 않았습니다. 가방 공간과 보상 수령 가능 여부를 확인한 뒤 다시 시도하세요." },
            ["ja-JP"] = new[] { "参加補給を受け取る", "報酬を近くに配置しました。調べて受け取った後、ポーズメニューから次の補給を受け取れます。", "ここでは補給を受け取れません。ロードと戦闘が終わってから、開けた場所で再試行してください。", "参加補給の残り：{0}。ポーズメニューから一つずつ受け取れます。", "今回の探索には以前のルート報酬の記録がありません。補給には成長報酬と記録済みの報酬機会のみ含まれます。", "補給を受け取りました。", "エラーにより参加補給を停止しました。一部の報酬は受け取り済みの可能性があり、自動で再配布しません。", "選択は反映されませんでした。バッグの空きと報酬を受け取れる状態かを確認して再試行してください。" },
            ["de-DE"] = new[] { "Beitrittsvorräte abholen", "Die Belohnung liegt neben dir. Interagiere damit und hole danach die nächste im Pausenmenü ab.", "Hier sind keine Vorräte verfügbar. Warte, bis Laden und Kampf beendet sind, und versuche es an einer freien Stelle erneut.", "Verbleibende Beitrittsvorräte: {0}. Einzeln im Pausenmenü abholen.", "Frühere Routenbelohnungen dieser Erkundung wurden nicht aufgezeichnet. Vorräte enthalten nur Stufenbelohnungen und aufgezeichnete Belohnungsgelegenheiten.", "Vorräte erhalten.", "Die Beitrittsvorräte wurden wegen eines Fehlers gestoppt. Einige Belohnungen wurden möglicherweise bereits erhalten und werden nicht automatisch erneut vergeben.", "Die Auswahl wurde nicht angewendet. Prüfe den Inventarplatz und ob die Belohnung noch verfügbar ist, und versuche es erneut." },
            ["es-ES"] = new[] { "Recoger provisiones de incorporación", "La recompensa está a tu lado. Interactúa para recogerla y pide la siguiente en el menú de pausa.", "Aquí no puedes recibir provisiones. Espera a que terminen la carga y el combate, y prueba en una zona despejada.", "Provisiones de incorporación restantes: {0}. Recógelas de una en una desde el menú de pausa.", "No se registraron las recompensas de rutas anteriores de esta exploración. Las provisiones solo incluyen recompensas de nivel y oportunidades registradas.", "Provisiones recibidas.", "Las provisiones de incorporación se detuvieron por un error. Puede que ya hayas recibido algunas recompensas; no se volverán a entregar automáticamente.", "No se aplicó la selección. Comprueba el espacio del inventario y si la recompensa sigue disponible antes de reintentarlo." },
            ["fr-FR"] = new[] { "Récupérer les provisions d’arrivée", "La récompense est à côté de vous. Interagissez pour la récupérer, puis demandez la suivante dans le menu pause.", "Les provisions sont indisponibles ici. Attendez la fin du chargement et du combat, puis réessayez dans un espace dégagé.", "Provisions d’arrivée restantes : {0}. Récupérez-les une par une dans le menu pause.", "Les récompenses des parcours précédents de cette exploration n’ont pas été enregistrées. Les provisions comprennent seulement les récompenses de niveau et les occasions enregistrées.", "Provisions reçues.", "Les provisions d’arrivée ont été interrompues par une erreur. Certaines récompenses ont peut-être déjà été reçues et ne seront pas redistribuées automatiquement.", "Le choix n’a pas été appliqué. Vérifiez la place dans l’inventaire et la disponibilité de la récompense, puis réessayez." },
            ["it-IT"] = new[] { "Ritira le scorte d’ingresso", "La ricompensa è accanto a te. Interagisci per ritirarla, poi richiedi la successiva dal menu di pausa.", "Qui le scorte non sono disponibili. Attendi la fine del caricamento e del combattimento, poi riprova in uno spazio libero.", "Scorte d’ingresso rimaste: {0}. Ritirale una alla volta dal menu di pausa.", "Le ricompense dei percorsi precedenti di questa esplorazione non sono state registrate. Le scorte includono solo ricompense di livello e opportunità registrate.", "Scorte ricevute.", "Le scorte d’ingresso sono state interrotte da un errore. Alcune ricompense potrebbero essere già state ricevute e non saranno inviate di nuovo automaticamente.", "La scelta non è stata applicata. Controlla lo spazio nell’inventario e la disponibilità della ricompensa, poi riprova." },
            ["pl-PL"] = new[] { "Odbierz zaopatrzenie po dołączeniu", "Nagroda jest obok ciebie. Wejdź z nią w interakcję, a potem odbierz kolejną z menu pauzy.", "Tutaj nie można odebrać zaopatrzenia. Poczekaj na koniec wczytywania i walki, a potem spróbuj na otwartej przestrzeni.", "Pozostałe zaopatrzenie po dołączeniu: {0}. Odbieraj pojedynczo z menu pauzy.", "Nagrody z wcześniejszych tras tej eksploracji nie zostały zapisane. Zaopatrzenie obejmuje tylko nagrody za poziomy i zapisane okazje do nagród.", "Odebrano zaopatrzenie.", "Zaopatrzenie po dołączeniu zatrzymano z powodu błędu. Część nagród mogła już zostać przyznana i nie zostanie automatycznie wysłana ponownie.", "Wybór nie został zastosowany. Sprawdź miejsce w ekwipunku i dostępność nagrody, a potem spróbuj ponownie." },
            ["pt-BR"] = new[] { "Resgatar suprimentos de entrada", "A recompensa está ao seu lado. Interaja para resgatá-la e peça a próxima no menu de pausa.", "Os suprimentos estão indisponíveis aqui. Espere o carregamento e o combate terminarem e tente em uma área livre.", "Suprimentos de entrada restantes: {0}. Resgate um por vez no menu de pausa.", "As recompensas das rotas anteriores desta exploração não foram registradas. Os suprimentos incluem apenas recompensas de nível e oportunidades registradas.", "Suprimentos recebidos.", "Os suprimentos de entrada foram interrompidos por um erro. Algumas recompensas podem já ter sido recebidas e não serão reenviadas automaticamente.", "A escolha não foi aplicada. Confira o espaço no inventário e se a recompensa ainda está disponível antes de tentar de novo." },
            ["ru-RU"] = new[] { "Получить припасы при вступлении", "Награда рядом с вами. Взаимодействуйте с ней, затем запросите следующую в меню паузы.", "Здесь припасы недоступны. Дождитесь окончания загрузки и боя, затем повторите попытку на свободном месте.", "Осталось припасов при вступлении: {0}. Получайте их по одному в меню паузы.", "Награды прежних маршрутов этого похода не записаны. Припасы включают только награды за уровни и записанные возможности получить награду.", "Припасы получены.", "Выдача припасов при вступлении остановлена из-за ошибки. Часть наград могла быть получена; автоматически повторно они не выдаются.", "Выбор не применён. Проверьте место в инвентаре и доступность награды, затем повторите попытку." },
            ["sv-SE"] = new[] { "Hämta anslutningsförråd", "Belöningen ligger bredvid dig. Interagera för att hämta den och begär sedan nästa i pausmenyn.", "Förråd kan inte hämtas här. Vänta tills laddning och strid är över och försök på en öppen plats.", "Återstående anslutningsförråd: {0}. Hämta dem ett i taget från pausmenyn.", "Belöningar från tidigare rutter i denna utforskning registrerades inte. Förråden innehåller bara nivåbelöningar och registrerade belöningstillfällen.", "Förråd mottagna.", "Anslutningsförråden stoppades efter ett fel. Vissa belöningar kan redan ha mottagits och skickas inte igen automatiskt.", "Valet tillämpades inte. Kontrollera plats i inventariet och att belöningen är tillgänglig, och försök igen." },
            ["th-TH"] = new[] { "รับเสบียงสำหรับผู้เข้าร่วม", "รางวัลอยู่ข้างตัวแล้ว โต้ตอบเพื่อรับ แล้วขอรางวัลถัดไปจากเมนูพักเกม", "ยังรับเสบียงที่นี่ไม่ได้ รอให้โหลดและการต่อสู้จบ แล้วลองอีกครั้งในพื้นที่โล่ง", "เสบียงสำหรับผู้เข้าร่วมเหลือ {0} ชุด รับทีละชุดจากเมนูพักเกม", "ไม่มีบันทึกรางวัลเส้นทางก่อนหน้าของการสำรวจนี้ เสบียงจึงมีเฉพาะรางวัลเลเวลและโอกาสรับรางวัลที่บันทึกไว้", "รับเสบียงแล้ว", "เสบียงสำหรับผู้เข้าร่วมหยุดเนื่องจากข้อผิดพลาด บางรางวัลอาจได้รับแล้วและจะไม่ส่งซ้ำโดยอัตโนมัติ", "ยังไม่ได้ใช้ตัวเลือกนี้ ตรวจสอบที่ว่างในกระเป๋าและว่ายังรับรางวัลได้หรือไม่ แล้วลองอีกครั้ง" },
            ["tr-TR"] = new[] { "Katılım erzaklarını al", "Ödül yanında. Etkileşime girerek al, ardından duraklatma menüsünden sıradakini iste.", "Burada erzak alınamıyor. Yükleme ve savaşın bitmesini bekle, ardından açık bir alanda tekrar dene.", "Kalan katılım erzağı: {0}. Duraklatma menüsünden tek tek al.", "Bu keşfin önceki rota ödülleri kaydedilmedi. Erzaklar yalnızca seviye ödüllerini ve kaydedilmiş ödül fırsatlarını içerir.", "Erzaklar alındı.", "Katılım erzakları bir hata nedeniyle durduruldu. Bazı ödüller alınmış olabilir; otomatik olarak tekrar gönderilmezler.", "Seçim uygulanmadı. Envanter alanını ve ödülün hâlâ alınabilir olduğunu kontrol edip tekrar dene." },
        };
        internal static void Register(Action<string, string, string> addText, IEnumerable<string> languages) =>
            Configuration.LocalizationGroup.Register(addText, languages,
                new[] { Claim, Placed, Unavailable, Ready, MissingHistory, Claimed, Failed, ChoiceChanged }, Texts);
    }
}
