using System;
using System.Collections.Generic;

namespace SephiriaEnhancements.MultiplayerAccess.Presentation
{
    internal static class MultiplayerAccessLocalization
    {
        internal const string AllowMidRunJoinSetting = "SephiriaEnhancements.MultiplayerAccess.AllowMidRunJoin";
        internal const string AllowMidRunJoinHelp = "SephiriaEnhancements.MultiplayerAccess.AllowMidRunJoin.Help";
        internal const string ReconnectSetting = "SephiriaEnhancements.MultiplayerAccess.ReconnectSupport";
        internal const string ReconnectHelp = "SephiriaEnhancements.MultiplayerAccess.ReconnectSupport.Help";
        internal const string Off = "SephiriaEnhancements.MultiplayerAccess.Off";
        internal const string On = "SephiriaEnhancements.MultiplayerAccess.On";
        private static readonly Dictionary<string, string[]> Texts = new()
        {
            ["en-US"] = new[] { "New players during exploration", "Host option: choose before exploration. New arrivals use a new character and save slot; they receive no missed-route rewards. This does not control returning players.", "Reconnect support", "Enable the game's reconnect support on this device and keep a hosted Steam room open during exploration. Choose before exploration or joining. Turning this off does not ban returning players or override the game's own reconnect settings.", "Off", "On" },
            ["zh-CN"] = new[] { "新玩家中途加入", "房主在探索前设置。新加入者使用新角色和新存档槽，不补发错过路线的奖励。此项不控制原玩家重连。", "重连支持", "在本机启用游戏的重连支持，并在担任房主时保持探索中的 Steam 房间开放。请在探索或加入房间前设置。关闭此项不会禁止原玩家重连，也不会覆盖游戏自身的重连设置。", "关闭", "开启" },
            ["zh-TW"] = new[] { "新玩家中途加入", "房主在探索前設定。新加入者使用新角色與新存檔欄位，不補發錯過路線的獎勵。此項不控制原玩家重連。", "重連支援", "在本機啟用遊戲的重連支援，並在擔任房主時保持探索中的 Steam 房間開放。請在探索或加入房間前設定。關閉此項不會禁止原玩家重連，也不會覆蓋遊戲自身的重連設定。", "關閉", "開啟" },
            ["ko-KR"] = new[] { "탐험 중 새 플레이어 참가", "호스트가 탐험 전에 설정합니다. 새 참가자는 새 캐릭터와 저장 슬롯을 사용하며 지나친 경로의 보상은 받지 않습니다. 기존 플레이어의 재접속에는 영향을 주지 않습니다.", "재접속 지원", "이 기기에서 게임의 재접속 지원을 켜고, 호스트일 때 탐험 중 Steam 방을 열어 둡니다. 탐험 또는 참가 전에 설정하세요. 꺼도 기존 플레이어의 복귀를 금지하거나 게임 자체 재접속 설정을 덮어쓰지 않습니다.", "꺼짐", "켜짐" },
            ["ja-JP"] = new[] { "探索中の新規プレイヤー参加", "ホストが探索前に設定します。新規参加者は新しいキャラクターとセーブ枠を使い、通過済みルートの報酬は受け取りません。既存プレイヤーの再接続には影響しません。", "再接続サポート", "この端末でゲームの再接続機能を有効にし、ホスト時は探索中のSteamルームを開放します。探索や参加の前に設定してください。オフにしても既存プレイヤーの復帰は禁止せず、ゲーム側の再接続設定は変更しません。", "オフ", "オン" },
            ["de-DE"] = new[] { "Neue Spieler während der Erkundung", "Vor der Erkundung vom Host einstellen. Neue Spieler erhalten einen neuen Charakter und Speicherplatz, aber keine verpassten Routenbelohnungen. Gilt nicht für Rückkehrer.", "Unterstützung für Wiederbeitritt", "Aktiviert die Wiederbeitrittsfunktion auf diesem Gerät und hält als Host den Steam-Raum während der Erkundung offen. Vor Erkundung oder Beitritt einstellen. Ausschalten sperrt keine Rückkehrer und überschreibt keine Spieleinstellungen.", "Aus", "An" },
            ["es-ES"] = new[] { "Nuevos jugadores durante la exploración", "El anfitrión lo configura antes de explorar. Los nuevos usan un personaje y espacio de guardado nuevos, sin premios de rutas omitidas. No controla el regreso de jugadores.", "Soporte de reconexión", "Activa la reconexión del juego en este dispositivo y mantiene abierta la sala Steam al ser anfitrión durante la exploración. Configura antes de explorar o unirte. Desactivarlo no prohíbe regresar ni anula los ajustes del juego.", "Desactivado", "Activado" },
            ["fr-FR"] = new[] { "Nouveaux joueurs en exploration", "À régler par l’hôte avant l’exploration. Les nouveaux joueurs utilisent un nouveau personnage et emplacement de sauvegarde, sans récompenses des chemins manqués. Ne contrôle pas le retour des joueurs.", "Prise en charge de la reconnexion", "Active la reconnexion du jeu sur cet appareil et garde le salon Steam ouvert pendant l’exploration si vous hébergez. À régler avant d’explorer ou de rejoindre. Désactiver ne bannit pas les joueurs de retour et ne remplace pas les réglages du jeu.", "Désactivé", "Activé" },
            ["it-IT"] = new[] { "Nuovi giocatori durante l’esplorazione", "L’host imposta prima di esplorare. I nuovi arrivati usano un nuovo personaggio e slot di salvataggio, senza ricompense dei percorsi saltati. Non controlla il ritorno dei giocatori.", "Supporto riconnessione", "Attiva la riconnessione del gioco su questo dispositivo e mantiene aperta la stanza Steam durante l’esplorazione se sei host. Imposta prima di esplorare o unirti. Disattivare non vieta il ritorno e non sovrascrive le impostazioni del gioco.", "Disattivato", "Attivato" },
            ["pl-PL"] = new[] { "Nowi gracze podczas eksploracji", "Gospodarz ustawia przed eksploracją. Nowi gracze używają nowej postaci i miejsca zapisu, bez nagród z pominiętych tras. Nie steruje powrotem graczy.", "Obsługa ponownego połączenia", "Włącza ponowne połączenie gry na tym urządzeniu i utrzymuje otwarty pokój Steam podczas eksploracji, gdy jesteś gospodarzem. Ustaw przed eksploracją lub dołączeniem. Wyłączenie nie zabrania powrotu ani nie zastępuje ustawień gry.", "Wyłączone", "Włączone" },
            ["pt-BR"] = new[] { "Novos jogadores durante a exploração", "O anfitrião configura antes de explorar. Novos jogadores usam um novo personagem e espaço de salvamento, sem recompensas das rotas perdidas. Não controla o retorno de jogadores.", "Suporte à reconexão", "Ativa a reconexão do jogo neste dispositivo e mantém a sala Steam aberta durante a exploração quando você é anfitrião. Configure antes de explorar ou entrar. Desativar não proíbe o retorno nem substitui os ajustes do jogo.", "Desativado", "Ativado" },
            ["ru-RU"] = new[] { "Новые игроки во время похода", "Хост настраивает до похода. Новые игроки получают нового персонажа и ячейку сохранения, без наград за пропущенные маршруты. Не управляет возвращением игроков.", "Поддержка переподключения", "Включает переподключение игры на этом устройстве и держит комнату Steam открытой в походе, если вы хост. Настройте до похода или входа. Отключение не запрещает возвращаться и не заменяет настройки игры.", "Выключено", "Включено" },
            ["sv-SE"] = new[] { "Nya spelare under utforskning", "Värden ställer in före utforskning. Nya spelare använder en ny figur och sparplats, utan belöningar från missade rutter. Styr inte återvändande spelare.", "Stöd för återanslutning", "Aktiverar spelets återanslutning på denna enhet och håller Steam-rummet öppet under utforskning när du är värd. Ställ in före utforskning eller anslutning. Avstängning förbjuder inte återkomst och ersätter inte spelets inställningar.", "Av", "På" },
            ["th-TH"] = new[] { "ผู้เล่นใหม่เข้าระหว่างสำรวจ", "โฮสต์ตั้งค่าก่อนสำรวจ ผู้เล่นใหม่ใช้ตัวละครและช่องบันทึกใหม่ ไม่ได้รับรางวัลจากเส้นทางที่พลาด ตัวเลือกนี้ไม่ควบคุมผู้เล่นเดิมที่กลับมา", "รองรับการเชื่อมต่อใหม่", "เปิดระบบเชื่อมต่อใหม่ของเกมบนเครื่องนี้ และเปิดห้อง Steam ไว้ระหว่างสำรวจเมื่อเป็นโฮสต์ ตั้งค่าก่อนสำรวจหรือเข้าร่วม การปิดไม่ห้ามผู้เล่นเดิมกลับมาและไม่แทนที่การตั้งค่าของเกม", "ปิด", "เปิด" },
            ["tr-TR"] = new[] { "Keşif sırasında yeni oyuncular", "Ev sahibi keşiften önce ayarlar. Yeni gelenler yeni karakter ve kayıt yuvası kullanır; kaçırılan rota ödüllerini almaz. Geri dönen oyuncuları kontrol etmez.", "Yeniden bağlantı desteği", "Bu cihazda oyunun yeniden bağlantı desteğini açar ve ev sahibiyken keşif sırasında Steam odasını açık tutar. Keşif veya katılımdan önce ayarlayın. Kapatmak geri dönüşü yasaklamaz veya oyun ayarlarını geçersiz kılmaz.", "Kapalı", "Açık" },
        };
        internal static void Register(Action<string, string, string> addText, IEnumerable<string> languages) =>
            Configuration.LocalizationGroup.Register(addText, languages,
                new[] { AllowMidRunJoinSetting, AllowMidRunJoinHelp, ReconnectSetting, ReconnectHelp, Off, On }, Texts);
    }
}
