using System;
using System.Collections.Generic;

namespace SephiriaEnhancements.MultiplayerAccess.Presentation
{
    internal static class MultiplayerAccessLocalization
    {
        internal const string AllowMidRunJoinSetting = "SephiriaEnhancements.MultiplayerAccess.AllowMidRunJoin";
        internal const string AllowMidRunJoinHelp = "SephiriaEnhancements.MultiplayerAccess.AllowMidRunJoin.Help";
        internal const string ReconnectSetting = "SephiriaEnhancements.MultiplayerAccess.ReconnectSupport";
        internal const string ReconnectHelp = "SephiriaEnhancements.MultiplayerAccess.ReconnectSupport.Help";
        internal const string Off = "SephiriaEnhancements.MultiplayerAccess.Off";
        internal const string On = "SephiriaEnhancements.MultiplayerAccess.On";
        private static readonly Dictionary<string, string[]> Texts = new()
        {
            ["en-US"] = new[] { "New players during exploration", "Host option: choose before exploration. With the same Mod version on both sides, new players catch up to teammates’ average level and gold and claim recorded route rewards one at a time from the pause menu. Returning players keep their progress.", "Reconnect support", "Enable the game's reconnect support on this device and keep a hosted Steam room open during exploration. Choose before exploration or joining. Turning this off does not ban returning players or override the game's own reconnect settings.", "Off", "On" },
            ["zh-CN"] = new[] { "新玩家中途加入", "房主在探索前设置。双方安装相同版本 Mod 时，新玩家补足至队友平均等级和金币，并从暂停菜单逐份领取已记录的路线奖励。原玩家重连保留进度。", "重连支持", "在本机启用游戏的重连支持，并在担任房主时保持探索中的 Steam 房间开放。请在探索或加入房间前设置。关闭此项不会禁止原玩家重连，也不会覆盖游戏自身的重连设置。", "关闭", "开启" },
            ["zh-TW"] = new[] { "新玩家中途加入", "房主在探索前設定。雙方安裝相同版本 Mod 時，新玩家補足至隊友平均等級和金幣，並從暫停選單逐份領取已記錄的路線獎勵。原玩家重連保留進度。", "重連支援", "在本機啟用遊戲的重連支援，並在擔任房主時保持探索中的 Steam 房間開放。請在探索或加入房間前設定。關閉此項不會禁止原玩家重連，也不會覆蓋遊戲自身的重連設定。", "關閉", "開啟" },
            ["ko-KR"] = new[] { "탐험 중 새 플레이어 참가", "호스트가 탐험 전에 설정합니다. 양쪽에 같은 버전의 Mod가 있으면 새 참가자는 팀원 평균 레벨과 골드까지 보충받고, 기록된 경로 보상을 일시정지 메뉴에서 하나씩 받습니다. 재접속 플레이어는 진행 상황을 유지합니다.", "재접속 지원", "이 기기에서 게임의 재접속 지원을 켜고, 호스트일 때 탐험 중 Steam 방을 열어 둡니다. 탐험 또는 참가 전에 설정하세요. 꺼도 기존 플레이어의 복귀를 금지하거나 게임 자체 재접속 설정을 덮어쓰지 않습니다.", "꺼짐", "켜짐" },
            ["ja-JP"] = new[] { "探索中の新規プレイヤー参加", "ホストが探索前に設定します。双方が同じModバージョンを導入していれば、新規参加者のレベルとゴールドを仲間の平均まで補い、記録済みルート報酬をポーズメニューから一つずつ受け取れます。再接続では進行状況を引き継ぎます。", "再接続サポート", "この端末でゲームの再接続機能を有効にし、ホスト時は探索中のSteamルームを開放します。探索や参加の前に設定してください。オフにしても既存プレイヤーの復帰は禁止せず、ゲーム側の再接続設定は変更しません。", "オフ", "オン" },
            ["de-DE"] = new[] { "Neue Spieler während der Erkundung", "Vor der Erkundung vom Host einstellen. Mit derselben Mod-Version auf beiden Seiten werden neue Spieler bis zum durchschnittlichen Level und Gold der Mitspieler versorgt. Aufgezeichnete Routenbelohnungen sind einzeln im Pausenmenü verfügbar. Rückkehrer behalten ihren Fortschritt.", "Unterstützung für Wiederbeitritt", "Aktiviert die Wiederbeitrittsfunktion auf diesem Gerät und hält als Host den Steam-Raum während der Erkundung offen. Vor Erkundung oder Beitritt einstellen. Ausschalten sperrt keine Rückkehrer und überschreibt keine Spieleinstellungen.", "Aus", "An" },
            ["es-ES"] = new[] { "Nuevos jugadores durante la exploración", "El anfitrión lo configura antes de explorar. Con la misma versión del Mod en ambos lados, los nuevos alcanzan el nivel y oro medios del equipo y recogen recompensas de rutas registradas de una en una en el menú de pausa. Al reconectarse se conserva el progreso.", "Soporte de reconexión", "Activa la reconexión del juego en este dispositivo y mantiene abierta la sala Steam al ser anfitrión durante la exploración. Configura antes de explorar o unirte. Desactivarlo no prohíbe regresar ni anula los ajustes del juego.", "Desactivado", "Activado" },
            ["fr-FR"] = new[] { "Nouveaux joueurs en exploration", "À régler par l’hôte avant l’exploration. Avec la même version du Mod des deux côtés, les nouveaux rejoignent le niveau et l’or moyens de l’équipe et récupèrent les récompenses de parcours enregistrées une par une dans le menu pause. La reconnexion conserve la progression.", "Prise en charge de la reconnexion", "Active la reconnexion du jeu sur cet appareil et garde le salon Steam ouvert pendant l’exploration si vous hébergez. À régler avant d’explorer ou de rejoindre. Désactiver ne bannit pas les joueurs de retour et ne remplace pas les réglages du jeu.", "Désactivé", "Activé" },
            ["it-IT"] = new[] { "Nuovi giocatori durante l’esplorazione", "L’host imposta prima di esplorare. Con la stessa versione del Mod su entrambi i lati, i nuovi raggiungono il livello e l’oro medi dei compagni e ritirano le ricompense dei percorsi registrati una alla volta dal menu di pausa. La riconnessione conserva i progressi.", "Supporto riconnessione", "Attiva la riconnessione del gioco su questo dispositivo e mantiene aperta la stanza Steam durante l’esplorazione se sei host. Imposta prima di esplorare o unirti. Disattivare non vieta il ritorno e non sovrascrive le impostazioni del gioco.", "Disattivato", "Attivato" },
            ["pl-PL"] = new[] { "Nowi gracze podczas eksploracji", "Gospodarz ustawia przed eksploracją. Przy tej samej wersji Moda po obu stronach nowi gracze otrzymują poziom i złoto do średniej drużyny oraz odbierają zapisane nagrody tras pojedynczo z menu pauzy. Ponowne połączenie zachowuje postępy.", "Obsługa ponownego połączenia", "Włącza ponowne połączenie gry na tym urządzeniu i utrzymuje otwarty pokój Steam podczas eksploracji, gdy jesteś gospodarzem. Ustaw przed eksploracją lub dołączeniem. Wyłączenie nie zabrania powrotu ani nie zastępuje ustawień gry.", "Wyłączone", "Włączone" },
            ["pt-BR"] = new[] { "Novos jogadores durante a exploração", "O anfitrião configura antes de explorar. Com a mesma versão do Mod dos dois lados, novos jogadores recebem nível e ouro até a média da equipe e resgatam recompensas de rotas registradas uma por vez no menu de pausa. A reconexão mantém o progresso.", "Suporte à reconexão", "Ativa a reconexão do jogo neste dispositivo e mantém a sala Steam aberta durante a exploração quando você é anfitrião. Configure antes de explorar ou entrar. Desativar não proíbe o retorno nem substitui os ajustes do jogo.", "Desativado", "Ativado" },
            ["ru-RU"] = new[] { "Новые игроки во время похода", "Хост настраивает до похода. При одинаковой версии мода у обеих сторон новые игроки получают уровни и золото до среднего значения команды и забирают записанные награды маршрутов по одной в меню паузы. Переподключение сохраняет прогресс.", "Поддержка переподключения", "Включает переподключение игры на этом устройстве и держит комнату Steam открытой в походе, если вы хост. Настройте до похода или входа. Отключение не запрещает возвращаться и не заменяет настройки игры.", "Выключено", "Включено" },
            ["sv-SE"] = new[] { "Nya spelare under utforskning", "Värden ställer in före utforskning. Med samma Mod-version på båda sidor får nya spelare nivå och guld upp till lagets genomsnitt och hämtar registrerade ruttbelöningar en i taget i pausmenyn. Återanslutning behåller framstegen.", "Stöd för återanslutning", "Aktiverar spelets återanslutning på denna enhet och håller Steam-rummet öppet under utforskning när du är värd. Ställ in före utforskning eller anslutning. Avstängning förbjuder inte återkomst och ersätter inte spelets inställningar.", "Av", "På" },
            ["th-TH"] = new[] { "ผู้เล่นใหม่เข้าระหว่างสำรวจ", "โฮสต์ตั้งค่าก่อนสำรวจ เมื่อทั้งสองฝ่ายใช้ Mod รุ่นเดียวกัน ผู้เล่นใหม่จะได้รับเลเวลและทองจนถึงค่าเฉลี่ยของทีม และรับรางวัลเส้นทางที่บันทึกไว้ทีละชุดจากเมนูพักเกม การเชื่อมต่อใหม่จะคงความคืบหน้าเดิม", "รองรับการเชื่อมต่อใหม่", "เปิดระบบเชื่อมต่อใหม่ของเกมบนเครื่องนี้ และเปิดห้อง Steam ไว้ระหว่างสำรวจเมื่อเป็นโฮสต์ ตั้งค่าก่อนสำรวจหรือเข้าร่วม การปิดไม่ห้ามผู้เล่นเดิมกลับมาและไม่แทนที่การตั้งค่าของเกม", "ปิด", "เปิด" },
            ["tr-TR"] = new[] { "Keşif sırasında yeni oyuncular", "Ev sahibi keşiften önce ayarlar. İki tarafta aynı Mod sürümü varsa yeni oyuncular takımın ortalama seviye ve altınına tamamlanır, kayıtlı rota ödüllerini duraklatma menüsünden tek tek alır. Yeniden bağlananların ilerlemesi korunur.", "Yeniden bağlantı desteği", "Bu cihazda oyunun yeniden bağlantı desteğini açar ve ev sahibiyken keşif sırasında Steam odasını açık tutar. Keşif veya katılımdan önce ayarlayın. Kapatmak geri dönüşü yasaklamaz veya oyun ayarlarını geçersiz kılmaz.", "Kapalı", "Açık" },
        };
        internal static void Register(Action<string, string, string> addText, IEnumerable<string> languages) =>
            Configuration.LocalizationGroup.Register(addText, languages,
                new[] { AllowMidRunJoinSetting, AllowMidRunJoinHelp, ReconnectSetting, ReconnectHelp, Off, On }, Texts);
    }
}
