using System;

namespace SephiriaEnhancements.Runtime
{
    internal static class FeaturePatchOwnership
    {
        internal static FeatureId Get(Type patchType)
        {
            switch (patchType.FullName)
            {
                case "SephiriaEnhancements.EffectStats.Integration.EffectStatsPanelPatch": return FeatureId.EffectStats;
                case "SephiriaEnhancements.Integration.NativePresetSavePatch": return FeatureId.Inventory;
                case "SephiriaEnhancements.AutoCasting.Integration.AutoCastingManualInputPatch":
                case "SephiriaEnhancements.AutoCasting.Integration.AutoCastingOptionsPatch":
                case "SephiriaEnhancements.AutoCasting.Integration.AutoCastingPanelPatch":
                case "SephiriaEnhancements.AutoCasting.Integration.AutoCastingSubmitPatch":
                case "SephiriaEnhancements.AutoCasting.Integration.SkillNavigationMovePatch":
                case "SephiriaEnhancements.AutoCasting.Integration.SkillNavigationTogglePatch":
                    return FeatureId.AutoCasting;
                case "SephiriaEnhancements.Integration.DamageDetailCapture":
                case "SephiriaEnhancements.Integration.DamageFeedbackCapture":
                case "SephiriaEnhancements.Integration.LocalFinalBlowCapture":
                case "SephiriaEnhancements.Integration.NativeReportDismissal":
                case "SephiriaEnhancements.Integration.NativeStatisticsPauseEntry":
                case "SephiriaEnhancements.Integration.UnitDeathCapture":
                    return FeatureId.CombatInsights;
                case "SephiriaEnhancements.CombatTargeting.CombatTargetingCastPatch":
                case "SephiriaEnhancements.CombatTargeting.CombatTargetingDashPatch":
                case "SephiriaEnhancements.CombatTargeting.CombatTargetingInputPatch":
                case "SephiriaEnhancements.CombatTargeting.CombatTargetingReleasePatch":
                    return FeatureId.CombatTargeting;
                case "SephiriaEnhancements.CombatVisuals.CombatVisualOptionReadPatch":
                case "SephiriaEnhancements.CombatVisuals.CompanionAreaJudgementTransparencyPatch":
                case "SephiriaEnhancements.CombatVisuals.CompanionBodyTransparencyPatch":
                case "SephiriaEnhancements.CombatVisuals.CompanionBulletDestroyTransparencyPatch":
                case "SephiriaEnhancements.CombatVisuals.CompanionBulletHitTransparencyPatch":
                case "SephiriaEnhancements.CombatVisuals.CompanionBulletTailTransparencyPatch":
                case "SephiriaEnhancements.CombatVisuals.CompanionBulletTransparencyPatch":
                case "SephiriaEnhancements.CombatVisuals.CompanionChainLightningTransparencyPatch":
                case "SephiriaEnhancements.CombatVisuals.CompanionMeleeTransparencyPatch":
                case "SephiriaEnhancements.CombatVisuals.CompanionSpreadAoeTransparencyPatch":
                    return FeatureId.CombatVisuals;
                case "SephiriaEnhancements.DefeatRetry.ApplyDefeatRetryPlacementPatch":
                case "SephiriaEnhancements.DefeatRetry.BossEncounterRetryCheckpointPatch":
                case "SephiriaEnhancements.DefeatRetry.BossRetryPreserveFloorPatch":
                case "SephiriaEnhancements.DefeatRetry.BossRetryPropRecipePatch":
                case "SephiriaEnhancements.DefeatRetry.DefeatRetryClientNotificationPatch":
                case "SephiriaEnhancements.DefeatRetry.DefeatRetryCutscenePatch":
                case "SephiriaEnhancements.DefeatRetry.DefeatRetryNewGamePatch":
                case "SephiriaEnhancements.DefeatRetry.DefeatRetryPlayerRestorePatch":
                case "SephiriaEnhancements.DefeatRetry.DefeatRetryTravelRequestPatch":
                case "SephiriaEnhancements.DefeatRetry.GameOverDefeatRetryButtonPatch":
                case "SephiriaEnhancements.DefeatRetry.NativeRetryRestart":
                case "SephiriaEnhancements.DefeatRetry.PreserveDefeatRetryLobbyPatch":
                case "SephiriaEnhancements.DefeatRetry.PreserveDefeatRetryRejoinStatePatch":
                case "SephiriaEnhancements.DefeatRetry.PreserveDefeatRetrySaveCreationPatch":
                case "SephiriaEnhancements.DefeatRetry.PreserveDefeatRetrySaveDeletionPatch":
                case "SephiriaEnhancements.DefeatRetry.RenderedCombatFloorRetryCheckpointPatch":
                case "SephiriaEnhancements.DefeatRetry.SeedBossEncounterRetryCheckpointPatch":
                case "SephiriaEnhancements.Integration.NativeSaveCapturePatch":
                    return FeatureId.DefeatRetry;
                case "SephiriaEnhancements.DeveloperConsole.DeveloperConsoleOpenPatch":
                case "SephiriaEnhancements.DeveloperTools.DeveloperPlayerDamagePatch":
                case "SephiriaEnhancements.Diagnostics.NativeFloorRenderProfilingPatch":
                case "SephiriaEnhancements.Diagnostics.NativeLoadingOperationProfilingPatch":
                case "SephiriaEnhancements.Diagnostics.NativeLoadingStateProfilingPatch":
                case "SephiriaEnhancements.Diagnostics.NativeStartupProfilingPatch":
                    return FeatureId.DeveloperTools;
                case "SephiriaEnhancements.Runtime.NativeBossEncounterCompletedPatch":
                case "SephiriaEnhancements.Runtime.NativeBossEncounterCompletionStartedPatch":
                case "SephiriaEnhancements.Runtime.NativeBossEncounterDefeatedPatch":
                case "SephiriaEnhancements.Runtime.NativeBossEncounterPausedPatch":
                case "SephiriaEnhancements.Runtime.NativeBossEncounterResumedPatch":
                case "SephiriaEnhancements.Runtime.NativeBossEncounterStartedPatch":
                case "SephiriaEnhancements.Runtime.NativeOrdinaryEncounterClearedPatch":
                case "SephiriaEnhancements.Runtime.NativeSeedBossEncounterCompletedPatch":
                case "SephiriaEnhancements.Runtime.NativeSeedBossEncounterCompletionStartedPatch":
                case "SephiriaEnhancements.Runtime.NativeSeedBossEncounterDefeatedPatch":
                case "SephiriaEnhancements.Runtime.NativeSeedBossEncounterStartedPatch":
                    return FeatureId.CombatInsights;
                case "SephiriaEnhancements.Inventory.InventoryArtifactIntentClickPatch":
                case "SephiriaEnhancements.Inventory.InventoryArtifactIntentClosedPatch":
                case "SephiriaEnhancements.Inventory.InventoryArtifactIntentInputPatch":
                case "SephiriaEnhancements.Inventory.InventoryArtifactIntentModePatch":
                case "SephiriaEnhancements.Inventory.InventoryPanelCancelPatch":
                case "SephiriaEnhancements.Inventory.InventoryPanelTooltipPlacementPatch":
                case "SephiriaEnhancements.Inventory.InventoryTemporaryItemDropPatch":
                case "SephiriaEnhancements.Runtime.GameBridge.Inventory.ArtifactCategoryRefreshOrderPatch":
                case "SephiriaEnhancements.Runtime.GameBridge.Inventory.ArtifactRefreshOrderPatch":
                case "SephiriaEnhancements.Runtime.GameBridge.Inventory.InventoryEvaluationOrderTraceStartPatch":
                case "SephiriaEnhancements.Runtime.GameBridge.Inventory.NativeInventoryItemSelectionModePatch":
                case "SephiriaEnhancements.Runtime.GameBridge.Inventory.UniqueEffectRegistrationTracePatch":
                    return FeatureId.Inventory;
                case "SephiriaEnhancements.KeyboardUiNavigation.ItemBoxKeyboardSecondaryActionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.ItemIconKeyboardSubmitPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.KeyboardCarriedItemPositionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.KeyboardControlsChangedPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.KeyboardCursorVisibilityPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.KeyboardMapSelectionPositionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.KeyboardPointerHoverPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.KeyboardPointerInputPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.MenuKeyboardSelectionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.MessageBoxKeyboardInitialSelectionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.MessageBoxKeyboardRestoredSelectionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.OptionsKeyboardEmptyFocusPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.OptionsKeyboardMovePatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.OptionsKeyboardTabSelectionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.RewardKeyboardCancelSelectionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.RewardKeyboardClosedSelectionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.RewardKeyboardControlSelectionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.RewardKeyboardGeneratedSelectionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.RewardKeyboardInventoryOpenedSelectionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.RewardKeyboardToggleSelectionPatch":
                case "SephiriaEnhancements.KeyboardUiNavigation.TreeShopKeyboardSecondaryActionPatch":
                    return FeatureId.KeyboardUiNavigation;
                case "SephiriaEnhancements.MapEnhancements.MapNavigationUpdatePatch":
                case "SephiriaEnhancements.MapEnhancements.MapPanelClosedPatch":
                case "SephiriaEnhancements.MapEnhancements.MapPanelOpenedPatch":
                case "SephiriaEnhancements.MapEnhancements.MapPanelShowPatch":
                    return FeatureId.MapEnhancements;
                case "SephiriaEnhancements.ModJournal.Integration.ModJournalCategoryPatch":
                case "SephiriaEnhancements.ModJournal.Integration.ModJournalClearPatch":
                case "SephiriaEnhancements.ModJournal.Integration.ModJournalRefreshPatch":
                case "SephiriaEnhancements.ModJournal.Integration.ModJournalTutorialPatch":
                    return FeatureId.ModJournal;
                case "SephiriaEnhancements.MultiplayerAccess.Integration.FreshPlayerSaveSlotPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.FreshPlayerStartingItemPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyAnvilConfirmationPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyAnvilSelectionPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyCheckpointPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyCommandOwnershipPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyDespawnPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyDisconnectPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyEmbeddedAnvilPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyEmbeddedMiraclePatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyEnchantConfirmationPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyExplorationPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyFacilityDicePatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyFinishPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyInitializationPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyInteractionOwnershipPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyLevelFeedbackPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyLevelRewardPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyLoadPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyMiracleConfirmationPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyRewardOwnershipPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplySavePatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplySpawnPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyTabletPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyWriteSavePatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.MidRunAuthenticationPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.MidRunDisconnectCleanupPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.MidRunDungeonAccessPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.MidRunLobbyAvailabilityPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.MidRunReconnectSupportPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.MidRunServerCleanupPatch":
                case "SephiriaEnhancements.MultiplayerAccess.Integration.NativeJoiningSupplyPauseEntry":
                    return FeatureId.MultiplayerAccess;
                case "SephiriaEnhancements.MultiplayerRules.Integration.AvatarSpawnOriginCapturePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.DirectMerchantInventoryRulePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.EnemyGroupDifficultyOffsetRulePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.EnemyHealthInitializationPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.EnemySpawnRoutineOriginPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.FestivalOfBloodHealingRulePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.FloorGenerationRuleContextPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.HiddenRoomBreakableRewardCountRulePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.HiddenRoomNativeBreakableSuppressionPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.KrazBossSpawnOriginPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.LifeSupplyCreatePropRulePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.MerchantCandidateRulePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.MerchantGenerationRuleContextPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.MindEaterRootSummonOriginPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.MoneyAwardRulePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.MonsterSpawnEntryMultiplierPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.MultiplayerRulesExplorationStartPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.MultiplayerRulesLobbyDeparturePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.NativeLobbyRulesEntryPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.MultiplayerRulesNetworkSessionEndPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.NetworkSpawnOriginCapturePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.PlayerMoneyAwardAmountPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.QliphothFinalBattleEntryTrackingRulePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.QliphothFinalBattleGridRulePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.QliphothSealRulePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.QliphothTempleTrioActiveCountRulePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.SafeMerchantInventoryRulePatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.StandardBossRulesPatch":
                case "SephiriaEnhancements.MultiplayerRules.Integration.TargetedExperienceOrbDivisorPatch":
                    return FeatureId.MultiplayerRules;
                case "SephiriaEnhancements.ResourceBarValues.Integration.NativeBossBarValuesPatch":
                case "SephiriaEnhancements.ResourceBarValues.Integration.NativeCompanionBarValuesPatch":
                case "SephiriaEnhancements.ResourceBarValues.Integration.NativeManaBarValuesPatch":
                case "SephiriaEnhancements.ResourceBarValues.Integration.NativePlayerBarValuesPatch":
                case "SephiriaEnhancements.ResourceBarValues.Integration.NativePropBarValuesPatch":
                case "SephiriaEnhancements.ResourceBarValues.Integration.NativeUnitBarValuesPatch":
                    return FeatureId.ResourceBarValues;
                case "SephiriaEnhancements.Configuration.ModLanguageLoadPatch":
                case "SephiriaEnhancements.Configuration.NativeControlOptionsClosedPatch":
                case "SephiriaEnhancements.Configuration.OptionsPanelPatch":
                    return FeatureId.Settings;
                case "SephiriaEnhancements.ViewDistance.ViewDistancePatch":
                    return FeatureId.ViewDistance;
                default: throw new InvalidOperationException("Patch has no feature owner: " + patchType.FullName);
            }
        }
    }
}
