using System;
using SephiriaEnhancements.Runtime;

namespace SephiriaEnhancements
{
    public sealed partial class SephiriaEnhancementsMod
    {
        // One declaration owns the feature, installation phase and order of each patch.
        private static (FeatureId Feature, Type Patch)[] StartupPatches() =>
            new[]
            {
                (FeatureId.ItemCommunication, typeof(global::SephiriaEnhancements.ItemCommunication.Integration.ItemCommunicationNavigationPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Integration.DamageFeedbackCapture)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Integration.DamageDetailCapture)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Integration.UnitDeathCapture)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Integration.LocalFinalBlowCapture)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Integration.NativeReportDismissal)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Integration.NativeStatisticsPauseEntry)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Integration.DamageSourcesOpenedPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Integration.DamageSourcesCurrentAreaPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Integration.DamageSourcesAllAreasPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Integration.TrainingDirectDamagePatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Integration.TrainingCompanionDamagePatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Integration.TrainingPlayerTravelPatch)),
                (FeatureId.ModJournal, typeof(global::SephiriaEnhancements.ModJournal.Integration.ModJournalRefreshPatch)),
                (FeatureId.EffectStats, typeof(global::SephiriaEnhancements.EffectStats.Integration.EffectStatsPanelPatch)),
                (FeatureId.ModJournal, typeof(global::SephiriaEnhancements.ModJournal.Integration.ModJournalClearPatch)),
                (FeatureId.ModJournal, typeof(global::SephiriaEnhancements.ModJournal.Integration.ModJournalCategoryPatch)),
                (FeatureId.ModJournal, typeof(global::SephiriaEnhancements.ModJournal.Integration.ModJournalTutorialPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Runtime.NativeOrdinaryEncounterClearedPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Runtime.NativeBossEncounterStartedPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Runtime.NativeBossEncounterDefeatedPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Runtime.NativeBossEncounterCompletionStartedPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Runtime.NativeBossEncounterCompletedPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Runtime.NativeBossEncounterPausedPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Runtime.NativeBossEncounterResumedPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Runtime.NativeSeedBossEncounterStartedPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Runtime.NativeSeedBossEncounterDefeatedPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Runtime.NativeSeedBossEncounterCompletionStartedPatch)),
                (FeatureId.CombatInsights, typeof(global::SephiriaEnhancements.Runtime.NativeSeedBossEncounterCompletedPatch)),
                (FeatureId.ResourceBarValues, typeof(global::SephiriaEnhancements.ResourceBarValues.Integration.NativeBossBarValuesPatch)),
                (FeatureId.ResourceBarValues, typeof(global::SephiriaEnhancements.ResourceBarValues.Integration.NativeUnitBarValuesPatch)),
                (FeatureId.ResourceBarValues, typeof(global::SephiriaEnhancements.ResourceBarValues.Integration.NativePropBarValuesPatch)),
                (FeatureId.ResourceBarValues, typeof(global::SephiriaEnhancements.ResourceBarValues.Integration.NativePlayerBarValuesPatch)),
                (FeatureId.ResourceBarValues, typeof(global::SephiriaEnhancements.ResourceBarValues.Integration.NativeCompanionBarValuesPatch)),
                (FeatureId.ResourceBarValues, typeof(global::SephiriaEnhancements.ResourceBarValues.Integration.NativeManaBarValuesPatch)),
                (FeatureId.Settings, typeof(global::SephiriaEnhancements.Configuration.OptionsPanelPatch)),
                (FeatureId.Settings, typeof(global::SephiriaEnhancements.Configuration.ModLanguageLoadPatch)),
                (FeatureId.Settings, typeof(global::SephiriaEnhancements.Configuration.NativeControlOptionsClosedPatch)),
                (FeatureId.CombatVisuals, typeof(global::SephiriaEnhancements.CombatVisuals.CombatVisualOptionReadPatch)),
                (FeatureId.CombatVisuals, typeof(global::SephiriaEnhancements.CombatVisuals.CompanionBodyTransparencyPatch)),
                (FeatureId.CombatVisuals, typeof(global::SephiriaEnhancements.CombatVisuals.CompanionBulletTransparencyPatch)),
                (FeatureId.CombatVisuals, typeof(global::SephiriaEnhancements.CombatVisuals.CompanionAreaJudgementTransparencyPatch)),
                (FeatureId.CombatVisuals, typeof(global::SephiriaEnhancements.CombatVisuals.CompanionSpreadAoeTransparencyPatch)),
                (FeatureId.CombatVisuals, typeof(global::SephiriaEnhancements.CombatVisuals.CompanionMeleeTransparencyPatch)),
                (FeatureId.CombatVisuals, typeof(global::SephiriaEnhancements.CombatVisuals.CompanionBulletTailTransparencyPatch)),
                (FeatureId.CombatVisuals, typeof(global::SephiriaEnhancements.CombatVisuals.CompanionBulletHitTransparencyPatch)),
                (FeatureId.CombatVisuals, typeof(global::SephiriaEnhancements.CombatVisuals.CompanionBulletDestroyTransparencyPatch)),
                (FeatureId.CombatVisuals, typeof(global::SephiriaEnhancements.CombatVisuals.CompanionChainLightningTransparencyPatch)),
                (FeatureId.DeveloperTools, typeof(global::SephiriaEnhancements.DeveloperConsole.DeveloperConsoleOpenPatch)),
#if SEPHIRIA_ENHANCEMENTS_DEVTOOLS
                (FeatureId.DeveloperTools, typeof(global::SephiriaEnhancements.DeveloperTools.DeveloperPlayerDamagePatch)),
                (FeatureId.DeveloperTools, typeof(global::SephiriaEnhancements.Diagnostics.NativeStartupProfilingPatch)),
                (FeatureId.DeveloperTools, typeof(global::SephiriaEnhancements.Diagnostics.NativeLoadingOperationProfilingPatch)),
                (FeatureId.DeveloperTools, typeof(global::SephiriaEnhancements.Diagnostics.NativeLoadingStateProfilingPatch)),
                (FeatureId.DeveloperTools, typeof(global::SephiriaEnhancements.Diagnostics.NativeFloorRenderProfilingPatch)),
#endif
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Integration.NativePresetSavePatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Integration.NativePresetEditPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.BossEncounterRetryCheckpointPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.SeedBossEncounterRetryCheckpointPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.FloorEntryRetryCheckpointPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.ApplyDefeatRetryPlacementPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.DefeatRetryPlayerRestorePatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.DefeatRetryClientNotificationPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.NativeRetryPurchasePatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.DefeatRetryCutscenePatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.NativeRetryRestart)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.DefeatRetryTravelRequestPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.BossRetryPropRecipePatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.BossRetryPreserveFloorPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.GameOverDefeatRetryButtonPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.RetryDeathCausePatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.RetryConclusionDispatchPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.RetryDisconnectCausePatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.PreserveDefeatRetrySaveDeletionPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.PreserveDefeatRetrySaveCreationPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.PreserveDefeatRetryLobbyPatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.PreserveDefeatRetryRejoinStatePatch)),
                (FeatureId.DefeatRetry, typeof(global::SephiriaEnhancements.DefeatRetry.DefeatRetryNewGamePatch)),
                (FeatureId.CombatTargeting, typeof(global::SephiriaEnhancements.CombatTargeting.CombatTargetingInputPatch)),
                (FeatureId.AutoCasting, typeof(global::SephiriaEnhancements.AutoCasting.Integration.AutoCastingManualInputPatch)),
                (FeatureId.AutoCasting, typeof(global::SephiriaEnhancements.AutoCasting.Integration.AutoCastingPanelPatch)),
                (FeatureId.StageRewardAutoClaim, typeof(global::SephiriaEnhancements.StageRewardAutoClaim.Integration.StageRewardTutorialPatch)),
                (FeatureId.StageRewardAutoClaim, typeof(global::SephiriaEnhancements.StageRewardAutoClaim.Integration.StageRewardCommandPatch)),
                (FeatureId.CostumeAppearance, typeof(global::SephiriaEnhancements.CostumeAppearance.Integration.CostumeAppearanceEquipPatch)),
                (FeatureId.CostumeAppearance, typeof(global::SephiriaEnhancements.CostumeAppearance.Integration.CostumeAppearancePreferencePatch)),
                (FeatureId.CostumeAppearance, typeof(global::SephiriaEnhancements.CostumeAppearance.Integration.CostumeAppearancePanelPatch)),
                (FeatureId.AutoCasting, typeof(global::SephiriaEnhancements.AutoCasting.Integration.AutoCastingOptionsPatch)),
                (FeatureId.AutoCasting, typeof(global::SephiriaEnhancements.AutoCasting.Integration.AutoCastingSubmitPatch)),
                (FeatureId.CharacterPanelNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.CharacterPanelNavigationMovePatch)),
                (FeatureId.CharacterPanelNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.CharacterPanelNavigationTogglePatch)),
                (FeatureId.CombatTargeting, typeof(global::SephiriaEnhancements.CombatTargeting.CombatTargetingCastPatch)),
                (FeatureId.CombatTargeting, typeof(global::SephiriaEnhancements.CombatTargeting.CombatTargetingReleasePatch)),
                (FeatureId.CombatTargeting, typeof(global::SephiriaEnhancements.CombatTargeting.CombatTargetingDashPatch)),
                (FeatureId.ViewDistance, typeof(global::SephiriaEnhancements.ViewDistance.ViewDistancePatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.MenuKeyboardSelectionPatch)),
                (FeatureId.RewardNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.RewardKeyboardGeneratedSelectionPatch)),
                (FeatureId.RewardNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.RewardKeyboardControlSelectionPatch)),
                (FeatureId.RewardNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.RewardKeyboardInventoryOpenedSelectionPatch)),
                (FeatureId.RewardNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.RewardKeyboardToggleSelectionPatch)),
                (FeatureId.RewardNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.RewardKeyboardClosedSelectionPatch)),
                (FeatureId.RewardNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.RewardKeyboardCancelSelectionPatch)),
                (FeatureId.OptionsNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.OptionsKeyboardTabSelectionPatch)),
                (FeatureId.OptionsNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.OptionsKeyboardMovePatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.KeyboardPointerInputPatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.KeyboardPointerHoverPatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.KeyboardCursorVisibilityPatch)),
                (FeatureId.CharacterPanelNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.KeyboardCarriedItemPositionPatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.KeyboardMapSelectionPositionPatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.MessageBoxKeyboardInitialSelectionPatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.Integration.NativeTextInputKeyboardDefocusPatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.Integration.NativeTextInputKeyboardClosedPatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.MessageBoxKeyboardRestoredSelectionPatch)),
                (FeatureId.OptionsNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.OptionsKeyboardEmptyFocusPatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.KeyboardControlsChangedPatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.ItemIconKeyboardSubmitPatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.ItemBoxKeyboardSecondaryActionPatch)),
                (FeatureId.KeyboardUiNavigation, typeof(global::SephiriaEnhancements.KeyboardUiNavigation.TreeShopKeyboardSecondaryActionPatch)),
                (FeatureId.MapEnhancements, typeof(global::SephiriaEnhancements.MapEnhancements.MapPanelShowPatch)),
                (FeatureId.MapEnhancements, typeof(global::SephiriaEnhancements.MapEnhancements.MapNavigationUpdatePatch)),
                (FeatureId.MapEnhancements, typeof(global::SephiriaEnhancements.MapEnhancements.MapPanelOpenedPatch)),
                (FeatureId.MapEnhancements, typeof(global::SephiriaEnhancements.MapEnhancements.MapPanelClosedPatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Runtime.GameBridge.Inventory.NativeInventoryItemSelectionModePatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Inventory.InventoryArtifactIntentClickPatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Inventory.InventoryArtifactIntentInputPatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Inventory.InventoryPanelCancelPatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Inventory.InventoryPanelTooltipPlacementPatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Inventory.InventoryArtifactIntentClosedPatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Inventory.InventoryArtifactIntentModePatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Inventory.InventoryTemporaryItemDropPatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Runtime.GameBridge.Inventory.InventoryEvaluationOrderTraceStartPatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Runtime.GameBridge.Inventory.ArtifactCategoryRefreshOrderPatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Runtime.GameBridge.Inventory.ArtifactRefreshOrderPatch)),
                (FeatureId.Inventory, typeof(global::SephiriaEnhancements.Runtime.GameBridge.Inventory.UniqueEffectRegistrationTracePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.MultiplayerRulesNetworkSessionEndPatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.MultiplayerRulesLobbyDeparturePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.MultiplayerRulesExplorationStartPatch))
            };

        private static (FeatureId Feature, Type Patch)[] MidRunAdmissionPatches() =>
            new[]
            {
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.MidRunAuthenticationPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.MidRunDungeonAccessPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.MidRunReconnectSupportPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.FreshPlayerStartingItemPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.MidRunLobbyAvailabilityPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.FreshPlayerSaveSlotPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.MidRunDisconnectCleanupPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.MidRunServerCleanupPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyInitializationPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyExplorationPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyLoadPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplySpawnPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyFinishPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyTabletPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyCheckpointPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplySavePatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyDisconnectPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyCommandOwnershipPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyRewardOwnershipPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyWriteSavePatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyDespawnPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyFacilityDicePatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyInteractionOwnershipPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyEmbeddedMiraclePatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyEmbeddedAnvilPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyMiracleConfirmationPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyAnvilSelectionPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyAnvilConfirmationPatch)),
                (FeatureId.MultiplayerAccess, typeof(global::SephiriaEnhancements.MultiplayerAccess.Integration.JoiningSupplyEnchantConfirmationPatch))
            };

        private static (FeatureId Feature, Type Patch)[] MultiplayerRuleBehaviorPatches() =>
            new[]
            {
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.EnemySpawnRoutineOriginPatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.AvatarSpawnOriginCapturePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.NetworkSpawnOriginCapturePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.EnemyHealthInitializationPatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.KrazBossSpawnOriginPatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.MindEaterRootSummonOriginPatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.MonsterSpawnEntryMultiplierPatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.TargetedExperienceOrbDivisorPatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.MoneyAwardRulePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.PlayerMoneyAwardAmountPatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.StandardBossRulesPatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.QliphothSealRulePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.QliphothFinalBattleGridRulePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.QliphothFinalBattleEntryTrackingRulePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.QliphothTempleTrioActiveCountRulePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.MerchantGenerationRuleContextPatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.MerchantCandidateRulePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.SafeMerchantInventoryRulePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.DirectMerchantInventoryRulePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.FestivalOfBloodHealingRulePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.HiddenRoomBreakableRewardCountRulePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.HiddenRoomNativeBreakableSuppressionPatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.FloorGenerationRuleContextPatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.EnemyGroupDifficultyOffsetRulePatch)),
                (FeatureId.MultiplayerRules, typeof(global::SephiriaEnhancements.MultiplayerRules.Integration.LifeSupplyCreatePropRulePatch))
            };
    }
}
