using System;
using System.Collections.Generic;
using SephiriaEnhancements.Configuration;

namespace SephiriaEnhancements.DefeatRetry
{
    internal static class RetryRecoveryLocalization
    {
        internal const string Failed = "SephiriaEnhancements.DefeatRetry.RecoveryFailed";
        internal const string TimedOut = "SephiriaEnhancements.DefeatRetry.RecoveryTimedOut";
        internal const string Disconnected = "SephiriaEnhancements.DefeatRetry.RecoveryDisconnected";
        internal const string PurchaseWait = "SephiriaEnhancements.DefeatRetry.PurchaseWait";
        internal const string ControlsIncomplete = "SephiriaEnhancements.DefeatRetry.ControlsIncomplete";
        private static readonly string[] Keys = { Failed, TimedOut, Disconnected, PurchaseWait, ControlsIncomplete };
        private static readonly Dictionary<string, string[]> Texts = new Dictionary<string, string[]>
        {
            ["en-US"] = new[] { "Retry recovery failed. Boss battles remain blocked. Confirm to open the pause menu, where you can return to the title screen.", "Retry recovery timed out. Boss battles remain blocked. Confirm to open the pause menu, where you can return to the title screen.", "A player disconnected during retry recovery. Boss battles remain blocked. Confirm to open the pause menu, where you can return to the title screen.", "Please try again shortly. Nothing was spent.", "Retry continued. Some skill settings could not be restored. Check your quick slots and auto casting." },
            ["zh-CN"] = new[] { "重试恢复失败。 已阻止 Boss 战开始。确认后打开暂停菜单，可从那里返回标题画面。", "重试恢复等待超时。 已阻止 Boss 战开始。确认后打开暂停菜单，可从那里返回标题画面。", "重试恢复期间有玩家断开连接。 已阻止 Boss 战开始。确认后打开暂停菜单，可从那里返回标题画面。", "请稍后再试，本次未扣费。", "已继续重试，但部分技能设置未能恢复。请检查技能快捷栏与自动施法。" },
            ["zh-TW"] = new[] { "重試恢復失敗。 已阻止 Boss 戰開始。確認後開啟暫停選單，可從那裡返回標題畫面。", "重試恢復等待逾時。 已阻止 Boss 戰開始。確認後開啟暫停選單，可從那裡返回標題畫面。", "重試恢復期間有玩家斷線。 已阻止 Boss 戰開始。確認後開啟暫停選單，可從那裡返回標題畫面。", "請稍後再試，本次未扣費。", "已繼續重試，但部分技能設定未能恢復。請檢查技能快捷列與自動施法。" },
            ["ko-KR"] = new[] { "재시도 복구에 실패했습니다. 보스 전투 시작이 차단되어 있습니다. 확인하면 일시 정지 메뉴가 열리며, 타이틀 화면으로 돌아갈 수 있습니다.", "재시도 복구 대기 시간이 초과되었습니다. 보스 전투 시작이 차단되어 있습니다. 확인하면 일시 정지 메뉴가 열리며, 타이틀 화면으로 돌아갈 수 있습니다.", "재시도 복구 중 플레이어의 연결이 끊어졌습니다. 보스 전투 시작이 차단되어 있습니다. 확인하면 일시 정지 메뉴가 열리며, 타이틀 화면으로 돌아갈 수 있습니다.", "잠시 후 다시 시도하세요. 비용은 차감되지 않았습니다.", "재시도는 계속됩니다. 일부 스킬 설정을 복원하지 못했습니다. 퀵슬롯과 자동 시전을 확인하세요." },
            ["ja-JP"] = new[] { "再挑戦の復元に失敗しました。 ボス戦の開始は停止しています。確認するとポーズメニューが開き、タイトル画面に戻れます。", "再挑戦の復元がタイムアウトしました。 ボス戦の開始は停止しています。確認するとポーズメニューが開き、タイトル画面に戻れます。", "再挑戦の復元中にプレイヤーが切断されました。 ボス戦の開始は停止しています。確認するとポーズメニューが開き、タイトル画面に戻れます。", "少し待ってから再度お試しください。費用は消費されていません。", "再挑戦は続行されます。一部のスキル設定を復元できませんでした。クイックスロットと自動詠唱を確認してください。" },
            ["de-DE"] = new[] { "Wiederherstellung für den Neustart fehlgeschlagen. Bosskämpfe bleiben gesperrt. Bestätigen öffnet das Pausenmenü, über das du zum Titelbildschirm zurückkehren kannst.", "Zeitüberschreitung bei der Wiederherstellung. Bosskämpfe bleiben gesperrt. Bestätigen öffnet das Pausenmenü, über das du zum Titelbildschirm zurückkehren kannst.", "Ein Spieler hat während der Wiederherstellung die Verbindung verloren. Bosskämpfe bleiben gesperrt. Bestätigen öffnet das Pausenmenü, über das du zum Titelbildschirm zurückkehren kannst.", "Bitte versuche es gleich noch einmal. Es wurde nichts ausgegeben.", "Der neue Versuch läuft weiter. Einige Fertigkeitseinstellungen konnten nicht wiederhergestellt werden. Prüfe die Schnellplätze und das automatische Wirken." },
            ["es-ES"] = new[] { "No se pudo restaurar el reintento. Los combates contra jefes siguen bloqueados. Confirma para abrir el menú de pausa, desde donde puedes volver al título.", "Se agotó el tiempo de restauración. Los combates contra jefes siguen bloqueados. Confirma para abrir el menú de pausa, desde donde puedes volver al título.", "Un jugador se desconectó durante la restauración. Los combates contra jefes siguen bloqueados. Confirma para abrir el menú de pausa, desde donde puedes volver al título.", "Vuelve a intentarlo en unos instantes. No se ha gastado nada.", "El reintento continúa. No se pudieron restaurar algunos ajustes de habilidades. Revisa los accesos rápidos y el lanzamiento automático." },
            ["fr-FR"] = new[] { "La restauration de la nouvelle tentative a échoué. Les combats de boss restent bloqués. Confirmez pour ouvrir le menu de pause, puis revenir à l’écran titre.", "Le délai de restauration est dépassé. Les combats de boss restent bloqués. Confirmez pour ouvrir le menu de pause, puis revenir à l’écran titre.", "Un joueur a été déconnecté pendant la restauration. Les combats de boss restent bloqués. Confirmez pour ouvrir le menu de pause, puis revenir à l’écran titre.", "Réessayez dans un instant. Rien n’a été dépensé.", "La nouvelle tentative continue. Certains réglages de compétences n’ont pas pu être restaurés. Vérifiez les raccourcis et le lancement automatique." },
            ["it-IT"] = new[] { "Ripristino del tentativo non riuscito. Gli scontri con i boss restano bloccati. Conferma per aprire il menu di pausa, da cui puoi tornare al titolo.", "Tempo di attesa del ripristino scaduto. Gli scontri con i boss restano bloccati. Conferma per aprire il menu di pausa, da cui puoi tornare al titolo.", "Un giocatore si è disconnesso durante il ripristino. Gli scontri con i boss restano bloccati. Conferma per aprire il menu di pausa, da cui puoi tornare al titolo.", "Riprova tra poco. Non è stato speso nulla.", "Il nuovo tentativo continua. Alcune impostazioni delle abilità non sono state ripristinate. Controlla gli slot rapidi e il lancio automatico." },
            ["pt-BR"] = new[] { "Falha ao restaurar a tentativa. As lutas contra chefes continuam bloqueadas. Confirme para abrir o menu de pausa, onde você pode voltar à tela inicial.", "O tempo de restauração esgotou. As lutas contra chefes continuam bloqueadas. Confirme para abrir o menu de pausa, onde você pode voltar à tela inicial.", "Um jogador desconectou durante a restauração. As lutas contra chefes continuam bloqueadas. Confirme para abrir o menu de pausa, onde você pode voltar à tela inicial.", "Tente novamente em instantes. Nada foi gasto.", "A nova tentativa continua. Não foi possível restaurar algumas configurações de habilidades. Confira os atalhos e a conjuração automática." },
            ["pl-PL"] = new[] { "Przywracanie ponownej próby nie powiodło się. Rozpoczęcie walk z bossami pozostaje zablokowane. Potwierdź, aby otworzyć menu pauzy i móc wrócić do ekranu tytułowego.", "Przekroczono czas przywracania. Rozpoczęcie walk z bossami pozostaje zablokowane. Potwierdź, aby otworzyć menu pauzy i móc wrócić do ekranu tytułowego.", "Gracz rozłączył się podczas przywracania. Rozpoczęcie walk z bossami pozostaje zablokowane. Potwierdź, aby otworzyć menu pauzy i móc wrócić do ekranu tytułowego.", "Spróbuj ponownie za chwilę. Nic nie wydano.", "Ponowna próba trwa dalej. Nie udało się przywrócić części ustawień umiejętności. Sprawdź szybkie sloty i automatyczne rzucanie." },
            ["ru-RU"] = new[] { "Не удалось восстановить повторную попытку. Начало боёв с боссами заблокировано. Подтвердите, чтобы открыть меню паузы и вернуться на титульный экран.", "Время ожидания восстановления истекло. Начало боёв с боссами заблокировано. Подтвердите, чтобы открыть меню паузы и вернуться на титульный экран.", "Игрок отключился во время восстановления. Начало боёв с боссами заблокировано. Подтвердите, чтобы открыть меню паузы и вернуться на титульный экран.", "Повторите попытку чуть позже. Ничего не потрачено.", "Повторная попытка продолжается. Некоторые настройки умений не удалось восстановить. Проверьте панель быстрого доступа и автоматическое применение." },
            ["tr-TR"] = new[] { "Yeniden deneme geri yüklenemedi. Boss savaşlarının başlaması engelleniyor. Duraklatma menüsünü açmak için onaylayın; oradan başlık ekranına dönebilirsiniz.", "Geri yükleme zaman aşımına uğradı. Boss savaşlarının başlaması engelleniyor. Duraklatma menüsünü açmak için onaylayın; oradan başlık ekranına dönebilirsiniz.", "Geri yükleme sırasında bir oyuncunun bağlantısı kesildi. Boss savaşlarının başlaması engelleniyor. Duraklatma menüsünü açmak için onaylayın; oradan başlık ekranına dönebilirsiniz.", "Lütfen birazdan tekrar dene. Hiçbir şey harcanmadı.", "Yeniden deneme devam ediyor. Bazı beceri ayarları geri yüklenemedi. Hızlı yuvaları ve otomatik kullanımı kontrol et." },
            ["sv-SE"] = new[] { "Återställningen inför ett nytt försök misslyckades. Bossstrider förblir blockerade. Bekräfta för att öppna pausmenyn, där du kan återgå till titelskärmen.", "Tidsgränsen för återställningen överskreds. Bossstrider förblir blockerade. Bekräfta för att öppna pausmenyn, där du kan återgå till titelskärmen.", "En spelare kopplades från under återställningen. Bossstrider förblir blockerade. Bekräfta för att öppna pausmenyn, där du kan återgå till titelskärmen.", "Försök igen om en liten stund. Inget har spenderats.", "Det nya försöket fortsätter. Vissa färdighetsinställningar kunde inte återställas. Kontrollera snabbplatserna och automatisk besvärjelse." },
            ["th-TH"] = new[] { "กู้คืนการลองใหม่ไม่สำเร็จ การเริ่มต่อสู้กับบอสยังถูกระงับ ยืนยันเพื่อเปิดเมนูหยุดชั่วคราว แล้วกลับไปหน้าชื่อเกมได้จากเมนูนั้น", "หมดเวลารอการกู้คืน การเริ่มต่อสู้กับบอสยังถูกระงับ ยืนยันเพื่อเปิดเมนูหยุดชั่วคราว แล้วกลับไปหน้าชื่อเกมได้จากเมนูนั้น", "ผู้เล่นขาดการเชื่อมต่อระหว่างการกู้คืน การเริ่มต่อสู้กับบอสยังถูกระงับ ยืนยันเพื่อเปิดเมนูหยุดชั่วคราว แล้วกลับไปหน้าชื่อเกมได้จากเมนูนั้น", "กรุณาลองอีกครั้งในอีกสักครู่ ยังไม่มีการหักค่าใช้จ่าย", "ดำเนินการลองใหม่ต่อแล้ว แต่กู้คืนการตั้งค่าทักษะบางส่วนไม่ได้ โปรดตรวจสอบช่องทักษะลัดและการร่ายอัตโนมัติ" },
        };
        internal static void Register(Action<string, string, string> addText, IEnumerable<string> languages) =>
            LocalizationGroup.Register(addText, languages, Keys, Texts);
    }
}
