using System;
using System.Collections.Generic;
using SephiriaEnhancements.Configuration;

namespace SephiriaEnhancements.DefeatRetry
{
    internal static class RetryRecoveryLocalization
    {
        internal const string Failed = "SephiriaEnhancements.DefeatRetry.RecoveryFailed";
        internal const string TimedOut = "SephiriaEnhancements.DefeatRetry.RecoveryTimedOut";
        internal const string Disconnected = "SephiriaEnhancements.DefeatRetry.RecoveryDisconnected";
        private static readonly string[] Keys = { Failed, TimedOut, Disconnected };
        private static readonly Dictionary<string, string[]> Texts = new Dictionary<string, string[]>
        {
            ["en-US"] = new[] { "Retry recovery failed. Boss battles remain blocked. Confirm to open the pause menu, where you can return to the title screen.", "Retry recovery timed out. Boss battles remain blocked. Confirm to open the pause menu, where you can return to the title screen.", "A player disconnected during retry recovery. Boss battles remain blocked. Confirm to open the pause menu, where you can return to the title screen." },
            ["zh-CN"] = new[] { "重试恢复失败。 已阻止 Boss 战开始。确认后打开暂停菜单，可从那里返回标题画面。", "重试恢复等待超时。 已阻止 Boss 战开始。确认后打开暂停菜单，可从那里返回标题画面。", "重试恢复期间有玩家断开连接。 已阻止 Boss 战开始。确认后打开暂停菜单，可从那里返回标题画面。" },
            ["zh-TW"] = new[] { "重試恢復失敗。 已阻止 Boss 戰開始。確認後開啟暫停選單，可從那裡返回標題畫面。", "重試恢復等待逾時。 已阻止 Boss 戰開始。確認後開啟暫停選單，可從那裡返回標題畫面。", "重試恢復期間有玩家斷線。 已阻止 Boss 戰開始。確認後開啟暫停選單，可從那裡返回標題畫面。" },
            ["ko-KR"] = new[] { "재시도 복구에 실패했습니다. 보스 전투 시작이 차단되어 있습니다. 확인하면 일시 정지 메뉴가 열리며, 타이틀 화면으로 돌아갈 수 있습니다.", "재시도 복구 대기 시간이 초과되었습니다. 보스 전투 시작이 차단되어 있습니다. 확인하면 일시 정지 메뉴가 열리며, 타이틀 화면으로 돌아갈 수 있습니다.", "재시도 복구 중 플레이어의 연결이 끊어졌습니다. 보스 전투 시작이 차단되어 있습니다. 확인하면 일시 정지 메뉴가 열리며, 타이틀 화면으로 돌아갈 수 있습니다." },
            ["ja-JP"] = new[] { "再挑戦の復元に失敗しました。 ボス戦の開始は停止しています。確認するとポーズメニューが開き、タイトル画面に戻れます。", "再挑戦の復元がタイムアウトしました。 ボス戦の開始は停止しています。確認するとポーズメニューが開き、タイトル画面に戻れます。", "再挑戦の復元中にプレイヤーが切断されました。 ボス戦の開始は停止しています。確認するとポーズメニューが開き、タイトル画面に戻れます。" },
            ["de-DE"] = new[] { "Wiederherstellung für den Neustart fehlgeschlagen. Bosskämpfe bleiben gesperrt. Bestätigen öffnet das Pausenmenü, über das du zum Titelbildschirm zurückkehren kannst.", "Zeitüberschreitung bei der Wiederherstellung. Bosskämpfe bleiben gesperrt. Bestätigen öffnet das Pausenmenü, über das du zum Titelbildschirm zurückkehren kannst.", "Ein Spieler hat während der Wiederherstellung die Verbindung verloren. Bosskämpfe bleiben gesperrt. Bestätigen öffnet das Pausenmenü, über das du zum Titelbildschirm zurückkehren kannst." },
            ["es-ES"] = new[] { "No se pudo restaurar el reintento. Los combates contra jefes siguen bloqueados. Confirma para abrir el menú de pausa, desde donde puedes volver al título.", "Se agotó el tiempo de restauración. Los combates contra jefes siguen bloqueados. Confirma para abrir el menú de pausa, desde donde puedes volver al título.", "Un jugador se desconectó durante la restauración. Los combates contra jefes siguen bloqueados. Confirma para abrir el menú de pausa, desde donde puedes volver al título." },
            ["fr-FR"] = new[] { "La restauration de la nouvelle tentative a échoué. Les combats de boss restent bloqués. Confirmez pour ouvrir le menu de pause, puis revenir à l’écran titre.", "Le délai de restauration est dépassé. Les combats de boss restent bloqués. Confirmez pour ouvrir le menu de pause, puis revenir à l’écran titre.", "Un joueur a été déconnecté pendant la restauration. Les combats de boss restent bloqués. Confirmez pour ouvrir le menu de pause, puis revenir à l’écran titre." },
            ["it-IT"] = new[] { "Ripristino del tentativo non riuscito. Gli scontri con i boss restano bloccati. Conferma per aprire il menu di pausa, da cui puoi tornare al titolo.", "Tempo di attesa del ripristino scaduto. Gli scontri con i boss restano bloccati. Conferma per aprire il menu di pausa, da cui puoi tornare al titolo.", "Un giocatore si è disconnesso durante il ripristino. Gli scontri con i boss restano bloccati. Conferma per aprire il menu di pausa, da cui puoi tornare al titolo." },
            ["pt-BR"] = new[] { "Falha ao restaurar a tentativa. As lutas contra chefes continuam bloqueadas. Confirme para abrir o menu de pausa, onde você pode voltar à tela inicial.", "O tempo de restauração esgotou. As lutas contra chefes continuam bloqueadas. Confirme para abrir o menu de pausa, onde você pode voltar à tela inicial.", "Um jogador desconectou durante a restauração. As lutas contra chefes continuam bloqueadas. Confirme para abrir o menu de pausa, onde você pode voltar à tela inicial." },
            ["pl-PL"] = new[] { "Przywracanie ponownej próby nie powiodło się. Rozpoczęcie walk z bossami pozostaje zablokowane. Potwierdź, aby otworzyć menu pauzy i móc wrócić do ekranu tytułowego.", "Przekroczono czas przywracania. Rozpoczęcie walk z bossami pozostaje zablokowane. Potwierdź, aby otworzyć menu pauzy i móc wrócić do ekranu tytułowego.", "Gracz rozłączył się podczas przywracania. Rozpoczęcie walk z bossami pozostaje zablokowane. Potwierdź, aby otworzyć menu pauzy i móc wrócić do ekranu tytułowego." },
            ["ru-RU"] = new[] { "Не удалось восстановить повторную попытку. Начало боёв с боссами заблокировано. Подтвердите, чтобы открыть меню паузы и вернуться на титульный экран.", "Время ожидания восстановления истекло. Начало боёв с боссами заблокировано. Подтвердите, чтобы открыть меню паузы и вернуться на титульный экран.", "Игрок отключился во время восстановления. Начало боёв с боссами заблокировано. Подтвердите, чтобы открыть меню паузы и вернуться на титульный экран." },
            ["tr-TR"] = new[] { "Yeniden deneme geri yüklenemedi. Boss savaşlarının başlaması engelleniyor. Duraklatma menüsünü açmak için onaylayın; oradan başlık ekranına dönebilirsiniz.", "Geri yükleme zaman aşımına uğradı. Boss savaşlarının başlaması engelleniyor. Duraklatma menüsünü açmak için onaylayın; oradan başlık ekranına dönebilirsiniz.", "Geri yükleme sırasında bir oyuncunun bağlantısı kesildi. Boss savaşlarının başlaması engelleniyor. Duraklatma menüsünü açmak için onaylayın; oradan başlık ekranına dönebilirsiniz." },
            ["sv-SE"] = new[] { "Återställningen inför ett nytt försök misslyckades. Bossstrider förblir blockerade. Bekräfta för att öppna pausmenyn, där du kan återgå till titelskärmen.", "Tidsgränsen för återställningen överskreds. Bossstrider förblir blockerade. Bekräfta för att öppna pausmenyn, där du kan återgå till titelskärmen.", "En spelare kopplades från under återställningen. Bossstrider förblir blockerade. Bekräfta för att öppna pausmenyn, där du kan återgå till titelskärmen." },
            ["th-TH"] = new[] { "กู้คืนการลองใหม่ไม่สำเร็จ การเริ่มต่อสู้กับบอสยังถูกระงับ ยืนยันเพื่อเปิดเมนูหยุดชั่วคราว แล้วกลับไปหน้าชื่อเกมได้จากเมนูนั้น", "หมดเวลารอการกู้คืน การเริ่มต่อสู้กับบอสยังถูกระงับ ยืนยันเพื่อเปิดเมนูหยุดชั่วคราว แล้วกลับไปหน้าชื่อเกมได้จากเมนูนั้น", "ผู้เล่นขาดการเชื่อมต่อระหว่างการกู้คืน การเริ่มต่อสู้กับบอสยังถูกระงับ ยืนยันเพื่อเปิดเมนูหยุดชั่วคราว แล้วกลับไปหน้าชื่อเกมได้จากเมนูนั้น" },
        };
        internal static void Register(Action<string, string, string> addText, IEnumerable<string> languages) =>
            LocalizationGroup.Register(addText, languages, Keys, Texts);
    }
}
