using System;
using System.Collections.Generic;
using SephiriaEnhancements.Configuration;

namespace SephiriaEnhancements.StageRewardAutoClaim
{
    internal static class StageRewardAutoClaimLocalization
    {
        internal const string Name = "SephiriaEnhancements.StageRewardAutoClaim.Name";
        internal const string Help = "SephiriaEnhancements.StageRewardAutoClaim.Help";
        internal const string On = "SephiriaEnhancements.StageRewardAutoClaim.On";
        internal const string Off = "SephiriaEnhancements.StageRewardAutoClaim.Off";
        internal const string Claimed = "SephiriaEnhancements.StageRewardAutoClaim.Claimed";
        internal const string Unconfirmed = "SephiriaEnhancements.StageRewardAutoClaim.Unconfirmed";
        internal const string Tutorial = "SephiriaEnhancements.StageRewardAutoClaim.Tutorial";
        private static readonly string[] Keys = { Name, Help, On, Off, Claimed, Unconfirmed, Tutorial };
        private static readonly Dictionary<string, string[]> Texts = new()
        {
            ["en-US"] = new[] { "Auto-claim tier rewards", "Off by default. When enabled, claims missing tier rewards up to this save’s highest cleared tier once your character has loaded. No need to clear them again. Turning this off does not remove rewards already claimed.", "On", "Off", "Claimed {0} tier rewards. Talent points +{1}.", "Rewards are recorded, but the talent points have not been confirmed yet. Return to the title screen and reload this save.", "Choose modifiers on the left to increase the challenge tier. Auto-claim tier rewards is enabled: missing rewards up to this save’s highest cleared tier are claimed automatically. Rewards already claimed are kept." },
            ["zh-CN"] = new[] { "自动领取阶段奖励", "默认关闭。开启后，按当前存档的最高通关阶段自动补领遗漏奖励，无需重新挑战。加载期间会稍后领取。关闭后，已领取的奖励仍会保留。", "开启", "关闭", "已补领 {0} 项阶段奖励，天赋点数 +{1}。", "奖励已记录，但天赋点数尚未确认。请返回标题画面后重新载入此存档。", "选择左侧的项目可以提高挑战阶段。\n\n已开启“自动领取阶段奖励”：按当前存档的最高通关阶段自动补领遗漏奖励，无需逐级重打。已领取的奖励会保留。" },
            ["zh-TW"] = new[] { "自動領取階段獎勵", "預設關閉。開啟後，依目前存檔的最高通關階段自動補領遺漏獎勵，無須重新挑戰。載入期間會稍後領取。關閉後，已領取的獎勵仍會保留。", "開啟", "關閉", "已補領 {0} 項階段獎勵，天賦點數 +{1}。", "獎勵已記錄，但天賦點數尚未確認。請返回標題畫面後重新載入此存檔。", "選擇左側的項目可以提高挑戰階段。\n\n已開啟「自動領取階段獎勵」：依目前存檔的最高通關階段自動補領遺漏獎勵，無須逐階重打。已領取的獎勵會保留。" },
            ["ko-KR"] = new[] { "단계 보상 자동 수령", "기본값은 꺼짐입니다. 켜면 캐릭터 로딩 후 현재 저장 파일의 최고 클리어 단계까지 받지 못한 보상을 수령합니다. 다시 클리어할 필요가 없으며, 꺼도 이미 받은 보상은 유지됩니다.", "켜기", "끄기", "단계 보상 {0}개 수령. 재능 포인트 +{1}.", "보상은 기록되었지만 재능 포인트는 아직 확인되지 않았습니다. 타이틀 화면으로 돌아가 이 저장 파일을 다시 불러오세요.", "왼쪽 항목을 선택해 도전 단계를 높일 수 있습니다. 단계 보상 자동 수령이 켜져 있습니다. 현재 저장 파일의 최고 클리어 단계까지 놓친 보상을 자동 수령하며, 이미 받은 보상은 유지됩니다." },
            ["ja-JP"] = new[] { "段階報酬の自動受け取り", "初期設定はオフです。オンにすると、キャラクターの読み込み後、このセーブの最高クリア段階までの未受領報酬を受け取ります。再挑戦は不要です。オフにしても受領済みの報酬は残ります。", "オン", "オフ", "段階報酬を{0}件受け取りました。才能ポイント +{1}。", "報酬は記録されましたが、才能ポイントはまだ確認できていません。タイトル画面に戻り、このセーブを読み込み直してください。", "左側の項目で挑戦段階を上げられます。段階報酬の自動受け取りがオンです。このセーブの最高クリア段階までの未受領報酬を自動で受け取ります。受領済みの報酬は残ります。" },
            ["de-DE"] = new[] { "Stufenbelohnungen automatisch abholen", "Standardmäßig aus. Holt nach dem Laden der Figur fehlende Belohnungen bis zur höchsten abgeschlossenen Stufe dieses Spielstands ab. Erneutes Abschließen ist nicht nötig. Bereits erhaltene Belohnungen bleiben beim Ausschalten erhalten.", "Ein", "Aus", "{0} Stufenbelohnungen erhalten. Talentpunkte +{1}.", "Belohnungen wurden erfasst, die Talentpunkte sind aber noch nicht bestätigt. Kehre zum Titelbildschirm zurück und lade diesen Spielstand erneut.", "Wähle links Modifikatoren, um die Herausforderungsstufe zu erhöhen. Automatisches Abholen ist aktiv: Fehlende Belohnungen bis zur höchsten abgeschlossenen Stufe dieses Spielstands werden abgeholt. Bereits erhaltene Belohnungen bleiben erhalten." },
            ["es-ES"] = new[] { "Recoger recompensas de nivel automáticamente", "Desactivado por defecto. Tras cargar el personaje, recoge las recompensas pendientes hasta el mayor nivel superado en esta partida guardada. No hace falta repetirlos. Desactivarlo no elimina las recompensas recibidas.", "Activado", "Desactivado", "Recibidas {0} recompensas de nivel. Puntos de talento +{1}.", "Las recompensas están registradas, pero los puntos de talento aún no se han confirmado. Vuelve al título y carga esta partida de nuevo.", "Elige modificadores a la izquierda para aumentar el nivel del desafío. La recogida automática está activada: recibirás las recompensas pendientes hasta el mayor nivel superado en esta partida guardada. Las recompensas recibidas se conservan." },
            ["fr-FR"] = new[] { "Récupérer automatiquement les récompenses de palier", "Désactivé par défaut. Après le chargement du personnage, récupère les récompenses manquantes jusqu’au plus haut palier terminé de cette sauvegarde, sans le rejouer. Désactiver conserve les récompenses reçues.", "Activé", "Désactivé", "{0} récompenses de palier reçues. Points de talent +{1}.", "Les récompenses sont enregistrées, mais les points de talent ne sont pas encore confirmés. Revenez au titre et rechargez cette sauvegarde.", "Choisissez les modificateurs à gauche pour augmenter le palier du défi. La récupération automatique est activée : les récompenses manquantes jusqu’au plus haut palier terminé de cette sauvegarde sont récupérées. Les récompenses reçues sont conservées." },
            ["it-IT"] = new[] { "Riscatta automaticamente le ricompense dei livelli", "Disattivato per impostazione predefinita. Dopo il caricamento del personaggio, riscatta le ricompense mancanti fino al livello più alto completato in questo salvataggio, senza ripeterlo. Disattivare mantiene le ricompense ricevute.", "Attivato", "Disattivato", "Ricevute {0} ricompense dei livelli. Punti talento +{1}.", "Le ricompense sono registrate, ma i punti talento non sono ancora confermati. Torna al titolo e ricarica questo salvataggio.", "Scegli i modificatori a sinistra per aumentare il livello della sfida. Il riscatto automatico è attivo: riceverai le ricompense mancanti fino al livello più alto completato in questo salvataggio. Le ricompense ricevute restano disponibili." },
            ["pl-PL"] = new[] { "Automatycznie odbieraj nagrody za progi", "Domyślnie wyłączone. Po wczytaniu postaci odbiera brakujące nagrody do najwyższego ukończonego progu w tym zapisie. Nie trzeba powtarzać wyzwań. Wyłączenie nie usuwa odebranych nagród.", "Wł.", "Wył.", "Odebrano nagrody za progi: {0}. Punkty talentów +{1}.", "Nagrody zostały odnotowane, ale punkty talentów nie są jeszcze potwierdzone. Wróć do ekranu tytułowego i ponownie wczytaj ten zapis.", "Wybierz modyfikatory po lewej, aby zwiększyć próg wyzwania. Automatyczne odbieranie jest włączone: brakujące nagrody do najwyższego ukończonego progu w tym zapisie zostaną odebrane. Odebrane nagrody pozostają." },
            ["pt-BR"] = new[] { "Resgatar recompensas de nível automaticamente", "Desativado por padrão. Após carregar o personagem, resgata as recompensas pendentes até o maior nível concluído neste jogo salvo. Não é preciso repetir os desafios. Desativar não remove recompensas recebidas.", "Ativado", "Desativado", "{0} recompensas de nível recebidas. Pontos de talento +{1}.", "As recompensas foram registradas, mas os pontos de talento ainda não foram confirmados. Volte ao título e carregue este jogo salvo novamente.", "Escolha modificadores à esquerda para aumentar o nível do desafio. O resgate automático está ativado: você recebe as recompensas pendentes até o maior nível concluído neste jogo salvo. As recompensas recebidas são mantidas." },
            ["ru-RU"] = new[] { "Автополучение наград за ступени", "По умолчанию выключено. После загрузки персонажа выдаёт пропущенные награды до высшей пройденной ступени в этом сохранении. Повторять прохождение не нужно. Отключение не убирает полученные награды.", "Вкл.", "Выкл.", "Получено наград за ступени: {0}. Очки талантов +{1}.", "Награды учтены, но очки талантов ещё не подтверждены. Вернитесь на титульный экран и загрузите это сохранение заново.", "Выберите модификаторы слева, чтобы повысить ступень испытания. Автополучение включено: пропущенные награды до высшей пройденной ступени в этом сохранении выдаются автоматически. Полученные награды сохраняются." },
            ["sv-SE"] = new[] { "Hämta nivåbelöningar automatiskt", "Av som standard. Hämtar saknade belöningar upp till den högsta avklarade nivån i denna sparfil när figuren har laddats. Du behöver inte klara dem igen. Belöningar du fått behålls om du stänger av.", "På", "Av", "Hämtade {0} nivåbelöningar. Talangpoäng +{1}.", "Belöningarna är registrerade, men talangpoängen har inte bekräftats ännu. Gå till titelskärmen och ladda sparfilen igen.", "Välj modifierare till vänster för att höja utmaningsnivån. Automatisk hämtning är på: saknade belöningar upp till den högsta avklarade nivån i denna sparfil hämtas automatiskt. Hämtade belöningar behålls." },
            ["th-TH"] = new[] { "รับรางวัลแต่ละขั้นอัตโนมัติ", "ปิดเป็นค่าเริ่มต้น เมื่อเปิดจะรับรางวัลที่ยังไม่ได้รับจนถึงขั้นสูงสุดที่ผ่านในเซฟนี้หลังโหลดตัวละครเสร็จ ไม่ต้องเล่นซ้ำ การปิดจะไม่ลบรางวัลที่รับไปแล้ว", "เปิด", "ปิด", "รับรางวัล {0} ขั้นแล้ว แต้มพรสวรรค์ +{1}", "บันทึกรางวัลแล้ว แต่ยังไม่ยืนยันแต้มพรสวรรค์ โปรดกลับหน้าชื่อเกมแล้วโหลดเซฟนี้ใหม่", "เลือกตัวปรับทางซ้ายเพื่อเพิ่มขั้นความท้าทาย เปิดการรับรางวัลอัตโนมัติอยู่ ระบบจะรับรางวัลที่ขาดจนถึงขั้นสูงสุดที่ผ่านในเซฟนี้ รางวัลที่รับแล้วจะยังคงอยู่" },
            ["tr-TR"] = new[] { "Kademe ödüllerini otomatik al", "Varsayılan olarak kapalı. Karakter yüklendikten sonra bu kayıtta tamamlanan en yüksek kademeye kadar eksik ödülleri alır. Tekrar tamamlamak gerekmez. Kapatmak alınan ödülleri silmez.", "Açık", "Kapalı", "{0} kademe ödülü alındı. Yetenek puanı +{1}.", "Ödüller kaydedildi ancak yetenek puanları henüz doğrulanmadı. Başlık ekranına dönüp bu kaydı yeniden yükleyin.", "Meydan okuma kademesini artırmak için soldaki değiştiricileri seçin. Otomatik ödül alma açık: bu kayıtta tamamlanan en yüksek kademeye kadar eksik ödüller alınır. Alınan ödüller korunur." },
        };
        internal static void Register(Action<string, string, string> addText, IEnumerable<string> languages) =>
            LocalizationGroup.Register(addText, languages, Keys, Texts);
    }
}
