using System;
using System.Collections.Generic;
using SephiriaEnhancements.Configuration;

namespace SephiriaEnhancements.Combat
{
    internal static class CombatInsightsLocalization
    {
        internal const string SettingHitStreakFeedback =
            "SephiriaEnhancements.Setting.HitStreakFeedback";
        internal const string SettingDamageStatisticsScale =
            "SephiriaEnhancements.Setting.DamageStatisticsScale";
        internal const string HelpHitStreakFeedback =
            "SephiriaEnhancements.Help.HitStreakFeedback";
        internal const string HelpDamageStatisticsScale =
            "SephiriaEnhancements.Help.DamageStatisticsScale";
        internal const string SettingDisplayPolicy = "SephiriaEnhancements.Setting.DisplayPolicy";
        internal const string HelpDisplayPolicy = "SephiriaEnhancements.Help.DisplayPolicy";
        internal const string InsightsDisabled =
            "SephiriaEnhancements.CombatInsights.Disabled";
        internal const string DamageStatisticsDisplayHidden =
            "SephiriaEnhancements.CombatInsights.DisplayHidden";
        internal const string DamageStatisticsDisplayRestored =
            "SephiriaEnhancements.CombatInsights.DisplayRestored";
        internal const string StatisticsOpened =
            "SephiriaEnhancements.CombatInsights.StatisticsOpened";
        internal const string StatisticsClosed =
            "SephiriaEnhancements.CombatInsights.StatisticsClosed";
        internal const string EncounterReportUnavailable =
            "SephiriaEnhancements.CombatInsights.ReportUnavailable";
        internal const string EncounterReportLoading =
            "SephiriaEnhancements.CombatInsights.ReportLoading";
        internal const string EncounterReportScreenTransition =
            "SephiriaEnhancements.CombatInsights.ReportScreenTransition";
        internal const string EncounterReportCutscene =
            "SephiriaEnhancements.CombatInsights.ReportCutscene";
        internal const string EncounterReportMenu =
            "SephiriaEnhancements.CombatInsights.ReportMenu";
        internal const string EncounterReportHudUnavailable =
            "SephiriaEnhancements.CombatInsights.ReportHudUnavailable";
        internal const string Dps = "SephiriaEnhancements.Hud.Dps";
        internal const string Defeated = "SephiriaEnhancements.Hud.Defeated";
        internal const string FinalBlows = "SephiriaEnhancements.Hud.FinalBlows";
        internal const string NormalEnemy = "SephiriaEnhancements.Hud.Normal";

        // Mirrors EMonsterType.Miniboss; do not broaden this back to "Elite".
        internal const string MinibossEnemy = "SephiriaEnhancements.Hud.Miniboss";
        internal const string BossEnemy = "SephiriaEnhancements.Hud.Boss";
        internal const string CombatSummary = "SephiriaEnhancements.Hud.CombatSummary";
        internal const string DamageShare = "SephiriaEnhancements.Hud.DamageShare";
        internal const string DamageAverageDps =
            "SephiriaEnhancements.Hud.DamageAverageDps";
        internal const string ReportDamage =
            "SephiriaEnhancements.Hud.ReportDamage";
        internal const string ReportShare =
            "SephiriaEnhancements.Hud.ReportShare";
        internal const string ReportAverageDps =
            "SephiriaEnhancements.Hud.ReportAverageDps";
        internal const string ReportDamageMix =
            "SephiriaEnhancements.Hud.ReportDamageMix";
        internal const string ViewStatistics = "SephiriaEnhancements.Hud.ViewStatistics";
        internal const string RecentEncounterStatistics = "SephiriaEnhancements.Hud.RecentEncounterStatistics";
        internal const string CurrentEncounterStatistics = "SephiriaEnhancements.Hud.CurrentEncounterStatistics";
        internal const string CurrentFloorStatistics = "SephiriaEnhancements.Hud.CurrentFloorStatistics";
        internal const string CloseStatistics = "SephiriaEnhancements.Hud.CloseStatistics";
        internal const string FloorBattleDuration = "SephiriaEnhancements.Hud.FloorBattleDuration";
        internal const string FloorBattleTime = "SephiriaEnhancements.Hud.FloorBattleTime";
        internal const string EncounterBattleTime = "SephiriaEnhancements.Hud.EncounterBattleTime";
        internal const string FloorStatisticsEmpty = "SephiriaEnhancements.Hud.FloorStatisticsEmpty";
        internal const string ReportDismissHint =
            "SephiriaEnhancements.Hud.ReportDismissHint";
        internal const string DamagePhysical =
            "SephiriaEnhancements.Hud.DamagePhysical";
        internal const string DamageFire =
            "SephiriaEnhancements.Hud.DamageFire";
        internal const string DamageIce =
            "SephiriaEnhancements.Hud.DamageIce";
        internal const string DamageLightning =
            "SephiriaEnhancements.Hud.DamageLightning";
        internal const string DamageChaos =
            "SephiriaEnhancements.Hud.DamageChaos";
        internal const string DamageNormal =
            "SephiriaEnhancements.Hud.DamageNormal";
        internal const string DamageMixed =
            "SephiriaEnhancements.Hud.DamageMixed";
        internal const string DamageOther =
            "SephiriaEnhancements.Hud.DamageOther";

        internal static readonly string[] ScaleKeys =
        {
            "SephiriaEnhancements.Scale.80", "SephiriaEnhancements.Scale.90",
            "SephiriaEnhancements.Scale.100", "SephiriaEnhancements.Scale.110",
            "SephiriaEnhancements.Scale.120"
        };

        internal static readonly string[] DisplayPolicyKeys =
        {
            "SephiriaEnhancements.DisplayPolicy.Smart",
            "SephiriaEnhancements.DisplayPolicy.BossOnly",
            "SephiriaEnhancements.DisplayPolicy.AllCombat",
            InsightsDisabled
        };

        private static readonly Dictionary<string, Dictionary<string, string>> InsightsTexts =
            new Dictionary<string, Dictionary<string, string>>
            {
                ["en-US"] = CreateInsightsTexts("Damage statistics", "Smart", "Boss only", "Every fight",
                    "DPS", "defeated", "my final blows", "normal", "miniboss", "boss",
                    "Combat summary", "DMG · SHARE", "DMG · AVG DPS",
                    "DMG", "SHARE", "AVG DPS",
                    "DAMAGE MIX", "physical", "fire", "ice", "lightning",
                    "chaos", "normal", "mixed", "other",
                    "Smart shows recent 5-second DPS in ordinary fights and cumulative damage in BOSS fights; reports show battle and floor totals.\nOutside combat, tap the statistics shortcut or use View statistics in the pause menu. Hold the shortcut for half a second to hide or restore the display without stopping recording.\nTotals are temporary and local: co-op results may differ. Changing floors, reconnecting, reloading or disabling statistics can clear them.",
                    "Disabled", "Damage statistics display hidden",
                    "Damage statistics display restored",
                    "Statistics opened", "Statistics closed",
                    "No combat report available on this floor",
                    "Statistics display unavailable while loading",
                    "Statistics display unavailable during a screen transition",
                    "Statistics display unavailable during a cutscene",
                    "Close the menu to view statistics",
                    "Combat report display is not ready yet", "{0}  ·  Close report",
                    "View statistics", "Recent battle", "Current floor", "Close statistics",
                    "Battle average DPS · accumulated battle time",
                    "Average DPS · encounter duration", "No combat recorded on this floor yet",
                    "This battle",
                    "Total battle time {0}"),
                ["zh-CN"] = CreateInsightsTexts("伤害统计", "智能", "仅 BOSS", "每场战斗",
                    "DPS", "击败", "我的最后一击", "普通", "小头目", "BOSS",
                    "战斗统计", "DMG · 占比", "DMG · 平均 DPS",
                    "DMG", "占比", "平均 DPS",
                    "伤害构成", "物理", "火焰", "冰霜", "闪电", "混沌",
                    "普通", "混合", "其他",
                    "智能模式在普通战斗中显示近 5 秒 DPS，BOSS 战显示累计伤害；战报可查看单场与本层累计。\n脱战后短按统计快捷键，或从暂停菜单选择“查看统计”。长按快捷键半秒可隐藏或恢复显示，隐藏不停止记录。\n统计是本机临时记录，联机结果可能不同；换层、重连、重新加载或关闭统计可能清空数据。",
                    "关闭", "伤害统计显示已隐藏", "伤害统计显示已恢复",
                    "已打开统计", "统计已关闭", "本层暂无可查看的战报",
                    "正在加载，暂时无法显示统计", "画面切换中，暂时无法显示统计",
                    "剧情播放中，暂时无法显示统计", "请关闭菜单后查看统计",
                    "战报界面尚未就绪", "{0}  ·  收起战报",
                    "查看统计", "最近战斗", "本层累计", "关闭统计",
                    "战斗平均 DPS · 按累计战斗时长计算", "平均 DPS · 按单场战斗时长计算",
                    "本层尚未记录战斗数据",
                    "本场战斗",
                    "累计战斗时长 {0}"),
                ["zh-TW"] = CreateInsightsTexts("傷害統計", "智慧", "僅 BOSS", "每場戰鬥",
                    "DPS", "擊敗", "我的最後一擊", "普通", "小頭目", "BOSS",
                    "戰鬥統計", "DMG · 佔比", "DMG · 平均 DPS",
                    "DMG", "佔比", "平均 DPS",
                    "傷害構成", "物理", "火焰", "冰霜", "閃電", "混沌",
                    "普通", "混合", "其他",
                    "智慧模式在普通戰鬥中顯示近 5 秒 DPS，BOSS 戰顯示累計傷害；戰報可查看單場與本層累計。\n脫戰後短按統計快捷鍵，或從暫停選單選擇「查看統計」。長按快捷鍵半秒可隱藏或恢復顯示，隱藏不會停止記錄。\n統計是本機暫存記錄，連線結果可能不同；換層、重新連線、重新載入或關閉統計可能清空資料。",
                    "關閉", "傷害統計顯示已隱藏", "傷害統計顯示已恢復",
                    "已開啟統計", "統計已關閉", "本層暫無可查看的戰報",
                    "正在載入，暫時無法顯示統計", "畫面切換中，暫時無法顯示統計",
                    "劇情播放中，暫時無法顯示統計", "請關閉選單後查看統計",
                    "戰報介面尚未就緒", "{0}  ·  收起戰報",
                    "查看統計", "最近戰鬥", "本層累計", "關閉統計",
                    "戰鬥平均 DPS · 按累計戰鬥時間計算", "平均 DPS · 按單場戰鬥時間計算",
                    "本層尚未記錄戰鬥資料",
                    "本場戰鬥",
                    "累計戰鬥時間 {0}"),
                ["ja-JP"] = CreateInsightsTexts("ダメージ統計",
                    "自動",
                    "ボスのみ",
                    "すべての戦闘",
                    "DPS",
                    "撃破",
                    "自分の最後の一撃",
                    "通常",
                    "中ボス",
                    "BOSS",
                    "戦闘の集計",
                    "DMG · 割合",
                    "DMG · 平均 DPS",
                    "DMG",
                    "割合",
                    "平均 DPS",
                    "ダメージ内訳",
                    "物理",
                    "火",
                    "氷",
                    "雷",
                    "混沌",
                    "通常",
                    "混合",
                    "その他",
                    "自動は通常戦で直近5秒のDPS、BOSS戦で累計ダメージを表示します。レポートでは1戦と現在の階層の合計を確認できます。\n戦闘外で統計ショートカットを短く押すか、ポーズメニューの統計を見るを選択します。0.5秒長押しすると記録を続けたまま表示を切り替えます。\n統計は端末内の一時記録のため、協力プレイでは数値が異なる場合があります。階層移動、再接続、再読み込み、統計の無効化で消えることがあります。",
                    "無効",
                    "ダメージ統計を非表示にしました",
                    "ダメージ統計の表示を再開しました",
                    "統計を開きました",
                    "統計を閉じました",
                    "このフロアの戦闘レポートはまだありません",
                    "ロード中は統計を表示できません",
                    "画面切替中は統計を表示できません",
                    "イベントシーン中は統計を表示できません",
                    "メニューを閉じてから統計を表示してください",
                    "戦闘レポートの準備ができていません",
                    "{0} · レポートを閉じる",
                    "統計を見る",
                    "直近の戦闘",
                    "現在の階層",
                    "統計を閉じる",
                    "戦闘平均 DPS · 累計戦闘時間で計算",
                    "平均 DPS · 1 戦の時間で計算",
                    "この階層の戦闘データはまだありません",
                    "今回の戦闘",
                    "累計戦闘時間 {0}"),
                ["ko-KR"] = CreateInsightsTexts("피해 통계",
                    "자동",
                    "보스만",
                    "모든 전투",
                    "DPS",
                    "처치",
                    "내 마지막 일격",
                    "일반",
                    "중간 보스",
                    "BOSS",
                    "전투 요약",
                    "DMG · 비중",
                    "DMG · 평균 DPS",
                    "DMG",
                    "비중",
                    "평균 DPS",
                    "피해 구성",
                    "물리",
                    "화염",
                    "얼음",
                    "번개",
                    "혼돈",
                    "일반",
                    "혼합",
                    "기타",
                    "자동은 일반 전투에서 최근 5초 DPS, BOSS전에서 누적 피해를 표시합니다. 보고서에서 전투와 현재 층의 합계를 볼 수 있습니다.\n전투 밖에서 통계 단축키를 짧게 누르거나 일시 정지 메뉴의 통계 보기를 사용하세요. 0.5초간 누르면 기록을 유지한 채 표시를 숨기거나 복원합니다.\n통계는 기기에 임시 저장되어 협동 플레이 결과가 다를 수 있습니다. 층 변경, 재접속, 다시 불러오기 또는 통계 끄기로 기록이 지워질 수 있습니다.",
                    "비활성화",
                    "피해 통계를 숨겼습니다",
                    "피해 통계 표시를 복원했습니다",
                    "통계를 열었습니다",
                    "통계를 닫았습니다",
                    "이 층에는 아직 전투 보고서가 없습니다",
                    "로딩 중에는 통계를 표시할 수 없습니다",
                    "화면 전환 중에는 통계를 표시할 수 없습니다",
                    "연출 중에는 통계를 표시할 수 없습니다",
                    "메뉴를 닫은 뒤 통계를 확인하세요",
                    "전투 보고서가 아직 준비되지 않았습니다",
                    "{0} · 보고서 닫기",
                    "통계 보기",
                    "최근 전투",
                    "현재 층",
                    "통계 닫기",
                    "전투 평균 DPS · 누적 전투 시간 기준",
                    "평균 DPS · 해당 전투 시간 기준",
                    "이 층에서 기록된 전투가 없습니다",
                    "이번 전투",
                    "누적 전투 시간 {0}"),
                ["de-DE"] = CreateInsightsTexts("Schadensstatistik",
                    "Automatisch",
                    "Nur Bosse",
                    "Jeder Kampf",
                    "DPS",
                    "besiegt",
                    "meine letzten Treffer",
                    "normal",
                    "Miniboss",
                    "BOSS",
                    "Kampfübersicht",
                    "DMG · ANTEIL",
                    "DMG · Ø DPS",
                    "DMG",
                    "ANTEIL",
                    "Ø DPS",
                    "SCHADENSARTEN",
                    "Physisch",
                    "Feuer",
                    "Eis",
                    "Blitz",
                    "Chaos",
                    "normal",
                    "gemischt",
                    "sonstige",
                    "Automatisch zeigt in normalen Kämpfen die DPS der letzten 5 Sekunden, bei BOSS-Kämpfen den Gesamtschaden. Berichte zeigen Kampf- und Ebenensummen.\nAußerhalb des Kampfes die Statistiktaste kurz drücken oder die Statistik im Pausenmenü öffnen. Eine halbe Sekunde halten blendet die Anzeige aus oder ein; die Aufzeichnung läuft weiter.\nSummen sind lokal und vorübergehend; Koop-Werte können abweichen. Ebenenwechsel, Wiederverbindung, Neuladen oder Abschalten der Statistik können sie löschen.",
                    "Deaktiviert",
                    "Schadensstatistik ausgeblendet",
                    "Schadensstatistik wieder eingeblendet",
                    "Statistik geöffnet",
                    "Statistik geschlossen",
                    "Auf dieser Ebene ist noch kein Kampfbericht verfügbar",
                    "Statistik beim Laden nicht verfügbar",
                    "Statistik während des Bildschirmwechsels nicht verfügbar",
                    "Statistik während Zwischensequenzen nicht verfügbar",
                    "Schließe das Menü, um die Statistik zu sehen",
                    "Der Kampfbericht ist noch nicht bereit",
                    "{0} · Bericht schließen",
                    "Statistik ansehen",
                    "Letzter Kampf",
                    "Aktuelle Etage",
                    "Statistik schließen",
                    "Kampf-DPS · gesamte Kampfzeit",
                    "Ø DPS · Dauer dieses Kampfes",
                    "Noch keine Kampfdaten auf dieser Etage",
                    "Dieser Kampf",
                    "Gesamte Kampfzeit {0}"),
                ["es-ES"] = CreateInsightsTexts("Estadísticas de daño",
                    "Automático",
                    "Solo jefes",
                    "Cada combate",
                    "DPS",
                    "derrotados",
                    "mis golpes finales",
                    "normal",
                    "minijefe",
                    "BOSS",
                    "Resumen de combate",
                    "DMG · APORTE",
                    "DMG · DPS MEDIO",
                    "DMG",
                    "APORTE",
                    "DPS MEDIO",
                    "TIPOS DE DAÑO",
                    "Físico",
                    "Fuego",
                    "Hielo",
                    "Rayo",
                    "Caos",
                    "normal",
                    "mixto",
                    "otro",
                    "Automático muestra los DPS de los últimos 5 segundos en combates normales y el daño acumulado contra BOSS. Los informes muestran totales del combate y la planta.\nFuera del combate, pulsa el atajo de estadísticas o ábrelas desde el menú de pausa. Mantén el atajo medio segundo para ocultar o mostrar el panel sin dejar de registrar.\nLos totales son temporales y locales; pueden diferir en cooperativo. Cambiar de planta, reconectar, recargar o desactivar las estadísticas puede borrarlos.",
                    "Desactivado",
                    "Estadísticas de daño ocultas",
                    "Estadísticas de daño visibles",
                    "Estadísticas abiertas",
                    "Estadísticas cerradas",
                    "Aún no hay un informe de combate de esta planta",
                    "Estadísticas no disponibles durante la carga",
                    "Estadísticas no disponibles durante una transición de pantalla",
                    "Estadísticas no disponibles durante una cinemática",
                    "Cierra el menú para ver las estadísticas",
                    "El informe de combate aún no está listo",
                    "{0} · Cerrar informe",
                    "Ver estadísticas",
                    "Último combate",
                    "Planta actual",
                    "Cerrar estadísticas",
                    "DPS medio · tiempo de combate acumulado",
                    "DPS medio · duración del combate",
                    "Aún no hay combates registrados en esta planta",
                    "Este combate",
                    "Tiempo total de combate {0}"),
                ["fr-FR"] = CreateInsightsTexts("Statistiques de dégâts",
                    "Automatique",
                    "Boss uniquement",
                    "Chaque combat",
                    "DPS",
                    "vaincus",
                    "mes coups finaux",
                    "normal",
                    "mini-boss",
                    "BOSS",
                    "Bilan du combat",
                    "DMG · PART",
                    "DMG · DPS MOYEN",
                    "DMG",
                    "PART",
                    "DPS MOYEN",
                    "TYPES DE DÉGÂTS",
                    "Physique",
                    "Feu",
                    "Glace",
                    "Foudre",
                    "Chaos",
                    "normal",
                    "mixte",
                    "autres",
                    "Automatique affiche les DPS des 5 dernières secondes en combat ordinaire et les dégâts cumulés contre les BOSS. Les rapports présentent les totaux du combat et de l’étage.\nHors combat, appuyez brièvement sur le raccourci des statistiques ou ouvrez-les dans le menu pause. Maintenez-le une demi-seconde pour masquer ou rétablir l’affichage sans arrêter l’enregistrement.\nLes totaux sont temporaires et locaux : ils peuvent différer en coopération. Changer d’étage, se reconnecter, recharger ou désactiver les statistiques peut les effacer.",
                    "Désactivé",
                    "Statistiques de dégâts masquées",
                    "Statistiques de dégâts rétablies",
                    "Statistiques ouvertes",
                    "Statistiques fermées",
                    "Aucun rapport de combat disponible à cet étage",
                    "Statistiques indisponibles pendant le chargement",
                    "Statistiques indisponibles pendant une transition d’écran",
                    "Statistiques indisponibles pendant une cinématique",
                    "Fermez le menu pour voir les statistiques",
                    "Le rapport de combat n’est pas encore prêt",
                    "{0} · Fermer le rapport",
                    "Voir les statistiques",
                    "Dernier combat",
                    "Étage actuel",
                    "Fermer les statistiques",
                    "DPS moyen · temps de combat cumulé",
                    "DPS moyen · durée du combat",
                    "Aucun combat enregistré à cet étage",
                    "Ce combat",
                    "Temps de combat cumulé {0}"),
                ["it-IT"] = CreateInsightsTexts("Statistiche danni",
                    "Automatico",
                    "Solo boss",
                    "Ogni scontro",
                    "DPS",
                    "sconfitti",
                    "i miei colpi finali",
                    "normale",
                    "miniboss",
                    "BOSS",
                    "Riepilogo del combattimento",
                    "DMG · QUOTA",
                    "DMG · DPS MEDIO",
                    "DMG",
                    "QUOTA",
                    "DPS MEDIO",
                    "TIPI DI DANNO",
                    "Fisico",
                    "Fuoco",
                    "Ghiaccio",
                    "Fulmine",
                    "Caos",
                    "normale",
                    "misto",
                    "altro",
                    "Automatico mostra i DPS degli ultimi 5 secondi nei combattimenti normali e i danni cumulativi contro i BOSS. I resoconti mostrano i totali della battaglia e del piano.\nFuori dal combattimento, premi la scorciatoia delle statistiche o aprile dal menu di pausa. Tieni premuto per mezzo secondo per nascondere o ripristinare il pannello senza interrompere la registrazione.\nI totali sono temporanei e locali: in cooperativa possono differire. Cambiare piano, riconnettersi, ricaricare o disattivare le statistiche può cancellarli.",
                    "Disattivato",
                    "Statistiche danni nascoste",
                    "Statistiche danni ripristinate",
                    "Statistiche aperte",
                    "Statistiche chiuse",
                    "Nessun resoconto disponibile su questo piano",
                    "Statistiche non disponibili durante il caricamento",
                    "Statistiche non disponibili durante il cambio schermata",
                    "Statistiche non disponibili durante una scena",
                    "Chiudi il menu per vedere le statistiche",
                    "Il resoconto non è ancora pronto",
                    "{0} · Chiudi resoconto",
                    "Vedi statistiche",
                    "Ultimo scontro",
                    "Piano attuale",
                    "Chiudi statistiche",
                    "DPS medi · tempo di combattimento totale",
                    "DPS medi · durata dello scontro",
                    "Nessun combattimento registrato in questo piano",
                    "Questo scontro",
                    "Tempo totale in battaglia {0}"),
                ["pl-PL"] = CreateInsightsTexts("Statystyki obrażeń",
                    "Automatycznie",
                    "Tylko bossowie",
                    "Każda walka",
                    "DPS",
                    "pokonani",
                    "moje ostatnie ciosy",
                    "zwykły",
                    "miniboss",
                    "BOSS",
                    "Podsumowanie walki",
                    "DMG · UDZIAŁ",
                    "DMG · ŚR. DPS",
                    "DMG",
                    "UDZIAŁ",
                    "ŚR. DPS",
                    "RODZAJE OBRAŻEŃ",
                    "Fizyczne",
                    "Ogień",
                    "Lód",
                    "Błyskawice",
                    "Chaos",
                    "zwykłe",
                    "mieszane",
                    "inne",
                    "Tryb automatyczny pokazuje DPS z ostatnich 5 sekund zwykłej walki i łączne obrażenia w walce z BOSS-em. Raporty zawierają sumy walki i piętra.\nPoza walką naciśnij skrót statystyk lub otwórz je w menu pauzy. Przytrzymanie przez pół sekundy ukrywa lub przywraca panel bez zatrzymywania zapisu.\nSumy są tymczasowe i lokalne, więc wyniki w kooperacji mogą się różnić. Zmiana piętra, ponowne połączenie, wczytanie lub wyłączenie statystyk może je usunąć.",
                    "Wyłączone",
                    "Statystyki obrażeń ukryte",
                    "Statystyki obrażeń przywrócone",
                    "Statystyki otwarte",
                    "Statystyki zamknięte",
                    "Brak raportu walki na tym piętrze",
                    "Statystyki niedostępne podczas ładowania",
                    "Statystyki niedostępne podczas przejścia ekranu",
                    "Statystyki niedostępne podczas przerywnika",
                    "Zamknij menu, aby zobaczyć statystyki",
                    "Raport walki nie jest jeszcze gotowy",
                    "{0} · Zamknij raport",
                    "Zobacz statystyki",
                    "Ostatnia walka",
                    "Obecne piętro",
                    "Zamknij statystyki",
                    "Średnie DPS · łączny czas walki",
                    "Średnie DPS · czas tej walki",
                    "Brak zapisanych walk na tym piętrze",
                    "Ta walka",
                    "Łączny czas walki {0}"),
                ["pt-BR"] = CreateInsightsTexts("Estatísticas de dano",
                    "Automático",
                    "Só chefes",
                    "Cada combate",
                    "DPS",
                    "derrotados",
                    "meus golpes finais",
                    "normal",
                    "minichefe",
                    "BOSS",
                    "Resumo do combate",
                    "DMG · PARCELA",
                    "DMG · DPS MÉDIO",
                    "DMG",
                    "PARCELA",
                    "DPS MÉDIO",
                    "TIPOS DE DANO",
                    "Físico",
                    "Fogo",
                    "Gelo",
                    "Elétrico",
                    "Caos",
                    "normal",
                    "misto",
                    "outro",
                    "Automático mostra o DPS dos últimos 5 segundos em lutas comuns e o dano acumulado contra BOSS. Os relatórios mostram totais da luta e do andar.\nFora de combate, toque no atalho de estatísticas ou abra-as no menu de pausa. Segure por meio segundo para ocultar ou restaurar a exibição sem parar o registro.\nOs totais são temporários e locais; podem diferir no cooperativo. Mudar de andar, reconectar, recarregar ou desativar as estatísticas pode apagá-los.",
                    "Desativado",
                    "Estatísticas de dano ocultas",
                    "Exibição das estatísticas restaurada",
                    "Estatísticas abertas",
                    "Estatísticas fechadas",
                    "Ainda não há relatório de combate neste andar",
                    "Estatísticas indisponíveis durante o carregamento",
                    "Estatísticas indisponíveis durante a transição de tela",
                    "Estatísticas indisponíveis durante cenas",
                    "Feche o menu para ver as estatísticas",
                    "O relatório de combate ainda não está pronto",
                    "{0} · Fechar relatório",
                    "Ver estatísticas",
                    "Último combate",
                    "Andar atual",
                    "Fechar estatísticas",
                    "DPS médio · tempo de combate acumulado",
                    "DPS médio · duração do combate",
                    "Nenhum combate registrado neste andar",
                    "Este combate",
                    "Tempo total de combate {0}"),
                ["ru-RU"] = CreateInsightsTexts("Статистика урона",
                    "Автоматически",
                    "Только боссы",
                    "Каждый бой",
                    "DPS",
                    "побеждено",
                    "мои последние удары",
                    "обычный",
                    "мини-босс",
                    "BOSS",
                    "Итоги боя",
                    "DMG · ДОЛЯ",
                    "DMG · СР. DPS",
                    "DMG",
                    "ДОЛЯ",
                    "СР. DPS",
                    "ТИПЫ УРОНА",
                    "Физический",
                    "Огонь",
                    "Лёд",
                    "Молния",
                    "Хаос",
                    "обычный",
                    "смешанный",
                    "прочий",
                    "Автоматический режим показывает DPS за последние 5 секунд в обычных боях и накопленный урон в боях с BOSS. Отчёты содержат итоги боя и этажа.\nВне боя нажмите клавишу статистики или откройте её в меню паузы. Удерживайте полсекунды, чтобы скрыть или вернуть панель, не прекращая запись.\nИтоги временные и локальные, поэтому в совместной игре могут различаться. Смена этажа, переподключение, перезагрузка или отключение статистики могут их очистить.",
                    "Отключено",
                    "Статистика урона скрыта",
                    "Отображение статистики восстановлено",
                    "Статистика открыта",
                    "Статистика закрыта",
                    "На этом этаже ещё нет отчёта о бое",
                    "Статистика недоступна при загрузке",
                    "Статистика недоступна при переходе экрана",
                    "Статистика недоступна во время сюжетной сцены",
                    "Закройте меню для просмотра статистики",
                    "Отчёт о бое ещё не готов",
                    "{0} · Закрыть отчёт",
                    "Показать статистику",
                    "Последний бой",
                    "Текущий этаж",
                    "Закрыть статистику",
                    "Средний DPS · суммарное время боя",
                    "Средний DPS · длительность боя",
                    "На этом этаже ещё нет записанных боёв",
                    "Этот бой",
                    "Общее время боя {0}"),
                ["sv-SE"] = CreateInsightsTexts("Skadestatistik",
                    "Automatiskt",
                    "Endast bossar",
                    "Varje strid",
                    "DPS",
                    "besegrade",
                    "mina sista slag",
                    "vanlig",
                    "miniboss",
                    "BOSS",
                    "Stridssammanfattning",
                    "DMG · ANDEL",
                    "DMG · SNITT-DPS",
                    "DMG",
                    "ANDEL",
                    "SNITT-DPS",
                    "SKADETYPER",
                    "Fysisk",
                    "Eld",
                    "Is",
                    "Blixt",
                    "Kaos",
                    "normal",
                    "blandad",
                    "övrig",
                    "Automatiskt visar DPS för de senaste 5 sekunderna i vanliga strider och sammanlagd skada mot BOSS. Rapporter visar summor för striden och våningen.\nTryck kort på statistikgenvägen utanför strid eller öppna statistiken i pausmenyn. Håll i en halv sekund för att dölja eller visa panelen utan att stoppa registreringen.\nSummorna är tillfälliga och lokala; samarbetsresultat kan skilja sig. Våningsbyte, återanslutning, omladdning eller avstängd statistik kan rensa dem.",
                    "Inaktiverat",
                    "Skadestatistik dold",
                    "Skadestatistik visas igen",
                    "Statistik öppnad",
                    "Statistik stängd",
                    "Ingen stridsrapport finns på denna våning ännu",
                    "Statistik är inte tillgänglig under laddning",
                    "Statistik är inte tillgänglig vid skärmövergång",
                    "Statistik är inte tillgänglig under en mellansekvens",
                    "Stäng menyn för att visa statistik",
                    "Stridsrapporten är inte redo ännu",
                    "{0} · Stäng rapporten",
                    "Visa statistik",
                    "Senaste striden",
                    "Aktuell våning",
                    "Stäng statistik",
                    "Genomsnittlig DPS · sammanlagd stridstid",
                    "Genomsnittlig DPS · stridens längd",
                    "Inga strider registrerade på denna våning",
                    "Denna strid",
                    "Sammanlagd stridstid {0}"),
                ["th-TH"] = CreateInsightsTexts("สถิติดาเมจ",
                    "อัตโนมัติ",
                    "บอสเท่านั้น",
                    "ทุกการต่อสู้",
                    "DPS",
                    "ปราบแล้ว",
                    "การโจมตีปิดท้ายของฉัน",
                    "ทั่วไป",
                    "มินิบอส",
                    "BOSS",
                    "สรุปการต่อสู้",
                    "DMG · สัดส่วน",
                    "DMG · DPS เฉลี่ย",
                    "DMG",
                    "สัดส่วน",
                    "DPS เฉลี่ย",
                    "ประเภทดาเมจ",
                    "กายภาพ",
                    "ไฟ",
                    "น้ำแข็ง",
                    "สายฟ้า",
                    "โกลาหล",
                    "ทั่วไป",
                    "ผสม",
                    "อื่น ๆ",
                    "โหมดอัตโนมัติแสดง DPS ย้อนหลัง 5 วินาทีในการต่อสู้ทั่วไป และดาเมจสะสมในการต่อสู้กับ BOSS รายงานแสดงยอดรวมของการต่อสู้และชั้นปัจจุบัน\nนอกการต่อสู้ กดปุ่มลัดสถิติสั้น ๆ หรือเปิดสถิติจากเมนูหยุดชั่วคราว กดค้างครึ่งวินาทีเพื่อซ่อนหรือแสดงโดยยังบันทึกต่อ\nยอดรวมเป็นข้อมูลชั่วคราวในเครื่อง ผลในโหมดร่วมมือจึงอาจต่างกัน การเปลี่ยนชั้น เชื่อมต่อใหม่ โหลดใหม่ หรือปิดสถิติอาจล้างข้อมูล",
                    "ปิด",
                    "ซ่อนสถิติดาเมจแล้ว",
                    "แสดงสถิติดาเมจอีกครั้งแล้ว",
                    "เปิดสถิติแล้ว",
                    "ปิดสถิติแล้ว",
                    "ยังไม่มีรายงานการต่อสู้ในชั้นนี้",
                    "แสดงสถิติระหว่างโหลดไม่ได้",
                    "แสดงสถิติระหว่างเปลี่ยนหน้าจอไม่ได้",
                    "แสดงสถิติระหว่างฉากเนื้อเรื่องไม่ได้",
                    "โปรดปิดเมนูเพื่อดูสถิติ",
                    "รายงานการต่อสู้ยังไม่พร้อม",
                    "{0} · ปิดรายงาน",
                    "ดูสถิติ",
                    "การต่อสู้ล่าสุด",
                    "ชั้นปัจจุบัน",
                    "ปิดสถิติ",
                    "DPS เฉลี่ย · เวลาต่อสู้สะสม",
                    "DPS เฉลี่ย · ระยะเวลาการต่อสู้",
                    "ยังไม่มีข้อมูลการต่อสู้ในชั้นนี้",
                    "การต่อสู้นี้",
                    "เวลาต่อสู้สะสม {0}"),
                ["tr-TR"] = CreateInsightsTexts("Hasar istatistikleri",
                    "Otomatik",
                    "Yalnızca bosslar",
                    "Her savaş",
                    "DPS",
                    "yenilen",
                    "son vuruşlarım",
                    "normal",
                    "mini boss",
                    "BOSS",
                    "Savaş özeti",
                    "DMG · PAY",
                    "DMG · ORT. DPS",
                    "DMG",
                    "PAY",
                    "ORT. DPS",
                    "HASAR TÜRLERİ",
                    "Fiziksel",
                    "Ateş",
                    "Buz",
                    "Yıldırım",
                    "Kaos",
                    "normal",
                    "karma",
                    "diğer",
                    "Otomatik mod normal savaşlarda son 5 saniyenin DPS değerini, BOSS savaşlarında toplam hasarı gösterir. Raporlarda savaş ve kat toplamları bulunur.\nSavaş dışında istatistik kısayoluna dokunun veya duraklatma menüsünden istatistikleri açın. Yarım saniye basılı tutmak kaydı durdurmadan gösterimi gizler veya geri getirir.\nToplamlar geçici ve yereldir; ortak oyunda farklı olabilir. Kat değiştirmek, yeniden bağlanmak, yeniden yüklemek veya istatistikleri kapatmak bunları silebilir.",
                    "Kapalı",
                    "Hasar istatistikleri gizlendi",
                    "Hasar istatistikleri yeniden gösteriliyor",
                    "İstatistikler açıldı",
                    "İstatistikler kapatıldı",
                    "Bu katta henüz savaş raporu yok",
                    "Yükleme sırasında istatistikler gösterilemez",
                    "Ekran geçişinde istatistikler gösterilemez",
                    "Ara sahne sırasında istatistikler gösterilemez",
                    "İstatistikleri görmek için menüyü kapatın",
                    "Savaş raporu henüz hazır değil",
                    "{0} · Raporu kapat",
                    "İstatistikleri görüntüle",
                    "Son savaş",
                    "Mevcut kat",
                    "İstatistikleri kapat",
                    "Ortalama DPS · toplam savaş süresi",
                    "Ortalama DPS · bu savaşın süresi",
                    "Bu katta henüz savaş kaydı yok",
                    "Bu savaş",
                    "Toplam savaş süresi {0}")
            };

        private static readonly Dictionary<string, Dictionary<string, string>> ScaleTexts =
            new Dictionary<string, Dictionary<string, string>>
            {
                ["en-US"] = CreateScaleTexts("Statistics size", "Scale live statistics and combat reports. 100% is recommended; reports fit within the screen. The game's native HUD and combo text are unchanged."),
                ["zh-CN"] = CreateScaleTexts("统计界面大小", "缩放实时统计和战后战报，推荐 100%；战报自动适配屏幕边界。不改变游戏原生 HUD 与连招文字。"),
                ["zh-TW"] = CreateScaleTexts("統計介面大小", "縮放即時統計與戰後戰報，建議 100%；戰報自動適配螢幕邊界。不改變遊戲原生 HUD 與連招文字。"),
                ["ko-KR"] = CreateScaleTexts("통계 패널 크기", "실시간 통계와 전투 보고서의 크기를 조절합니다. 100%를 권장하며 보고서는 화면 안에 맞춰집니다. 게임 기본 HUD와 콤보 표시는 바뀌지 않습니다."),
                ["ja-JP"] = CreateScaleTexts("統計パネルのサイズ", "リアルタイム統計と戦闘レポートの大きさを変更します。100%を推奨し、レポートは画面内に収まります。ゲーム本体のHUDとコンボ表示は変更しません。"),
                ["de-DE"] = CreateScaleTexts("Größe der Statistik", "Skaliert Live-Statistik und Kampfberichte. 100% wird empfohlen; Berichte passen sich dem Bildschirm an. Das Spiel-HUD und die Kombo-Anzeige bleiben unverändert."),
                ["es-ES"] = CreateScaleTexts("Tamaño de las estadísticas", "Ajusta el tamaño de las estadísticas en vivo y los informes. Se recomienda 100%; los informes se adaptan a la pantalla. No cambia el HUD ni el texto de combos del juego."),
                ["fr-FR"] = CreateScaleTexts("Taille des statistiques", "Redimensionne les statistiques en direct et les rapports. 100% est recommandé ; les rapports s’adaptent à l’écran. Le HUD et l’affichage des combos du jeu restent inchangés."),
                ["it-IT"] = CreateScaleTexts("Dimensione statistiche", "Ridimensiona le statistiche in tempo reale e i resoconti. Si consiglia 100%; i resoconti si adattano allo schermo. HUD e testo delle combo del gioco restano invariati."),
                ["pl-PL"] = CreateScaleTexts("Rozmiar statystyk", "Skaluje bieżące statystyki i raporty walki. Zalecane 100%; raporty mieszczą się na ekranie. Nie zmienia HUD-u ani tekstu kombinacji w grze."),
                ["pt-BR"] = CreateScaleTexts("Tamanho das estatísticas", "Ajusta o tamanho das estatísticas em tempo real e dos relatórios. Recomendado: 100%; os relatórios se adaptam à tela. Não altera o HUD nem o texto de combos do jogo."),
                ["ru-RU"] = CreateScaleTexts("Размер статистики", "Масштабирует текущую статистику и отчёты о бое. Рекомендуется 100%; отчёты подстраиваются под экран. HUD игры и текст комбо не меняются."),
                ["sv-SE"] = CreateScaleTexts("Statistikstorlek", "Skalar löpande statistik och stridsrapporter. 100% rekommenderas; rapporterna anpassas till skärmen. Spelets HUD och kombinationstext ändras inte."),
                ["th-TH"] = CreateScaleTexts("ขนาดแผงสถิติ", "ปรับขนาดสถิติสดและรายงานการต่อสู้ แนะนำ 100% โดยรายงานจะปรับให้พอดีหน้าจอ ไม่เปลี่ยน HUD และข้อความคอมโบของเกม"),
                ["tr-TR"] = CreateScaleTexts("İstatistik boyutu", "Canlı istatistikleri ve savaş raporlarını ölçekler. %100 önerilir; raporlar ekrana sığar. Oyunun HUD ve kombo metni değişmez.")
            };

        private static readonly Dictionary<string, Dictionary<string, string>>
            HitStreakFeedbackTexts =
            new Dictionary<string, Dictionary<string, string>>
            {
                ["en-US"] = CreateHitStreakTexts("Hit-streak indicator",
                    "Show the local player's consecutive-hit count near the hit target, following its movement. Critical hits, executions, and milestones receive stronger emphasis. Follower attacks and identified damage-over-time ticks do not extend the streak."),
                ["zh-CN"] = CreateHitStreakTexts("连续命中提示", "在受击目标侧上方显示本地玩家本人的连续命中计数，并跟随目标移动；暴击、处决与里程碑会获得更强强调。随从攻击和游戏可识别的持续伤害不会延长连续命中。"),
                ["zh-TW"] = CreateHitStreakTexts("連續命中提示", "在受擊目標側上方顯示本機玩家本人的連續命中計數，並跟隨目標移動；暴擊、處決與里程碑會獲得更強強調。隨從攻擊和遊戲可辨識的持續傷害不會延長連續命中。"),
                ["ko-KR"] = CreateHitStreakTexts("연속 타격 표시", "명중한 대상 근처에 로컬 플레이어 본인의 연속 타격 수를 표시하고 대상의 움직임을 따라갑니다. 치명타, 처형, 연속 타격 이정표를 더 강하게 강조합니다. 추종자의 공격과 식별된 지속 피해는 연속 타격을 연장하지 않습니다."),
                ["ja-JP"] = CreateHitStreakTexts("連続ヒット表示", "攻撃を当てた対象の近くに自分自身の連続ヒット数を表示し、対象の動きに追従します。クリティカル、処刑、節目のヒット数を強く演出します。従者の攻撃と識別できた継続ダメージは連続ヒットを延長しません。"),
                ["de-DE"] = CreateHitStreakTexts("Trefferfolgen-Anzeige",
                    "Zeigt die eigene Trefferfolge nahe dem getroffenen Ziel und folgt dessen Bewegung. Kritische Treffer, Hinrichtungen und Meilensteine werden stärker betont. Angriffe von Begleitern und erkannter Schaden über Zeit verlängern die Trefferfolge nicht."),
                ["es-ES"] = CreateHitStreakTexts("Indicador de golpes consecutivos",
                    "Muestra los golpes consecutivos del propio jugador local cerca del objetivo golpeado y sigue su movimiento. Destaca más los críticos, las ejecuciones y los hitos de la racha. Los ataques de seguidores y el daño periódico identificado no prolongan la racha."),
                ["fr-FR"] = CreateHitStreakTexts("Indicateur de série de coups",
                    "Affiche la série de coups du joueur local près de la cible touchée et suit son déplacement. Les coups critiques, exécutions et paliers sont davantage mis en valeur. Les attaques des compagnons et les dégâts sur la durée identifiés ne prolongent pas la série."),
                ["it-IT"] = CreateHitStreakTexts("Indicatore serie di colpi",
                    "Mostra i colpi consecutivi del giocatore locale vicino al bersaglio colpito e ne segue il movimento. Critici, esecuzioni e traguardi ricevono maggiore enfasi. Gli attacchi dei seguaci e i danni nel tempo identificati non prolungano la serie."),
                ["pl-PL"] = CreateHitStreakTexts("Wskaźnik serii trafień",
                    "Pokazuje serię własnych trafień lokalnego gracza przy trafionym celu i podąża za jego ruchem. Trafienia krytyczne, egzekucje i kolejne progi serii są mocniej wyróżniane. Ataki towarzyszy i rozpoznane obrażenia w czasie nie przedłużają serii."),
                ["pt-BR"] = CreateHitStreakTexts("Indicador de sequência de acertos",
                    "Mostra a sequência de acertos do próprio jogador local perto do alvo atingido e acompanha seu movimento. Críticos, execuções e marcos da sequência recebem mais destaque. Ataques de seguidores e dano periódico identificado não prolongam a sequência."),
                ["ru-RU"] = CreateHitStreakTexts("Индикатор серии попаданий",
                    "Показывает серию собственных попаданий локального игрока рядом с поражённой целью и следует за её движением. Критические удары, казни и этапы серии выделяются сильнее. Атаки спутников и распознанный периодический урон не продлевают серию."),
                ["sv-SE"] = CreateHitStreakTexts("Indikator för träffserie", "Visar den lokala spelarens egen träffserie nära det träffade målet och följer dess rörelse. Kritiska träffar, avrättningar och milstolpar framhävs mer. Följeslagares attacker och identifierad skada över tid förlänger inte serien."),
                ["th-TH"] = CreateHitStreakTexts("ตัวแสดงการโจมตีต่อเนื่อง", "แสดงจำนวนการโจมตีต่อเนื่องของผู้เล่นในเครื่องเองใกล้เป้าหมายที่โดนโจมตี และเคลื่อนตามเป้าหมาย เน้นคริติคอล การประหาร และหลักจำนวนครั้งให้เด่นขึ้น การโจมตีของผู้ติดตามและดาเมจต่อเนื่องที่ตรวจพบจะไม่ต่อเวลาชุดโจมตี"),
                ["tr-TR"] = CreateHitStreakTexts("Seri vuruş göstergesi", "Yerel oyuncunun kendi seri vuruş sayısını vurulan hedefin yakınında gösterir ve hedefin hareketini takip eder. Kritik vuruşlar, infazlar ve seri eşikleri daha güçlü vurgulanır. Takipçilerin saldırıları ve tanımlanan zamanla hasar, seriyi uzatmaz.")
            };

        private static Dictionary<string, string> CreateScaleTexts(string uiScale, string help)
        {
            return new Dictionary<string, string>
            {
                [SettingDamageStatisticsScale] = uiScale,
                [HelpDamageStatisticsScale] = help
            };
        }

        private static Dictionary<string, string> CreateHitStreakTexts(string label, string help)
        {
            return new Dictionary<string, string>
            {
                [SettingHitStreakFeedback] = label,
                [HelpHitStreakFeedback] = help
            };
        }

        private static Dictionary<string, string> CreateInsightsTexts(string setting, string smart,
            string bossOnly, string allCombat, string dps, string defeated,
            string finalBlows, string normal, string miniboss, string boss,
            string combatSummary, string damageShare, string damageAverageDps,
            string reportDamage, string reportShare, string reportAverageDps,
            string reportDamageMix, string damagePhysical, string damageFire,
            string damageIce, string damageLightning, string damageChaos,
            string damageNormal, string damageMixed, string damageOther,
            string policyHelp, string disabled, string displayHidden,
            string displayRestored, string statisticsOpened, string statisticsClosed,
            string reportUnavailable, string reportLoading, string reportScreenTransition,
            string reportCutscene, string reportMenu, string reportHudUnavailable,
            string reportDismissHint, string viewStatistics, string recentEncounterStatistics,
            string currentFloorStatistics, string closeStatistics, string floorBattleTime,
            string encounterBattleTime, string floorStatisticsEmpty, string currentEncounterStatistics,
            string floorBattleDuration)
        {
            return new Dictionary<string, string>
            {
                [SettingDisplayPolicy] = setting,
                [DisplayPolicyKeys[0]] = smart,
                [DisplayPolicyKeys[1]] = bossOnly,
                [DisplayPolicyKeys[2]] = allCombat,
                [InsightsDisabled] = disabled,
                [DamageStatisticsDisplayHidden] = displayHidden,
                [DamageStatisticsDisplayRestored] = displayRestored,
                [StatisticsOpened] = statisticsOpened,
                [StatisticsClosed] = statisticsClosed,
                [EncounterReportUnavailable] = reportUnavailable,
                [EncounterReportLoading] = reportLoading,
                [EncounterReportScreenTransition] = reportScreenTransition,
                [EncounterReportCutscene] = reportCutscene,
                [EncounterReportMenu] = reportMenu,
                [EncounterReportHudUnavailable] = reportHudUnavailable,
                [HelpDisplayPolicy] = policyHelp,
                [Dps] = dps,
                [Defeated] = defeated,
                [FinalBlows] = finalBlows,
                [NormalEnemy] = normal,
                [MinibossEnemy] = miniboss,
                [BossEnemy] = boss,
                [CombatSummary] = combatSummary,
                [DamageShare] = damageShare,
                [DamageAverageDps] = damageAverageDps,
                [ReportDamage] = reportDamage,
                [ReportShare] = reportShare,
                [ReportAverageDps] = reportAverageDps,
                [ReportDamageMix] = reportDamageMix,
                [ReportDismissHint] = reportDismissHint,
                [ViewStatistics] = viewStatistics,
                [RecentEncounterStatistics] = recentEncounterStatistics,
                [CurrentEncounterStatistics] = currentEncounterStatistics,
                [CurrentFloorStatistics] = currentFloorStatistics,
                [CloseStatistics] = closeStatistics,
                [FloorBattleTime] = floorBattleTime,
                [FloorBattleDuration] = floorBattleDuration,
                [EncounterBattleTime] = encounterBattleTime,
                [FloorStatisticsEmpty] = floorStatisticsEmpty,
                [DamagePhysical] = damagePhysical,
                [DamageFire] = damageFire,
                [DamageIce] = damageIce,
                [DamageLightning] = damageLightning,
                [DamageChaos] = damageChaos,
                [DamageNormal] = damageNormal,
                [DamageMixed] = damageMixed,
                [DamageOther] = damageOther
            };
        }

        internal static void Register(Action<string, string, string> addText, IEnumerable<string> languages)
        {
            LocalizationGroup.Register(addText, languages, InsightsTexts);
            LocalizationGroup.Register(addText, languages, ScaleTexts);
            LocalizationGroup.Register(addText, languages, HitStreakFeedbackTexts);
            int[] percentages = { 80, 90, 100, 110, 120 };
            foreach (string language in languages)
                for (int index = 0; index < ScaleKeys.Length; index++)
                    addText(language, ScaleKeys[index], percentages[index] + "%");
        }
    }
}
