using System;
using System.Collections.Generic;
using SephiriaEnhancements.Configuration;

namespace SephiriaEnhancements.CostumeAppearance
{
    internal static class CostumeAppearanceLocalization
    {
        private const string Prefix = "SephiriaEnhancements.CostumeAppearance.";
        internal const string Title = Prefix + "Title", Appearance = Prefix + "Appearance",
            Follow = Prefix + "Follow", Following = Prefix + "Following", Help = Prefix + "Help",
            Preview = Prefix + "Preview", Apply = Prefix + "Apply", Cancel = Prefix + "Cancel",
            Thumbnails = Prefix + "Thumbnails", List = Prefix + "List", HostRequired = Prefix + "HostRequired",
            Applied = Prefix + "Applied", Interrupted = Prefix + "Interrupted", Unconfirmed = Prefix + "Unconfirmed",
            Waiting = Prefix + "Waiting", Empty = Prefix + "Empty";
        private static readonly string[] Keys = { Title, Appearance, Follow, Following, Help, Preview, Apply, Cancel,
            Thumbnails, List, HostRequired, Applied, Interrupted, Unconfirmed, Waiting, Empty };
        private static readonly Dictionary<string, string[]> Texts = new()
        {
            ["en-US"] = new[] { "Choose appearance", "Appearance: {0}", "Follow costume", "Follow costume", "Changes appearance only. Keeps your costume's abilities and starting equipment. Saved for this save slot until you choose Follow costume.", "Preview: {0}", "Apply appearance", "Cancel", "Thumbnails", "List", "Appearance needs host support", "Appearance saved.", "Appearance change interrupted. Open the appearance selector again to check.", "Appearance change was not confirmed. Check your appearance before trying again.", "Waiting for appearance confirmation…", "No owned appearances available." },
            ["zh-CN"] = new[] { "选择外观", "外观：{0}", "跟随装扮", "跟随装扮", "只更换外观，保留装扮的能力与初始装备。选择保存在当前存档中，直到恢复跟随装扮。", "预览：{0}", "应用外观", "取消", "缩略图", "列表", "外观功能需要房主支持", "外观选择已保存。", "外观更换已中断，请重新打开外观选择界面检查。", "尚未确认外观已更换，请检查当前外观后再试。", "正在等待外观更换确认……", "暂无已拥有的外观。" },
            ["zh-TW"] = new[] { "選擇外觀", "外觀：{0}", "跟隨裝扮", "跟隨裝扮", "只更換外觀，保留裝扮的能力與初始裝備。選擇儲存在目前存檔中，直到恢復跟隨裝扮。", "預覽：{0}", "套用外觀", "取消", "縮圖", "清單", "外觀功能需要房主支援", "外觀選擇已儲存。", "外觀更換已中斷，請重新開啟外觀選擇介面檢查。", "尚未確認外觀已更換，請檢查目前外觀後再試。", "正在等待外觀更換確認……", "暫無已擁有的外觀。" },
            ["ko-KR"] = new[] { "외형 선택", "외형: {0}", "의상에 맞추기", "의상에 맞추기", "외형만 변경하며 의상의 능력과 시작 장비는 유지합니다. 의상에 맞추기를 선택할 때까지 현재 저장 슬롯에 유지됩니다.", "미리 보기: {0}", "외형 적용", "취소", "미리 보기", "목록", "호스트의 외형 기능 지원 필요", "외형 선택을 저장했습니다.", "외형 변경이 중단되었습니다. 외형 선택 창을 다시 열어 확인하세요.", "외형 변경이 확인되지 않았습니다. 현재 외형을 확인한 뒤 다시 시도하세요.", "외형 변경 확인 중…", "보유한 외형이 없습니다." },
            ["ja-JP"] = new[] { "外見を選択", "外見：{0}", "衣装に合わせる", "衣装に合わせる", "外見だけを変更し、衣装の能力と初期装備は維持します。「衣装に合わせる」を選ぶまで、このセーブに保存されます。", "プレビュー：{0}", "外見を適用", "キャンセル", "サムネイル", "リスト", "ホスト側の外見機能の対応が必要", "外見の選択を保存しました。", "外見の変更が中断されました。選択画面を開き直して確認してください。", "外見の変更を確認できませんでした。現在の外見を確認してから再試行してください。", "外見の変更を確認中…", "所有している外見がありません。" },
            ["de-DE"] = new[] { "Aussehen wählen", "Aussehen: {0}", "Kostüm folgen", "Kostüm folgen", "Ändert nur das Aussehen. Fähigkeiten und Startausrüstung bleiben erhalten. Gilt für diesen Spielstand, bis du „Kostüm folgen“ wählst.", "Vorschau: {0}", "Aussehen anwenden", "Abbrechen", "Vorschaubilder", "Liste", "Host muss Aussehen unterstützen", "Aussehen gespeichert.", "Änderung unterbrochen. Öffne die Auswahl erneut und prüfe das Aussehen.", "Änderung nicht bestätigt. Prüfe das Aussehen vor einem weiteren Versuch.", "Warte auf Bestätigung…", "Kein eigenes Aussehen verfügbar." },
            ["es-ES"] = new[] { "Elegir apariencia", "Apariencia: {0}", "Seguir al traje", "Seguir al traje", "Solo cambia la apariencia. Conserva las habilidades y el equipo inicial del traje. Se guarda en esta partida hasta elegir Seguir al traje.", "Vista previa: {0}", "Aplicar apariencia", "Cancelar", "Miniaturas", "Lista", "Requiere soporte del anfitrión", "Apariencia guardada.", "Cambio interrumpido. Abre el selector de nuevo para comprobarlo.", "Cambio sin confirmar. Comprueba tu apariencia antes de volver a intentarlo.", "Esperando confirmación…", "No tienes apariencias disponibles." },
            ["fr-FR"] = new[] { "Choisir l’apparence", "Apparence : {0}", "Suivre le costume", "Suivre le costume", "Change uniquement l’apparence. Conserve les capacités et l’équipement de départ du costume. Enregistré pour cette sauvegarde jusqu’à choisir Suivre le costume.", "Aperçu : {0}", "Appliquer l’apparence", "Annuler", "Miniatures", "Liste", "Prise en charge par l’hôte requise", "Apparence enregistrée.", "Changement interrompu. Rouvrez le sélecteur pour vérifier.", "Changement non confirmé. Vérifiez votre apparence avant de réessayer.", "En attente de confirmation…", "Aucune apparence possédée disponible." },
            ["it-IT"] = new[] { "Scegli aspetto", "Aspetto: {0}", "Segui il costume", "Segui il costume", "Cambia solo l’aspetto. Mantiene abilità ed equipaggiamento iniziale del costume. Salvato in questa partita finché non scegli Segui il costume.", "Anteprima: {0}", "Applica aspetto", "Annulla", "Miniature", "Elenco", "È necessario il supporto dell’host", "Aspetto salvato.", "Modifica interrotta. Riapri la selezione per verificare.", "Modifica non confermata. Controlla l’aspetto prima di riprovare.", "In attesa di conferma…", "Nessun aspetto posseduto disponibile." },
            ["pl-PL"] = new[] { "Wybierz wygląd", "Wygląd: {0}", "Zgodnie ze strojem", "Zgodnie ze strojem", "Zmienia tylko wygląd. Zachowuje zdolności i wyposażenie początkowe stroju. Dotyczy tego zapisu do wybrania opcji Zgodnie ze strojem.", "Podgląd: {0}", "Zastosuj wygląd", "Anuluj", "Miniatury", "Lista", "Wymagana obsługa przez gospodarza", "Wygląd zapisany.", "Zmiana przerwana. Otwórz ponownie wybór wyglądu i sprawdź.", "Nie potwierdzono zmiany. Sprawdź wygląd przed ponowną próbą.", "Oczekiwanie na potwierdzenie…", "Brak posiadanych wyglądów." },
            ["pt-BR"] = new[] { "Escolher aparência", "Aparência: {0}", "Seguir traje", "Seguir traje", "Muda apenas a aparência. Mantém habilidades e equipamento inicial do traje. Fica neste salvamento até escolher Seguir traje.", "Prévia: {0}", "Aplicar aparência", "Cancelar", "Miniaturas", "Lista", "Requer suporte do anfitrião", "Aparência salva.", "Mudança interrompida. Abra a seleção novamente para conferir.", "Mudança não confirmada. Confira sua aparência antes de tentar de novo.", "Aguardando confirmação…", "Nenhuma aparência adquirida disponível." },
            ["ru-RU"] = new[] { "Выбрать внешность", "Внешность: {0}", "Как у костюма", "Как у костюма", "Меняет только внешность. Способности и начальное снаряжение костюма сохраняются. Выбор действует в этом сохранении до выбора «Как у костюма».", "Просмотр: {0}", "Применить внешность", "Отмена", "Миниатюры", "Список", "Нужна поддержка функции у хоста", "Внешность сохранена.", "Смена прервана. Откройте выбор внешности снова и проверьте результат.", "Смена не подтверждена. Проверьте внешность перед повторной попыткой.", "Ожидание подтверждения…", "Нет доступных приобретённых обликов." },
            ["sv-SE"] = new[] { "Välj utseende", "Utseende: {0}", "Följ dräkten", "Följ dräkten", "Ändrar bara utseendet. Behåller dräktens förmågor och startutrustning. Sparas i denna sparfil tills du väljer Följ dräkten.", "Förhandsvisning: {0}", "Använd utseende", "Avbryt", "Miniatyrer", "Lista", "Värden måste stödja utseenden", "Utseendet har sparats.", "Ändringen avbröts. Öppna utseendevalet igen och kontrollera.", "Ändringen bekräftades inte. Kontrollera utseendet innan du försöker igen.", "Väntar på bekräftelse…", "Inga ägda utseenden tillgängliga." },
            ["th-TH"] = new[] { "เลือกรูปลักษณ์", "รูปลักษณ์: {0}", "ตามชุด", "ตามชุด", "เปลี่ยนเฉพาะรูปลักษณ์ คงความสามารถและอุปกรณ์เริ่มต้นของชุดไว้ บันทึกในช่องเซฟนี้จนกว่าจะเลือกตามชุด", "ตัวอย่าง: {0}", "ใช้รูปลักษณ์", "ยกเลิก", "ภาพย่อ", "รายการ", "โฮสต์ต้องรองรับการเปลี่ยนรูปลักษณ์", "บันทึกรูปลักษณ์แล้ว", "การเปลี่ยนถูกขัดจังหวะ โปรดเปิดหน้าเลือกรูปลักษณ์อีกครั้งเพื่อตรวจสอบ", "ยังไม่ยืนยันการเปลี่ยน โปรดตรวจสอบรูปลักษณ์ก่อนลองใหม่", "กำลังรอการยืนยัน…", "ไม่มีรูปลักษณ์ที่เป็นเจ้าของให้เลือก" },
            ["tr-TR"] = new[] { "Görünüm seç", "Görünüm: {0}", "Kostümü takip et", "Kostümü takip et", "Yalnızca görünümü değiştirir. Kostümün yetenekleri ve başlangıç ekipmanı korunur. Kostümü takip et seçilene kadar bu kayıt için saklanır.", "Önizleme: {0}", "Görünümü uygula", "İptal", "Küçük resimler", "Liste", "Sunucunun görünüm desteği gerekli", "Görünüm kaydedildi.", "Değişiklik kesildi. Görünüm seçimini yeniden açıp kontrol edin.", "Değişiklik doğrulanmadı. Tekrar denemeden önce görünümünüzü kontrol edin.", "Onay bekleniyor…", "Sahip olunan görünüm yok." },
        };

        internal static void Register(Action<string, string, string> addText, IEnumerable<string> languages) =>
            LocalizationGroup.Register(addText, languages, Keys, Texts);
    }
}
