using System;
using System.Collections.Generic;
using SephiriaEnhancements.Configuration;

namespace SephiriaEnhancements.AutoCasting
{
    internal static class AutoCastingLocalization
    {
        internal const string Title = "SephiriaEnhancements.AutoCasting.Title";
        internal const string On = "SephiriaEnhancements.AutoCasting.On";
        internal const string Off = "SephiriaEnhancements.AutoCasting.Off";
        internal const string Hint = "SephiriaEnhancements.AutoCasting.Hint";
        internal const string Help = "SephiriaEnhancements.AutoCasting.Help";
        internal const string Unavailable = "SephiriaEnhancements.AutoCasting.Unavailable";
        internal const string TogglePause = "SephiriaEnhancements.AutoCasting.TogglePause";
        internal const string Paused = "SephiriaEnhancements.AutoCasting.Paused";
        internal const string PausedMessage = "SephiriaEnhancements.AutoCasting.PausedMessage";
        internal const string ResumedMessage = "SephiriaEnhancements.AutoCasting.ResumedMessage";
        internal const string SelectFirst = "SephiriaEnhancements.AutoCasting.SelectFirst";
        private static readonly string[] Keys = { Title, On, Off, Hint, Help, Unavailable, TogglePause, Paused, PausedMessage, ResumedMessage, SelectFirst };
        private static readonly Dictionary<string, string[]> Texts = new Dictionary<string, string[]>
        {
            ["en-US"] = new[] { "Auto casting", "On", "Off", "{0}: toggle auto casting", "Automatically casts only in combat, using normal mana and charges. With automatic targeting enabled, prefers your locked target, otherwise a nearby visible, unobstructed enemy; waits if none is available. With targeting disabled, uses your current aim. Pauses in menus. Follows this artifact when rebound; clears when it is lost, the character is replaced, or the world is reloaded. Use the pause / resume shortcut to keep your selections while pausing all auto casting.", "No supported magic", "Pause / resume auto casting", "Paused", "Auto casting paused", "Auto casting resumed", "First select magic for auto casting in the backpack or key-binding settings." },
            ["zh-CN"] = new[] { "自动施法", "开启", "关闭", "{0}：切换自动施法", "仅在战斗中自动释放，正常消耗魔力与次数。开启自动索敌时优先攻击锁定目标，否则选择附近可见、无遮挡的敌人；无目标时等待。关闭自动索敌时沿用当前瞄准。菜单中暂停。更换快捷键时跟随这件神器；失去神器、更换角色或重新加载世界后清除。可用暂停／恢复快捷键暂停全部自动施法，并保留已选魔法。", "无可用魔法", "暂停／恢复自动施法", "已暂停", "自动施法已暂停", "自动施法已恢复", "请先在背包或按键设置中选择要自动施法的魔法。" },
            ["zh-TW"] = new[] { "自動施法", "開啟", "關閉", "{0}：切換自動施法", "僅在戰鬥中自動施放，正常消耗魔力與次數。開啟自動索敵時優先攻擊鎖定目標，否則選擇附近可見、無遮擋的敵人；無目標時等待。關閉自動索敵時沿用目前瞄準。選單中暫停。更換快捷鍵時跟隨這件神器；失去神器、更換角色或重新載入世界後清除。可用暫停／恢復快捷鍵暫停全部自動施法，並保留已選魔法。", "無可用魔法", "暫停／恢復自動施法", "已暫停", "自動施法已暫停", "自動施法已恢復", "請先在背包或按鍵設定中選擇要自動施法的魔法。" },
            ["ko-KR"] = new[] { "자동 시전", "켜짐", "꺼짐", "{0}: 자동 시전 전환", "전투 중에만 자동 시전하며 마나와 횟수를 정상적으로 소모합니다. 자동 조준을 켜면 고정한 대상을 우선하고, 없으면 가까운 시야 내의 가려지지 않은 적을 선택합니다. 대상이 없으면 기다립니다. 자동 조준을 끄면 현재 조준을 사용합니다. 메뉴에서는 멈춥니다. 단축키를 바꿔도 이 유물을 따르며, 유물을 잃거나 캐릭터를 바꾸거나 세계를 다시 불러오면 해제됩니다. 일시 정지 / 재개 단축키로 선택을 유지한 채 모든 자동 시전을 멈출 수 있습니다.", "사용 가능한 마법 없음", "자동 시전 일시 정지 / 재개", "일시 정지", "자동 시전이 일시 정지되었습니다", "자동 시전이 재개되었습니다", "먼저 가방이나 키 설정에서 자동 시전할 마법을 선택하세요." },
            ["ja-JP"] = new[] { "自動詠唱", "オン", "オフ", "{0}：自動詠唱を切り替え", "戦闘中のみ自動で使い、魔力と回数を通常どおり消費します。自動照準が有効ならロック中の対象を優先し、なければ近くの画面内にいる遮られていない敵を狙います。対象がいなければ待機します。自動照準が無効なら現在の照準を使います。メニュー中は停止します。キーを変更してもこのアーティファクトに設定が残り、失った時・キャラクター変更時・世界の再読み込み時に解除されます。一時停止／再開キーで選択を保持したまま、すべての自動詠唱を停止できます。", "対応する魔法なし", "自動詠唱を一時停止／再開", "一時停止", "自動詠唱を一時停止しました", "自動詠唱を再開しました", "先にバッグまたはキー設定で自動詠唱する魔法を選んでください。" },
            ["de-DE"] = new[] { "Automatisches Zaubern", "An", "Aus", "{0}: automatisches Zaubern umschalten", "Zaubert nur im Kampf und verbraucht normal Mana und Ladungen. Bei automatischer Zielwahl wird das fixierte Ziel bevorzugt, sonst ein naher sichtbarer Gegner ohne Hindernisse. Ohne Ziel wird gewartet. Bei deaktivierter Zielwahl gilt die aktuelle Zielrichtung. Pausiert in Menüs. Bleibt beim Umbelegen am Artefakt; wird bei Verlust, Charakterwechsel oder erneutem Laden der Welt gelöscht. Mit der Taste zum Pausieren / Fortsetzen kannst du alles automatische Zaubern pausieren, ohne die Auswahl zu löschen.", "Kein geeigneter Zauber", "Automatisches Zaubern pausieren / fortsetzen", "Pausiert", "Automatisches Zaubern pausiert", "Automatisches Zaubern fortgesetzt", "Wähle zuerst im Rucksack oder in der Tastenbelegung Zauber zum automatischen Zaubern aus." },
            ["es-ES"] = new[] { "Lanzamiento automático", "Activado", "Desactivado", "{0}: alternar lanzamiento automático", "Lanza magia solo en combate y consume maná y cargas normales. Con selección automática, prioriza el objetivo fijado o elige un enemigo cercano, visible y sin obstáculos; espera si no hay ninguno. Si está desactivada, usa la puntería actual. Se pausa en los menús. Sigue al artefacto al reasignarlo; se borra al perderlo, cambiar de personaje o recargar el mundo. El atajo de pausa / reanudación detiene todo lanzamiento automático y conserva la selección.", "Sin magia compatible", "Pausar / reanudar lanzamiento automático", "En pausa", "Lanzamiento automático en pausa", "Lanzamiento automático reanudado", "Primero selecciona magia para el lanzamiento automático en la mochila o en los ajustes de teclas." },
            ["fr-FR"] = new[] { "Lancement automatique", "Activé", "Désactivé", "{0} : basculer le lancement automatique", "Lance la magie uniquement en combat, avec un coût normal en mana et charges. Le ciblage automatique privilégie la cible verrouillée, sinon un ennemi proche, visible et sans obstacle ; attend sans cible. Si le ciblage est désactivé, utilise la visée actuelle. Pause dans les menus. Suit cet artefact après réattribution ; effacé en cas de perte, de changement de personnage ou de rechargement du monde. Le raccourci de pause / reprise suspend tous les lancements automatiques en conservant la sélection.", "Aucune magie compatible", "Suspendre / reprendre le lancement automatique", "En pause", "Lancement automatique suspendu", "Lancement automatique repris", "Sélectionnez d’abord la magie à lancer automatiquement dans le sac ou les paramètres des touches." },
            ["it-IT"] = new[] { "Lancio automatico", "Attivo", "Disattivo", "{0}: alterna il lancio automatico", "Lancia magie solo in combattimento, consumando normalmente mana e cariche. Con la mira automatica dà priorità al bersaglio agganciato, altrimenti sceglie un nemico vicino, visibile e senza ostacoli; attende se non ne trova. Con la mira automatica disattivata usa la mira attuale. Si ferma nei menu. Segue l'artefatto se riassegnato; si azzera alla perdita, al cambio di personaggio o al ricaricamento del mondo. La scorciatoia di pausa / ripresa sospende tutti i lanci automatici mantenendo la selezione.", "Nessuna magia compatibile", "Sospendi / riprendi il lancio automatico", "In pausa", "Lancio automatico sospeso", "Lancio automatico ripreso", "Prima seleziona la magia da lanciare automaticamente nello zaino o nelle impostazioni dei tasti." },
            ["pl-PL"] = new[] { "Automatyczne rzucanie", "Włączone", "Wyłączone", "{0}: przełącz automatyczne rzucanie", "Rzuca magię tylko w walce, zużywając normalnie manę i ładunki. Automatyczne celowanie preferuje zablokowany cel, a w przeciwnym razie pobliskiego, widocznego wroga bez przeszkód; czeka, gdy brak celu. Po wyłączeniu celowania używa bieżącego kierunku. Pauzuje w menu. Podąża za artefaktem po zmianie przypisania; znika po jego utracie, zmianie postaci lub ponownym wczytaniu świata. Skrót wstrzymania / wznowienia zatrzymuje całe automatyczne rzucanie, zachowując wybór magii.", "Brak obsługiwanej magii", "Wstrzymaj / wznów automatyczne rzucanie", "Wstrzymane", "Automatyczne rzucanie wstrzymane", "Automatyczne rzucanie wznowione", "Najpierw wybierz magię do automatycznego rzucania w plecaku lub ustawieniach klawiszy." },
            ["pt-BR"] = new[] { "Conjuração automática", "Ativada", "Desativada", "{0}: alternar conjuração automática", "Conjura apenas em combate, consumindo mana e cargas normalmente. Com mira automática, prioriza o alvo travado ou escolhe um inimigo próximo, visível e sem obstáculos; espera se não houver alvo. Com a mira automática desativada, usa a mira atual. Pausa nos menus. Acompanha o artefato ao remapear; é apagada ao perdê-lo, trocar de personagem ou recarregar o mundo. O atalho de pausa / retomada interrompe toda conjuração automática e mantém a seleção.", "Nenhuma magia compatível", "Pausar / retomar conjuração automática", "Em pausa", "Conjuração automática pausada", "Conjuração automática retomada", "Primeiro selecione a magia para conjuração automática na mochila ou nas configurações de teclas." },
            ["ru-RU"] = new[] { "Автоприменение магии", "Включено", "Выключено", "{0}: переключить автоприменение", "Применяет магию только в бою с обычным расходом маны и зарядов. Автонаведение предпочитает закреплённую цель, иначе выбирает ближайшего видимого врага без препятствий; без цели ждёт. При выключенном автонаведении использует текущее прицеливание. В меню приостанавливается. Следует за артефактом при смене привязки; сбрасывается при его потере, смене персонажа или перезагрузке мира. Клавиша паузы / возобновления приостанавливает всё автоприменение, сохраняя выбранную магию.", "Нет подходящей магии", "Приостановить / возобновить автоприменение", "Приостановлено", "Автоприменение магии приостановлено", "Автоприменение магии возобновлено", "Сначала выберите магию для автоприменения в рюкзаке или настройках клавиш." },
            ["sv-SE"] = new[] { "Automatisk magi", "På", "Av", "{0}: växla automatisk magi", "Använder magi endast i strid med normal förbrukning av mana och laddningar. Automatisk målsökning prioriterar det låsta målet, annars en närliggande synlig fiende utan hinder; väntar om inget mål finns. När målsökningen är avstängd används nuvarande sikte. Pausar i menyer. Följer artefakten vid ombindning; rensas när den förloras, karaktären byts eller världen laddas om. Genvägen för paus / återupptagning pausar all automatisk magi och behåller dina val.", "Ingen kompatibel magi", "Pausa / återuppta automatisk magi", "Pausad", "Automatisk magi pausad", "Automatisk magi återupptagen", "Välj först magi för automatisk användning i ryggsäcken eller tangentinställningarna." },
            ["th-TH"] = new[] { "ร่ายเวทอัตโนมัติ", "เปิด", "ปิด", "{0}: สลับการร่ายเวทอัตโนมัติ", "ร่ายเวทอัตโนมัติเฉพาะขณะต่อสู้ ใช้มานาและจำนวนครั้งตามปกติ เมื่อเปิดเล็งอัตโนมัติจะเลือกเป้าหมายที่ล็อกไว้ก่อน หากไม่มีจะเลือกศัตรูใกล้เคียงที่มองเห็นและไม่มีสิ่งกีดขวาง และรอเมื่อไม่มีเป้าหมาย เมื่อปิดเล็งอัตโนมัติจะใช้ทิศเล็งปัจจุบัน หยุดในเมนู การตั้งค่าจะตามสิ่งประดิษฐ์นี้เมื่อเปลี่ยนปุ่ม และจะล้างเมื่อเสียสิ่งประดิษฐ์ เปลี่ยนตัวละคร หรือโหลดโลกใหม่ ใช้ปุ่มพัก / ร่ายต่อเพื่อพักการร่ายเวทอัตโนมัติทั้งหมดโดยเก็บเวทที่เลือกไว้", "ไม่มีเวทที่รองรับ", "พัก / ร่ายเวทอัตโนมัติต่อ", "พักอยู่", "พักการร่ายเวทอัตโนมัติแล้ว", "ร่ายเวทอัตโนมัติต่อแล้ว", "เลือกเวทที่จะร่ายอัตโนมัติในกระเป๋าหรือการตั้งค่าปุ่มก่อน" },
            ["tr-TR"] = new[] { "Otomatik büyü", "Açık", "Kapalı", "{0}: otomatik büyüyü değiştir", "Yalnızca savaşta büyü kullanır; normal mana ve kullanım hakkı harcar. Otomatik hedefleme kilitli hedefe öncelik verir, yoksa yakındaki görünür ve engelsiz bir düşmanı seçer; hedef yoksa bekler. Hedefleme kapalıyken mevcut nişanı kullanır. Menülerde durur. Tuş değişince eseri takip eder; eser kaybolduğunda, karakter değiştiğinde veya dünya yeniden yüklendiğinde temizlenir. Duraklatma / sürdürme kısayolu, seçimlerini koruyarak tüm otomatik büyüleri duraklatır.", "Uygun büyü yok", "Otomatik büyüyü duraklat / sürdür", "Duraklatıldı", "Otomatik büyü duraklatıldı", "Otomatik büyü sürdürüldü", "Önce çantadan veya tuş ayarlarından otomatik kullanılacak büyüyü seç." }
        };
        internal static void Register(Action<string, string, string> addText, IEnumerable<string> languages) =>
            LocalizationGroup.Register(addText, languages, Keys, Texts);
    }
}
