using System.Collections.Generic;

namespace SephiriaEnhancements.MultiplayerRules.Presentation
{
    internal static partial class MultiplayerRulesLocalization
    {
        internal const string PanelTitle = "SephiriaEnhancements.MultiplayerRules.Panel.Title";
        internal const string PanelEditing = "SephiriaEnhancements.MultiplayerRules.Panel.Editing";
        internal const string PanelReadOnly = "SephiriaEnhancements.MultiplayerRules.Panel.ReadOnly";
        internal const string PanelSave = "SephiriaEnhancements.MultiplayerRules.Panel.Save";
        internal const string PanelResetGroup = "SephiriaEnhancements.MultiplayerRules.Panel.ResetGroup";
        internal const string PanelDiscard = "SephiriaEnhancements.MultiplayerRules.Panel.Discard";
        internal const string HostRulesUnavailable = "SephiriaEnhancements.MultiplayerRules.Panel.Unavailable";
        internal const string PanelReference = "SephiriaEnhancements.MultiplayerRules.Panel.Reference";
        internal const string PanelEntryHelp = "SephiriaEnhancements.MultiplayerRules.Panel.EntryHelp";
        internal const string PanelHealthExample = "SephiriaEnhancements.MultiplayerRules.Panel.HealthExample";
        internal const string PanelDamageExample = "SephiriaEnhancements.MultiplayerRules.Panel.DamageExample";
        internal const string PanelTeamHeading = "SephiriaEnhancements.MultiplayerRules.Panel.TeamHeading";
        internal const string PanelTeamChanged = "SephiriaEnhancements.MultiplayerRules.Panel.TeamChanged";
        internal const string TeamUnsupported = "SephiriaEnhancements.MultiplayerRules.Panel.TeamUnsupported";
        private static readonly string[] PanelKeys = { PanelTitle, PanelEditing, PanelReadOnly, PanelSave,
            PanelResetGroup, PanelDiscard, HostRulesUnavailable, PanelReference, PanelEntryHelp, PanelHealthExample, PanelDamageExample, PanelTeamHeading, PanelTeamChanged, TeamUnsupported };
        private static readonly Dictionary<string, string[]> PanelTexts = new()
        {
            ["en-US"] = new[] { "Team rules", "Editing · save before departure", "Host rules · read only", "Save and close", "Reset this group", "Discard and close", "The host has not shared rules. Both players need a supported Mod version.", "Original player scaling: {0}\nAfter adjustment: {1}", "The host can edit in the lobby before departure. Saved rules are reused for future explorations. During exploration, everyone can inspect the current rules.", "Example only: base HP 100, other HP bonuses +50% → {0} HP. Actual HP depends on the enemy and floor.", "Example only: base damage 100 → {0}, before other damage modifiers.", "Team rules · {0} players", "Team size changed. Edits are kept; review the current team to continue.", "Custom rules support 1–4 connected players." },
            ["zh-CN"] = new[] { "队伍规则", "编辑中 · 出发前保存", "房主规则 · 只读", "保存并关闭", "恢复本组原版", "放弃修改并关闭", "房主尚未提供规则。请确认双方已安装支持此功能的 Mod 版本。", "原版人数效果：{0}\n调整后：{1}", "房主可在大厅出发前修改；保存后用于以后的探索。探索中所有人都可查看当前规则。", "仅作示例：基础生命 100，其他生命加成 +50% → {0} 生命。实际生命取决于敌人和楼层。", "仅作示例：基础伤害 100 → {0}，尚未计算其他伤害加成。", "队伍规则 · 当前 {0} 人", "队伍人数已变化，修改已保留。请查看当前人数后继续。", "自定义规则支持 1–4 名已连接玩家。" },
            ["zh-TW"] = new[] { "隊伍規則", "編輯中 · 出發前儲存", "房主規則 · 唯讀", "儲存並關閉", "恢復本組原版", "放棄修改並關閉", "房主尚未提供規則。請確認雙方已安裝支援此功能的 Mod 版本。", "原版人數效果：{0}\n調整後：{1}", "房主可在大廳出發前修改；儲存後用於以後的探索。探索中所有人都可查看目前規則。", "僅作範例：基礎生命 100，其他生命加成 +50% → {0} 生命。實際生命取決於敵人和樓層。", "僅作範例：基礎傷害 100 → {0}，尚未計算其他傷害加成。", "隊伍規則 · 目前 {0} 人", "隊伍人數已變化，修改已保留。請查看目前人數後繼續。", "自訂規則支援 1–4 名已連線玩家。" },
            ["ja-JP"] = new[] { "チームルール", "編集中・出発前に保存", "ホストのルール・閲覧のみ", "保存して閉じる", "この分類を標準に戻す", "変更を破棄して閉じる", "ホストのルールがありません。双方で対応するModを使用してください。", "標準の人数補正：{0}\n調整後：{1}", "ホストは出発前のロビーで編集できます。保存した設定は今後の探索でも使われます。探索中は全員がルールを確認できます。", "計算例：基本HP 100、その他のHP補正 +50% → HP {0}。実際は敵と階層により変わります。", "計算例：基本ダメージ100 → {0}。他の補正は含みません。", "チームルール・現在{0}人", "人数が変わりました。変更は保持されています。現在の人数を確認して続けてください。", "カスタムルールは接続中の1～4人に対応します。" },
            ["ko-KR"] = new[] { "팀 규칙", "편집 중 · 출발 전에 저장", "호스트 규칙 · 읽기 전용", "저장 후 닫기", "이 그룹 기본값 복원", "변경 취소 후 닫기", "호스트가 규칙을 제공하지 않았습니다. 양쪽 모두 지원되는 Mod 버전이 필요합니다.", "기본 인원 보정: {0}\n조정 후: {1}", "호스트는 출발 전 로비에서 수정할 수 있습니다. 저장한 규칙은 이후 탐험에도 사용됩니다. 탐험 중에는 모두 현재 규칙을 볼 수 있습니다.", "계산 예시: 기본 체력 100, 기타 체력 보너스 +50% → 체력 {0}. 실제 값은 적과 층에 따라 다릅니다.", "계산 예시: 기본 피해 100 → {0}. 다른 피해 보정은 제외합니다.", "팀 규칙 · 현재 {0}명", "인원이 바뀌었습니다. 변경 사항은 유지됩니다. 현재 인원을 확인하고 계속하세요.", "사용자 규칙은 연결된 플레이어 1–4명을 지원합니다." },
            ["de-DE"] = new[] { "Teamregeln", "Bearbeitung · vor Abreise speichern", "Hostregeln · nur lesen", "Speichern und schließen", "Diese Gruppe zurücksetzen", "Verwerfen und schließen", "Der Host teilt keine Regeln. Beide Spieler benötigen eine unterstützte Mod-Version.", "Originale Spieleranpassung: {0}\nNach Anpassung: {1}", "Der Host bearbeitet Regeln vor Abreise in der Lobby. Gespeicherte Regeln gelten auch für spätere Erkundungen. Während der Erkundung können alle die Regeln ansehen.", "Nur Beispiel: Basis-LP 100, andere LP-Boni +50% → {0} LP. Tatsächliche LP hängen von Gegner und Ebene ab.", "Nur Beispiel: Basisschaden 100 → {0}, ohne weitere Schadensmodifikatoren.", "Teamregeln · {0} Spieler", "Teamgröße geändert. Änderungen bleiben erhalten. Aktuelles Team prüfen, um fortzufahren.", "Eigene Regeln unterstützen 1–4 verbundene Spieler." },
            ["fr-FR"] = new[] { "Règles d’équipe", "Édition · enregistrer avant le départ", "Règles de l’hôte · lecture seule", "Enregistrer et fermer", "Rétablir ce groupe", "Abandonner et fermer", "L’hôte ne partage pas ses règles. Les deux joueurs doivent utiliser une version compatible du Mod.", "Ajustement d’origine par effectif : {0}\nAprès modification : {1}", "L’hôte modifie les règles au salon avant le départ. Elles sont conservées pour les explorations futures. Tous peuvent les consulter pendant l’exploration.", "Exemple : PV de base 100, autres bonus de PV +50% → {0} PV. Le résultat réel dépend de l’ennemi et de l’étage.", "Exemple : dégâts de base 100 → {0}, avant les autres modificateurs.", "Règles d’équipe · {0} joueurs", "L’effectif a changé. Vos modifications sont conservées. Vérifiez l’effectif actuel pour continuer.", "Les règles personnalisées prennent en charge 1 à 4 joueurs connectés." },
            ["es-ES"] = new[] { "Reglas del equipo", "Editando · guardar antes de salir", "Reglas del anfitrión · solo lectura", "Guardar y cerrar", "Restablecer este grupo", "Descartar y cerrar", "El anfitrión no ha compartido reglas. Ambos jugadores necesitan una versión compatible del Mod.", "Ajuste original por jugadores: {0}\nTras el ajuste: {1}", "El anfitrión edita en la sala antes de salir. Las reglas guardadas se reutilizan en futuras exploraciones. Todos pueden consultarlas al explorar.", "Solo ejemplo: vida base 100, otras bonificaciones +50% → {0} de vida. La vida real depende del enemigo y el piso.", "Solo ejemplo: daño base 100 → {0}, antes de otros modificadores.", "Reglas del equipo · {0} jugadores", "Cambió el equipo. Se conservan los cambios. Revisa el equipo actual para continuar.", "Las reglas personalizadas admiten de 1 a 4 jugadores conectados." },
            ["it-IT"] = new[] { "Regole della squadra", "Modifica · salva prima di partire", "Regole dell’host · sola lettura", "Salva e chiudi", "Ripristina questo gruppo", "Scarta e chiudi", "L’host non ha condiviso regole. Entrambi i giocatori devono usare una versione supportata del Mod.", "Adattamento originale ai giocatori: {0}\nDopo la modifica: {1}", "L’host modifica le regole nella lobby prima di partire. Le regole salvate valgono anche per le esplorazioni future. Tutti possono consultarle durante l’esplorazione.", "Solo esempio: PV base 100, altri bonus PV +50% → {0} PV. I PV effettivi dipendono dal nemico e dal piano.", "Solo esempio: danno base 100 → {0}, prima degli altri modificatori.", "Regole squadra · {0} giocatori", "La squadra è cambiata. Le modifiche sono conservate. Controlla la squadra attuale per continuare.", "Le regole personalizzate supportano da 1 a 4 giocatori connessi." },
            ["pt-BR"] = new[] { "Regras da equipe", "Editando · salve antes de partir", "Regras do anfitrião · só leitura", "Salvar e fechar", "Restaurar este grupo", "Descartar e fechar", "O anfitrião não compartilhou regras. Ambos os jogadores precisam de uma versão compatível do Mod.", "Ajuste original por jogadores: {0}\nApós o ajuste: {1}", "O anfitrião edita no lobby antes de sair. Regras salvas são reutilizadas em explorações futuras. Todos podem consultá-las durante a exploração.", "Apenas exemplo: vida base 100, outros bônus +50% → {0} de vida. A vida real depende do inimigo e do andar.", "Apenas exemplo: dano base 100 → {0}, antes de outros modificadores.", "Regras da equipe · {0} jogadores", "A equipe mudou. As alterações foram mantidas. Revise a equipe atual para continuar.", "Regras personalizadas aceitam de 1 a 4 jogadores conectados." },
            ["pl-PL"] = new[] { "Reguły drużyny", "Edycja · zapisz przed wyruszeniem", "Reguły hosta · tylko odczyt", "Zapisz i zamknij", "Przywróć tę grupę", "Odrzuć i zamknij", "Gospodarz nie udostępnił reguł. Obaj gracze potrzebują obsługiwanej wersji moda.", "Oryginalna korekta liczby graczy: {0}\nPo zmianie: {1}", "Gospodarz edytuje reguły w lobby przed wyjściem. Zapisane reguły obowiązują też w kolejnych wyprawach. Wszyscy mogą je przeglądać podczas wyprawy.", "Przykład: bazowe PŻ 100, inne premie +50% → {0} PŻ. Rzeczywiste PŻ zależą od wroga i piętra.", "Przykład: bazowe obrażenia 100 → {0}, przed innymi modyfikatorami.", "Reguły drużyny · {0} graczy", "Skład drużyny się zmienił. Zmiany zachowano. Sprawdź bieżący skład, aby kontynuować.", "Własne reguły obsługują 1–4 połączonych graczy." },
            ["ru-RU"] = new[] { "Правила команды", "Редактирование · сохраните до выхода", "Правила хоста · только чтение", "Сохранить и закрыть", "Сбросить эту группу", "Отменить и закрыть", "Хост не предоставил правила. Обоим игрокам нужна поддерживаемая версия Mod.", "Исходная поправка на число игроков: {0}\nПосле изменения: {1}", "Хост меняет правила в лобби до выхода. Сохранённые правила используются и в будущих исследованиях. Во время исследования все могут их просматривать.", "Пример: базовое HP 100, другие бонусы HP +50% → {0} HP. Реальное HP зависит от врага и этажа.", "Пример: базовый урон 100 → {0}, без других модификаторов.", "Правила команды · {0} игроков", "Состав команды изменился. Правки сохранены в редакторе. Проверьте текущий состав, чтобы продолжить.", "Свои правила поддерживают от 1 до 4 подключённых игроков." },
            ["sv-SE"] = new[] { "Lagregler", "Redigerar · spara före avfärd", "Värdens regler · skrivskyddat", "Spara och stäng", "Återställ denna grupp", "Kasta ändringar och stäng", "Värden har inte delat regler. Båda spelarna behöver en stödd Mod-version.", "Ursprunglig spelaranpassning: {0}\nEfter justering: {1}", "Värden redigerar i lobbyn före avfärd. Sparade regler återanvänds vid kommande utforskningar. Alla kan läsa dem under utforskningen.", "Endast exempel: bas-HP 100, andra HP-bonusar +50% → {0} HP. Faktiskt HP beror på fiende och våning.", "Endast exempel: basskada 100 → {0}, före andra modifierare.", "Lagregler · {0} spelare", "Laget har ändrats. Ändringarna finns kvar. Granska aktuellt lag för att fortsätta.", "Egna regler stöder 1–4 anslutna spelare." },
            ["tr-TR"] = new[] { "Takım kuralları", "Düzenleniyor · ayrılmadan kaydedin", "Ev sahibinin kuralları · salt okunur", "Kaydet ve kapat", "Bu grubu sıfırla", "Vazgeç ve kapat", "Ev sahibi kuralları paylaşmadı. İki oyuncunun da desteklenen Mod sürümü gerekir.", "Özgün oyuncu sayısı ayarı: {0}\nAyarlamadan sonra: {1}", "Ev sahibi ayrılmadan önce lobide düzenler. Kaydedilen kurallar sonraki keşiflerde de kullanılır. Keşifte herkes kuralları görebilir.", "Yalnızca örnek: temel can 100, diğer can bonusları +50% → {0} can. Gerçek can düşmana ve kata bağlıdır.", "Yalnızca örnek: temel hasar 100 → {0}, diğer değiştiricilerden önce.", "Takım kuralları · {0} oyuncu", "Takım değişti. Düzenlemeler korundu. Devam etmek için mevcut takımı inceleyin.", "Özel kurallar 1–4 bağlı oyuncuyu destekler." },
            ["th-TH"] = new[] { "กฎของทีม", "กำลังแก้ไข · บันทึกก่อนออกเดินทาง", "กฎของโฮสต์ · อ่านอย่างเดียว", "บันทึกแล้วปิด", "คืนค่าเดิมของกลุ่มนี้", "ทิ้งการแก้ไขแล้วปิด", "โฮสต์ยังไม่ได้แชร์กฎ ทั้งสองฝ่ายต้องใช้ Mod รุ่นที่รองรับ", "การปรับตามจำนวนคนแบบเดิม: {0}\nหลังปรับ: {1}", "โฮสต์แก้กฎในล็อบบี้ก่อนออกเดินทาง กฎที่บันทึกจะใช้ในการสำรวจครั้งต่อไปด้วย ทุกคนดูกฎได้ระหว่างสำรวจ", "ตัวอย่างเท่านั้น: HP พื้นฐาน 100 โบนัส HP อื่น +50% → {0} HP ค่าจริงขึ้นอยู่กับศัตรูและชั้น", "ตัวอย่างเท่านั้น: ความเสียหายพื้นฐาน 100 → {0} ยังไม่รวมตัวปรับอื่น", "กฎทีม · ผู้เล่น {0} คน", "จำนวนคนในทีมเปลี่ยนแล้ว การแก้ไขยังอยู่ โปรดตรวจสอบทีมปัจจุบันก่อนดำเนินการต่อ", "กฎกำหนดเองรองรับผู้เล่นที่เชื่อมต่อ 1–4 คน" },
        };
    }
}
