using System.Collections.Generic;

namespace SephiriaEnhancements.MultiplayerRules.Presentation
{
    internal static partial class MultiplayerRulesLocalization
    {
        internal const string LobbyTitle = "SephiriaEnhancements.MultiplayerRules.Lobby.Title";
        internal const string LobbyDraft = "SephiriaEnhancements.MultiplayerRules.Lobby.Draft";
        internal const string LobbyReadOnly = "SephiriaEnhancements.MultiplayerRules.Lobby.ReadOnly";
        internal const string LobbyApply = "SephiriaEnhancements.MultiplayerRules.Lobby.Apply";
        internal const string LobbyRestore = "SephiriaEnhancements.MultiplayerRules.Lobby.Restore";
        internal const string LobbyCancel = "SephiriaEnhancements.MultiplayerRules.Lobby.Cancel";
        internal const string LobbyUnavailable = "SephiriaEnhancements.MultiplayerRules.Lobby.Unavailable";
        internal const string LobbyReference = "SephiriaEnhancements.MultiplayerRules.Lobby.Reference";
        internal const string LobbyEntryHelp = "SephiriaEnhancements.MultiplayerRules.Lobby.EntryHelp";
        internal const string LobbyHealthExample = "SephiriaEnhancements.MultiplayerRules.Lobby.HealthExample";
        internal const string LobbyDamageExample = "SephiriaEnhancements.MultiplayerRules.Lobby.DamageExample";
        internal const string LobbyTeamHeading = "SephiriaEnhancements.MultiplayerRules.Lobby.TeamHeading";
        internal const string LobbyTeamChanged = "SephiriaEnhancements.MultiplayerRules.Lobby.TeamChanged";
        internal const string LobbyTeamUnsupported = "SephiriaEnhancements.MultiplayerRules.Lobby.TeamUnsupported";
        private static readonly string[] LobbyKeys = { LobbyTitle, LobbyDraft, LobbyReadOnly, LobbyApply,
            LobbyRestore, LobbyCancel, LobbyUnavailable, LobbyReference, LobbyEntryHelp, LobbyHealthExample, LobbyDamageExample, LobbyTeamHeading, LobbyTeamChanged, LobbyTeamUnsupported };
        private static readonly Dictionary<string, string[]> LobbyTexts = new()
        {
            ["en-US"] = new[] { "Team rules", "Draft · apply before leaving", "Host rules · read only", "Apply and close", "Reset current {0}-player rules", "Close without applying", "Host rules are unavailable on this connection. Local preferences are not shown as host rules.", "Original player scaling: {0}\nAfter adjustment: {1}", "Open in the multiplayer lobby. The host edits a draft and applies it before departure; exploration locks the rules.", "Example only: base HP 100, other HP bonuses +50% → {0} HP. Actual HP depends on the enemy and floor.", "Example only: base damage 100 → {0}, before other damage modifiers.", "Team rules · {0} players", "Team size changed. Review before applying.", "Custom rules support 1–4 connected players." },
            ["zh-CN"] = new[] { "队伍规则", "草稿 · 出发前应用", "房主规则 · 只读", "应用并关闭", "恢复当前 {0} 人的原版规则", "关闭，不应用", "当前连接无法读取房主规则。不会用本机偏好代替房主设置。", "原版人数效果：{0}\n调整后：{1}", "在联机大厅打开。房主编辑草稿，出发前统一应用；开始探索后锁定规则。", "仅作示例：基础生命 100，其他生命加成 +50% → {0} 生命。实际生命取决于敌人和楼层。", "仅作示例：基础伤害 100 → {0}，尚未计算其他伤害加成。", "队伍规则 · 当前 {0} 人", "队伍人数已变化，请查看当前调整后再应用。", "自定义规则支持 1–4 名已连接玩家。" },
            ["zh-TW"] = new[] { "隊伍規則", "草稿 · 出發前套用", "房主規則 · 唯讀", "套用並關閉", "恢復目前 {0} 人的原版規則", "關閉，不套用", "目前連線無法讀取房主規則。不會以本機偏好取代房主設定。", "原版人數效果：{0}\n調整後：{1}", "在連線大廳開啟。房主編輯草稿，出發前統一套用；開始探索後鎖定規則。", "僅作範例：基礎生命 100，其他生命加成 +50% → {0} 生命。實際生命取決於敵人和樓層。", "僅作範例：基礎傷害 100 → {0}，尚未計算其他傷害加成。", "隊伍規則 · 目前 {0} 人", "隊伍人數已變化，請查看目前調整後再套用。", "自訂規則支援 1–4 名已連線玩家。" },
            ["ja-JP"] = new[] { "チームルール", "下書き・出発前に適用", "ホストのルール・閲覧のみ", "適用して閉じる", "現在の{0}人のルールを標準に戻す", "適用せず閉じる", "この接続ではホストのルールを取得できません。ローカル設定で代用しません。", "標準の人数補正：{0}\n調整後：{1}", "マルチプレイロビーで開きます。ホストが下書きを編集して出発前に適用。探索開始後は固定されます。", "計算例：基本HP 100、その他のHP補正 +50% → HP {0}。実際は敵と階層により変わります。", "計算例：基本ダメージ100 → {0}。他の補正は含みません。", "チームルール・現在{0}人", "人数が変わりました。変更を確認して適用してください。", "カスタムルールは接続中の1～4人に対応します。" },
            ["ko-KR"] = new[] { "팀 규칙", "초안 · 출발 전에 적용", "호스트 규칙 · 읽기 전용", "적용 후 닫기", "현재 {0}인 기본 규칙 복원", "적용하지 않고 닫기", "이 연결에서 호스트 규칙을 읽을 수 없습니다. 로컬 설정으로 대체하지 않습니다.", "기본 인원 보정: {0}\n조정 후: {1}", "멀티플레이 로비에서 엽니다. 호스트가 초안을 편집하고 출발 전에 적용합니다. 탐험이 시작되면 잠깁니다.", "계산 예시: 기본 체력 100, 기타 체력 보너스 +50% → 체력 {0}. 실제 값은 적과 층에 따라 다릅니다.", "계산 예시: 기본 피해 100 → {0}. 다른 피해 보정은 제외합니다.", "팀 규칙 · 현재 {0}명", "인원이 변경되었습니다. 조정을 확인한 뒤 적용하세요.", "사용자 규칙은 연결된 플레이어 1–4명을 지원합니다." },
            ["de-DE"] = new[] { "Teamregeln", "Entwurf · vor Abreise anwenden", "Hostregeln · nur lesen", "Anwenden und schließen", "Regeln für aktuell {0} Spieler zurücksetzen", "Ohne Anwenden schließen", "Hostregeln sind über diese Verbindung nicht verfügbar. Lokale Einstellungen werden nicht als Hostregeln angezeigt.", "Originale Spieleranpassung: {0}\nNach Anpassung: {1}", "In der Mehrspielerlobby öffnen. Der Host bearbeitet einen Entwurf und wendet ihn vor Abreise an. Die Erkundung sperrt die Regeln.", "Nur Beispiel: Basis-LP 100, andere LP-Boni +50% → {0} LP. Tatsächliche LP hängen von Gegner und Ebene ab.", "Nur Beispiel: Basisschaden 100 → {0}, ohne weitere Schadensmodifikatoren.", "Teamregeln · {0} Spieler", "Teamgröße geändert. Vor dem Anwenden prüfen.", "Eigene Regeln unterstützen 1–4 verbundene Spieler." },
            ["fr-FR"] = new[] { "Règles d’équipe", "Brouillon · appliquer avant de partir", "Règles de l’hôte · lecture seule", "Appliquer et fermer", "Rétablir les règles pour {0} joueurs", "Fermer sans appliquer", "Les règles de l’hôte sont indisponibles avec cette connexion. Les préférences locales ne les remplacent pas.", "Ajustement d’origine par effectif : {0}\nAprès modification : {1}", "À ouvrir dans le salon multijoueur. L’hôte modifie un brouillon puis l’applique avant le départ. L’exploration verrouille les règles.", "Exemple : PV de base 100, autres bonus de PV +50% → {0} PV. Le résultat réel dépend de l’ennemi et de l’étage.", "Exemple : dégâts de base 100 → {0}, avant les autres modificateurs.", "Règles d’équipe · {0} joueurs", "L’effectif a changé. Vérifiez avant d’appliquer.", "Les règles personnalisées prennent en charge 1 à 4 joueurs connectés." },
            ["es-ES"] = new[] { "Reglas del equipo", "Borrador · aplicar antes de salir", "Reglas del anfitrión · solo lectura", "Aplicar y cerrar", "Restablecer reglas para {0} jugadores", "Cerrar sin aplicar", "No se pueden leer las reglas del anfitrión en esta conexión. No se sustituyen por las preferencias locales.", "Ajuste original por jugadores: {0}\nTras el ajuste: {1}", "Abre en la sala multijugador. El anfitrión edita un borrador y lo aplica antes de salir. Las reglas se bloquean al explorar.", "Solo ejemplo: vida base 100, otras bonificaciones +50% → {0} de vida. La vida real depende del enemigo y el piso.", "Solo ejemplo: daño base 100 → {0}, antes de otros modificadores.", "Reglas del equipo · {0} jugadores", "Cambió el número de jugadores. Revisa antes de aplicar.", "Las reglas personalizadas admiten de 1 a 4 jugadores conectados." },
            ["it-IT"] = new[] { "Regole della squadra", "Bozza · applica prima di partire", "Regole dell’host · sola lettura", "Applica e chiudi", "Ripristina regole per {0} giocatori", "Chiudi senza applicare", "Le regole dell’host non sono disponibili su questa connessione. Le preferenze locali non le sostituiscono.", "Adattamento originale ai giocatori: {0}\nDopo la modifica: {1}", "Apri nella lobby multigiocatore. L’host modifica una bozza e la applica prima di partire. L’esplorazione blocca le regole.", "Solo esempio: PV base 100, altri bonus PV +50% → {0} PV. I PV effettivi dipendono dal nemico e dal piano.", "Solo esempio: danno base 100 → {0}, prima degli altri modificatori.", "Regole squadra · {0} giocatori", "Il numero di giocatori è cambiato. Controlla prima di applicare.", "Le regole personalizzate supportano da 1 a 4 giocatori connessi." },
            ["pt-BR"] = new[] { "Regras da equipe", "Rascunho · aplique antes de partir", "Regras do anfitrião · só leitura", "Aplicar e fechar", "Restaurar regras para {0} jogadores", "Fechar sem aplicar", "As regras do anfitrião não estão disponíveis nesta conexão. As preferências locais não as substituem.", "Ajuste original por jogadores: {0}\nApós o ajuste: {1}", "Abra no lobby multijogador. O anfitrião edita um rascunho e aplica antes de partir. A exploração bloqueia as regras.", "Apenas exemplo: vida base 100, outros bônus +50% → {0} de vida. A vida real depende do inimigo e do andar.", "Apenas exemplo: dano base 100 → {0}, antes de outros modificadores.", "Regras da equipe · {0} jogadores", "A quantidade de jogadores mudou. Confira antes de aplicar.", "Regras personalizadas aceitam de 1 a 4 jogadores conectados." },
            ["pl-PL"] = new[] { "Reguły drużyny", "Szkic · zastosuj przed wyjściem", "Reguły hosta · tylko odczyt", "Zastosuj i zamknij", "Przywróć reguły dla {0} graczy", "Zamknij bez zastosowania", "Reguły hosta są niedostępne w tym połączeniu. Lokalne ustawienia ich nie zastępują.", "Oryginalna korekta liczby graczy: {0}\nPo zmianie: {1}", "Otwórz w lobby. Host edytuje szkic i stosuje go przed wyjściem. Rozpoczęcie eksploracji blokuje reguły.", "Przykład: bazowe PŻ 100, inne premie +50% → {0} PŻ. Rzeczywiste PŻ zależą od wroga i piętra.", "Przykład: bazowe obrażenia 100 → {0}, przed innymi modyfikatorami.", "Reguły drużyny · {0} graczy", "Liczba graczy się zmieniła. Sprawdź przed zastosowaniem.", "Własne reguły obsługują 1–4 połączonych graczy." },
            ["ru-RU"] = new[] { "Правила команды", "Черновик · применить до выхода", "Правила хоста · только чтение", "Применить и закрыть", "Сбросить правила для {0} игроков", "Закрыть без применения", "Правила хоста недоступны при этом подключении. Локальные настройки не заменяют их.", "Исходная поправка на число игроков: {0}\nПосле изменения: {1}", "Открывается в сетевом лобби. Хост редактирует черновик и применяет его до выхода. Начало исследования блокирует правила.", "Пример: базовое HP 100, другие бонусы HP +50% → {0} HP. Реальное HP зависит от врага и этажа.", "Пример: базовый урон 100 → {0}, без других модификаторов.", "Правила команды · {0} игроков", "Число игроков изменилось. Проверьте изменения перед применением.", "Свои правила поддерживают от 1 до 4 подключённых игроков." },
            ["sv-SE"] = new[] { "Lagregler", "Utkast · tillämpa före avfärd", "Värdens regler · skrivskyddat", "Tillämpa och stäng", "Återställ regler för {0} spelare", "Stäng utan att tillämpa", "Värdens regler är inte tillgängliga på denna anslutning. Lokala inställningar ersätter dem inte.", "Ursprunglig spelaranpassning: {0}\nEfter justering: {1}", "Öppna i flerspelarlobbyn. Värden redigerar ett utkast och tillämpar det före avfärd. Utforskningen låser reglerna.", "Endast exempel: bas-HP 100, andra HP-bonusar +50% → {0} HP. Faktiskt HP beror på fiende och våning.", "Endast exempel: basskada 100 → {0}, före andra modifierare.", "Lagregler · {0} spelare", "Spelarantalet har ändrats. Granska innan du tillämpar.", "Egna regler stöder 1–4 anslutna spelare." },
            ["tr-TR"] = new[] { "Takım kuralları", "Taslak · ayrılmadan önce uygula", "Ev sahibinin kuralları · salt okunur", "Uygula ve kapat", "{0} oyuncu için kuralları sıfırla", "Uygulamadan kapat", "Bu bağlantıda ev sahibinin kuralları okunamıyor. Yerel tercihler onların yerine gösterilmez.", "Özgün oyuncu sayısı ayarı: {0}\nAyarlamadan sonra: {1}", "Çok oyunculu lobide açılır. Ev sahibi taslağı düzenleyip ayrılmadan önce uygular. Keşif başladığında kurallar kilitlenir.", "Yalnızca örnek: temel can 100, diğer can bonusları +50% → {0} can. Gerçek can düşmana ve kata bağlıdır.", "Yalnızca örnek: temel hasar 100 → {0}, diğer değiştiricilerden önce.", "Takım kuralları · {0} oyuncu", "Oyuncu sayısı değişti. Uygulamadan önce gözden geçirin.", "Özel kurallar 1–4 bağlı oyuncuyu destekler." },
            ["th-TH"] = new[] { "กฎของทีม", "แบบร่าง · ใช้ก่อนออกเดินทาง", "กฎของโฮสต์ · อ่านอย่างเดียว", "ใช้แล้วปิด", "คืนกฎเดิมสำหรับ {0} คน", "ปิดโดยไม่ใช้", "ไม่สามารถอ่านกฎของโฮสต์ผ่านการเชื่อมต่อนี้ได้ จะไม่ใช้ค่าของเครื่องนี้แทน", "การปรับตามจำนวนคนแบบเดิม: {0}\nหลังปรับ: {1}", "เปิดในล็อบบี้ผู้เล่นหลายคน โฮสต์แก้แบบร่างแล้วใช้ก่อนออกเดินทาง กฎจะล็อกเมื่อเริ่มสำรวจ", "ตัวอย่างเท่านั้น: HP พื้นฐาน 100 โบนัส HP อื่น +50% → {0} HP ค่าจริงขึ้นอยู่กับศัตรูและชั้น", "ตัวอย่างเท่านั้น: ความเสียหายพื้นฐาน 100 → {0} ยังไม่รวมตัวปรับอื่น", "กฎทีม · ผู้เล่น {0} คน", "จำนวนผู้เล่นเปลี่ยนไป โปรดตรวจสอบก่อนใช้", "กฎกำหนดเองรองรับผู้เล่นที่เชื่อมต่อ 1–4 คน" },
        };
    }
}
