using System.Collections.Generic;
namespace SephiriaEnhancements.MultiplayerRules.Presentation
{
    internal static partial class MultiplayerRulesLocalization
    {
        internal const string EditAction = "SephiriaEnhancements.MultiplayerRules.EditAction";
        internal const string ReviewValues = "SephiriaEnhancements.MultiplayerRules.ReviewValues";
        internal const string ReviewChanges = "SephiriaEnhancements.MultiplayerRules.ReviewChanges";
        internal const string ReviewScope = "SephiriaEnhancements.MultiplayerRules.ReviewScope";
        internal const string InvalidNumber = "SephiriaEnhancements.MultiplayerRules.InvalidNumber";
        internal const string InvalidRange = "SephiriaEnhancements.MultiplayerRules.InvalidRange";
        internal const string InvalidStep = "SephiriaEnhancements.MultiplayerRules.InvalidStep";
        internal const string InputActions = "SephiriaEnhancements.MultiplayerRules.InputActions";
        internal const string InputSaved = "SephiriaEnhancements.MultiplayerRules.InputSaved";
        internal const string InputDefault = "SephiriaEnhancements.MultiplayerRules.InputDefault";
        private static readonly string[] ReviewKeys = { EditAction, ReviewValues, ReviewChanges, ReviewScope, InvalidNumber, InvalidRange, InvalidStep, InputActions, InputSaved, InputDefault };
        private static readonly Dictionary<string, string[]> ReviewTexts = new()
        {
            ["en-US"] = new[] { "Edit", "Original: {0}\nApplied: {1}\nDraft: {2}", "Unapplied changes: {0}", "Apply before departure. Numerical changes apply to the current {0}-player team; health-bonus handling is shared across team sizes. Closing discards unapplied changes.", "Enter a number.", "Allowed range: {0}–{1}.", "Use increments of {0}, starting at {1}.", "{0}: confirm · {1}: cancel\n{2}: next control · {3}+{2}: previous", "Confirm adds this value to the draft. Apply the draft before departure.", "An empty field restores this rule to game behavior in the draft." },
            ["zh-CN"] = new[] { "编辑", "原版：{0}\n已应用：{1}\n本次修改：{2}", "未应用修改：{0} 项", "出发前统一应用。数值修改适用于当前 {0} 人队伍；生命加成的叠加方式由各人数共用。关闭会丢弃未应用修改。", "请输入数字。", "允许范围：{0}–{1}。", "从 {1} 起，按 {0} 的间隔填写。", "{0}：确认 · {1}：取消\n{2}：下一控件 · {3}+{2}：上一控件", "确认后只写入本次修改，出发前还需应用。", "留空并确认，将此项恢复为原版；应用后生效。" },
            ["zh-TW"] = new[] { "編輯", "原版：{0}\n已套用：{1}\n本次修改：{2}", "未套用修改：{0} 項", "出發前統一套用。數值修改適用於目前 {0} 人隊伍；生命加成的疊加方式由各人數共用。關閉會捨棄未套用修改。", "請輸入數字。", "允許範圍：{0}–{1}。", "從 {1} 起，按 {0} 的間隔填寫。", "{0}：確認 · {1}：取消\n{2}：下一控制項 · {3}+{2}：上一控制項", "確認後僅寫入本次修改，出發前仍需套用。", "留空並確認，將此項恢復為原版；套用後生效。" },
            ["ja-JP"] = new[] { "編集", "標準：{0}\n適用済み：{1}\n変更後：{2}", "未適用の変更：{0}", "出発前に適用してください。数値は現在の{0}人用です。HP補正の計算方式は全人数で共通です。閉じると未適用の変更は破棄されます。", "数値を入力してください。", "範囲：{0}～{1}。", "{1}から{0}刻みで入力してください。", "{0}：決定 · {1}：取消\n{2}：次 · {3}+{2}：前", "決定で下書きに保存します。出発前に適用してください。", "空欄で決定すると、この項目を標準に戻す変更になります。" },
            ["ko-KR"] = new[] { "편집", "기본: {0}\n적용됨: {1}\n수정값: {2}", "미적용 변경: {0}", "출발 전에 적용하세요. 수치는 현재 {0}인 팀에 적용되며 체력 보너스 계산 방식은 모든 인원이 공유합니다. 닫으면 미적용 변경은 사라집니다.", "숫자를 입력하세요.", "허용 범위: {0}–{1}.", "{1}부터 {0} 간격으로 입력하세요.", "{0}: 확인 · {1}: 취소\n{2}: 다음 · {3}+{2}: 이전", "확인하면 초안에 저장됩니다. 출발 전에 적용하세요.", "비우고 확인하면 이 항목을 기본값으로 되돌리는 초안이 됩니다." },
            ["de-DE"] = new[] { "Bearbeiten", "Original: {0}\nAngewendet: {1}\nEntwurf: {2}", "Nicht angewendete Änderungen: {0}", "Vor Abreise anwenden. Zahlen gelten für aktuell {0} Spieler; die LP-Bonusberechnung gilt für alle Teamgrößen. Schließen verwirft nicht angewendete Änderungen.", "Eine Zahl eingeben.", "Bereich: {0}–{1}.", "Ab {1} in Schritten von {0}.", "{0}: bestätigen · {1}: abbrechen\n{2}: weiter · {3}+{2}: zurück", "Bestätigen speichert im Entwurf. Vor Abreise anwenden.", "Leere Eingabe setzt diese Regel im Entwurf auf das Spielverhalten zurück." },
            ["fr-FR"] = new[] { "Modifier", "Origine : {0}\nAppliqué : {1}\nBrouillon : {2}", "Modifications non appliquées : {0}", "Appliquez avant de partir. Les valeurs concernent les {0} joueurs actuels ; le calcul des bonus de PV est commun aux effectifs. Fermer abandonne les changements non appliqués.", "Saisissez un nombre.", "Plage : {0}–{1}.", "Par pas de {0}, à partir de {1}.", "{0} : valider · {1} : annuler\n{2} : suivant · {3}+{2} : précédent", "Valider modifie le brouillon. Appliquez avant de partir.", "Un champ vide rétablit cette règle d’origine dans le brouillon." },
            ["es-ES"] = new[] { "Editar", "Original: {0}\nAplicado: {1}\nBorrador: {2}", "Cambios sin aplicar: {0}", "Aplica antes de salir. Los valores afectan al equipo actual de {0}; el cálculo de bonificaciones de vida es común a todos los tamaños. Cerrar descarta los cambios pendientes.", "Introduce un número.", "Rango: {0}–{1}.", "Incrementos de {0} desde {1}.", "{0}: confirmar · {1}: cancelar\n{2}: siguiente · {3}+{2}: anterior", "Confirmar guarda en el borrador. Aplica antes de salir.", "El campo vacío restaura esta regla original en el borrador." },
            ["it-IT"] = new[] { "Modifica", "Originale: {0}\nApplicato: {1}\nBozza: {2}", "Modifiche non applicate: {0}", "Applica prima di partire. I valori riguardano gli attuali {0} giocatori; il calcolo dei bonus PV vale per ogni dimensione della squadra. Chiudere scarta le modifiche non applicate.", "Inserisci un numero.", "Intervallo: {0}–{1}.", "Passi di {0} a partire da {1}.", "{0}: conferma · {1}: annulla\n{2}: avanti · {3}+{2}: indietro", "Confermare aggiorna la bozza. Applica prima di partire.", "Il campo vuoto ripristina questa regola originale nella bozza." },
            ["pt-BR"] = new[] { "Editar", "Original: {0}\nAplicado: {1}\nRascunho: {2}", "Alterações não aplicadas: {0}", "Aplique antes de partir. Os valores afetam os {0} jogadores atuais; o cálculo dos bônus de vida vale para todos os tamanhos de equipe. Fechar descarta alterações pendentes.", "Digite um número.", "Intervalo: {0}–{1}.", "Passos de {0} a partir de {1}.", "{0}: confirmar · {1}: cancelar\n{2}: próximo · {3}+{2}: anterior", "Confirmar salva no rascunho. Aplique antes de partir.", "O campo vazio restaura esta regra original no rascunho." },
            ["pl-PL"] = new[] { "Edytuj", "Oryginał: {0}\nZastosowane: {1}\nSzkic: {2}", "Niezastosowane zmiany: {0}", "Zastosuj przed wyjściem. Liczby dotyczą obecnych {0} graczy; sposób liczenia premii PŻ jest wspólny dla wszystkich liczebności. Zamknięcie odrzuca niezastosowane zmiany.", "Wpisz liczbę.", "Zakres: {0}–{1}.", "Krok {0}, począwszy od {1}.", "{0}: zatwierdź · {1}: anuluj\n{2}: dalej · {3}+{2}: wstecz", "Zatwierdzenie zapisuje szkic. Zastosuj przed wyjściem.", "Puste pole przywraca oryginalną regułę w szkicu." },
            ["ru-RU"] = new[] { "Изменить", "Оригинал: {0}\nПрименено: {1}\nЧерновик: {2}", "Неприменённых изменений: {0}", "Примените до выхода. Числа относятся к текущим {0} игрокам; способ расчёта бонусов HP общий для всех размеров команды. Закрытие отменяет неприменённые изменения.", "Введите число.", "Диапазон: {0}–{1}.", "Шаг {0}, начиная с {1}.", "{0}: подтвердить · {1}: отменить\n{2}: далее · {3}+{2}: назад", "Подтверждение сохраняет в черновик. Примените до выхода.", "Пустое поле возвращает исходную настройку в черновике." },
            ["sv-SE"] = new[] { "Ändra", "Original: {0}\nTillämpat: {1}\nUtkast: {2}", "Ej tillämpade ändringar: {0}", "Tillämpa före avfärd. Tal gäller nuvarande {0} spelare; HP-bonusberäkningen delas av alla lagstorlekar. Stängning slänger ej tillämpade ändringar.", "Ange ett tal.", "Intervall: {0}–{1}.", "Steg om {0}, med början på {1}.", "{0}: bekräfta · {1}: avbryt\n{2}: nästa · {3}+{2}: föregående", "Bekräfta sparar i utkastet. Tillämpa före avfärd.", "Tomt fält återställer denna regel i utkastet." },
            ["tr-TR"] = new[] { "Düzenle", "Özgün: {0}\nUygulanan: {1}\nTaslak: {2}", "Uygulanmamış değişiklik: {0}", "Ayrılmadan önce uygulayın. Sayılar mevcut {0} oyuncuya aittir; can bonusu hesabı tüm takım boyutları için ortaktır. Kapatmak uygulanmamış değişiklikleri siler.", "Bir sayı girin.", "Aralık: {0}–{1}.", "{1} değerinden başlayarak {0} adımlarla girin.", "{0}: onayla · {1}: iptal\n{2}: sonraki · {3}+{2}: önceki", "Onaylamak taslağa kaydeder. Ayrılmadan önce uygulayın.", "Boş alan bu kuralı taslakta özgün davranışına döndürür." },
            ["th-TH"] = new[] { "แก้ไข", "ค่าเดิม: {0}\nใช้แล้ว: {1}\nแบบร่าง: {2}", "การเปลี่ยนแปลงที่ยังไม่ใช้: {0}", "ใช้ก่อนออกเดินทาง ตัวเลขมีผลกับทีมปัจจุบัน {0} คน วิธีคำนวณโบนัส HP ใช้ร่วมกันทุกขนาดทีม การปิดจะทิ้งการแก้ไขที่ยังไม่ใช้", "ป้อนตัวเลข", "ช่วงที่อนุญาต: {0}–{1}", "เพิ่มทีละ {0} โดยเริ่มจาก {1}", "{0}: ยืนยัน · {1}: ยกเลิก\n{2}: ถัดไป · {3}+{2}: ก่อนหน้า", "ยืนยันจะบันทึกในแบบร่าง ต้องใช้ก่อนออกเดินทาง", "เว้นว่างเพื่อคืนกฎเดิมในแบบร่าง" },
        };
    }
}
