using System.Collections.Generic;

namespace SephiriaEnhancements.MultiplayerRules.Presentation
{
    internal static partial class MultiplayerRulesLocalization
    {
        internal const string ParticipantsSetting = "SephiriaEnhancements.MultiplayerRules.ParticipantsSetting";
        internal const string ParticipantsValue = "SephiriaEnhancements.MultiplayerRules.ParticipantsValue";
        internal const string ParticipantsHelp = "SephiriaEnhancements.MultiplayerRules.ParticipantsHelp";
        internal const string ReviewTeamChange = "SephiriaEnhancements.MultiplayerRules.ReviewTeamChange";
        internal const string ReviewChangesAction = "SephiriaEnhancements.MultiplayerRules.ReviewChangesAction";
        internal const string AnnounceSummary = "SephiriaEnhancements.MultiplayerRules.AnnounceSummary";
        internal const string CloseAction = "SephiriaEnhancements.MultiplayerRules.CloseAction";
        internal const string StateExternal = "SephiriaEnhancements.MultiplayerRules.StateExternal";
        internal const string StateDisabled = "SephiriaEnhancements.MultiplayerRules.StateDisabled";
        internal const string StateUnavailable = "SephiriaEnhancements.MultiplayerRules.StateUnavailable";
        internal const string StateAvailable = "SephiriaEnhancements.MultiplayerRules.StateAvailable";
        internal const string StateWaiting = "SephiriaEnhancements.MultiplayerRules.StateWaiting";
        internal const string UseOriginalAction = "SephiriaEnhancements.MultiplayerRules.UseOriginalAction";
        internal const string ExperienceResult = "SephiriaEnhancements.MultiplayerRules.ExperienceResult";
        internal const string ReadOnlyValues = "SephiriaEnhancements.MultiplayerRules.ReadOnlyValues";
        private static readonly string[] StateKeys = { ParticipantsSetting, ParticipantsValue, ParticipantsHelp, ReviewTeamChange, ReviewChangesAction, AnnounceSummary, CloseAction, StateExternal, StateDisabled, StateUnavailable, StateAvailable, StateWaiting, UseOriginalAction, ExperienceResult, ReadOnlyValues };
        private static readonly Dictionary<string, string[]> StateTexts = new()
        {
            ["en-US"] = new[] { "Rules for", "{0} players", "Choose a player count to inspect or edit its rules. This does not change team size. Later spawns and rewards use the current team size.", "Review current team; keep edits", "Review changes", "Share current rules", "Close", "Another multiplayer extension controls these effects.", "The Mod is disabled; game rules apply.", "Custom rules are unavailable; game rules apply.", "Rules are chosen by team size. Exploration locks editing.", "Receiving host rules…", "Use game default", "Receive {0}% experience", "Original: {0}\nHost rule: {1}" },
            ["zh-CN"] = new[] { "适用人数", "{0} 人", "选择要查看或修改的人数规则，不会改变队伍人数。后续生成和奖励按当时人数使用规则。", "查看当前人数，保留修改", "查看全部修改", "发送当前规则摘要", "关闭", "当前由其他联机扩展控制这些效果。", "Mod 已关闭，使用游戏规则。", "自定义规则不可用，使用游戏规则。", "规则按队伍人数使用，探索中不可修改。", "正在接收房主规则…", "使用原版", "获得 {0}% 的经验", "原版：{0}\n房主规则：{1}" },
            ["zh-TW"] = new[] { "適用人數", "{0} 人", "選擇要查看或修改的人數規則，不會改變隊伍人數。後續生成和獎勵按當時人數使用規則。", "查看目前人數，保留修改", "查看全部修改", "傳送目前規則摘要", "關閉", "目前由其他連線擴充控制這些效果。", "Mod 已關閉，使用遊戲規則。", "自訂規則無法使用，使用遊戲規則。", "規則按隊伍人數使用，探索中無法修改。", "正在接收房主規則…", "使用原版", "獲得 {0}% 的經驗", "原版：{0}\n房主規則：{1}" },
            ["ja-JP"] = new[] { "適用人数", "{0}人", "表示・編集する人数別ルールを選びます。実際の人数は変わりません。以後の出現や報酬には、その時点の人数のルールを使います。", "現在の人数を確認・変更を保持", "変更一覧", "現在のルールを通知", "閉じる", "これらの効果は別のマルチプレイ拡張が管理します。", "Modが無効のため、ゲームのルールを使います。", "カスタムルールを使用できないため、ゲームのルールを使います。", "人数別にルールを適用。探索中は編集できません。", "ホストのルールを受信中…", "ゲームの標準に戻す", "経験値を{0}%獲得", "元の値：{0}\nホストのルール：{1}" },
            ["ko-KR"] = new[] { "적용 인원", "{0}명", "확인하거나 수정할 인원별 규칙을 선택합니다. 실제 인원은 바뀌지 않습니다. 이후 생성과 보상은 당시 인원의 규칙을 사용합니다.", "현재 인원 확인 · 변경 유지", "변경 사항 보기", "현재 규칙 알리기", "닫기", "다른 멀티플레이 확장이 이 효과를 제어합니다.", "Mod가 꺼져 있어 게임 규칙을 사용합니다.", "사용자 규칙을 사용할 수 없어 게임 규칙을 사용합니다.", "인원별 규칙을 사용하며 탐험 중에는 수정할 수 없습니다.", "호스트 규칙 수신 중…", "게임 기본값 사용", "경험치 {0}% 획득", "원본: {0}\n호스트 규칙: {1}" },
            ["de-DE"] = new[] { "Regeln für", "{0} Spieler", "Regeln nach Spielerzahl ansehen oder bearbeiten. Ändert die Teamgröße nicht. Spätere Gegner und Belohnungen richten sich nach der dann aktuellen Spielerzahl.", "Aktuelles Team prüfen; Änderungen behalten", "Änderungen prüfen", "Aktuelle Regeln teilen", "Schließen", "Eine andere Mehrspieler-Erweiterung steuert diese Effekte.", "Mod deaktiviert; Spielregeln gelten.", "Eigene Regeln nicht verfügbar; Spielregeln gelten.", "Regeln nach Spielerzahl. Während der Erkundung nicht änderbar.", "Hostregeln werden empfangen…", "Spielvorgabe verwenden", "{0}% Erfahrung erhalten", "Original: {0}\nHostregel: {1}" },
            ["fr-FR"] = new[] { "Règles pour", "{0} joueurs", "Choisissez les règles à consulter ou modifier par effectif. Cela ne change pas l’équipe. Les apparitions et récompenses suivantes utilisent l’effectif du moment.", "Vérifier l’effectif, garder les modifications", "Voir les modifications", "Partager les règles actuelles", "Fermer", "Une autre extension multijoueur gère ces effets.", "Mod désactivé : règles du jeu.", "Règles personnalisées indisponibles : règles du jeu.", "Règles selon l’effectif, verrouillées pendant l’exploration.", "Réception des règles de l’hôte…", "Utiliser la valeur du jeu", "Recevoir {0}% d’expérience", "Original : {0}\nRègle de l’hôte : {1}" },
            ["es-ES"] = new[] { "Reglas para", "{0} jugadores", "Elige las reglas por número de jugadores. No cambia el equipo. Las siguientes apariciones y recompensas usan el número de jugadores de ese momento.", "Revisar equipo y conservar cambios", "Revisar cambios", "Compartir reglas actuales", "Cerrar", "Otra extensión multijugador controla estos efectos.", "Mod desactivado; se usan las reglas del juego.", "Reglas personalizadas no disponibles; se usan las del juego.", "Reglas según el equipo, bloqueadas durante la exploración.", "Recibiendo reglas del anfitrión…", "Usar valor del juego", "Recibir {0}% de experiencia", "Original: {0}\nRegla del anfitrión: {1}" },
            ["it-IT"] = new[] { "Regole per", "{0} giocatori", "Scegli le regole per numero di giocatori da vedere o modificare. Non cambia la squadra. Le apparizioni e ricompense successive usano il numero di giocatori del momento.", "Controlla squadra e conserva modifiche", "Rivedi modifiche", "Condividi regole attuali", "Chiudi", "Un’altra estensione multigiocatore gestisce questi effetti.", "Mod disattivato; si usano le regole del gioco.", "Regole personalizzate non disponibili; si usano quelle del gioco.", "Regole per numero di giocatori, bloccate durante l’esplorazione.", "Ricezione delle regole dell’host…", "Usa valore del gioco", "Ricevi {0}% di esperienza", "Originale: {0}\nRegola dell’host: {1}" },
            ["pt-BR"] = new[] { "Regras para", "{0} jogadores", "Escolha as regras por número de jogadores para ver ou editar. Não muda a equipe. As próximas aparições e recompensas usam a quantidade de jogadores do momento.", "Revisar equipe e manter alterações", "Revisar alterações", "Compartilhar regras atuais", "Fechar", "Outra extensão multijogador controla estes efeitos.", "Mod desativado; valem as regras do jogo.", "Regras personalizadas indisponíveis; valem as do jogo.", "Regras por tamanho da equipe, bloqueadas durante a exploração.", "Recebendo regras do anfitrião…", "Usar padrão do jogo", "Receber {0}% de experiência", "Original: {0}\nRegra do anfitrião: {1}" },
            ["pl-PL"] = new[] { "Reguły dla", "{0} graczy", "Wybierz reguły dla danej liczby graczy. Nie zmienia to drużyny. Kolejni wrogowie i nagrody używają reguł dla aktualnej wtedy liczby graczy.", "Sprawdź drużynę i zachowaj zmiany", "Przejrzyj zmiany", "Udostępnij bieżące reguły", "Zamknij", "Inne rozszerzenie wieloosobowe steruje tymi efektami.", "Mod wyłączony; obowiązują reguły gry.", "Własne reguły niedostępne; obowiązują reguły gry.", "Reguły według liczby graczy, zablokowane podczas wyprawy.", "Odbieranie reguł gospodarza…", "Użyj wartości gry", "Otrzymuj {0}% doświadczenia", "Oryginał: {0}\nReguła gospodarza: {1}" },
            ["ru-RU"] = new[] { "Правила для", "{0} игроков", "Выберите правила для просмотра или изменения по числу игроков. Состав команды не меняется. Последующие появления и награды учитывают число игроков в тот момент.", "Проверить состав, сохранив изменения", "Просмотреть изменения", "Сообщить текущие правила", "Закрыть", "Этими эффектами управляет другое сетевое расширение.", "Mod отключён; действуют правила игры.", "Свои правила недоступны; действуют правила игры.", "Правила зависят от числа игроков. Во время исследования их нельзя менять.", "Получение правил хоста…", "Использовать значение игры", "Получать {0}% опыта", "Оригинал: {0}\nПравило хоста: {1}" },
            ["sv-SE"] = new[] { "Regler för", "{0} spelare", "Välj regler att visa eller ändra efter spelarantal. Lagets storlek ändras inte. Senare fiender och belöningar använder dåvarande spelarantal.", "Granska laget och behåll ändringar", "Granska ändringar", "Dela aktuella regler", "Stäng", "Ett annat flerspelartillägg styr dessa effekter.", "Mod avstängd; spelets regler gäller.", "Egna regler saknas; spelets regler gäller.", "Regler efter spelarantal, låsta under utforskningen.", "Tar emot värdens regler…", "Använd spelets standard", "Få {0}% erfarenhet", "Original: {0}\nVärdens regel: {1}" },
            ["tr-TR"] = new[] { "Kural oyuncu sayısı", "{0} oyuncu", "Oyuncu sayısına göre incelenecek veya değiştirilecek kuralları seçin. Takım değişmez. Sonraki düşmanlar ve ödüller o anki oyuncu sayısını kullanır.", "Takımı incele, değişiklikleri koru", "Değişiklikleri incele", "Geçerli kuralları paylaş", "Kapat", "Bu etkileri başka bir çok oyunculu eklenti yönetiyor.", "Mod kapalı; oyun kuralları geçerli.", "Özel kurallar kullanılamıyor; oyun kuralları geçerli.", "Kurallar oyuncu sayısına göredir; keşifte değiştirilemez.", "Ev sahibinin kuralları alınıyor…", "Oyun varsayılanını kullan", "{0}% deneyim kazan", "Özgün: {0}\nEv sahibinin kuralı: {1}" },
            ["th-TH"] = new[] { "กฎสำหรับจำนวนคน", "{0} คน", "เลือกกฎตามจำนวนคนเพื่อดูหรือแก้ไข ไม่เปลี่ยนจำนวนคนในทีม การเกิดศัตรูและรางวัลครั้งต่อไปใช้จำนวนคนในขณะนั้น", "ตรวจสอบทีมปัจจุบันและเก็บการแก้ไข", "ตรวจสอบการแก้ไข", "แจ้งกฎปัจจุบัน", "ปิด", "ส่วนเสริมผู้เล่นหลายคนอื่นควบคุมผลเหล่านี้", "ปิด Mod อยู่ จึงใช้กฎของเกม", "ใช้กฎกำหนดเองไม่ได้ จึงใช้กฎของเกม", "ใช้กฎตามจำนวนคน และแก้ไขไม่ได้ระหว่างสำรวจ", "กำลังรับกฎของโฮสต์…", "ใช้ค่าเดิมของเกม", "ได้รับประสบการณ์ {0}%", "ค่าเดิม: {0}\nกฎของโฮสต์: {1}" },
        };
    }
}
