using System.Collections.Generic;
namespace SephiriaEnhancements.MultiplayerRules.Presentation
{
    internal static partial class MultiplayerRulesLocalization
    {
        internal const string EditAction = "SephiriaEnhancements.MultiplayerRules.EditAction";
        internal const string ReviewValues = "SephiriaEnhancements.MultiplayerRules.ReviewValues";
        internal const string ReviewChanges = "SephiriaEnhancements.MultiplayerRules.ReviewChanges";
        internal const string ReviewScope = "SephiriaEnhancements.MultiplayerRules.ReviewScope";
        internal const string InvalidNumber = "SephiriaEnhancements.MultiplayerRules.InvalidNumber";
        internal const string InvalidRange = "SephiriaEnhancements.MultiplayerRules.InvalidRange";
        internal const string InvalidStep = "SephiriaEnhancements.MultiplayerRules.InvalidStep";
        internal const string InputActions = "SephiriaEnhancements.MultiplayerRules.InputActions";
        internal const string InputValid = "SephiriaEnhancements.MultiplayerRules.InputValid";
        internal const string InputDefault = "SephiriaEnhancements.MultiplayerRules.InputDefault";
        private static readonly string[] ReviewKeys = { EditAction, ReviewValues, ReviewChanges, ReviewScope, InvalidNumber, InvalidRange, InvalidStep, InputActions, InputValid, InputDefault };
        private static readonly Dictionary<string, string[]> ReviewTexts = new()
        {
            ["en-US"] = new[] { "Edit", "Original: {0}\nSaved: {1}\nEdited: {2}", "Unsaved changes: {0}", "Saves edits for all player counts. Health bonus combination applies to every count. Closing without saving discards edits.", "Enter a number.", "Allowed range: {0}–{1}.", "Use increments of {0}, starting at {1}.", "{0}: confirm · {1}: cancel\n{2}: next control · {3}+{2}: previous", "Confirm to keep this edit.", "Confirm to use game behavior." },
            ["zh-CN"] = new[] { "编辑", "原版：{0}\n已保存：{1}\n本次修改：{2}", "未保存修改：{0} 项", "保存所有人数的修改，生命加成叠加方式由各人数共用。关闭而不保存会丢弃修改。", "请输入数字。", "允许范围：{0}–{1}。", "从 {1} 起，按 {0} 的间隔填写。", "{0}：确认 · {1}：取消\n{2}：下一控件 · {3}+{2}：上一控件", "确认后保留本次修改。", "确认后此项使用原版。" },
            ["zh-TW"] = new[] { "編輯", "原版：{0}\n已儲存：{1}\n本次修改：{2}", "未儲存修改：{0} 項", "儲存所有人數的修改，生命加成疊加方式由各人數共用。關閉而不儲存會捨棄修改。", "請輸入數字。", "允許範圍：{0}–{1}。", "從 {1} 起，按 {0} 的間隔填寫。", "{0}：確認 · {1}：取消\n{2}：下一控制項 · {3}+{2}：上一控制項", "確認後保留本次修改。", "確認後此項使用原版。" },
            ["ja-JP"] = new[] { "編集", "元の値：{0}\n保存済み：{1}\n変更後：{2}", "未保存の変更：{0}件", "全人数の変更を保存します。HP補正の計算方法は全人数で共通です。保存せず閉じると変更を破棄します。", "数値を入力してください。", "範囲：{0}～{1}。", "{1}から{0}刻みで入力してください。", "{0}：決定 · {1}：取消\n{2}：次 · {3}+{2}：前", "確定でこの変更を保持。", "確定で元の動作を使用。" },
            ["ko-KR"] = new[] { "편집", "원본: {0}\n저장됨: {1}\n수정: {2}", "저장하지 않은 변경: {0}개", "모든 인원의 변경을 저장합니다. 체력 보너스 합산 방식은 모든 인원에 공통입니다. 저장하지 않고 닫으면 변경을 취소합니다.", "숫자를 입력하세요.", "허용 범위: {0}–{1}.", "{1}부터 {0} 간격으로 입력하세요.", "{0}: 확인 · {1}: 취소\n{2}: 다음 · {3}+{2}: 이전", "확인하면 이 변경을 유지합니다.", "확인하면 게임 기본값을 사용합니다." },
            ["de-DE"] = new[] { "Bearbeiten", "Original: {0}\nGespeichert: {1}\nBearbeitet: {2}", "Ungespeicherte Änderungen: {0}", "Speichert Änderungen für alle Spielerzahlen. LP-Bonusberechnung gilt für alle. Schließen ohne Speichern verwirft Änderungen.", "Eine Zahl eingeben.", "Bereich: {0}–{1}.", "Ab {1} in Schritten von {0}.", "{0}: bestätigen · {1}: abbrechen\n{2}: weiter · {3}+{2}: zurück", "Bestätigen übernimmt diese Eingabe.", "Bestätigen übernimmt das Spielverhalten." },
            ["fr-FR"] = new[] { "Modifier", "Original : {0}\nEnregistré : {1}\nModifié : {2}", "Modifications non enregistrées : {0}", "Enregistre les modifications pour tous les effectifs. Le calcul des bonus de PV est commun. Fermer sans enregistrer abandonne les modifications.", "Saisissez un nombre.", "Plage : {0}–{1}.", "Par pas de {0}, à partir de {1}.", "{0} : valider · {1} : annuler\n{2} : suivant · {3}+{2} : précédent", "Confirmer pour garder cette saisie.", "Confirmer pour utiliser le jeu de base." },
            ["es-ES"] = new[] { "Editar", "Original: {0}\nGuardado: {1}\nEditado: {2}", "Cambios sin guardar: {0}", "Guarda cambios para todos los tamaños de equipo. El cálculo de vida es compartido. Cerrar sin guardar descarta los cambios.", "Introduce un número.", "Rango: {0}–{1}.", "Incrementos de {0} desde {1}.", "{0}: confirmar · {1}: cancelar\n{2}: siguiente · {3}+{2}: anterior", "Confirma para conservar este cambio.", "Confirma para usar las reglas del juego." },
            ["it-IT"] = new[] { "Modifica", "Originale: {0}\nSalvato: {1}\nModificato: {2}", "Modifiche non salvate: {0}", "Salva le modifiche per tutti i numeri di giocatori. Il calcolo dei bonus PV è comune. Chiudere senza salvare scarta le modifiche.", "Inserisci un numero.", "Intervallo: {0}–{1}.", "Passi di {0} a partire da {1}.", "{0}: conferma · {1}: annulla\n{2}: avanti · {3}+{2}: indietro", "Conferma per mantenere la modifica.", "Conferma per usare le regole del gioco." },
            ["pt-BR"] = new[] { "Editar", "Original: {0}\nSalvo: {1}\nEditado: {2}", "Alterações não salvas: {0}", "Salva alterações para todos os tamanhos de equipe. O cálculo de bônus de vida é comum. Fechar sem salvar descarta as alterações.", "Digite um número.", "Intervalo: {0}–{1}.", "Passos de {0} a partir de {1}.", "{0}: confirmar · {1}: cancelar\n{2}: próximo · {3}+{2}: anterior", "Confirme para manter esta alteração.", "Confirme para usar as regras do jogo." },
            ["pl-PL"] = new[] { "Edytuj", "Oryginał: {0}\nZapisane: {1}\nZmienione: {2}", "Niezapisane zmiany: {0}", "Zapisuje zmiany dla wszystkich liczb graczy. Obliczanie premii PŻ jest wspólne. Zamknięcie bez zapisu odrzuca zmiany.", "Wpisz liczbę.", "Zakres: {0}–{1}.", "Krok {0}, począwszy od {1}.", "{0}: zatwierdź · {1}: anuluj\n{2}: dalej · {3}+{2}: wstecz", "Zatwierdź, aby zachować tę zmianę.", "Zatwierdź, aby użyć reguł gry." },
            ["ru-RU"] = new[] { "Изменить", "Оригинал: {0}\nСохранено: {1}\nИзменено: {2}", "Несохранённых изменений: {0}", "Сохраняет правки для всех составов команды. Расчёт бонусов HP общий. Закрытие без сохранения отменяет правки.", "Введите число.", "Диапазон: {0}–{1}.", "Шаг {0}, начиная с {1}.", "{0}: подтвердить · {1}: отменить\n{2}: далее · {3}+{2}: назад", "Подтвердите, чтобы оставить изменение.", "Подтвердите, чтобы использовать правила игры." },
            ["sv-SE"] = new[] { "Ändra", "Original: {0}\nSparat: {1}\nÄndrat: {2}", "Osparade ändringar: {0}", "Sparar ändringar för alla spelarantal. HP-bonusberäkningen är gemensam. Stäng utan att spara för att kasta ändringar.", "Ange ett tal.", "Intervall: {0}–{1}.", "Steg om {0}, med början på {1}.", "{0}: bekräfta · {1}: avbryt\n{2}: nästa · {3}+{2}: föregående", "Bekräfta för att behålla ändringen.", "Bekräfta för att använda spelets regler." },
            ["tr-TR"] = new[] { "Düzenle", "Özgün: {0}\nKaydedilen: {1}\nDüzenlenen: {2}", "Kaydedilmemiş değişiklik: {0}", "Tüm oyuncu sayıları için değişiklikleri kaydeder. Can bonusu hesabı ortaktır. Kaydetmeden kapatmak değişiklikleri siler.", "Bir sayı girin.", "Aralık: {0}–{1}.", "{1} değerinden başlayarak {0} adımlarla girin.", "{0}: onayla · {1}: iptal\n{2}: sonraki · {3}+{2}: önceki", "Bu değişikliği tutmak için onaylayın.", "Oyun kurallarını kullanmak için onaylayın." },
            ["th-TH"] = new[] { "แก้ไข", "ค่าเดิม: {0}\nบันทึกแล้ว: {1}\nแก้ไข: {2}", "การแก้ไขที่ยังไม่บันทึก: {0}", "บันทึกการแก้ไขสำหรับทุกจำนวนคน วิธีรวมโบนัส HP ใช้ร่วมกันทุกจำนวนคน ปิดโดยไม่บันทึกจะทิ้งการแก้ไข", "ป้อนตัวเลข", "ช่วงที่อนุญาต: {0}–{1}", "เพิ่มทีละ {0} โดยเริ่มจาก {1}", "{0}: ยืนยัน · {1}: ยกเลิก\n{2}: ถัดไป · {3}+{2}: ก่อนหน้า", "ยืนยันเพื่อเก็บการแก้ไขนี้", "ยืนยันเพื่อใช้กฎเดิมของเกม" },
        };
    }
}
