using System;
using System.Collections.Generic;

namespace SephiriaEnhancements.EffectStats
{
    internal static class EffectStatsLocalization
    {
        internal const string Title = "SephiriaEnhancements.EffectStats.Title";
        internal const string Note = "SephiriaEnhancements.EffectStats.Note";
        internal const string SolarDamage = "SephiriaEnhancements.EffectStats.SolarDamage";
        internal const string CloudDamage = "SephiriaEnhancements.EffectStats.CloudDamage";
        internal const string CloudSupply = "SephiriaEnhancements.EffectStats.CloudSupply";
        internal const string Magic = "SephiriaEnhancements.EffectStats.Magic";
        internal const string Burn = "SephiriaEnhancements.EffectStats.Burn";
        private static readonly Dictionary<string, string[]> Texts = new()
        {
            ["en-US"] = new[] { "Effect details", "Current values and bonuses for supported effects. Reference damage excludes hit resolution; activation conditions still apply.", "Normal throw damage: {0}\nBefore critical hits and target defenses; excludes empowered throws and recall attacks.", "Normal discharge damage: {0}\nBefore critical hits and target defenses; excludes empowered discharges.", "Stock: {0}/{1}\nAutomatic cycle: {2} s · Discharges: {3}\nNo consumption: {4}%\nIn combat: restore {5} every {6} s\nRequires a valid target to discharge.", "{0}. {1}\nMP per cast: {2} · MP budget: {3} casts\nCharges: {4}/{5} · New charge cycle: {6} s\nBudget excludes regeneration and casting limits.", "Burn reference per stack: {0}\nTick interval: {1} s · Stack limit: {2}\nBefore application-specific multipliers and hit resolution. Requires a source of Burn." },
            ["zh-CN"] = new[] { "效果详情", "显示已支持效果的当前数值与加成。参考伤害未计入命中结算，效果仍需满足触发条件。", "普通投掷伤害：{0}\n未计入暴击与目标防御，不含强化投掷及回收攻击。", "普通放电伤害：{0}\n未计入暴击与目标防御，不含强化放电。", "库存：{0}/{1}\n自动放电周期：{2} 秒 · 每轮 {3} 次\n不消耗概率：{4}%\n战斗中每 {6} 秒恢复 {5}\n需要有效目标才能放电。", "{0}. {1}\n每次耗蓝：{2} · 当前魔力可支付 {3} 次\n充能：{4}/{5} · 新充能周期：{6} 秒\n可支付次数未计恢复，不代表可立即连发。", "灼伤每层参考伤害：{0}\n跳伤间隔：{1} 秒 · 层数上限：{2}\n未计入施加来源倍率及命中结算，仍需灼伤来源。" },
            ["zh-TW"] = new[] { "效果詳情", "顯示已支援效果的目前數值與加成。參考傷害未計入命中結算，效果仍須滿足觸發條件。", "普通投擲傷害：{0}\n未計入暴擊與目標防禦，不含強化投擲及回收攻擊。", "普通放電傷害：{0}\n未計入暴擊與目標防禦，不含強化放電。", "庫存：{0}/{1}\n自動放電週期：{2} 秒 · 每輪 {3} 次\n不消耗機率：{4}%\n戰鬥中每 {6} 秒恢復 {5}\n需要有效目標才能放電。", "{0}. {1}\n每次耗魔：{2} · 目前魔力可支付 {3} 次\n充能：{4}/{5} · 新充能週期：{6} 秒\n可支付次數未計恢復，不代表可立即連發。", "灼傷每層參考傷害：{0}\n傷害間隔：{1} 秒 · 層數上限：{2}\n未計入施加來源倍率及命中結算，仍需灼傷來源。" },
            ["ko-KR"] = new[] { "효과 상세", "지원되는 효과의 현재 수치와 보너스입니다. 참고 피해는 명중 판정 전 수치이며, 발동 조건은 그대로 적용됩니다.", "일반 투척 피해: {0}\n치명타와 대상 방어 적용 전 수치입니다. 강화 투척과 회수 공격은 제외됩니다.", "일반 방전 피해: {0}\n치명타와 대상 방어 적용 전입니다. 강화 방전은 제외됩니다.", "보유량: {0}/{1}\n자동 방전 주기: {2}초 · 회당 {3}번\n소모하지 않을 확률: {4}%\n전투 중 {6}초마다 {5} 회복\n유효한 대상이 있어야 방전합니다.", "{0}. {1}\n시전당 MP: {2} · 현재 MP로 {3}회\n충전: {4}/{5} · 새 충전 주기: {6}초\nMP 회복과 시전 제한을 제외한 횟수입니다.", "화상 중첩당 참고 피해: {0}\n피해 간격: {1}초 · 최대 중첩: {2}\n부여 효과의 배율과 명중 판정 전입니다. 화상 부여 수단이 필요합니다." },
            ["ja-JP"] = new[] { "効果詳細", "対応する効果の現在値とボーナスです。参考ダメージは命中処理前の値で、発動条件は引き続き適用されます。", "通常投擲ダメージ：{0}\nクリティカルと対象の防御を適用する前の値です。強化投擲と回収攻撃は含みません。", "通常放電ダメージ：{0}\nクリティカルと対象の防御の適用前。強化放電は含みません。", "保有量：{0}/{1}\n自動放電周期：{2}秒 · 1周期 {3}回\n消費しない確率：{4}%\n戦闘中は{6}秒ごとに{5}回復\n有効な対象が必要です。", "{0}. {1}\n消費MP：{2} · 現在のMPで{3}回分\nチャージ：{4}/{5} · 次の充填周期：{6}秒\n回復と発動制限を除いたMP上の回数です。", "火傷1スタックの参考ダメージ：{0}\nダメージ間隔：{1}秒 · 上限：{2}\n付与元の倍率と命中処理前。火傷を付与する効果が必要です。" },
            ["de-DE"] = new[] { "Effektdetails", "Aktuelle Werte und Boni unterstützter Effekte. Referenzschaden vor Trefferberechnung; Auslösebedingungen gelten weiterhin.", "Schaden beim normalen Wurf: {0}\nVor kritischen Treffern und Zielverteidigung; ohne verstärkte Würfe und Rückholangriffe.", "Normaler Entladungsschaden: {0}\nVor kritischen Treffern und Zielverteidigung; ohne verstärkte Entladungen.", "Vorrat: {0}/{1}\nAutomatischer Zyklus: {2} s · Entladungen: {3}\nKein Verbrauch: {4}%\nIm Kampf: {5} alle {6} s regeneriert\nEntladung erfordert ein gültiges Ziel.", "{0}. {1}\nMP pro Einsatz: {2} · MP reichen für {3} Einsätze\nLadungen: {4}/{5} · Neuer Ladezyklus: {6} s\nOhne Regeneration und Einsatzbeschränkungen.", "Brennen-Referenzschaden pro Stapel: {0}\nSchadensintervall: {1} s · Stapellimit: {2}\nVor Multiplikatoren der Quelle und Trefferberechnung. Erfordert eine Brennen-Quelle." },
            ["es-ES"] = new[] { "Detalles de efectos", "Valores y bonificaciones actuales de efectos compatibles. Daño de referencia antes del cálculo del impacto; se mantienen las condiciones de activación.", "Daño de lanzamiento normal: {0}\nAntes de críticos y defensas del objetivo; excluye lanzamientos potenciados y ataques de recuperación.", "Daño de descarga normal: {0}\nAntes de críticos y defensas del objetivo; sin descargas potenciadas.", "Reserva: {0}/{1}\nCiclo automático: {2} s · Descargas: {3}\nSin consumo: {4}%\nEn combate: recupera {5} cada {6} s\nRequiere un objetivo válido para descargar.", "{0}. {1}\nMP por uso: {2} · MP para {3} usos\nCargas: {4}/{5} · Nuevo ciclo de carga: {6} s\nSin regeneración ni límites de lanzamiento.", "Daño de quemadura de referencia por acumulación: {0}\nIntervalo: {1} s · Límite: {2}\nAntes de multiplicadores de la fuente y del impacto. Requiere una fuente de quemadura." },
            ["fr-FR"] = new[] { "Détails des effets", "Valeurs et bonus actuels des effets pris en charge. Dégâts de référence avant résolution des impacts ; les conditions d’activation restent nécessaires.", "Dégâts du lancer normal : {0}\nAvant les coups critiques et les défenses de la cible ; hors lancers renforcés et attaques de rappel.", "Dégâts de décharge normale : {0}\nAvant les critiques et les défenses de la cible ; hors décharges renforcées.", "Réserve : {0}/{1}\nCycle automatique : {2} s · Décharges : {3}\nSans consommation : {4}%\nEn combat : récupère {5} toutes les {6} s\nUne cible valide est nécessaire.", "{0}. {1}\nMP par utilisation : {2} · MP pour {3} utilisations\nCharges : {4}/{5} · Nouveau cycle : {6} s\nSans régénération ni limites de lancement.", "Brûlure, dégâts de référence par cumul : {0}\nIntervalle : {1} s · Limite : {2}\nAvant les multiplicateurs de la source et les impacts. Nécessite une source de brûlure." },
            ["it-IT"] = new[] { "Dettagli degli effetti", "Valori e bonus attuali degli effetti supportati. Danni di riferimento prima del calcolo del colpo; restano valide le condizioni di attivazione.", "Danni del lancio normale: {0}\nPrima dei critici e delle difese del bersaglio; esclude lanci potenziati e attacchi di richiamo.", "Danni della scarica normale: {0}\nPrima dei critici e delle difese del bersaglio; senza scariche potenziate.", "Riserva: {0}/{1}\nCiclo automatico: {2} s · Scariche: {3}\nNessun consumo: {4}%\nIn combattimento: recupera {5} ogni {6} s\nServe un bersaglio valido.", "{0}. {1}\nMP per uso: {2} · MP per {3} usi\nCariche: {4}/{5} · Nuovo ciclo: {6} s\nEsclude rigenerazione e limiti di lancio.", "Ustione, danni di riferimento per accumulo: {0}\nIntervallo: {1} s · Limite: {2}\nPrima dei moltiplicatori della fonte e del calcolo del colpo. Serve una fonte di ustione." },
            ["pl-PL"] = new[] { "Szczegóły efektów", "Aktualne wartości i premie obsługiwanych efektów. Obrażenia orientacyjne przed rozliczeniem trafienia; warunki aktywacji nadal obowiązują.", "Obrażenia zwykłego rzutu: {0}\nPrzed trafieniami krytycznymi i obroną celu; bez wzmocnionych rzutów i ataków przy powrocie.", "Obrażenia zwykłego wyładowania: {0}\nPrzed trafieniami krytycznymi i obroną celu; bez wzmocnionych wyładowań.", "Zapas: {0}/{1}\nCykl automatyczny: {2} s · Wyładowania: {3}\nBez zużycia: {4}%\nW walce: odzyskuje {5} co {6} s\nWymaga odpowiedniego celu.", "{0}. {1}\nMP na użycie: {2} · MP na {3} użyć\nŁadunki: {4}/{5} · Nowy cykl: {6} s\nBez regeneracji i ograniczeń rzucania.", "Podpalenie, obrażenia orientacyjne na kumulację: {0}\nOdstęp: {1} s · Limit: {2}\nPrzed mnożnikami źródła i rozliczeniem trafienia. Wymaga źródła podpalenia." },
            ["pt-BR"] = new[] { "Detalhes dos efeitos", "Valores e bônus atuais dos efeitos compatíveis. Dano de referência antes do cálculo do acerto; as condições de ativação continuam valendo.", "Dano do arremesso normal: {0}\nAntes de críticos e defesas do alvo; exclui arremessos fortalecidos e ataques de retorno.", "Dano da descarga normal: {0}\nAntes de críticos e defesas do alvo; sem descargas fortalecidas.", "Reserva: {0}/{1}\nCiclo automático: {2} s · Descargas: {3}\nSem consumo: {4}%\nEm combate: recupera {5} a cada {6} s\nRequer um alvo válido.", "{0}. {1}\nMP por uso: {2} · MP para {3} usos\nCargas: {4}/{5} · Novo ciclo: {6} s\nSem regeneração nem limites de conjuração.", "Queimadura, dano de referência por acúmulo: {0}\nIntervalo: {1} s · Limite: {2}\nAntes dos multiplicadores da fonte e do cálculo do acerto. Requer uma fonte de queimadura." },
            ["ru-RU"] = new[] { "Подробности эффектов", "Текущие значения и бонусы поддерживаемых эффектов. Справочный урон до расчёта попадания; условия активации сохраняются.", "Урон обычного броска: {0}\nДо критических попаданий и защиты цели; без усиленных бросков и атак при возврате.", "Урон обычного разряда: {0}\nДо критических попаданий и защиты цели; без усиленных разрядов.", "Запас: {0}/{1}\nАвтоматический цикл: {2} с · Разрядов: {3}\nБез расхода: {4}%\nВ бою: восстанавливает {5} каждые {6} с\nТребуется подходящая цель.", "{0}. {1}\nMP за применение: {2} · MP хватит на {3} применений\nЗаряды: {4}/{5} · Новый цикл: {6} с\nБез учёта восстановления и ограничений применения.", "Горение, справочный урон за слой: {0}\nИнтервал: {1} с · Предел слоёв: {2}\nДо множителей источника и расчёта попадания. Нужен источник горения." },
            ["sv-SE"] = new[] { "Effektdetaljer", "Aktuella värden och bonusar för effekter som stöds. Referensskada före träffberäkning; aktiveringsvillkoren gäller fortfarande.", "Skada vid normalt kast: {0}\nFöre kritiska träffar och målets försvar; utan förstärkta kast och återkallningsattacker.", "Normal urladdningsskada: {0}\nFöre kritiska träffar och målets försvar; utan förstärkta urladdningar.", "Lager: {0}/{1}\nAutomatisk cykel: {2} s · Urladdningar: {3}\nIngen förbrukning: {4}%\nI strid: återställer {5} var {6} s\nKräver ett giltigt mål.", "{0}. {1}\nMP per användning: {2} · MP räcker till {3} användningar\nLaddningar: {4}/{5} · Ny laddningscykel: {6} s\nUtan återhämtning och användningsbegränsningar.", "Brännskada, referens per stapel: {0}\nIntervall: {1} s · Stapelgräns: {2}\nFöre källans multiplikatorer och träffberäkning. Kräver en källa till brännskada." },
            ["th-TH"] = new[] { "รายละเอียดเอฟเฟกต์", "ค่าปัจจุบันและโบนัสของเอฟเฟกต์ที่รองรับ ความเสียหายอ้างอิงยังไม่ผ่านการคำนวณเมื่อโจมตีโดน และยังต้องตรงตามเงื่อนไขการทำงาน", "ความเสียหายจากการขว้างปกติ: {0}\nก่อนคิดคริติคอลและการป้องกันของเป้าหมาย ไม่รวมการขว้างเสริมพลังและการโจมตีขณะเรียกกลับ", "ความเสียหายการปล่อยสายฟ้าปกติ: {0}\nก่อนคิดคริติคอลและการป้องกัน ไม่รวมการปล่อยแบบเสริมพลัง", "คงเหลือ: {0}/{1}\nรอบอัตโนมัติ: {2} วินาที · {3} ครั้งต่อรอบ\nโอกาสไม่ใช้ทรัพยากร: {4}%\nในต่อสู้ฟื้นฟู {5} ทุก {6} วินาที\nต้องมีเป้าหมายที่โจมตีได้", "{0}. {1}\nMP ต่อครั้ง: {2} · MP ปัจจุบันใช้ได้ {3} ครั้ง\nชาร์จ: {4}/{5} · รอบชาร์จใหม่: {6} วินาที\nจำนวนครั้งไม่รวมการฟื้นฟูและข้อจำกัดการร่าย", "ความเสียหายเผาไหม้อ้างอิงต่อชั้น: {0}\nช่วงความเสียหาย: {1} วินาที · สูงสุด: {2} ชั้น\nก่อนคิดตัวคูณจากแหล่งที่มาและผลเมื่อโจมตีโดน ต้องมีแหล่งที่ทำให้เผาไหม้" },
            ["tr-TR"] = new[] { "Etki ayrıntıları", "Desteklenen etkilerin mevcut değerleri ve bonusları. Referans hasar, isabet hesabından öncedir; etkinleşme koşulları geçerlidir.", "Normal atış hasarı: {0}\nKritik vuruş ve hedef savunması öncesi; güçlendirilmiş atışlar ve geri çağırma saldırıları hariçtir.", "Normal deşarj hasarı: {0}\nKritik vuruş ve hedef savunması öncesi; güçlendirilmiş deşarjlar hariç.", "Stok: {0}/{1}\nOtomatik döngü: {2} sn · Deşarj: {3}\nTüketmeme olasılığı: {4}%\nSavaşta her {6} sn içinde {5} yeniler\nGeçerli bir hedef gerektirir.", "{0}. {1}\nKullanım başına MP: {2} · MP ile {3} kullanım\nYük: {4}/{5} · Yeni yük döngüsü: {6} sn\nYenilenme ve kullanım sınırlamaları hariçtir.", "Yanma, yük başına referans hasar: {0}\nAralık: {1} sn · Yük sınırı: {2}\nKaynak çarpanları ve isabet hesabı öncesi. Yanma uygulayan bir kaynak gerektirir." }
        };

        internal static void Register(Action<string, string, string> addText, IEnumerable<string> languages)
        {
            Configuration.LocalizationGroup.Register(addText, languages,
                new[] { Title, Note, SolarDamage, CloudDamage, CloudSupply, Magic, Burn }, Texts);
        }
    }
}
